r"""Weeks 1-6: precalculus review, limits, derivatives, inverse/exponential/trig
functions, chain & quotient rules with logs, and critical points & curve sketching."""
from lesson_helpers import ex, lesson, mc, pr

WEEKS_1_6 = [
    # ======================= WEEK 1: PRECALCULUS REVIEW =======================
    lesson(
        "review-factoring", 1, "Factoring", "factor gcf difference of squares trinomial cubes grouping",
        "Beginner", 20, [],
        r"Factoring rewrites a sum as a <b>product</b>. Calculus uses it constantly: cancelling in limits, finding "
        r"zeros, critical points and sign charts. Always pull out the <b>greatest common factor</b> first, then look "
        r"for a pattern: difference of squares, a trinomial, or a sum/difference of cubes.",
        [
            ["Common factor", r"ab + ac = a(b+c)"],
            ["Difference of squares", r"a^2 - b^2 = (a-b)(a+b)"],
            [r"Trinomial (find \(p, q\) that multiply to the constant and add to the middle)", r"x^2 + (p+q)x + pq = (x+p)(x+q)"],
            ["Perfect square", r"a^2 \pm 2ab + b^2 = (a \pm b)^2"],
            ["Sum / difference of cubes", r"a^3 \pm b^3 = (a \pm b)(a^2 \mp ab + b^2)"],
        ],
        ex(r"Factor \(2x^3 - 8x^2 - 10x\) completely.",
           [r"Pull out the common factor \(2x\): \(2x(x^2 - 4x - 5)\).",
            r"Find two numbers that multiply to \(-5\) and add to \(-4\): \(-5\) and \(1\).",
            r"So \(x^2 - 4x - 5 = (x-5)(x+1)\)."],
           r"\(2x(x-5)(x+1)\)"),
        ["Skipping the common factor and ending up with a harder trinomial.",
         r"Trying to factor \(a^2 + b^2\). A sum of squares doesn't factor over the real numbers.",
         r"Sign errors in cubes. Remember SOAP: Same sign, Opposite sign, Always Positive: \(a^3 - b^3 = (a-b)(a^2+ab+b^2)\)."],
        [pr(r"Factor \(x^2 - 49\).", "Difference of squares.", r"\((x-7)(x+7)\)"),
         pr(r"Factor \(6x^2 + x - 2\).", r"Find two numbers that multiply to \(6\cdot(-2) = -12\) and add to 1, then group.", r"\((2x-1)(3x+2)\)"),
         pr(r"Factor \(x^3 - 27\).", r"Difference of cubes with \(b = 3\).", r"\((x-3)(x^2+3x+9)\)")],
        [mc(r"\(x^2 + 5x + 6 =\)", [r"\((x+1)(x+6)\)", r"\((x+2)(x+3)\)", r"\((x-2)(x-3)\)", r"\((x+5)(x+1)\)"], 1, "2 × 3 = 6 and 2 + 3 = 5."),
         mc(r"\(4x^2 - 9 =\)", [r"\((2x-3)^2\)", r"\((4x-3)(x+3)\)", r"\((2x-3)(2x+3)\)", "doesn't factor"], 2, r"Difference of squares: \((2x)^2 - 3^2\)."),
         mc(r"\(x^3 + 8 =\)", [r"\((x+2)(x^2-2x+4)\)", r"\((x+2)(x^2+2x+4)\)", r"\((x+2)^3\)", r"\((x-2)(x^2+2x+4)\)"], 0, "Sum of cubes: same, opposite, always positive.")],
    ),
    lesson(
        "review-expanding", 1, "Expanding", "expand foil distribute binomial square cube multiply brackets",
        "Beginner", 15, [],
        r"Expanding is the reverse of factoring: multiply out the brackets and collect like terms. You'll need it in "
        r"Week 3, where the limit definition of the derivative makes you expand things like \((x+h)^2\) and "
        r"\((x+h)^3\).",
        [
            ["Distributive law", r"a(b+c) = ab + ac"],
            ["FOIL", r"(a+b)(c+d) = ac + ad + bc + bd"],
            ["Square of a sum", r"(a+b)^2 = a^2 + 2ab + b^2"],
            ["Cube of a sum", r"(a+b)^3 = a^3 + 3a^2b + 3ab^2 + b^3"],
            ["Conjugates", r"(a-b)(a+b) = a^2 - b^2"],
        ],
        ex(r"Expand and simplify \((x+h)^3 - x^3\).",
           [r"Cube of a sum: \((x+h)^3 = x^3 + 3x^2h + 3xh^2 + h^3\).",
            r"Subtract \(x^3\): the \(x^3\) terms cancel."],
           r"\(3x^2h + 3xh^2 + h^3\)"),
        [r"Writing \((a+b)^2 = a^2 + b^2\). You lose the middle term \(2ab\).",
         r"Not distributing a minus sign to every term: \(-(x-2) = -x + 2\).",
         r"\((2x)^2 = 4x^2\), not \(2x^2\)."],
        [pr(r"Expand \((2x-3)(x+4)\).", "FOIL, then combine the middle terms.", r"\(2x^2 + 5x - 12\)"),
         pr(r"Expand \((x-5)^2\).", r"\((a-b)^2 = a^2 - 2ab + b^2\).", r"\(x^2 - 10x + 25\)"),
         pr(r"Expand \(-(x-2)(x+2)\).", "Conjugates first, then the minus sign.", r"\(-x^2 + 4\)")],
        [mc(r"\((x+3)^2 =\)", [r"\(x^2 + 9\)", r"\(x^2 + 3x + 9\)", r"\(x^2 + 6x + 9\)", r"\(x^2 + 6x + 6\)"], 2, r"\(a^2 + 2ab + b^2\) with \(b = 3\)."),
         mc(r"\((x+h)^2 - x^2 =\)", [r"\(2xh + h^2\)", r"\(h^2\)", r"\(2x + h\)", r"\(x^2 + h^2\)"], 0, r"\(x^2 + 2xh + h^2 - x^2\)."),
         mc(r"\((3x-1)(3x+1) =\)", [r"\(9x^2 + 1\)", r"\(3x^2 - 1\)", r"\(9x^2 - 6x - 1\)", r"\(9x^2 - 1\)"], 3, "Conjugates give a difference of squares.")],
    ),
    lesson(
        "review-simplifying", 1, "Simplifying Expressions", "simplify rational expression exponent laws radicals rationalize complex fraction",
        "Beginner", 25, ["review-factoring"],
        r"Simplifying makes expressions easier to work with: cancel common <b>factors</b> in rational expressions, use "
        r"the exponent laws, combine fractions over a common denominator, and rationalize roots. Clean algebra is "
        r"most of the work in limits and derivatives.",
        [
            ["Exponent laws", r"x^a x^b = x^{a+b},\quad \frac{x^a}{x^b} = x^{a-b},\quad (x^a)^b = x^{ab}"],
            ["Negative and fractional exponents", r"x^{-n} = \frac{1}{x^n},\qquad x^{m/n} = \sqrt[n]{x^m}"],
            [r"Cancel common factors (\(c \ne 0\))", r"\frac{ac}{bc} = \frac{a}{b}"],
            ["Add fractions", r"\frac{a}{b} + \frac{c}{d} = \frac{ad + bc}{bd}"],
            ["Rationalize with the conjugate", r"\frac{1}{\sqrt{a} + \sqrt{b}} = \frac{\sqrt{a} - \sqrt{b}}{a - b}"],
        ],
        ex(r"Simplify \(\dfrac{x^2 - 9}{x^2 + x - 6}\).",
           [r"Factor the top: \((x-3)(x+3)\).",
            r"Factor the bottom: \((x+3)(x-2)\).",
            r"Cancel the common factor \((x+3)\), remembering that \(x \ne -3\) in the original."],
           r"\(\dfrac{x-3}{x-2}\), for \(x \ne -3\)"),
        [r"Cancelling terms instead of factors: \(\frac{x+2}{2} \ne x\).",
         "Forgetting the restrictions (values that made the original denominator zero).",
         r"Splitting roots over addition: \(\sqrt{a + b} \ne \sqrt{a} + \sqrt{b}\)."],
        [pr(r"Simplify \(\dfrac{\frac1x - \frac13}{x - 3}\).", r"Combine the top into one fraction: \(\frac{3 - x}{3x}\).", r"\(-\dfrac{1}{3x}\)"),
         pr(r"Simplify \(\dfrac{x^{3/2}}{x^{1/2}}\).", "Subtract the exponents.", r"\(x\)"),
         pr(r"Rationalize \(\dfrac{2}{\sqrt5 - 1}\).", r"Multiply top and bottom by \(\sqrt5 + 1\).", r"\(\dfrac{2(\sqrt5+1)}{4} = \dfrac{\sqrt5 + 1}{2}\)")],
        [mc(r"\(x^3 \cdot x^{-5} =\)", [r"\(x^{-15}\)", r"\(\frac{1}{x^2}\)", r"\(x^8\)", r"\(x^{2}\)"], 1, "Add the exponents: 3 + (−5) = −2."),
         mc(r"\(\dfrac{x^2 - 4}{x - 2} =\)", [r"\(x - 2\)", r"\(x^2 - 2\)", r"\(x + 2\) (for \(x \ne 2\))", r"\(x\)"], 2, r"\(\frac{(x-2)(x+2)}{x-2}\)."),
         mc(r"\(\dfrac{1}{x} + \dfrac{1}{x+1} =\)", [r"\(\frac{2x+1}{x(x+1)}\)", r"\(\frac{2}{2x+1}\)", r"\(\frac{1}{x^2+x}\)", r"\(\frac{2}{x(x+1)}\)"], 0, r"Common denominator \(x(x+1)\): \(\frac{(x+1) + x}{x(x+1)}\).")],
    ),
    lesson(
        "review-solving", 1, "Solving Equations & Inequalities", "solve quadratic formula linear rational absolute value inequality sign chart",
        "Beginner", 25, ["review-factoring"],
        r"Solving means finding every value that makes an equation true. Move everything to one side, factor, and use "
        r"the <b>zero product property</b>. If it won't factor, use the quadratic formula. For inequalities, find where "
        r"the expression is zero or undefined, then test each interval with a <b>sign chart</b>. You'll use sign "
        r"charts again in Week 6.",
        [
            ["Zero product property", r"ab = 0 \;\Rightarrow\; a = 0 \text{ or } b = 0"],
            ["Quadratic formula", r"ax^2 + bx + c = 0 \;\Rightarrow\; x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}"],
            [r"Discriminant \(b^2 - 4ac\)", r"\gt 0: \text{two roots},\quad = 0: \text{one root},\quad \lt 0: \text{no real roots}"],
            ["Absolute value", r"|x| = a \;\Rightarrow\; x = \pm a,\qquad |x| \lt a \;\Rightarrow\; -a \lt x \lt a"],
        ],
        ex(r"Solve \(x^2 - x - 6 \lt 0\).",
           [r"Factor: \((x-3)(x+2) \lt 0\).",
            r"The expression is zero at \(x = -2\) and \(x = 3\). These split the number line into three intervals.",
            r"Test a point in each: \(x = -3\) gives \(+\), \(x = 0\) gives \(-\), \(x = 4\) gives \(+\).",
            r"We want negative, so keep the middle interval."],
           r"\(-2 \lt x \lt 3\)"),
        ["Dividing both sides by a variable, which can throw away a solution (like x = 0).",
         "Forgetting to flip the inequality when multiplying or dividing by a negative number.",
         "Not checking for extraneous solutions in rational or radical equations."],
        [pr(r"Solve \(3x^2 + 2x - 1 = 0\).", r"Factor: \((3x - 1)(x + 1)\).", r"\(x = \frac13\) or \(x = -1\)"),
         pr(r"Solve \(x^2 + 4x + 1 = 0\).", "It doesn't factor nicely; use the quadratic formula.", r"\(x = -2 \pm \sqrt3\)"),
         pr(r"Solve \(|2x - 1| = 5\).", r"\(2x - 1 = 5\) or \(2x - 1 = -5\).", r"\(x = 3\) or \(x = -2\)")],
        [mc(r"The solutions of \(x^2 = 5x\) are:", [r"\(x = 5\) only", r"\(x = 0\) only", r"\(x = 0\) and \(x = 5\)", r"\(x = \pm\sqrt5\)"], 2,
            r"\(x^2 - 5x = x(x - 5) = 0\). Dividing by \(x\) would lose \(x = 0\)."),
         mc(r"How many real roots does \(x^2 + 2x + 5 = 0\) have?", ["Two", "One", "Infinitely many", "None"], 3, r"The discriminant is \(4 - 20 = -16 \lt 0\)."),
         mc(r"Solve \(|x - 4| \lt 2\).", [r"\(2 \lt x \lt 6\)", r"\(x \lt 2\) or \(x \gt 6\)", r"\(-2 \lt x \lt 2\)", r"\(x \lt 6\)"], 0, r"\(-2 \lt x - 4 \lt 2\).")],
    ),
    lesson(
        "review-graphing", 1, "Graphing Functions", "graph function domain range transformations shift stretch reflect parabola intercepts line slope",
        "Beginner", 25, ["review-solving"],
        r"A graph shows every input-output pair of a function. Know the basic shapes (lines, parabolas, \(\sqrt{x}\), "
        r"\(\frac1x\), \(|x|\)) and how <b>transformations</b> move them. Find the <b>domain</b> by excluding inputs that "
        r"divide by zero, take an even root of a negative, or take the log of a non-positive number.",
        [
            ["Lines", r"y = mx + b,\qquad y - y_1 = m(x - x_1),\qquad m = \frac{y_2 - y_1}{x_2 - x_1}"],
            [r"Shifts (\(h\) right, \(k\) up)", r"y = f(x - h) + k"],
            ["Reflections and stretches", r"y = -f(x)\ (\text{over } x\text{-axis}),\quad y = f(-x)\ (\text{over } y\text{-axis}),\quad y = a f(x)"],
            ["Vertex form of a parabola", r"y = a(x - h)^2 + k,\quad \text{vertex } (h, k)"],
        ],
        ex(r"Graph \(y = -(x-2)^2 + 3\).",
           [r"Start with \(y = x^2\). Shift right 2, reflect over the \(x\)-axis (opens down), and shift up 3.",
            r"The vertex is \((2, 3)\).",
            r"\(y\)-intercept: \(x = 0\) gives \(-4 + 3 = -1\).",
            r"\(x\)-intercepts: \((x-2)^2 = 3\), so \(x = 2 \pm \sqrt3\)."],
           r"A downward parabola with vertex \((2,3)\), \(y\)-intercept \(-1\) and \(x\)-intercepts \(2 \pm \sqrt3\)"),
        [r"Shifting the wrong way: \(f(x-2)\) moves the graph <b>right</b> 2, not left.",
         r"Forgetting domain restrictions, like \(x \ge 3\) for \(\sqrt{x - 3}\).",
         r"Mixing up \(-f(x)\) (flip vertically) and \(f(-x)\) (flip horizontally)."],
        [pr(r"Domain of \(f(x) = \dfrac{1}{x^2 - 4}\).", "The denominator can't be zero.", r"All real \(x\) except \(x = \pm 2\)"),
         pr(r"Domain of \(f(x) = \sqrt{5 - x}\).", "The inside of the root must be at least 0.", r"\(x \le 5\)"),
         pr(r"Find the line through \((1, 2)\) and \((3, 8)\).", r"Slope first: \(\frac{8 - 2}{3 - 1}\).", r"\(m = 3\), so \(y = 3x - 1\)")],
        [mc(r"The vertex of \(y = (x + 1)^2 - 4\) is:", [r"\((1, -4)\)", r"\((-1, -4)\)", r"\((-1, 4)\)", r"\((1, 4)\)"], 1, r"\(x - h = x + 1\) means \(h = -1\)."),
         mc(r"The domain of \(\ln(x - 1)\) is:", [r"\(x \ge 1\)", r"all real \(x\)", r"\(x \gt 1\)", r"\(x \gt 0\)"], 2, "A log needs a positive input."),
         mc(r"Compared with \(y = f(x)\), the graph of \(y = f(x) + 3\) is:", ["shifted up 3", "shifted right 3", "shifted left 3", "stretched by 3"], 0, "Adding outside the function moves it vertically.")],
    ),

    # ======================= WEEK 2: LIMITS =======================
    lesson(
        "limits", 2, "Limits Numerically & Graphically", "limit table graph one-sided left right numerical estimate approach",
        "Beginner", 20, ["review-graphing"],
        r"A limit asks: <b>what value is \(f(x)\) heading toward as \(x\) gets close to \(a\)?</b> It doesn't care what "
        r"happens exactly at \(a\). Estimate it <b>numerically</b> with a table of \(x\)-values closing in from both "
        r"sides, or <b>graphically</b> by tracing the curve toward \(x = a\). If the left-hand and right-hand limits "
        r"agree, the limit exists.",
        [
            ["Notation", r"\lim_{x\to a} f(x) = L"],
            ["One-sided limits", r"\lim_{x\to a^-} f(x)\ (\text{from the left}),\qquad \lim_{x\to a^+} f(x)\ (\text{from the right})"],
            ["The limit exists exactly when both sides agree", r"\lim_{x\to a} f(x) = L \iff \lim_{x\to a^-} f(x) = \lim_{x\to a^+} f(x) = L"],
        ],
        ex(r"Estimate \(\displaystyle\lim_{x\to 0}\frac{\sin x}{x}\) numerically (radians).",
           [r"\(x = 0.1\): \(\frac{\sin 0.1}{0.1} \approx 0.99833\).",
            r"\(x = 0.01\): \(\approx 0.99998\).",
            r"\(x = -0.1\) and \(x = -0.01\) give the same values, since \(\frac{\sin x}{x}\) is even.",
            r"Both sides are closing in on 1, even though \(f(0)\) is undefined."],
           r"\(1\)"),
        [r"Using degree mode on your calculator. Limits with trig functions use radians.",
         r"Assuming the limit equals \(f(a)\). A hole or a moved point can make them different.",
         "Checking only one side of a number."],
        [pr(r"\(f(x) = x + 1\) for \(x \lt 2\) and \(f(x) = 5 - x\) for \(x \ge 2\). Find \(\lim_{x\to 2} f(x)\).",
            "Find each one-sided limit with its own formula.", r"Left: 3, right: 3, so the limit is 3."),
         pr(r"Estimate \(\displaystyle\lim_{x\to 1}\frac{x^2 - 1}{x - 1}\) with a table.", r"Try \(x = 0.9, 0.99, 1.01, 1.1\).", r"The values approach 2."),
         pr(r"Find \(\displaystyle\lim_{x\to 0}\frac{|x|}{x}\).", r"For \(x \lt 0\) the fraction is \(-1\); for \(x \gt 0\) it is \(1\).", "Left −1, right 1: the limit does not exist.")],
        [mc(r"The left-hand limit at \(x = 2\) is 4 and the right-hand limit is 5. Then \(\lim_{x\to 2} f(x)\):", ["is 4.5", "is 4", "is 5", "does not exist"], 3,
            "The two sides disagree."),
         mc(r"A table gives \(\frac{e^x - 1}{x} \approx 1.0517\) at \(x = 0.1\) and \(\approx 1.0050\) at \(x = 0.01\) (and similar from the left). The limit as \(x \to 0\) is about:",
            ["1", "0", "1.05", "it doesn't exist"], 0, "The values close in on 1."),
         mc(r"\(f(2) = 7\), but the graph approaches height 3 from both sides of \(x = 2\). Then \(\lim_{x\to 2} f(x) =\)", ["7", "3", "10", "does not exist"], 1,
            "The limit ignores the value at the point itself.")],
    ),
    lesson(
        "limits-algebraic", 2, "Evaluating Limits Algebraically", "limit laws direct substitution factor conjugate rationalize squeeze theorem 0/0",
        "Intermediate", 25, ["limits", "review-factoring", "review-simplifying"],
        r"Start with <b>direct substitution</b>. If you get a number, that's the limit. If you get \(\frac00\), that's "
        r"<b>indeterminate</b>: do algebra first (factor and cancel, multiply by a conjugate, or simplify a complex "
        r"fraction), then substitute again. If you get \(\frac{\text{nonzero}}{0}\), the limit is infinite or doesn't "
        r"exist. The <b>squeeze theorem</b> handles functions trapped between two others.",
        [
            ["Limit laws", r"\lim (f \pm g) = \lim f \pm \lim g,\quad \lim (fg) = \lim f \cdot \lim g,\quad \lim \frac fg = \frac{\lim f}{\lim g}\ (\lim g \ne 0)"],
            ["Direct substitution (polynomials, and rational functions where the bottom isn't 0)", r"\lim_{x\to a} f(x) = f(a)"],
            ["Squeeze theorem", r"g(x) \le f(x) \le h(x),\ \lim g = \lim h = L \;\Rightarrow\; \lim f = L"],
            ["Special trig limit", r"\lim_{x\to 0}\frac{\sin x}{x} = 1"],
        ],
        ex(r"Find \(\displaystyle\lim_{x\to 3}\frac{x^2 - 9}{x - 3}\).",
           [r"Substitute: \(\frac00\). Indeterminate, so simplify first.",
            r"Factor: \(\frac{(x-3)(x+3)}{x-3}\).",
            r"Cancel \((x-3)\). This is allowed because the limit only looks at \(x\) near 3, not at 3.",
            r"Substitute into \(x + 3\): \(6\)."],
           r"\(6\)"),
        [r"Concluding that \(\frac00\) means the limit is 0 or 1.",
         r"Cancelling when the form is \(\frac{\text{nonzero}}{0}\). That signals a vertical asymptote.",
         "Using the squeeze theorem with bounds that approach different values."],
        [pr(r"\(\displaystyle\lim_{x\to 0}\frac{\sqrt{x+4} - 2}{x}\)", r"Multiply top and bottom by \(\sqrt{x+4} + 2\).", r"\(\frac{1}{\sqrt{x+4} + 2} \to \frac14\)"),
         pr(r"\(\displaystyle\lim_{x\to 2}\frac{\frac1x - \frac12}{x - 2}\)", r"Combine the top: \(\frac{2 - x}{2x}\).", r"\(-\frac{1}{2x} \to -\frac14\)"),
         pr(r"\(\displaystyle\lim_{x\to 0} x^2\sin\frac1x\)", r"\(-x^2 \le x^2\sin\frac1x \le x^2\).", "Squeeze theorem: 0")],
        [mc(r"\(\displaystyle\lim_{x\to 1}\frac{x^2 - 1}{x - 1} =\)", ["0", "1", "2", "does not exist"], 2, r"Factor and cancel to get \(x + 1\)."),
         mc(r"\(\displaystyle\lim_{x\to 4}\frac{\sqrt{x} - 2}{x - 4} =\)", [r"\(\frac14\)", r"\(\frac12\)", "0", "4"], 0, r"\(x - 4 = (\sqrt x - 2)(\sqrt x + 2)\), leaving \(\frac{1}{\sqrt x + 2}\)."),
         mc(r"\(\displaystyle\lim_{x\to 0}\frac{\sin(3x)}{x} =\)", ["1", r"\(\frac13\)", "0", "3"], 3, r"\(3\cdot\frac{\sin 3x}{3x} \to 3\).")],
    ),
    lesson(
        "limits-infinity", 2, "Limits at Infinity & Infinite Limits", "infinity negative infinity asymptote horizontal vertical end behaviour dominant term",
        "Intermediate", 25, ["limits-algebraic"],
        r"As \(x \to \infty\) or \(x \to -\infty\), the limit describes <b>end behaviour</b> and gives horizontal "
        r"asymptotes. For rational functions, divide every term by the highest power of \(x\) in the denominator. An "
        r"<b>infinite limit</b> (\(f \to \pm\infty\) as \(x \to a\)) gives a vertical asymptote. Watch signs when "
        r"\(x \to -\infty\), especially with square roots, because \(\sqrt{x^2} = |x| = -x\) when \(x\) is negative.",
        [
            ["Basic fact", r"\lim_{x\to\pm\infty}\frac{1}{x^n} = 0 \quad (n \gt 0)"],
            ["Rational functions: compare the degrees of top and bottom", r"\text{top} \lt \text{bottom} \Rightarrow 0;\qquad \text{equal} \Rightarrow \frac{\text{leading coeff. of top}}{\text{leading coeff. of bottom}};\qquad \text{top} \gt \text{bottom} \Rightarrow \pm\infty"],
            [r"Vertical asymptote at \(x = a\)", r"\lim_{x\to a^\pm} f(x) = \pm\infty"],
            [r"Roots when \(x \lt 0\)", r"\sqrt{x^2} = |x| = -x"],
        ],
        ex(r"Find \(\displaystyle\lim_{x\to -\infty}\frac{\sqrt{4x^2 + 1}}{x - 3}\).",
           [r"For \(x \lt 0\): \(\sqrt{4x^2 + 1} = |x|\sqrt{4 + \frac{1}{x^2}} = -x\sqrt{4 + \frac{1}{x^2}}\).",
            r"Divide top and bottom by \(x\): \(\frac{-\sqrt{4 + 1/x^2}}{1 - 3/x}\).",
            r"As \(x \to -\infty\), \(\frac1{x^2} \to 0\) and \(\frac3x \to 0\).",
            r"So the limit is \(-\frac{\sqrt4}{1} = -2\). (As \(x \to +\infty\) it would be \(+2\).)"],
           r"\(-2\)"),
        [r"Forgetting that \(\sqrt{x^2} = -x\) for negative \(x\), which flips the sign of the answer.",
         r"Treating \(\infty - \infty\) as 0. It's indeterminate; use a conjugate or factor.",
         r"Mixing up horizontal asymptotes (\(x \to \pm\infty\)) and vertical asymptotes (\(f \to \pm\infty\))."],
        [pr(r"\(\displaystyle\lim_{x\to\infty}\frac{3x^2 + 1}{5x^2 - x}\)", r"Divide by \(x^2\).", r"\(\frac35\)"),
         pr(r"Find \(\displaystyle\lim_{x\to 2^+}\frac{1}{x - 2}\) and \(\displaystyle\lim_{x\to 2^-}\frac{1}{x - 2}\).", "Check the sign of the denominator on each side.", r"\(+\infty\) and \(-\infty\): a vertical asymptote at \(x = 2\)"),
         pr(r"\(\displaystyle\lim_{x\to\infty}\left(\sqrt{x^2 + x} - x\right)\)", r"\(\infty - \infty\): multiply by the conjugate over itself.", r"\(\frac{x}{\sqrt{x^2+x} + x} \to \frac12\)")],
        [mc(r"\(\displaystyle\lim_{x\to\infty}\frac{2x + 1}{x^2 + 3} =\)", ["2", "0", r"\(\infty\)", r"\(\frac13\)"], 1, "The bottom has the higher degree."),
         mc(r"\(\displaystyle\lim_{x\to -\infty}\frac{4x^3 - x}{2x^3 + 5} =\)", [r"\(-2\)", r"\(-\infty\)", "2", "0"], 2, "Equal degrees: 4/2 = 2."),
         mc(r"The vertical asymptotes of \(\dfrac{x + 1}{x^2 - 1}\) are:", [r"\(x = 1\) and \(x = -1\)", r"\(x = -1\) only", "none", r"\(x = 1\) only"], 3,
            r"It simplifies to \(\frac{1}{x - 1}\). At \(x = -1\) there's a hole, not an asymptote.")],
    ),
    lesson(
        "epsilon-delta", 2, "The Epsilon–Delta Definition", "epsilon delta precise definition formal proof limit",
        "Advanced", 30, ["limits-algebraic", "review-solving"],
        r"The precise definition of a limit is a challenge game. Someone picks any tolerance \(\varepsilon \gt 0\) "
        r"around \(L\). You must find a window \(\delta \gt 0\) around \(a\) so that every \(x\) in the window (except "
        r"possibly \(a\) itself) gives \(f(x)\) within \(\varepsilon\) of \(L\). If you can always win, then "
        r"\(\lim_{x\to a} f(x) = L\). To find \(\delta\), work backwards from \(|f(x) - L| \lt \varepsilon\).",
        [
            ["Definition", r"\forall \varepsilon \gt 0\ \exists \delta \gt 0:\quad 0 \lt |x - a| \lt \delta \;\Rightarrow\; |f(x) - L| \lt \varepsilon"],
            [r"For a line \(f(x) = mx + b\)", r"\delta = \frac{\varepsilon}{|m|}"],
            [r"What \(|x - a| \lt \delta\) means", r"a - \delta \lt x \lt a + \delta"],
        ],
        ex(r"Prove \(\displaystyle\lim_{x\to 2}(3x - 1) = 5\).",
           [r"Scratch work: \(|(3x - 1) - 5| = |3x - 6| = 3|x - 2|\). We need this \(\lt \varepsilon\), so we need \(|x - 2| \lt \frac{\varepsilon}{3}\).",
            r"Proof: let \(\varepsilon \gt 0\) and choose \(\delta = \frac{\varepsilon}{3}\).",
            r"If \(0 \lt |x - 2| \lt \delta\), then \(|f(x) - 5| = 3|x - 2| \lt 3\delta = \varepsilon\). ∎"],
           r"\(\delta = \frac{\varepsilon}{3}\) works for every \(\varepsilon \gt 0\)"),
        [r"Choosing a \(\delta\) that depends on \(x\). It may depend only on \(\varepsilon\) (and \(a\)).",
         r"Forgetting \(0 \lt |x - a|\): the value at \(x = a\) itself doesn't matter.",
         "Handing in the scratch work as the proof. The proof starts from δ and ends at ε."],
        [pr(r"Prove \(\displaystyle\lim_{x\to 1}(5x + 2) = 7\).", r"\(|5x + 2 - 7| = 5|x - 1|\).", r"Choose \(\delta = \frac{\varepsilon}{5}\)."),
         pr(r"For \(\displaystyle\lim_{x\to 3} 2x = 6\) and \(\varepsilon = 0.1\), find a \(\delta\).", r"\(|2x - 6| = 2|x - 3| \lt 0.1\).", r"\(\delta = 0.05\)"),
         pr(r"Prove \(\displaystyle\lim_{x\to 2} x^2 = 4\).", r"\(|x^2 - 4| = |x - 2||x + 2|\). If \(\delta \le 1\) then \(1 \lt x \lt 3\), so \(|x + 2| \lt 5\).",
            r"Choose \(\delta = \min\left(1, \frac{\varepsilon}{5}\right)\).")],
        [mc(r"For \(\displaystyle\lim_{x\to 2}(4x - 3) = 5\), a valid choice is:", [r"\(\delta = 4\varepsilon\)", r"\(\delta = \frac{\varepsilon}{4}\)", r"\(\delta = \varepsilon - 4\)", r"\(\delta = \frac{\varepsilon}{3}\)"], 1,
            r"\(|4x - 3 - 5| = 4|x - 2|\)."),
         mc(r"In the definition, the condition \(0 \lt |x - a|\) means:", [r"\(x\) is positive", r"\(x \gt a\)", r"\(x \ne a\)", r"\(\delta \gt 0\)"], 2, "The point a itself is excluded."),
         mc(r"For \(f(x) = 7x + 1\) at \(a = 0\) with \(\varepsilon = 0.01\), the largest \(\delta\) that works is:", [r"\(\frac{0.01}{7}\)", r"\(0.07\)", r"\(0.01\)", r"\(7\)"], 0, r"\(\delta = \frac{\varepsilon}{|m|}\).")],
    ),
    lesson(
        "continuity", 2, "Continuity", "continuous discontinuity removable jump infinite piecewise",
        "Intermediate", 20, ["limits-algebraic"],
        r"A function is <b>continuous</b> at \(a\) when its graph has no break there: the value exists, the limit exists, "
        r"and they're equal. Breaks come in three types: <b>removable</b> (a hole), <b>jump</b> (one-sided limits "
        r"disagree), and <b>infinite</b> (a vertical asymptote). Polynomials, \(\sin\), \(\cos\), \(e^x\), roots, logs "
        r"and rational functions are continuous everywhere on their domains.",
        [
            [r"Continuous at \(a\)", r"f(a) \text{ is defined},\quad \lim_{x\to a} f(x) \text{ exists},\quad \lim_{x\to a} f(x) = f(a)"],
            ["Removable discontinuity", r"\lim_{x\to a} f(x) \text{ exists but } \ne f(a) \text{ (or } f(a) \text{ undefined)}"],
            ["Jump discontinuity", r"\lim_{x\to a^-} f(x) \ne \lim_{x\to a^+} f(x)"],
            ["Infinite discontinuity", r"\lim_{x\to a^\pm} f(x) = \pm\infty"],
        ],
        ex(r"Find \(k\) so that \(f(x) = \begin{cases} kx + 1 & x \lt 2 \\ x^2 - k & x \ge 2 \end{cases}\) is continuous.",
           [r"Left-hand limit at 2: \(2k + 1\).",
            r"Right-hand limit and value at 2: \(4 - k\).",
            r"Set them equal: \(2k + 1 = 4 - k\), so \(3k = 3\)."],
           r"\(k = 1\)"),
        ["Thinking a limit existing is enough. The value must exist and match it too.",
         "Forgetting that continuity on a closed interval only needs one-sided limits at the endpoints.",
         "Relying only on 'draw it without lifting your pen'. Use the three conditions."],
        [pr(r"Classify the discontinuity of \(\dfrac{x^2 - 1}{x - 1}\) at \(x = 1\).", "Does the limit exist?", r"Removable (a hole at \((1, 2)\))"),
         pr(r"Classify the discontinuity of \(\dfrac{1}{x^2}\) at \(x = 0\).", "What happens to the values near 0?", "Infinite (vertical asymptote)"),
         pr(r"Find \(c\) so \(f(x) = cx^2\) for \(x \le 1\) and \(3x\) for \(x \gt 1\) is continuous.", r"Match the values at \(x = 1\).", r"\(c = 3\)")],
        [mc(r"\(\dfrac{x^2 - 4}{x - 2}\) at \(x = 2\) has a:", ["removable discontinuity", "jump discontinuity", "infinite discontinuity", "no discontinuity"], 0, "The limit exists (4) but f(2) is undefined."),
         mc(r"\(f(x) = \dfrac{1}{x - 3}\) at \(x = 3\) has a:", ["removable discontinuity", "jump discontinuity", "infinite discontinuity", "no discontinuity"], 2, "Vertical asymptote."),
         mc(r"For continuity at \(a\) you need:", [r"\(f(a)\) defined", "the limit to exist", "the limit to equal f(a)", "all three"], 3, "All three conditions.")],
    ),

    # ======================= WEEK 3: DERIVATIVES =======================
    lesson(
        "derivative-definition", 3, "Limit Definition of the Derivative", "derivative definition f(x+h) difference quotient first principles tangent line slope secant",
        "Intermediate", 30, ["limits-algebraic", "review-expanding"],
        r"The derivative is the slope of the tangent line, and it comes from a limit. The <b>difference quotient</b> "
        r"\(\frac{f(x+h) - f(x)}{h}\) is the slope of a secant line through two nearby points. Let \(h \to 0\) and the "
        r"secant becomes the tangent. In practice: compute \(f(x+h)\), subtract \(f(x)\), simplify, cancel the \(h\), "
        r"then let \(h \to 0\).",
        [
            ["Derivative (first principles)", r"f'(x) = \lim_{h\to 0}\frac{f(x+h) - f(x)}{h}"],
            [r"At a point \(a\)", r"f'(a) = \lim_{x\to a}\frac{f(x) - f(a)}{x - a}"],
            ["Tangent line", r"y - f(a) = f'(a)(x - a)"],
            ["Differentiable implies continuous (not the reverse, e.g. |x| at 0)", r"f'(a) \text{ exists} \Rightarrow f \text{ continuous at } a"],
        ],
        ex(r"Use the definition to differentiate \(f(x) = x^2 + 3x\).",
           [r"\(f(x+h) = (x+h)^2 + 3(x+h) = x^2 + 2xh + h^2 + 3x + 3h\).",
            r"Subtract \(f(x)\): \(f(x+h) - f(x) = 2xh + h^2 + 3h\).",
            r"Divide by \(h\): \(2x + h + 3\).",
            r"Let \(h \to 0\)."],
           r"\(f'(x) = 2x + 3\)"),
        [r"Writing \(f(x+h) = f(x) + h\). Replace every \(x\) in the formula with \((x+h)\).",
         r"Setting \(h = 0\) before cancelling, which gives \(\frac00\).",
         r"Forgetting to distribute the minus sign when subtracting all of \(f(x)\)."],
        [pr(r"Differentiate \(f(x) = \frac1x\) from the definition.", r"Combine \(\frac{1}{x+h} - \frac1x = \frac{-h}{x(x+h)}\).", r"\(-\frac{1}{x(x+h)} \to -\frac{1}{x^2}\)"),
         pr(r"Differentiate \(f(x) = \sqrt{x}\) from the definition.", r"Multiply by the conjugate \(\sqrt{x+h} + \sqrt x\).", r"\(\frac{1}{\sqrt{x+h} + \sqrt x} \to \frac{1}{2\sqrt x}\)"),
         pr(r"Find the tangent line to \(y = x^2 + 3x\) at \(x = 1\).", r"Use \(f'(x) = 2x + 3\) from the example.", r"Slope 5 through \((1, 4)\): \(y = 5x - 1\)")],
        [mc(r"Using the definition, the derivative of \(f(x) = 5x - 2\) is:", ["5", r"\(5x\)", "−2", "0"], 0, r"\(\frac{5(x+h) - 2 - (5x - 2)}{h} = 5\)."),
         mc(r"For \(f(x) = x^2\), \(\frac{f(x+h) - f(x)}{h}\) simplifies to:", [r"\(2x\)", r"\(h\)", r"\(2x + h\)", r"\(x^2 + h\)"], 2, r"\(\frac{2xh + h^2}{h}\)."),
         mc(r"At \(x = 0\), \(f(x) = |x|\) is:", ["differentiable", "not continuous", "undefined", "continuous but not differentiable"], 3, "There's a sharp corner: the slopes from each side are −1 and 1.")],
    ),
    lesson(
        "derivative-rules", 3, "Power Rule & Basic Rules", "power rule constant multiple sum difference derivative polynomial",
        "Beginner", 20, ["derivative-definition"],
        r"The limit definition always works, but it's slow. These rules give the same answers instantly. The "
        r"<b>power rule</b> works for any real exponent, so rewrite roots and fractions as powers first: "
        r"\(\sqrt{x} = x^{1/2}\) and \(\frac{1}{x^3} = x^{-3}\). Constants differentiate to 0, and sums are "
        r"differentiated term by term.",
        [
            ["Constant", r"\frac{d}{dx}c = 0"],
            ["Power rule", r"\frac{d}{dx}x^n = nx^{n-1}"],
            ["Constant multiple", r"\frac{d}{dx}\big[c\,f(x)\big] = c\,f'(x)"],
            ["Sum and difference", r"\frac{d}{dx}\big[f \pm g\big] = f' \pm g'"],
        ],
        ex(r"Differentiate \(f(x) = 4x^5 - \frac{3}{x^2} + 2\sqrt{x} - 7\).",
           [r"Rewrite as powers: \(4x^5 - 3x^{-2} + 2x^{1/2} - 7\).",
            r"Power rule on each term: \(20x^4 + 6x^{-3} + x^{-1/2} - 0\).",
            r"Rewrite without negative exponents."],
           r"\(f'(x) = 20x^4 + \frac{6}{x^3} + \frac{1}{\sqrt{x}}\)"),
        [r"Differentiating \(\frac{1}{x^2}\) as \(\frac{1}{2x}\). Rewrite as \(x^{-2}\) first.",
         r"Getting negative exponents wrong: \(x^{-2} \to -2x^{-3}\), not \(-2x^{-1}\).",
         "Writing the derivative of a constant as the constant. It's 0."],
        [pr(r"\(\frac{d}{dx}(x^3 - 6x^2 + 9x)\)", "Term by term.", r"\(3x^2 - 12x + 9\)"),
         pr(r"\(\frac{d}{dx}\frac{5}{x}\)", r"\(5x^{-1}\).", r"\(-\frac{5}{x^2}\)"),
         pr(r"\(\frac{d}{dx}x^{2/3}\)", "Bring the 2/3 down and subtract 1.", r"\(\frac23x^{-1/3}\)")],
        [mc(r"\(\frac{d}{dx}x^7 =\)", [r"\(7x^6\)", r"\(x^6\)", r"\(7x^8\)", r"\(6x^7\)"], 0, "Bring the 7 down and subtract 1 from the power."),
         mc(r"\(\frac{d}{dx}\frac{1}{x^3} =\)", [r"\(\frac{1}{3x^2}\)", r"\(-\frac{3}{x^4}\)", r"\(-\frac{3}{x^2}\)", r"\(\frac{3}{x^4}\)"], 1, r"\(x^{-3} \to -3x^{-4}\)."),
         mc(r"\(\frac{d}{dx}\sqrt{x} =\)", [r"\(2\sqrt x\)", r"\(\frac{1}{\sqrt x}\)", r"\(\frac{1}{2\sqrt x}\)", r"\(\frac12\sqrt x\)"], 2, r"\(x^{1/2} \to \frac12x^{-1/2}\).")],
    ),
    lesson(
        "product-rule", 3, "Product Rule", "product rule derivative two functions multiplied",
        "Beginner", 20, ["derivative-rules"],
        r"The derivative of a product is <b>not</b> the product of the derivatives. Instead: derivative of the first "
        r"times the second, plus the first times the derivative of the second. You can check a product rule answer "
        r"by expanding first and using the power rule.",
        [
            ["Product rule", r"(fg)' = f'g + fg'"],
            ["Three factors", r"(fgh)' = f'gh + fg'h + fgh'"],
            ["Not this!", r"(fg)' \ne f'g'"],
        ],
        ex(r"Differentiate \(y = (x^2 + 1)(x^3 - 2x)\).",
           [r"\(f = x^2 + 1\), \(f' = 2x\); \(g = x^3 - 2x\), \(g' = 3x^2 - 2\).",
            r"Product rule: \(2x(x^3 - 2x) + (x^2 + 1)(3x^2 - 2)\).",
            r"Expand: \(2x^4 - 4x^2 + 3x^4 - 2x^2 + 3x^2 - 2\).",
            r"Check: expanding first gives \(x^5 - x^3 - 2x\), whose derivative matches."],
           r"\(y' = 5x^4 - 3x^2 - 2\)"),
        [r"Multiplying the derivatives: \((x^2 \cdot x^3)' \ne 2x \cdot 3x^2\).",
         "Dropping one of the two terms.",
         "Not simplifying, which makes later steps (like solving y' = 0) much harder."],
        [pr(r"\(\frac{d}{dx}\big[x^3(2x + 5)\big]\)", "Product rule, then simplify.", r"\(3x^2(2x + 5) + 2x^3 = 8x^3 + 15x^2\)"),
         pr(r"\(\frac{d}{dx}\big[\sqrt{x}\,(x^2 - 1)\big]\)", r"\(\frac{1}{2\sqrt x}(x^2 - 1) + \sqrt x\cdot 2x\), then use a common denominator.", r"\(\frac{5x^2 - 1}{2\sqrt x}\)"),
         pr(r"Slope of \(y = (x + 1)(x^2 - 3)\) at \(x = 2\).", r"\(y' = (x^2 - 3) + (x + 1)\cdot 2x\).", r"\(1 + 12 = 13\)")],
        [mc(r"Using the product rule, \(\frac{d}{dx}\big[x^2\cdot x^3\big] =\)", [r"\(6x^3\)", r"\(5x^4\)", r"\(6x^5\)", r"\(x^5\)"], 1, r"\(2x\cdot x^3 + x^2\cdot 3x^2 = 5x^4\)."),
         mc(r"\(f = 3,\ f' = 2,\ g = 4,\ g' = -1\) at a point. Then \((fg)' =\)", ["−2", "11", "5", "8"], 2, r"\(2\cdot 4 + 3\cdot(-1) = 5\)."),
         mc(r"\(\frac{d}{dx}\big[x(x + 1)\big] =\)", [r"\(2x + 1\)", r"\(x + 1\)", r"\(2x\)", "1"], 0, r"\(1\cdot(x + 1) + x\cdot 1\).")],
    ),

    # ======================= WEEK 4: INVERSE, EXPONENTIAL & TRIG FUNCTIONS =======================
    lesson(
        "inverse-functions", 4, "Inverse Functions", "inverse function one-to-one horizontal line test reflection arcsin arctan inverse trig derivative of inverse",
        "Intermediate", 25, ["review-graphing", "review-solving"],
        r"An inverse function undoes the original: \(f^{-1}(f(x)) = x\). Only <b>one-to-one</b> functions (they pass "
        r"the horizontal line test) have inverses, so some functions need a restricted domain first. To find an "
        r"inverse, swap \(x\) and \(y\) and solve for \(y\). The graph of \(f^{-1}\) is the reflection of \(f\) over "
        r"the line \(y = x\), and the domain and range swap.",
        [
            ["Inverse property", r"f^{-1}(f(x)) = x,\qquad f(f^{-1}(x)) = x"],
            ["Finding the inverse", r"y = f(x) \;\to\; \text{swap } x, y \;\to\; \text{solve for } y"],
            [r"Derivative of an inverse, where \(f(a) = b\)", r"(f^{-1})'(b) = \frac{1}{f'(a)}"],
            ["Inverse trig ranges", r"\arcsin: [-1,1] \to \left[-\tfrac\pi2, \tfrac\pi2\right],\qquad \arctan: \mathbb{R} \to \left(-\tfrac\pi2, \tfrac\pi2\right)"],
        ],
        ex(r"Find the inverse of \(f(x) = \dfrac{2x + 1}{x - 3}\).",
           [r"Write \(y = \frac{2x + 1}{x - 3}\) and swap: \(x = \frac{2y + 1}{y - 3}\).",
            r"Multiply out: \(xy - 3x = 2y + 1\).",
            r"Collect the \(y\) terms: \(xy - 2y = 3x + 1\), so \(y(x - 2) = 3x + 1\).",
            r"Divide."],
           r"\(f^{-1}(x) = \dfrac{3x + 1}{x - 2}\), for \(x \ne 2\)"),
        [r"Thinking \(f^{-1}(x)\) means \(\frac{1}{f(x)}\). It means the inverse function.",
         r"Forgetting to restrict the domain, for example \(x \ge 0\) before inverting \(x^2\).",
         r"Assuming \(\arcsin(\sin x) = x\) for every \(x\). It only holds for \(-\frac\pi2 \le x \le \frac\pi2\)."],
        [pr(r"Find the inverse of \(f(x) = x^3 + 2\).", "Swap and solve.", r"\(f^{-1}(x) = \sqrt[3]{x - 2}\)"),
         pr(r"Find the inverse of \(f(x) = x^2\), \(x \ge 0\).", "The restriction picks the positive root.", r"\(f^{-1}(x) = \sqrt x\)"),
         pr(r"\(f(x) = x^3 + x\). Find \((f^{-1})'(2)\).", r"First find \(a\) with \(f(a) = 2\): \(a = 1\).", r"\(\frac{1}{f'(1)} = \frac{1}{4}\)")],
        [mc(r"The inverse of \(f(x) = 2x + 6\) is:", [r"\(\frac{1}{2x + 6}\)", r"\(\frac{x - 6}{2}\)", r"\(2x - 6\)", r"\(\frac{x}{2} + 6\)"], 1, r"Swap: \(x = 2y + 6\), so \(y = \frac{x - 6}{2}\)."),
         mc(r"\(\arcsin\left(\frac12\right) =\)", [r"\(\frac\pi3\)", r"\(\frac{5\pi}{6}\)", r"\(\frac\pi6\)", r"\(30\)"], 2, r"\(\sin\frac\pi6 = \frac12\), and \(\frac\pi6\) is in the range of arcsin."),
         mc("Which function is one-to-one on all real numbers?", [r"\(x^2\)", r"\(\cos x\)", r"\(|x|\)", r"\(x^3\)"], 3, "It passes the horizontal line test.")],
    ),
    lesson(
        "exponential-functions", 4, "Exponential Functions", "exponential growth decay e base exponent laws compound interest graph asymptote",
        "Beginner", 20, ["review-simplifying", "review-graphing"],
        r"In an exponential function \(b^x\), the variable is in the <b>exponent</b>. For \(b \gt 1\) it grows faster than "
        r"any power of \(x\); for \(0 \lt b \lt 1\) it decays. The most important base is \(e \approx 2.71828\), which "
        r"shows up in continuous growth and has the nicest derivative (Week 5). Every \(b^x\) has domain all reals, "
        r"range \((0, \infty)\), and the horizontal asymptote \(y = 0\).",
        [
            [r"Exponential function (\(b \gt 0,\ b \ne 1\))", r"f(x) = b^x"],
            ["The number e", r"e = \lim_{n\to\infty}\left(1 + \frac1n\right)^n \approx 2.71828"],
            ["Growth and decay", r"A(t) = A_0e^{kt}\quad (k \gt 0 \text{ growth},\ k \lt 0 \text{ decay})"],
            ["Compound interest", r"A = P\left(1 + \frac rn\right)^{nt},\qquad \text{continuous: } A = Pe^{rt}"],
        ],
        ex(r"A colony of 500 bacteria doubles every 3 hours. How many are there after 12 hours?",
           [r"Doubling every 3 hours: \(A(t) = 500\cdot 2^{t/3}\).",
            r"At \(t = 12\): \(500\cdot 2^{4}\).",
            r"\(2^4 = 16\)."],
           r"\(8000\) bacteria"),
        [r"\((2^x)^2 = 2^{2x}\), not \(2^{x^2}\).",
         r"Confusing \(2^x\) (exponential) with \(x^2\) (power function).",
         r"\(e^{a+b} = e^a e^b\), not \(e^a + e^b\)."],
        [pr(r"Simplify \(\dfrac{e^{2x}e^{-x}}{e^{x}}\).", "Add and subtract exponents.", r"\(e^{0} = 1\)"),
         pr(r"Solve \(2^{x+1} = 32\).", r"Write 32 as a power of 2.", r"\(x + 1 = 5\), so \(x = 4\)"),
         pr(r"Find \(\lim_{x\to -\infty} e^x\) and \(\lim_{x\to\infty} e^{-x}\).", "Think about the graph's asymptote.", "Both are 0.")],
        [mc(r"The range of \(3^x\) is:", ["all real numbers", r"\([0, \infty)\)", r"\((0, \infty)\)", r"\((1, \infty)\)"], 2, "It's always positive but never reaches 0."),
         mc(r"\(e^{3}\cdot e^{-1} =\)", [r"\(e^2\)", r"\(e^{-3}\)", r"\(e^4\)", r"\(2e\)"], 0, "Add the exponents."),
         mc(r"$1000 invested at 5% compounded continuously for 10 years grows to about:", ["$1500", "$1628.89", "$1050", "$1648.72"], 3,
            r"\(1000e^{0.05\cdot 10} = 1000e^{0.5}\).")],
    ),
    lesson(
        "trig-functions", 4, "Trigonometric Functions & Their Derivatives", "trig sine cosine tangent unit circle radians identities derivative sin cos tan sec",
        "Intermediate", 30, ["derivative-rules", "limits-algebraic"],
        r"On the unit circle, the point at angle \(\theta\) (in <b>radians</b>) is \((\cos\theta, \sin\theta)\). Calculus "
        r"always uses radians. The two key limits \(\frac{\sin x}{x} \to 1\) and \(\frac{1 - \cos x}{x} \to 0\) give the "
        r"derivatives of sine and cosine, and the others follow. Learn the six derivatives; the cosine-family "
        r"ones (\(\cos\), \(\csc\), \(\cot\)) all have a minus sign.",
        [
            ["Unit circle and radians", r"(\cos\theta, \sin\theta),\qquad \pi \text{ rad} = 180^\circ"],
            ["Identities", r"\sin^2x + \cos^2x = 1,\qquad \tan x = \frac{\sin x}{\cos x}"],
            ["Sine and cosine", r"\frac{d}{dx}\sin x = \cos x,\qquad \frac{d}{dx}\cos x = -\sin x"],
            ["Tangent and secant", r"\frac{d}{dx}\tan x = \sec^2x,\qquad \frac{d}{dx}\sec x = \sec x\tan x"],
            ["Cosecant and cotangent", r"\frac{d}{dx}\csc x = -\csc x\cot x,\qquad \frac{d}{dx}\cot x = -\csc^2x"],
        ],
        ex(r"Use the definition to show \(\frac{d}{dx}\sin x = \cos x\).",
           [r"\(\sin(x + h) = \sin x\cos h + \cos x\sin h\).",
            r"So \(\frac{\sin(x+h) - \sin x}{h} = \sin x\cdot\frac{\cos h - 1}{h} + \cos x\cdot\frac{\sin h}{h}\).",
            r"As \(h \to 0\): \(\frac{\cos h - 1}{h} \to 0\) and \(\frac{\sin h}{h} \to 1\).",
            r"The limit is \(\sin x\cdot 0 + \cos x\cdot 1\)."],
           r"\(\frac{d}{dx}\sin x = \cos x\)"),
        ["Leaving your calculator in degree mode.",
         r"Getting the sign wrong: \((\cos x)' = -\sin x\).",
         r"Reading \(\sin^2x\) as \(\sin(x^2)\). It means \((\sin x)^2\)."],
        [pr(r"\(\frac{d}{dx}(3\sin x - 2\cos x)\)", "Differentiate each term.", r"\(3\cos x + 2\sin x\)"),
         pr(r"\(\frac{d}{dx}(x^2\sin x)\)", "Product rule.", r"\(2x\sin x + x^2\cos x\)"),
         pr(r"Exact value of \(\cos\frac{2\pi}{3}\).", r"\(\frac{2\pi}{3} = 120^\circ\) is in the second quadrant.", r"\(-\frac12\)")],
        [mc(r"\(\frac{d}{dx}\tan x =\)", [r"\(\sec x\tan x\)", r"\(-\csc^2x\)", r"\(\cot x\)", r"\(\sec^2x\)"], 3, r"Quotient rule on \(\frac{\sin x}{\cos x}\) gives \(\frac{1}{\cos^2x}\)."),
         mc(r"\(\sin\frac\pi6 =\)", [r"\(\frac12\)", r"\(\frac{\sqrt3}{2}\)", r"\(\frac{\sqrt2}{2}\)", "1"], 0, r"\(\frac\pi6 = 30^\circ\)."),
         mc(r"\(\frac{d}{dx}\cos x =\)", [r"\(\sin x\)", r"\(-\sin x\)", r"\(-\cos x\)", r"\(\sec x\)"], 1, "Cosine-family derivatives carry a minus sign.")],
    ),

    # ======================= WEEK 5: CHAIN & QUOTIENT RULES, IMPLICIT, LOGS =======================
    lesson(
        "chain-rule", 5, "Chain Rule", "chain rule composite function layers inside outside",
        "Intermediate", 25, ["derivative-rules", "trig-functions"],
        r"Use the chain rule whenever one function is inside another. Differentiate the <b>outside</b> function, leaving "
        r"the inside alone, then multiply by the derivative of the <b>inside</b>. With more layers, keep peeling: one "
        r"factor per layer.",
        [
            ["Leibniz form", r"\frac{dy}{dx} = \frac{dy}{du}\cdot\frac{du}{dx}"],
            ["Function form", r"\big[f(g(x))\big]' = f'(g(x))\,g'(x)"],
            ["Power of a function", r"\frac{d}{dx}\big[g(x)\big]^n = n\big[g(x)\big]^{n-1}g'(x)"],
            ["Three layers", r"\big[f(g(h(x)))\big]' = f'(g(h(x)))\cdot g'(h(x))\cdot h'(x)"],
        ],
        ex(r"Differentiate \(y = (3x^2 + 1)^5\).",
           [r"Outside: \(u^5\); inside: \(u = 3x^2 + 1\).",
            r"Outside derivative: \(5(3x^2 + 1)^4\).",
            r"Inside derivative: \(6x\). Multiply."],
           r"\(y' = 30x(3x^2 + 1)^4\)"),
        ["Forgetting to multiply by the inside's derivative.",
         "Changing the inside while differentiating the outside.",
         r"Missing a layer: \(\sin^2(3x)\) has three layers (square, sine, \(3x\))."],
        [pr(r"\(\frac{d}{dx}\sqrt{x^2 + 1}\)", r"Outside \(\sqrt{u}\), inside \(x^2 + 1\).", r"\(\frac{x}{\sqrt{x^2 + 1}}\)"),
         pr(r"\(\frac{d}{dx}\sin(4x)\)", r"Inside \(4x\).", r"\(4\cos(4x)\)"),
         pr(r"\(\frac{d}{dx}\cos^3x\)", r"Outside \(u^3\), inside \(\cos x\).", r"\(-3\cos^2x\sin x\)")],
        [mc(r"\(\frac{d}{dx}(2x + 1)^3 =\)", [r"\(3(2x + 1)^2\)", r"\(6(2x + 1)^2\)", r"\(6(2x + 1)^3\)", r"\(3(2x)^2\)"], 1, r"\(3(2x + 1)^2\cdot 2\)."),
         mc(r"\(\frac{d}{dx}\sin(x^2) =\)", [r"\(\cos(x^2)\)", r"\(\cos(2x)\)", r"\(2x\cos(x^2)\)", r"\(2x\sin(x^2)\)"], 2, "Outside cos, times the inside's derivative 2x."),
         mc(r"\(h(x) = f(g(x))\), \(g(1) = 3\), \(g'(1) = 2\), \(f'(3) = 5\). Then \(h'(1) =\)", ["10", "15", "6", "5"], 0, r"\(f'(g(1))\cdot g'(1) = 5\cdot 2\).")],
    ),
    lesson(
        "quotient-rule", 5, "Quotient Rule", "quotient rule division derivative fraction low d high",
        "Intermediate", 20, ["product-rule"],
        r"For a fraction of two functions, use the quotient rule: <b>low d-high minus high d-low, over low squared</b>. "
        r"The order in the numerator matters because of the minus sign. If the numerator is a constant, it's often "
        r"faster to rewrite as a negative power and use the chain rule.",
        [
            ["Quotient rule", r"\left(\frac fg\right)' = \frac{f'g - fg'}{g^2}"],
            ["Constant over a function", r"\left(\frac{c}{g}\right)' = -\frac{c\,g'}{g^2}"],
            ["Where tan' comes from", r"\left(\frac{\sin x}{\cos x}\right)' = \frac{\cos^2x + \sin^2x}{\cos^2x} = \sec^2x"],
        ],
        ex(r"Differentiate \(y = \dfrac{x^2 + 1}{x - 3}\).",
           [r"\(f = x^2 + 1\), \(f' = 2x\); \(g = x - 3\), \(g' = 1\).",
            r"\(\frac{2x(x - 3) - (x^2 + 1)(1)}{(x - 3)^2}\).",
            r"Simplify the top: \(2x^2 - 6x - x^2 - 1\)."],
           r"\(y' = \dfrac{x^2 - 6x - 1}{(x - 3)^2}\)"),
        [r"Reversing the order to \(fg' - f'g\), which flips the sign.",
         "Forgetting to square the denominator.",
         "Sign errors when subtracting the second product. Keep it in brackets."],
        [pr(r"\(\frac{d}{dx}\dfrac{x}{x + 1}\)", "Quotient rule.", r"\(\frac{(x + 1) - x}{(x + 1)^2} = \frac{1}{(x + 1)^2}\)"),
         pr(r"\(\frac{d}{dx}\dfrac{\sin x}{x}\)", r"\(f = \sin x\), \(g = x\).", r"\(\frac{x\cos x - \sin x}{x^2}\)"),
         pr(r"\(\frac{d}{dx}\dfrac{3}{x^2 + 1}\)", "Constant numerator shortcut.", r"\(-\frac{6x}{(x^2 + 1)^2}\)")],
        [mc(r"Using the quotient rule, \(\frac{d}{dx}\frac1x =\)", [r"\(\frac{1}{x^2}\)", r"\(\ln x\)", r"\(-\frac{1}{x^2}\)", r"\(-\frac1x\)"], 2, r"\(\frac{0\cdot x - 1\cdot 1}{x^2}\)."),
         mc(r"\(\frac{d}{dx}\dfrac{x}{x^2 + 1} =\)", [r"\(\frac{1}{2x}\)", r"\(\frac{x^2 - 1}{(x^2 + 1)^2}\)", r"\(\frac{1 + x^2}{(x^2 + 1)^2}\)", r"\(\frac{1 - x^2}{(x^2 + 1)^2}\)"], 3,
            r"\(\frac{(x^2 + 1) - x\cdot 2x}{(x^2 + 1)^2}\)."),
         mc(r"\(f = 2,\ f' = 1,\ g = 4,\ g' = 3\) at a point. Then \(\left(\frac fg\right)' =\)", [r"\(-\frac18\)", r"\(\frac{1}{3}\)", r"\(\frac{5}{8}\)", r"\(-\frac12\)"], 0,
            r"\(\frac{1\cdot 4 - 2\cdot 3}{16} = -\frac{2}{16}\).")],
    ),
    lesson(
        "implicit", 5, "Implicit Differentiation", "implicit dy/dx circle relation",
        "Intermediate", 20, ["chain-rule"],
        r"Sometimes \(x\) and \(y\) are tangled together (like \(x^2+y^2=25\)) and solving for \(y\) is messy. "
        r"Instead, differentiate <b>both sides</b> with respect to \(x\), treating \(y\) as a function of \(x\). "
        r"Every time you take the derivative of something with \(y\) in it, the chain rule adds a factor of "
        r"\(\frac{dy}{dx}\). Then solve for \(\frac{dy}{dx}\) like an algebra problem.",
        [
            [r"Chain rule on \(y\)", r"\frac{d}{dx}\left[y^n\right] = n\,y^{n-1}\frac{dy}{dx}"],
            [r"Product rule with \(y\)", r"\frac{d}{dx}[xy] = y + x\frac{dy}{dx}"],
        ],
        ex(r"Find \(\frac{dy}{dx}\) for the circle \(x^2+y^2=25\), and the slope at \((3,4)\).",
           [r"Differentiate both sides: \(2x + 2y\frac{dy}{dx} = 0\). (The 25 is a constant, so its derivative is 0.)",
            r"Move the \(x\) term over: \(2y\frac{dy}{dx} = -2x\).",
            r"Divide: \(\frac{dy}{dx} = -\frac{x}{y}\).",
            r"At \((3,4)\): \(-\frac34\)."],
           r"\(\frac{dy}{dx}=-\frac{x}{y}\), slope \(-\frac34\) at \((3,4)\)"),
        [r"Forgetting the \(\frac{dy}{dx}\) after differentiating a \(y\) term.",
         r"Forgetting the product rule on terms like \(xy\) or \(x^2y^3\).",
         r"Writing the derivative of the constant on the right as anything other than 0."],
        [pr(r"Find \(y'\) if \(x^3+y^3=6xy\).", r"Use the product rule on \(6xy\), then collect the \(y'\) terms on one side.",
            r"\(3x^2+3y^2y' = 6y+6xy'\Rightarrow y'=\frac{2y-x^2}{y^2-2x}\)"),
         pr(r"Find \(y'\) if \(\sin y = x\).", "Differentiate both sides with respect to x.", r"\(\cos y\cdot y' = 1\Rightarrow y'=\frac{1}{\cos y}\)")],
        [mc(r"\(\frac{d}{dx}\left[y^2\right]=\)", [r"\(2y\)", r"\(2y\frac{dy}{dx}\)", r"\(\frac{dy}{dx}\)", r"\(2x\)"], 1, r"Chain rule: \(y\) depends on \(x\)."),
         mc(r"If \(xy=1\), then \(\frac{dy}{dx}=\)", [r"\(-\frac{y}{x}\)", r"\(\frac{y}{x}\)", r"\(-\frac{x}{y}\)", r"\(\frac1x\)"], 0,
            r"Product rule: \(y + xy' = 0\), so \(y'=-\frac{y}{x}\).")],
    ),
    lesson(
        "log-functions", 5, "Logarithmic Functions", "logarithm log ln natural log laws change of base solve exponential equation",
        "Intermediate", 20, ["exponential-functions", "inverse-functions"],
        r"A logarithm is the inverse of an exponential: \(\log_b x\) is the exponent you put on \(b\) to get \(x\). The "
        r"natural log \(\ln\) uses base \(e\). Logs turn products into sums and powers into multiples, which is how you "
        r"solve equations where the variable is in an exponent. Logs are only defined for positive inputs.",
        [
            ["Definition", r"\log_b x = y \iff b^y = x,\qquad \ln x = \log_e x"],
            ["Log laws", r"\ln(ab) = \ln a + \ln b,\quad \ln\frac ab = \ln a - \ln b,\quad \ln(a^r) = r\ln a"],
            ["Inverse pair", r"e^{\ln x} = x\ (x \gt 0),\qquad \ln(e^x) = x"],
            ["Change of base", r"\log_b x = \frac{\ln x}{\ln b}"],
        ],
        ex(r"Solve \(3e^{2x} - 5 = 7\).",
           [r"Isolate the exponential: \(3e^{2x} = 12\), so \(e^{2x} = 4\).",
            r"Take \(\ln\) of both sides: \(2x = \ln 4\).",
            r"\(x = \frac{\ln 4}{2} = \frac{2\ln 2}{2}\)."],
           r"\(x = \ln 2 \approx 0.693\)"),
        [r"Splitting a log over addition: \(\ln(a + b) \ne \ln a + \ln b\).",
         r"Forgetting that \(\ln x\) needs \(x \gt 0\). Check solutions against the domain.",
         r"Writing \(\frac{\ln a}{\ln b} = \ln\frac ab\). That's not a log law."],
        [pr(r"Simplify \(\ln(e^5)\).", "Inverse functions cancel.", "5"),
         pr(r"Expand \(\ln\dfrac{x^2\sqrt{y}}{z}\).", "Product, quotient and power laws.", r"\(2\ln x + \frac12\ln y - \ln z\)"),
         pr(r"Solve \(\log_2 x + \log_2(x - 2) = 3\).", r"Combine: \(\log_2[x(x - 2)] = 3\), so \(x(x - 2) = 8\).", r"\(x = 4\) (reject \(x = -2\), outside the domain)")],
        [mc(r"\(\log_3 81 =\)", ["3", "4", "27", "9"], 1, r"\(3^4 = 81\)."),
         mc(r"\(\ln 1 =\)", ["1", "e", "0", "undefined"], 2, r"\(e^0 = 1\)."),
         mc(r"The solution of \(e^x = 10\) is:", [r"\(\ln 10\)", r"\(\log 10\)", r"\(\frac{10}{e}\)", r"\(e^{10}\)"], 0, r"Take \(\ln\) of both sides.")],
    ),
    lesson(
        "exp-log-derivatives", 5, "Derivatives of eˣ, aˣ & Logarithms", "derivative e^x 2^x a^x ln x log logarithmic differentiation natural",
        "Intermediate", 25, ["chain-rule", "log-functions"],
        r"\(e^x\) is its own derivative, which is what makes \(e\) special. Every other base picks up a factor of "
        r"\(\ln a\). The natural log differentiates to \(\frac1x\). Combine these with the chain rule constantly. For "
        r"functions like \(x^x\), where the variable is in both the base and the exponent, use <b>logarithmic "
        r"differentiation</b>: take \(\ln\) of both sides first.",
        [
            ["Exponentials", r"\frac{d}{dx}e^x = e^x,\qquad \frac{d}{dx}a^x = a^x\ln a"],
            ["Logarithms", r"\frac{d}{dx}\ln x = \frac1x,\qquad \frac{d}{dx}\log_b x = \frac{1}{x\ln b},\qquad \frac{d}{dx}\ln|x| = \frac1x"],
            ["With the chain rule", r"\frac{d}{dx}e^{g(x)} = g'(x)e^{g(x)},\qquad \frac{d}{dx}\ln g(x) = \frac{g'(x)}{g(x)}"],
            ["Logarithmic differentiation", r"\ln y = \ln f(x) \;\Rightarrow\; \frac{y'}{y} = \frac{d}{dx}\ln f(x)"],
        ],
        ex(r"Differentiate \(y = x^x\) (for \(x \gt 0\)).",
           [r"Neither the power rule nor the exponential rule applies. Take \(\ln\): \(\ln y = x\ln x\).",
            r"Differentiate both sides: \(\frac{y'}{y} = \ln x + x\cdot\frac1x = \ln x + 1\).",
            r"Multiply by \(y = x^x\)."],
           r"\(y' = x^x(\ln x + 1)\)"),
        [r"Using the power rule on \(2^x\): \((2^x)' \ne x\,2^{x-1}\). It's \(2^x\ln 2\).",
         r"Forgetting the chain rule: \((e^{3x})' = 3e^{3x}\).",
         r"Treating \(x^x\) as a power or an exponential. It needs logarithmic differentiation."],
        [pr(r"\(\frac{d}{dx}2^x\)", r"\(a^x\ln a\).", r"\(2^x\ln 2\)"),
         pr(r"\(\frac{d}{dx}\ln(x^2 + 1)\)", r"\(\frac{g'}{g}\).", r"\(\frac{2x}{x^2 + 1}\)"),
         pr(r"\(\frac{d}{dx}e^{x^2}\)", r"Inside \(x^2\).", r"\(2xe^{x^2}\)")],
        [mc(r"\(\frac{d}{dx}5^x =\)", [r"\(x\,5^{x-1}\)", r"\(5^x\)", r"\(\frac{5^x}{\ln 5}\)", r"\(5^x\ln 5\)"], 3, r"\(a^x\ln a\)."),
         mc(r"\(\frac{d}{dx}\ln(3x) =\)", [r"\(\frac1x\)", r"\(\frac{3}{x}\)", r"\(\frac{1}{3x}\)", r"\(3\ln x\)"], 0, r"\(\frac{3}{3x} = \frac1x\)."),
         mc(r"\(\frac{d}{dx}\big(xe^x\big) =\)", [r"\(e^x\)", r"\(e^x(x + 1)\)", r"\(xe^x\)", r"\(e^x(x - 1)\)"], 1, r"Product rule: \(e^x + xe^x\).")],
    ),

    # ======================= WEEK 6: CRITICAL POINTS & CURVE SKETCHING =======================
    lesson(
        "critical-points", 6, "Critical Points & the First Derivative Test", "critical point number increasing decreasing first derivative test local max min absolute extrema closed interval",
        "Intermediate", 30, ["chain-rule", "review-solving"],
        r"A <b>critical number</b> is where \(f' = 0\) or \(f'\) doesn't exist (but \(f\) does). These are the only "
        r"places a local max or min can happen. Make a <b>sign chart</b> for \(f'\): \(f\) increases where \(f' \gt 0\) "
        r"and decreases where \(f' \lt 0\). If \(f'\) changes from \(+\) to \(-\), it's a local max; from \(-\) to "
        r"\(+\), a local min. For absolute extrema on a closed interval, compare the values at the critical numbers "
        r"and the endpoints.",
        [
            ["Critical number", r"f'(c) = 0 \text{ or } f'(c) \text{ undefined},\ c \text{ in the domain}"],
            ["Increasing / decreasing", r"f' \gt 0 \Rightarrow f \nearrow,\qquad f' \lt 0 \Rightarrow f \searrow"],
            ["First derivative test", r"f': + \to - \Rightarrow \text{local max},\qquad - \to + \Rightarrow \text{local min}"],
            [r"Closed interval \([a, b]\)", r"\text{absolute extrema are among } f(a),\ f(b),\ f(\text{critical numbers})"],
        ],
        ex(r"Find and classify the critical points of \(f(x) = x^3 - 3x^2 - 9x + 2\).",
           [r"\(f'(x) = 3x^2 - 6x - 9 = 3(x - 3)(x + 1)\), so the critical numbers are \(x = -1\) and \(x = 3\).",
            r"Sign chart: \(x \lt -1\): \(+\); \(-1 \lt x \lt 3\): \(-\); \(x \gt 3\): \(+\).",
            r"\(+ \to -\) at \(x = -1\): local max, \(f(-1) = -1 - 3 + 9 + 2 = 7\).",
            r"\(- \to +\) at \(x = 3\): local min, \(f(3) = 27 - 27 - 27 + 2 = -25\)."],
           r"Local max \((-1, 7)\), local min \((3, -25)\)"),
        [r"Forgetting points where \(f'\) is undefined, like \(x = 0\) for \(x^{2/3}\).",
         r"Assuming \(f'(c) = 0\) guarantees an extremum. For \(x^3\) at 0, it doesn't.",
         "Including 'critical numbers' that aren't in the domain of f."],
        [pr(r"Classify the critical points of \(f(x) = x^4 - 4x^3\).", r"\(f' = 4x^2(x - 3)\). Check the sign on each side of 0 and 3.",
            r"\(x = 0\): no change (\(-\) to \(-\)), neither. \(x = 3\): local min, \(f(3) = -27\)."),
         pr(r"Find the critical numbers of \(f(x) = x^{2/3}\).", r"\(f'(x) = \frac{2}{3x^{1/3}}\).", r"\(x = 0\) (\(f'\) undefined); it's a local min."),
         pr(r"Absolute max and min of \(f(x) = x^2 - 4x\) on \([0, 5]\).", r"Critical number \(x = 2\). Compare \(f(0), f(2), f(5)\).", r"Max 5 at \(x = 5\), min \(-4\) at \(x = 2\)")],
        [mc(r"The critical number of \(f(x) = x^2 - 6x\) is:", [r"\(x = 6\)", r"\(x = 3\)", r"\(x = 0\)", r"\(x = -3\)"], 1, r"\(f' = 2x - 6 = 0\)."),
         mc(r"If \(f'\) changes from negative to positive at \(c\), then \(f\) has:", ["a local max at c", "an inflection point at c", "a local min at c", "nothing special at c"], 2, "Down, then up: a valley."),
         mc(r"\(f(x) = x^3\) at \(x = 0\) has:", ["a local max", "a local min", "an absolute min", "neither (f' doesn't change sign)"], 3, r"\(f' = 3x^2 \ge 0\) on both sides.")],
    ),
    lesson(
        "concavity", 6, "Concavity & the Second Derivative Test", "concave up down inflection point second derivative test classify",
        "Intermediate", 25, ["critical-points"],
        r"The second derivative tells you which way a graph bends. \(f'' \gt 0\) means <b>concave up</b> (like a cup), "
        r"and \(f'' \lt 0\) means <b>concave down</b> (like a cap). An <b>inflection point</b> is where the concavity "
        r"actually changes. The <b>second derivative test</b> classifies a critical point quickly: concave up there "
        r"means a min, concave down means a max.",
        [
            ["Concavity", r"f'' \gt 0 \Rightarrow \text{concave up},\qquad f'' \lt 0 \Rightarrow \text{concave down}"],
            ["Inflection point", r"f'' \text{ changes sign at } c\ (f \text{ continuous at } c)"],
            [r"Second derivative test (\(f'(c) = 0\))", r"f''(c) \gt 0 \Rightarrow \text{min},\quad f''(c) \lt 0 \Rightarrow \text{max},\quad f''(c) = 0 \Rightarrow \text{inconclusive}"],
        ],
        ex(r"Concavity and inflection points of \(f(x) = x^3 - 3x^2 - 9x + 2\).",
           [r"\(f''(x) = 6x - 6\), which is zero at \(x = 1\).",
            r"\(x \lt 1\): \(f'' \lt 0\) (concave down); \(x \gt 1\): \(f'' \gt 0\) (concave up). It changes, so \(x = 1\) is an inflection point.",
            r"\(f(1) = 1 - 3 - 9 + 2 = -9\).",
            r"Second derivative test: \(f''(-1) = -12 \lt 0\) (max) and \(f''(3) = 12 \gt 0\) (min), matching the first derivative test."],
           r"Inflection point \((1, -9)\); concave down on \((-\infty, 1)\), up on \((1, \infty)\)"),
        [r"Calling every zero of \(f''\) an inflection point. For \(x^4\), \(f''(0) = 0\) but there's no change.",
         r"Treating \(f''(c) = 0\) as 'neither'. The test is inconclusive; use the first derivative test.",
         "Mixing up concavity (bending) with increasing/decreasing (direction)."],
        [pr(r"Inflection points of \(f(x) = x^4 - 6x^2\).", r"\(f'' = 12x^2 - 12\).", r"\(x = \pm 1\): the points \((\pm 1, -5)\)"),
         pr(r"Is \(x = 0\) an inflection point of \(f(x) = x^4\)?", r"Check the sign of \(f'' = 12x^2\) on both sides.", "No: f'' ≥ 0 on both sides, so concavity doesn't change."),
         pr(r"Classify the critical points of \(f(x) = 2x^3 + 3x^2 - 12x\).", r"\(f' = 6(x + 2)(x - 1)\), \(f'' = 12x + 6\).", r"\(f''(-2) = -18\): local max; \(f''(1) = 18\): local min")],
        [mc(r"\(f'(c) = 0\) and \(f''(c) \lt 0\). Then \(c\) is a:", ["local max", "local min", "inflection point", "can't tell"], 0, "Concave down at a flat point: a peak."),
         mc(r"The inflection point of \(f(x) = x^3\) is at:", [r"\(x = 1\)", r"\(x = -1\)", "there is none", r"\(x = 0\)"], 3, r"\(f'' = 6x\) changes sign at 0."),
         mc(r"For \(f(x) = x^4\) at \(x = 0\), the second derivative test is:", ["a max", "inconclusive", "a min", "an inflection point"], 1, r"\(f''(0) = 0\). (It's actually a min, by the first derivative test.)")],
    ),
    lesson(
        "curve-sketching", 6, "Curve Sketching", "curve sketching graph asymptotes intercepts symmetry increasing concavity checklist",
        "Advanced", 35, ["concavity", "limits-infinity"],
        r"Curve sketching puts everything together. Work through a checklist, then plot the key points and connect "
        r"them with the right shape: <b>domain</b>, <b>intercepts</b>, <b>symmetry</b>, <b>asymptotes</b>, then \(f'\) "
        r"for increasing/decreasing and extrema, and \(f''\) for concavity and inflection points.",
        [
            ["1. Domain, intercepts, symmetry", r"f(-x) = f(x)\ (\text{even, } y\text{-axis}),\qquad f(-x) = -f(x)\ (\text{odd, origin})"],
            ["2. Asymptotes", r"\text{vertical: } f \to \pm\infty \text{ as } x \to a;\qquad \text{horizontal: } \lim_{x\to\pm\infty} f(x)"],
            [r"3. First derivative", r"f' \text{ sign chart} \Rightarrow \text{increasing/decreasing, local extrema}"],
            [r"4. Second derivative", r"f'' \text{ sign chart} \Rightarrow \text{concavity, inflection points}"],
        ],
        ex(r"Sketch \(f(x) = \dfrac{x}{x^2 + 1}\).",
           [r"Domain: all reals. Intercept: \((0, 0)\). Odd function (symmetric about the origin).",
            r"Horizontal asymptote \(y = 0\) (the bottom has higher degree); no vertical asymptotes.",
            r"\(f'(x) = \frac{1 - x^2}{(x^2 + 1)^2}\): increasing on \((-1, 1)\), decreasing elsewhere. Min \(\left(-1, -\frac12\right)\), max \(\left(1, \frac12\right)\).",
            r"\(f''(x) = \frac{2x(x^2 - 3)}{(x^2 + 1)^3}\): inflection points at \(x = 0\) and \(x = \pm\sqrt3\)."],
           r"An S-shaped curve through the origin, peaking at \(\left(1, \frac12\right)\), dipping to \(\left(-1, -\frac12\right)\), and flattening toward \(y = 0\) on both ends"),
        ["Skipping the asymptotes, which control the shape at the ends.",
         r"Mixing up what \(f'\) tells you (direction) and what \(f''\) tells you (bending).",
         "Not checking that the sign actually changes at each candidate point."],
        [pr(r"Sketch \(f(x) = x^3 - 3x\): list the key features.", r"\(f' = 3(x^2 - 1)\), \(f'' = 6x\).",
            r"Intercepts \(0, \pm\sqrt3\); odd; max \((-1, 2)\); min \((1, -2)\); inflection \((0, 0)\)"),
         pr(r"Key features of \(f(x) = \dfrac{1}{x - 2}\).", r"Asymptotes first, then the sign of \(f' = -\frac{1}{(x - 2)^2}\).",
            r"VA \(x = 2\), HA \(y = 0\); decreasing on both pieces; concave down for \(x \lt 2\), up for \(x \gt 2\)"),
         pr(r"Inflection points of \(f(x) = x^4 - 4x^3\).", r"\(f'' = 12x^2 - 24x = 12x(x - 2)\).", r"\(x = 0\) and \(x = 2\): the points \((0, 0)\) and \((2, -16)\)")],
        [mc(r"The horizontal asymptote of \(f(x) = \dfrac{2x^2}{x^2 - 4}\) is:", [r"\(y = 0\)", r"\(y = 2\)", r"\(x = \pm 2\)", "none"], 1, "Equal degrees: the ratio of leading coefficients."),
         mc(r"An even function is symmetric about:", ["the origin", r"the line \(y = x\)", r"the \(y\)-axis", r"the \(x\)-axis"], 2, r"\(f(-x) = f(x)\)."),
         mc(r"On an interval with \(f' \gt 0\) and \(f'' \lt 0\), the graph is:", ["increasing and concave down", "increasing and concave up", "decreasing and concave down", "decreasing and concave up"], 0,
            "Rising, but bending downward (flattening out).")],
    ),
]
