"""What beginners call each topic.

Someone new to calculus doesn't search for "Limit Definition of the Derivative". They type
"rate of change", "slope of a curve" or "how fast". EVERYDAY[lesson id] lists those words and
phrases, so the site's search can lead from the learner's words to the right lesson.
lessons.py adds them to each lesson as "also", next to the other names from search_terms.py.
"""

EVERYDAY = {
    "review-factoring": ["factorise", "factorize", "factoring quadratics", "factoring polynomials", "common factor",
                         "ac method"],
    "review-expanding": ["multiply out", "expanding brackets", "parentheses", "distributive property",
                         "multiplying binomials"],
    "review-simplifying": ["fractions", "exponents", "powers", "negative exponents", "square roots",
                           "common denominator", "algebra", "cancel"],
    "review-solving": ["equations", "inequalities", "solve for x", "roots of a quadratic", "zeros", "discriminant"],
    "review-graphing": ["what is a function", "functions", "slope of a line", "straight line", "equation of a line",
                        "vertex", "domain and range"],
    "limits": ["what is a limit", "limits", "approaches", "gets close to", "left hand limit", "right hand limit",
               "does not exist", "dne"],
    "limits-algebraic": ["how to find a limit", "indeterminate", "zero over zero", "plug in", "sandwich theorem"],
    "limits-infinity": ["horizontal asymptote", "vertical asymptote", "goes to infinity", "x approaches infinity",
                        "end behavior", "blows up"],
    "epsilon-delta": ["epsilon delta proof", "formal definition of a limit", "prove a limit", "proofs"],
    "continuity": ["continuous function", "hole", "jump", "break in the graph", "types of discontinuity"],
    "derivative-definition": ["what is a derivative", "derivative", "derivatives", "rate of change",
                              "instantaneous rate of change", "slope of a curve", "slope at a point", "how fast",
                              "speed", "velocity", "tangent", "h approaches 0", "differentiate", "differentiation"],
    "derivative-rules": ["how to differentiate", "differentiation rules", "derivative rules",
                         "derivative of x squared", "derivative of a polynomial", "d/dx", "derivative notation",
                         "derivative of a constant"],
    "product-rule": ["derivative of a product", "two functions multiplied", "f times g"],
    "inverse-functions": ["inverse", "undo a function", "inverse sine", "inverse tangent", "f inverse"],
    "exponential-functions": ["exponential", "eulers number", "growth and decay", "doubling", "half life"],
    "trig-functions": ["sin", "cos", "tan", "trigonometry", "derivative of sin", "derivative of cos",
                       "derivative of tan", "trig identities", "csc", "cot", "degrees"],
    "chain-rule": ["function inside a function", "composite functions", "nested functions",
                   "derivative of a composition"],
    "quotient-rule": ["derivative of a fraction", "derivative of a quotient", "one function divided by another"],
    "implicit": ["y is not alone", "differentiate both sides", "derivative of a circle", "implicit derivative"],
    "log-functions": ["logs", "logarithms", "log rules", "solve for an exponent"],
    "exp-derivatives": ["derivative of e^x", "derivative of a^x", "derivative of 2^x", "derivative of e to the x",
                        "derivative of an exponential"],
    "exp-log-derivatives": ["derivative of ln", "derivative of ln x", "derivative of log", "derivative of e^2x",
                            "x to the x"],
    "critical-points": ["max and min", "maximum and minimum", "maxima and minima", "local maximum", "local minimum",
                        "turning point", "increasing and decreasing", "highest point", "lowest point"],
    "concavity": ["concave up", "concave down", "inflection points", "second derivative", "acceleration"],
    "curve-sketching": ["sketch a graph", "graphing with derivatives", "draw the curve"],
    "ivt": ["a root exists", "show there is a solution"],
    "mvt": ["rolles theorem", "average rate of change"],
    "newtons-method": ["approximate a root", "find a root numerically"],
    "optimization": ["max and min", "maximize", "minimize", "largest area", "smallest cost", "biggest", "best dimensions"],
    "antiderivatives": ["integral", "integrals", "integration", "integrate", "reverse derivative",
                        "undo a derivative", "plus c", "what is an integral"],
    "area-under-curves": ["area under a curve", "sigma notation", "summation", "approximate area"],
    "ftc": ["evaluate a definite integral", "integral and derivative connection"],
    "u-sub": ["u substitution", "substitution rule", "integration by substitution"],
    "area-between": ["area between two curves", "region between curves"],
    "average-value": ["average of a function"],
    "de-intro": ["differential equations", "ode", "what is a differential equation", "y prime"],
    "separable-de": ["separate variables", "exponential growth", "population growth", "newtons law of cooling",
                     "half life"],
    "second-order-linear": ["second order differential equation", "y double prime", "springs", "oscillation"],
    "direction-fields": ["slope fields", "equilibrium solutions", "stable and unstable"],
    "eulers-method": ["euler", "numerical solution"],
    "multivariable-intro": ["functions of two variables", "multivariable calculus", "3d graphs", "calc 3"],
    "partial-derivatives": ["partials", "partial derivative", "curly d", "derivative with two variables"],
    "tangent-planes": ["total differential", "estimate with differentials"],
    "related-rates": ["rates of change over time", "ladder problem", "balloon problem", "how fast is it changing"],
    "lhopital": ["lhopitals rule", "l hopital", "hospital rule", "infinity over infinity"],
    "ibp": ["integration by parts", "by parts"],
    "trig-integrals": ["trig substitution", "integrals of sin and cos", "powers of sine and cosine"],
    "partial-fractions": ["split a fraction", "integrating rational functions"],
    "improper-integrals": ["integral to infinity", "converge or diverge"],
    "series-tests": ["infinite series", "does the series converge", "convergence tests", "ratio test",
                     "geometric series", "sequences"],
    "taylor": ["taylor series", "maclaurin series", "polynomial approximation"],
    "parametric-polar": ["parametric equations", "polar coordinates", "polar curves"],
    "vectors": ["dot product", "cross product", "length of a vector", "angle between vectors"],
    "lines-planes": ["equation of a plane", "equation of a line in 3d", "normal vector"],
    "partial-gradient": ["gradient", "directional derivative", "steepest", "nabla"],
    "lagrange": ["constrained optimization", "max with a constraint"],
    "double-triple": ["double integral", "triple integral", "volume under a surface", "iterated integral"],
    "cyl-sph": ["cylindrical coordinates", "spherical coordinates"],
    "vector-calc": ["line integrals", "greens theorem", "stokes theorem", "divergence theorem",
                    "work done by a force", "vector fields"],
}