r"""Weeks 7-12: IVT/MVT, Newton's method & optimization; integrals; substitution & areas;
differential equations; direction fields, Euler's method & multivariable functions;
partial derivatives & tangent planes."""
from lesson_helpers import ex, lesson, mc, pr

WEEKS_7_12 = [
    # ======================= WEEK 7: IVT, MVT, NEWTON'S METHOD, OPTIMIZATION =======================
    lesson(
        "ivt", 7, "Intermediate Value Theorem", "intermediate value theorem ivt root existence continuous sign change",
        "Intermediate", 15, ["continuity"],
        r"If a function is <b>continuous</b> on \([a, b]\), it can't skip any heights: it takes every value between "
        r"\(f(a)\) and \(f(b)\). The most common use is proving a root exists: if \(f(a)\) and \(f(b)\) have opposite "
        r"signs, then \(f(c) = 0\) somewhere between them. The IVT tells you a solution exists, not where it is.",
        [
            ["Intermediate Value Theorem", r"f \text{ continuous on } [a, b],\ N \text{ between } f(a), f(b) \;\Rightarrow\; \exists c \in (a, b): f(c) = N"],
            ["Root version", r"f(a) \lt 0 \lt f(b) \;\Rightarrow\; f(c) = 0 \text{ for some } c \in (a, b)"],
        ],
        ex(r"Show that \(x^3 + x - 1 = 0\) has a solution between 0 and 1.",
           [r"Let \(f(x) = x^3 + x - 1\). It's a polynomial, so it's continuous on \([0, 1]\).",
            r"\(f(0) = -1 \lt 0\) and \(f(1) = 1 \gt 0\).",
            r"0 is between \(f(0)\) and \(f(1)\), so by the IVT there's a \(c\) in \((0, 1)\) with \(f(c) = 0\)."],
           r"A root exists in \((0, 1)\)"),
        [r"Forgetting to check continuity. \(\frac1x\) goes from \(-1\) to \(1\) on \([-1, 1]\) but never equals 0.",
         "Thinking the IVT says how many solutions there are, or where. It only guarantees at least one.",
         "Using it backwards: a function can have a root even without a sign change."],
        [pr(r"Show \(\cos x = x\) has a solution in \(\left(0, \frac\pi2\right)\).", r"Use \(g(x) = \cos x - x\).", r"\(g(0) = 1 \gt 0\), \(g\left(\frac\pi2\right) = -\frac\pi2 \lt 0\), and \(g\) is continuous."),
         pr(r"Show \(x^4 = x + 5\) has a solution in \((1, 2)\).", r"\(f(x) = x^4 - x - 5\).", r"\(f(1) = -5\), \(f(2) = 9\): a root exists."),
         pr(r"\(f(x) = \frac1x\) has \(f(-1) = -1\) and \(f(1) = 1\), but no root. Why doesn't this break the IVT?", "Check the hypothesis.", r"\(f\) isn't continuous on \([-1, 1]\) (it's undefined at 0).")],
        [mc("The IVT requires the function to be:", ["differentiable", r"continuous on \([a, b]\)", "increasing", "a polynomial"], 1, "Continuity is the only hypothesis."),
         mc(r"\(f\) is continuous with \(f(1) = -2\) and \(f(3) = 4\). Is there a root in \((1, 3)\)?", ["Yes, guaranteed", "No", "Only if f is a polynomial", "Only if f is increasing"], 0, "0 is between −2 and 4."),
         mc("The IVT guarantees:", ["exactly one c", "the value of c", "at least one c", "that f is increasing"], 2, "It's an existence result.")],
    ),
    lesson(
        "mvt", 7, "Mean Value Theorem", "mvt rolle mean value average slope",
        "Intermediate", 15, ["derivative-rules", "continuity"],
        r"If a function is smooth on an interval, then at some point the <b>instantaneous</b> slope equals the "
        r"<b>average</b> slope over the whole interval. If you drive 120 km in 2 hours, at some moment your "
        r"speedometer read exactly 60 km/h. <b>Rolle's theorem</b> is the special case where the endpoints are at the same height, so somewhere \(f'=0\).",
        [
            ["Mean Value Theorem", r"f'(c) = \frac{f(b)-f(a)}{b-a} \quad\text{for some } c\in(a,b)"],
            ["Requirements", r"f \text{ continuous on } [a,b],\ \text{differentiable on } (a,b)"],
            ["Rolle's theorem", r"f(a)=f(b) \;\Rightarrow\; f'(c)=0 \text{ for some } c\in(a,b)"],
        ],
        ex(r"Find \(c\) for \(f(x)=x^2\) on \([1,3]\).",
           [r"Average slope: \(\frac{f(3)-f(1)}{3-1}=\frac{9-1}{2}=4\).",
            r"Set \(f'(c)=2c\) equal to 4.",
            r"\(c=2\), which is inside \((1,3)\). ✓"],
           r"\(c=2\)"),
        [r"Not checking the requirements. For example \(|x|\) is not differentiable at 0, so MVT can fail on \([-1,1]\).",
         r"Giving a \(c\) that is outside the interval.",
         r"Thinking MVT tells you where \(c\) is. It only promises that \(c\) exists."],
        [pr(r"Find \(c\) for \(f(x)=x^3\) on \([0,2]\).", "Average slope is 8/2 = 4.", r"\(3c^2=4\Rightarrow c=\frac{2}{\sqrt3}\approx 1.155\)"),
         pr("You drive 120 km in 2 hours. Explain why your speed was exactly 60 km/h at some moment.",
            "Position is a smooth function of time.", "The average speed is 60 km/h, so by the MVT the instantaneous speed equals 60 at some time.")],
        [mc("The MVT requires:", [r"Continuous on \([a,b]\) and differentiable on \((a,b)\)", "Only continuity", r"\(f(a)=f(b)\)", r"\(f\) is increasing"], 0,
            "Both conditions are needed."),
         mc(r"For \(f(x)=x^2\) on \([0,4]\), the MVT point is \(c=\)", ["1", "2", "3", "4"], 1, r"Average slope is 4 and \(2c=4\).")],
    ),
    lesson(
        "newtons-method", 7, "Newton's Method", "newton's method newton raphson root approximation iteration tangent line",
        "Intermediate", 20, ["derivative-rules"],
        r"Newton's method finds roots of \(f(x) = 0\) numerically. Start with a guess \(x_0\), draw the tangent line "
        r"there, and use where it crosses the \(x\)-axis as the next guess. Repeat until the digits stop changing. "
        r"It converges very fast when the guess is good, but it fails if a tangent is horizontal (\(f'(x_n) = 0\)).",
        [
            ["Newton's method", r"x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}"],
            ["Where it comes from", r"\text{the tangent } y = f(x_n) + f'(x_n)(x - x_n) \text{ crosses } y = 0 \text{ at } x_{n+1}"],
            ["When to stop", r"|x_{n+1} - x_n| \text{ is smaller than the accuracy you need}"],
        ],
        ex(r"Approximate \(\sqrt2\) using \(f(x) = x^2 - 2\) and \(x_0 = 1\).",
           [r"\(f'(x) = 2x\), so \(x_{n+1} = x_n - \frac{x_n^2 - 2}{2x_n}\).",
            r"\(x_1 = 1 - \frac{-1}{2} = 1.5\).",
            r"\(x_2 = 1.5 - \frac{0.25}{3} \approx 1.41667\).",
            r"\(x_3 \approx 1.41667 - \frac{0.00694}{2.83333} \approx 1.41422\)."],
           r"\(\sqrt2 \approx 1.4142\) after three steps"),
        [r"Adding instead of subtracting \(\frac{f(x_n)}{f'(x_n)}\).",
         r"Starting where \(f'(x_0) = 0\): the tangent is horizontal and never crosses the axis.",
         "A poor starting guess can converge to a different root, or not converge at all."],
        [pr(r"One step of Newton's method on \(f(x) = x^3 - 2x - 5\) from \(x_0 = 2\).", r"\(f(2) = -1\), \(f'(2) = 10\).", r"\(x_1 = 2.1\)"),
         pr(r"Write the Newton formula for approximating \(\sqrt[3]{5}\).", r"Use \(f(x) = x^3 - 5\).", r"\(x_{n+1} = x_n - \frac{x_n^3 - 5}{3x_n^2}\)"),
         pr(r"Why does \(x_0 = 0\) fail for \(f(x) = x^2 - 2\)?", r"Compute \(f'(0)\).", r"\(f'(0) = 0\), so the formula divides by zero (horizontal tangent).")],
        [mc("Newton's method uses:", [r"\(x_{n+1} = x_n + \frac{f(x_n)}{f'(x_n)}\)", r"\(x_{n+1} = x_n - \frac{f'(x_n)}{f(x_n)}\)", r"\(x_{n+1} = x_n - f(x_n)\)", r"\(x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)}\)"], 3, "Subtract f over f-prime."),
         mc(r"For \(f(x) = x^2 - 5\) with \(x_0 = 2\), \(x_1 =\)", ["2.25", "2.5", "1.75", "2.2"], 0, r"\(2 - \frac{-1}{4} = 2.25\)."),
         mc(r"Geometrically, \(x_{n+1}\) is:", [r"the \(y\)-intercept of the tangent", r"where the tangent at \(x_n\) crosses the \(x\)-axis", "a critical point", "the midpoint of an interval"], 1, "That's the whole idea.")],
    ),
    lesson(
        "optimization", 7, "Optimization", "max min optimization word problems critical points extrema",
        "Intermediate", 30, ["critical-points"],
        r"Maximum and minimum values happen at <b>critical points</b> (where \(f'=0\) or \(f'\) doesn't exist) or at the "
        r"<b>endpoints</b> of an interval. In word problems: write the thing you want to maximize, use the constraint "
        r"to get it down to one variable, differentiate, set it to zero, then check that you found a max (or min).",
        [
            ["Critical points", r"f'(c)=0 \text{ or } f'(c) \text{ undefined}"],
            ["Second derivative test", r"f''(c)\gt 0 \Rightarrow \text{local min}, \qquad f''(c)\lt 0 \Rightarrow \text{local max}"],
            [r"Closed interval \([a,b]\)", r"\text{compare } f(a),\ f(b),\ f(\text{each critical point})"],
        ],
        ex(r"You have 100 m of fence for a rectangle. What dimensions give the most area?",
           [r"Constraint: \(2x+2y=100\), so \(y=50-x\).",
            r"Area in one variable: \(A=x(50-x)=50x-x^2\).",
            r"\(A'=50-2x=0\Rightarrow x=25\).",
            r"Check: \(A''=-2\lt 0\), so it is a max. Then \(y=25\)."],
           r"A 25 m × 25 m square, area 625 m²"),
        ["Forgetting to check the endpoints on a closed interval.",
         "Not checking whether a critical point is a max or a min.",
         "Differentiating the constraint instead of the quantity you want to optimize."],
        [pr(r"Absolute max and min of \(f(x)=x^3-3x\) on \([0,2]\).", r"\(f'=3x^2-3=0\Rightarrow x=1\). Check \(x=0,1,2\).",
            r"\(f(0)=0,\ f(1)=-2,\ f(2)=2\). Max 2 at \(x=2\), min \(-2\) at \(x=1\)."),
         pr("Two positive numbers add up to 20. Maximize their product.", r"\(P=x(20-x)\).", r"\(x=10,\ 10\). Product 100."),
         pr(r"An open-top box is made from a 12 × 12 cm sheet by cutting squares of side \(x\) from each corner. Which \(x\) maximizes the volume?",
            r"\(V = x(12 - 2x)^2\) for \(0 \lt x \lt 6\).", r"\(V' = (12 - 2x)(12 - 6x) = 0\) gives \(x = 2\) cm (volume 128 cm³).")],
        [mc(r"The critical point of \(f(x)=x^2-4x\) is:", [r"\(x=2\)", r"\(x=4\)", r"\(x=0\)", r"\(x=-2\)"], 0, r"\(f'=2x-4=0\)."),
         mc(r"If \(f'(c)=0\) and \(f''(c)=3\), then at \(c\) there is a:", ["Local max", "Local min", "Inflection point", "Nothing special"], 1,
            "Positive second derivative means concave up, which is a valley (min).")],
    ),

    # ======================= WEEK 8: ANTIDERIVATIVES, AREAS UNDER CURVES, FTC =======================
    lesson(
        "antiderivatives", 8, "Antiderivatives & Indefinite Integrals", "antiderivative indefinite integral +C reverse power rule initial value problem",
        "Beginner", 25, ["derivative-rules", "trig-functions", "exp-log-derivatives"],
        r"An antiderivative reverses differentiation: \(F\) is an antiderivative of \(f\) if \(F' = f\). Since constants "
        r"differentiate to 0, every antiderivative has a <b>\(+C\)</b>. The indefinite integral \(\int f\,dx\) means the "
        r"whole family \(F(x) + C\). An <b>initial condition</b> like \(f(1) = 5\) picks out the one value of \(C\).",
        [
            ["Definition", r"\int f(x)\,dx = F(x) + C \iff F'(x) = f(x)"],
            ["Reverse power rule", r"\int x^n\,dx = \frac{x^{n+1}}{n+1} + C\quad (n \ne -1),\qquad \int \frac1x\,dx = \ln|x| + C"],
            ["Exponential and trig", r"\int e^x\,dx = e^x + C,\quad \int\cos x\,dx = \sin x + C,\quad \int\sin x\,dx = -\cos x + C,\quad \int\sec^2x\,dx = \tan x + C"],
            ["Linearity", r"\int\big[af(x) + bg(x)\big]dx = a\int f\,dx + b\int g\,dx"],
        ],
        ex(r"Find \(f\) if \(f'(x) = 6x^2 - 4x + 1\) and \(f(1) = 5\).",
           [r"Antidifferentiate term by term: \(f(x) = 2x^3 - 2x^2 + x + C\).",
            r"Use the condition: \(f(1) = 2 - 2 + 1 + C = 1 + C = 5\).",
            r"So \(C = 4\)."],
           r"\(f(x) = 2x^3 - 2x^2 + x + 4\)"),
        [r"Forgetting \(+C\) on indefinite integrals.",
         r"Using the power rule on \(\frac1x\) (you'd divide by 0). It's \(\ln|x|\).",
         r"Sign of \(\int\sin x\,dx = -\cos x + C\). And \(\int fg\,dx \ne \int f\,dx\cdot\int g\,dx\)."],
        [pr(r"\(\displaystyle\int\left(3x^2 - \frac2x + e^x\right)dx\)", "Term by term.", r"\(x^3 - 2\ln|x| + e^x + C\)"),
         pr(r"\(\displaystyle\int\sqrt{x}\,dx\)", r"\(x^{1/2}\).", r"\(\frac23x^{3/2} + C\)"),
         pr(r"\(\displaystyle\int\frac{1}{x^2}\,dx\)", r"\(x^{-2}\).", r"\(-\frac1x + C\)")],
        [mc(r"\(\displaystyle\int x^4\,dx =\)", [r"\(4x^3 + C\)", r"\(x^5 + C\)", r"\(\frac{x^5}{5} + C\)", r"\(\frac{x^4}{4} + C\)"], 2, "Add 1 to the power and divide by the new power."),
         mc(r"\(\displaystyle\int\cos x\,dx =\)", [r"\(\sin x + C\)", r"\(-\sin x + C\)", r"\(\cos x + C\)", r"\(-\cos x + C\)"], 0, r"\((\sin x)' = \cos x\)."),
         mc(r"\(F'(x) = 2x\) and \(F(0) = 3\). Then \(F(x) =\)", [r"\(x^2\)", r"\(2x + 3\)", r"\(x^2 - 3\)", r"\(x^2 + 3\)"], 3, r"\(F = x^2 + C\) and \(C = 3\).")],
    ),
    lesson(
        "area-under-curves", 8, "Areas Under Curves & Riemann Sums", "area under curve riemann sum left right midpoint definite integral sigma rectangles",
        "Intermediate", 25, ["antiderivatives", "limits-infinity"],
        r"To find the area under a curve, chop \([a, b]\) into \(n\) strips of width \(\Delta x\), build a rectangle on "
        r"each, and add them up: that's a <b>Riemann sum</b>. Left, right and midpoint sums use different heights. "
        r"As \(n \to \infty\) the sum becomes exact: the <b>definite integral</b>. Area below the \(x\)-axis counts as "
        r"negative.",
        [
            ["Width and points", r"\Delta x = \frac{b - a}{n},\qquad x_i = a + i\,\Delta x"],
            ["Right Riemann sum", r"R_n = \sum_{i=1}^{n} f(x_i)\,\Delta x\quad (\text{left: } i = 0 \text{ to } n - 1)"],
            ["Definite integral", r"\int_a^b f(x)\,dx = \lim_{n\to\infty}\sum_{i=1}^{n} f(x_i)\,\Delta x"],
            ["Properties", r"\int_a^a f = 0,\qquad \int_b^a f = -\int_a^b f,\qquad \int_a^b f + \int_b^c f = \int_a^c f"],
        ],
        ex(r"Estimate the area under \(f(x) = x^2\) on \([0, 2]\) with a right sum, \(n = 4\).",
           [r"\(\Delta x = \frac{2 - 0}{4} = 0.5\). Right endpoints: \(0.5, 1, 1.5, 2\).",
            r"Heights: \(0.25, 1, 2.25, 4\), which add to \(7.5\).",
            r"Multiply by \(\Delta x\): \(7.5 \times 0.5\).",
            r"Since \(x^2\) is increasing on this interval, the right sum overestimates the true area (\(\frac83 \approx 2.67\))."],
           r"\(R_4 = 3.75\)"),
        [r"Getting \(\Delta x\) wrong. It's \(\frac{b - a}{n}\).",
         "Using the wrong endpoints (an off-by-one error between left and right sums).",
         "Confusing area (always positive) with the definite integral (signed)."],
        [pr(r"The left sum \(L_4\) for \(f(x) = x^2\) on \([0, 2]\).", r"Left endpoints \(0, 0.5, 1, 1.5\).", r"\((0 + 0.25 + 1 + 2.25)(0.5) = 1.75\)"),
         pr(r"The midpoint sum \(M_2\) for \(f(x) = x^3\) on \([0, 2]\).", r"\(\Delta x = 1\), midpoints \(0.5\) and \(1.5\).", r"\(0.125 + 3.375 = 3.5\) (the exact value is 4)"),
         pr(r"Use geometry to find \(\displaystyle\int_0^3 2x\,dx\).", "The region is a triangle.", r"\(\frac12\cdot 3\cdot 6 = 9\)")],
        [mc(r"\(\Delta x\) for \([1, 5]\) with \(n = 8\) is:", ["0.5", "4", "8", "0.25"], 0, r"\(\frac{5 - 1}{8}\)."),
         mc("For an increasing function, the right Riemann sum:", ["is exact", "overestimates", "underestimates", "can't be compared"], 1, "Each rectangle uses the highest point of its strip."),
         mc(r"\(\displaystyle\int_{-1}^{1} x\,dx =\)", ["1", "2", "0", r"\(\frac12\)"], 2, "The areas above and below the axis cancel.")],
    ),
    lesson(
        "ftc", 8, "Fundamental Theorem of Calculus", "fundamental theorem calculus ftc definite integral evaluate accumulation function net change",
        "Intermediate", 25, ["area-under-curves"],
        r"The Fundamental Theorem connects derivatives and integrals. <b>Part 1</b>: the accumulation function "
        r"\(\int_a^x f(t)\,dt\) has derivative \(f(x)\). <b>Part 2</b>: to evaluate a definite integral, find any "
        r"antiderivative \(F\) and compute \(F(b) - F(a)\). No more adding up rectangles.",
        [
            ["FTC part 1", r"\frac{d}{dx}\int_a^x f(t)\,dt = f(x)"],
            ["Part 1 with the chain rule", r"\frac{d}{dx}\int_a^{g(x)} f(t)\,dt = f(g(x))\,g'(x)"],
            ["FTC part 2", r"\int_a^b f(x)\,dx = F(b) - F(a),\quad F' = f"],
            ["Net change", r"\int_a^b F'(x)\,dx = F(b) - F(a)"],
        ],
        ex(r"Find the exact area under \(y = x^2\) on \([0, 2]\).",
           [r"An antiderivative is \(F(x) = \frac{x^3}{3}\).",
            r"FTC part 2: \(F(2) - F(0) = \frac83 - 0\).",
            r"That's between the left and right sums from the previous lesson (1.75 and 3.75)."],
           r"\(\frac83 \approx 2.67\)"),
        [r"Forgetting the chain rule in part 1 when the upper limit is something like \(x^2\).",
         r"Adding \(+C\) to a definite integral. It cancels, so leave it out.",
         r"Subtracting in the wrong order. It's \(F(b) - F(a)\): top minus bottom."],
        [pr(r"\(\displaystyle\int_1^4\sqrt{x}\,dx\)", r"\(F(x) = \frac23x^{3/2}\).", r"\(\frac23(8 - 1) = \frac{14}{3}\)"),
         pr(r"\(\frac{d}{dx}\displaystyle\int_0^{x^2}\cos t\,dt\)", "Part 1 plus the chain rule.", r"\(\cos(x^2)\cdot 2x\)"),
         pr(r"\(\displaystyle\int_0^\pi\sin x\,dx\)", r"\(F(x) = -\cos x\).", r"\(-\cos\pi + \cos 0 = 2\)")],
        [mc(r"\(\displaystyle\int_0^1 x^2\,dx =\)", [r"\(\frac12\)", "1", r"\(\frac23\)", r"\(\frac13\)"], 3, r"\(\left[\frac{x^3}{3}\right]_0^1\)."),
         mc(r"\(\frac{d}{dx}\displaystyle\int_2^x t^3\,dt =\)", [r"\(x^3\)", r"\(3x^2\)", r"\(\frac{x^4}{4}\)", r"\(x^3 - 8\)"], 0, "Part 1: replace t with x."),
         mc(r"\(\displaystyle\int_1^e\frac1x\,dx =\)", ["e", "1", "0", r"\(\frac1e\)"], 1, r"\(\ln e - \ln 1 = 1\).")],
    ),

    # ======================= WEEK 9: SUBSTITUTION, AREA BETWEEN CURVES, AVERAGE VALUE =======================
    lesson(
        "u-sub", 9, "Integration by Substitution", "substitution u-sub integral reverse chain rule change of variables",
        "Intermediate", 25, ["ftc", "chain-rule"],
        r"u-substitution is the <b>chain rule in reverse</b>. If the integrand contains a function and (a constant "
        r"multiple of) its derivative, let \(u\) be the inside function. Replace everything, including \(dx\), "
        r"with \(u\) and \(du\), so the integral becomes simple.",
        [
            ["Substitution", r"\int f(g(x))\,g'(x)\,dx = \int f(u)\,du,\qquad u=g(x),\ du=g'(x)\,dx"],
            ["Definite integrals: change the limits too", r"\int_a^b f(g(x))g'(x)\,dx = \int_{g(a)}^{g(b)} f(u)\,du"],
        ],
        ex(r"Compute \(\displaystyle\int 2x\cos(x^2)\,dx\).",
           [r"The inside function is \(x^2\), and its derivative \(2x\) is sitting right there. Let \(u=x^2\).",
            r"Then \(du=2x\,dx\).",
            r"The integral becomes \(\int\cos u\,du=\sin u+C\).",
            r"Substitute back: \(\sin(x^2)+C\)."],
           r"\(\sin(x^2)+C\)"),
        [r"Forgetting to convert \(dx\) into \(du\).",
         r"Leaving a mix of \(x\) and \(u\) in the integral.",
         r"Forgetting to change the limits on a definite integral (or to switch back to \(x\))."],
        [pr(r"\(\displaystyle\int x(x^2+1)^4\,dx\)", r"\(u=x^2+1,\ du=2x\,dx\).", r"\(\frac{1}{10}(x^2+1)^5+C\)"),
         pr(r"\(\displaystyle\int_0^1 e^{3x}\,dx\)", r"\(u=3x\), so the limits become 0 and 3.", r"\(\frac13(e^3-1)\)"),
         pr(r"\(\displaystyle\int\tan x\,dx\)", r"Write it as \(\frac{\sin x}{\cos x}\) and let \(u=\cos x\).", r"\(-\ln|\cos x|+C\)")],
        [mc(r"For \(\displaystyle\int 3x^2(x^3+5)^7\,dx\), the best choice of \(u\) is:", [r"\(x^2\)", r"\(x^3+5\)", r"\((x^3+5)^7\)", r"\(3x^2\)"], 1,
            r"Its derivative \(3x^2\) is already there."),
         mc(r"\(\displaystyle\int\frac{\ln x}{x}\,dx=\)", [r"\(\frac{(\ln x)^2}{2}+C\)", r"\(\ln(\ln x)+C\)", r"\(\frac{1}{x^2}+C\)", r"\(x\ln x+C\)"], 0,
            r"\(u=\ln x,\ du=\frac1x dx\), so you get \(\int u\,du\).")],
    ),
    lesson(
        "area-between", 9, "Area Between Curves", "area between curves top minus bottom intersection points integrate dy",
        "Intermediate", 25, ["ftc", "review-solving"],
        r"The area between two curves is the integral of <b>top minus bottom</b>. Find where the curves meet (solve "
        r"\(f(x) = g(x)\)) to get the limits. If the curves cross inside the interval, split the integral at the "
        r"crossing so you always subtract the lower curve from the upper one. Sometimes slicing horizontally "
        r"(integrating in \(y\), right minus left) is easier.",
        [
            [r"Area (with \(f \ge g\) on \([a, b]\))", r"A = \int_a^b\big[f(x) - g(x)\big]\,dx"],
            ["Limits of integration", r"\text{solve } f(x) = g(x)"],
            ["Curves that cross", r"A = \int_a^b\big|f(x) - g(x)\big|\,dx \quad (\text{split at the crossings})"],
            [r"Integrating in \(y\)", r"A = \int_c^d\big[x_{\text{right}}(y) - x_{\text{left}}(y)\big]\,dy"],
        ],
        ex(r"Find the area between \(y = x\) and \(y = x^2\).",
           [r"Intersections: \(x = x^2\), so \(x(x - 1) = 0\), giving \(x = 0\) and \(x = 1\).",
            r"On \([0, 1]\), \(x \ge x^2\) (test \(x = \frac12\)), so \(y = x\) is on top.",
            r"\(A = \int_0^1(x - x^2)\,dx = \left[\frac{x^2}{2} - \frac{x^3}{3}\right]_0^1\).",
            r"\(= \frac12 - \frac13\)."],
           r"\(\frac16\)"),
        ["Subtracting top from bottom, which gives a negative 'area'.",
         "Forgetting to split the integral where the curves cross.",
         "Using the wrong limits. They come from the intersection points."],
        [pr(r"Area between \(y = 4 - x^2\) and the \(x\)-axis.", r"Intersections at \(x = \pm 2\).", r"\(\int_{-2}^{2}(4 - x^2)\,dx = \frac{32}{3}\)"),
         pr(r"Area between \(y = x^2\) and \(y = 2x\).", r"They meet at \(x = 0\) and \(x = 2\); \(2x\) is on top.", r"\(\int_0^2(2x - x^2)\,dx = \frac43\)"),
         pr(r"Area between \(y = \sin x\) and \(y = \cos x\) on \(\left[0, \frac\pi2\right]\).", r"They cross at \(x = \frac\pi4\). Split there.", r"\(2(\sqrt2 - 1) \approx 0.828\)")],
        [mc(r"The area between \(y = x^2\) and \(y = x\) is:", [r"\(\frac13\)", r"\(\frac16\)", r"\(\frac12\)", "1"], 1, r"\(\int_0^1(x - x^2)\,dx\)."),
         mc(r"\(y = x^2\) and \(y = x + 2\) intersect at:", [r"\(x = 1, 2\)", r"\(x = -2, 1\)", r"\(x = -1, 2\)", r"\(x = 0, 2\)"], 2, r"\(x^2 - x - 2 = (x - 2)(x + 1) = 0\)."),
         mc(r"If \(f\) is the top curve and \(g\) the bottom, the integrand is:", [r"\(f - g\)", r"\(g - f\)", r"\(f + g\)", r"\(fg\)"], 0, "Top minus bottom.")],
    ),
    lesson(
        "average-value", 9, "Average Value of a Function", "average value mean value theorem for integrals",
        "Beginner", 15, ["ftc"],
        r"The average value of \(f\) on \([a, b]\) is the integral divided by the length of the interval. Picture a "
        r"rectangle over \([a, b]\) with the same area as the region under \(f\): its height is the average value. "
        r"The <b>Mean Value Theorem for integrals</b> says a continuous \(f\) actually reaches its average at some "
        r"point \(c\).",
        [
            ["Average value", r"f_{\text{avg}} = \frac{1}{b - a}\int_a^b f(x)\,dx"],
            ["Mean Value Theorem for integrals", r"f \text{ continuous} \Rightarrow f(c) = f_{\text{avg}} \text{ for some } c \in [a, b]"],
        ],
        ex(r"Find the average value of \(f(x) = x^2\) on \([0, 3]\), and a \(c\) where \(f\) equals it.",
           [r"\(\int_0^3 x^2\,dx = \left[\frac{x^3}{3}\right]_0^3 = 9\).",
            r"Divide by the length \(3 - 0 = 3\): \(f_{\text{avg}} = 3\).",
            r"Solve \(c^2 = 3\) with \(c\) in \([0, 3]\): \(c = \sqrt3\)."],
           r"\(f_{\text{avg}} = 3\), reached at \(c = \sqrt3\)"),
        [r"Forgetting to divide by \(b - a\).",
         "Averaging the endpoint values instead of integrating.",
         r"Giving a \(c\) outside \([a, b]\)."],
        [pr(r"Average value of \(\sin x\) on \([0, \pi]\).", r"\(\int_0^\pi\sin x\,dx = 2\).", r"\(\frac{2}{\pi}\)"),
         pr(r"Average value of \(2x + 1\) on \([1, 3]\).", r"\(\frac12\left[x^2 + x\right]_1^3\).", "5"),
         pr(r"The temperature is \(T(t) = 20 + 4t\) degrees for \(0 \le t \le 5\) hours. Find the average temperature.", r"\(\frac15\int_0^5(20 + 4t)\,dt\).", "30 degrees")],
        [mc(r"The average value of \(f(x) = x\) on \([0, 4]\) is:", ["4", "8", "2", "1"], 2, r"\(\frac14\cdot\frac{16}{2} = 2\)."),
         mc("The average value formula is:", [r"\(\frac{f(a) + f(b)}{2}\)", r"\(\int_a^b f(x)\,dx\)", r"\((b - a)\int_a^b f(x)\,dx\)", r"\(\frac{1}{b - a}\int_a^b f(x)\,dx\)"], 3, "Divide the integral by the length."),
         mc(r"The average value of \(\frac1x\) on \([1, e]\) is:", [r"\(\frac{1}{e - 1}\)", "1", r"\(e - 1\)", r"\(\frac1e\)"], 0, r"\(\frac{1}{e - 1}\int_1^e\frac{dx}{x} = \frac{1}{e - 1}\).")],
    ),

    # ======================= WEEK 10: DIFFERENTIAL EQUATIONS =======================
    lesson(
        "de-intro", 10, "Introduction to Differential Equations", "differential equation order solution verify initial value problem general particular",
        "Beginner", 20, ["antiderivatives", "exp-log-derivatives"],
        r"A <b>differential equation</b> (DE) is an equation involving an unknown function and its derivatives, like "
        r"\(y' = 3y\). Its <b>order</b> is the highest derivative that appears. A solution is a function that makes the "
        r"equation true. The <b>general solution</b> contains constants; an <b>initial value problem</b> gives extra "
        r"conditions that fix them. You can always check a solution by substituting it in.",
        [
            ["Order", r"\text{highest derivative: } y'' + y = 0 \text{ is second order}"],
            [r"Simplest type: \(y' = f(x)\)", r"y = \int f(x)\,dx"],
            ["Exponential growth/decay", r"y' = ky \;\Rightarrow\; y = Ce^{kx}"],
            ["Initial value problem", r"\text{a DE plus conditions like } y(0) = y_0 \text{ that determine the constants}"],
        ],
        ex(r"Show that \(y = Ce^{3x}\) solves \(y' = 3y\), then solve with \(y(0) = 5\).",
           [r"\(y' = 3Ce^{3x} = 3y\). ✓",
            r"Apply the condition: \(y(0) = Ce^0 = C = 5\)."],
           r"\(y = 5e^{3x}\)"),
        ["Confusing the order (highest derivative) with the degree (a power).",
         "Forgetting the constants in a general solution.",
         "Substituting a 'solution' into only one side of the equation."],
        [pr(r"What is the order of \(y''' + y' = x\)?", "Find the highest derivative.", "3"),
         pr(r"Does \(y = \sin x\) solve \(y'' + y = 0\)?", r"Compute \(y''\).", r"Yes: \(-\sin x + \sin x = 0\)."),
         pr(r"Solve \(y' = 2x\) with \(y(1) = 4\).", "Integrate, then find C.", r"\(y = x^2 + 3\)")],
        [mc(r"The order of \(y'' - 3y' + 2y = 0\) is:", ["1", "2", "3", "0"], 1, "The highest derivative is y''."),
         mc(r"\(y = e^{-2x}\) is a solution of:", [r"\(y' = 2y\)", r"\(y' = -y\)", r"\(y' + 2y = 0\)", r"\(y'' = -4y\)"], 2, r"\(y' = -2e^{-2x} = -2y\)."),
         mc(r"The general solution of \(y' = 4y\) is:", [r"\(y = Ce^{4x}\)", r"\(y = 4x + C\)", r"\(y = 2x^2 + C\)", r"\(y = e^{4x}\)"], 0, r"\(y' = ky\) with \(k = 4\).")],
    ),
    lesson(
        "separable-de", 10, "Separable Differential Equations", "separable separation of variables growth decay newton cooling",
        "Intermediate", 25, ["de-intro", "u-sub", "log-functions"],
        r"A DE is <b>separable</b> if you can write it as \(\frac{dy}{dx} = g(x)h(y)\). Move every \(y\) to one side and "
        r"every \(x\) to the other, then integrate both sides. Add one constant, then solve for \(y\) if you can. "
        r"Exponential growth, decay and Newton's law of cooling are all separable.",
        [
            ["Separation of variables", r"\frac{dy}{dx} = g(x)h(y) \;\Rightarrow\; \int\frac{dy}{h(y)} = \int g(x)\,dx"],
            ["Growth / decay", r"\frac{dy}{dt} = ky \;\Rightarrow\; y = y_0e^{kt}"],
            ["Newton's law of cooling", r"\frac{dT}{dt} = k(T - T_s) \;\Rightarrow\; T = T_s + (T_0 - T_s)e^{kt}"],
            ["Equilibrium solutions", r"h(y_0) = 0 \;\Rightarrow\; y = y_0 \text{ is a constant solution}"],
        ],
        ex(r"Solve \(\frac{dy}{dx} = xy\) with \(y(0) = 2\).",
           [r"Separate: \(\frac{dy}{y} = x\,dx\).",
            r"Integrate: \(\ln|y| = \frac{x^2}{2} + C\).",
            r"Solve for \(y\): \(y = Ae^{x^2/2}\).",
            r"Apply \(y(0) = 2\): \(A = 2\)."],
           r"\(y = 2e^{x^2/2}\)"),
        [r"Waiting until after solving for \(y\) to add \(+C\). Add it right after integrating.",
         r"Dividing by \(h(y)\) and losing constant solutions where \(h(y) = 0\).",
         r"Trying to separate something like \(\frac{dy}{dx} = x + y\), which isn't separable."],
        [pr(r"Solve \(\frac{dy}{dx} = y^2\) with \(y(0) = 1\).", r"\(\int y^{-2}\,dy = \int dx\) gives \(-\frac1y = x + C\).", r"\(y = \frac{1}{1 - x}\)"),
         pr(r"Solve \(\frac{dy}{dx} = \frac{3x^2}{2y}\) with \(y(0) = 2\).", r"\(2y\,dy = 3x^2\,dx\) gives \(y^2 = x^3 + C\).", r"\(y = \sqrt{x^3 + 4}\)"),
         pr("A population doubles every 5 years. Find k in P = P₀e^{kt}.", r"\(2 = e^{5k}\).", r"\(k = \frac{\ln 2}{5} \approx 0.139\) per year")],
        [mc(r"Is \(\frac{dy}{dx} = x + y\) separable?", ["Yes", "Only if x > 0", "No", "Only with y(0) given"], 2, "A sum can't be split into g(x)·h(y)."),
         mc(r"The solution of \(\frac{dy}{dx} = -2y\), \(y(0) = 3\) is:", [r"\(3e^{-2x}\)", r"\(3 - 2x\)", r"\(-2e^{3x}\)", r"\(e^{-2x} + 3\)"], 0, r"\(y = y_0e^{kx}\) with \(k = -2\)."),
         mc(r"Separating \(\frac{dy}{dx} = xy\) and integrating gives:", [r"\(y = \frac{x^2}{2} + C\)", r"\(\ln|y| = x + C\)", r"\(y^2 = x^2 + C\)", r"\(\ln|y| = \frac{x^2}{2} + C\)"], 3, r"\(\int\frac{dy}{y} = \int x\,dx\).")],
    ),
    lesson(
        "second-order-linear", 10, "Linear Second-Order DEs", "second order linear homogeneous constant coefficients characteristic auxiliary equation roots complex repeated",
        "Advanced", 35, ["de-intro", "trig-functions", "review-solving"],
        r"For \(ay'' + by' + cy = 0\) with constant coefficients, guess \(y = e^{rx}\). Substituting gives the "
        r"<b>characteristic equation</b> \(ar^2 + br + c = 0\). Its roots decide the solution: two real roots, one "
        r"repeated root, or a complex pair. Two initial conditions, \(y(0)\) and \(y'(0)\), pin down the two constants. "
        r"For a non-homogeneous equation, add a particular solution to the homogeneous one.",
        [
            ["Characteristic equation", r"ay'' + by' + cy = 0 \;\Rightarrow\; ar^2 + br + c = 0"],
            [r"Distinct real roots \(r_1 \ne r_2\)", r"y = C_1e^{r_1x} + C_2e^{r_2x}"],
            [r"Repeated root \(r\)", r"y = (C_1 + C_2x)e^{rx}"],
            [r"Complex roots \(\alpha \pm \beta i\)", r"y = e^{\alpha x}\big(C_1\cos\beta x + C_2\sin\beta x\big)"],
            ["Non-homogeneous", r"y = y_h + y_p"],
        ],
        ex(r"Solve \(y'' - 5y' + 6y = 0\) with \(y(0) = 1\), \(y'(0) = 0\).",
           [r"Characteristic equation: \(r^2 - 5r + 6 = (r - 2)(r - 3) = 0\), so \(r = 2, 3\).",
            r"General solution: \(y = C_1e^{2x} + C_2e^{3x}\).",
            r"\(y(0) = C_1 + C_2 = 1\) and \(y'(0) = 2C_1 + 3C_2 = 0\).",
            r"Solving: \(C_1 = 3\), \(C_2 = -2\)."],
           r"\(y = 3e^{2x} - 2e^{3x}\)"),
        [r"Forgetting the extra \(x\) for a repeated root.",
         r"Mixing up \(\alpha\) and \(\beta\) in the complex case: \(\alpha\) goes in the exponential, \(\beta\) inside cos and sin.",
         "Trying to find two constants with only one initial condition."],
        [pr(r"Solve \(y'' + 4y = 0\).", r"\(r^2 + 4 = 0\) gives \(r = \pm 2i\).", r"\(y = C_1\cos 2x + C_2\sin 2x\)"),
         pr(r"Solve \(y'' + 6y' + 9y = 0\).", r"\(r^2 + 6r + 9 = (r + 3)^2\).", r"\(y = (C_1 + C_2x)e^{-3x}\)"),
         pr(r"Solve \(y'' + 2y' + 5y = 0\).", "Use the quadratic formula on the characteristic equation.", r"\(r = -1 \pm 2i\): \(y = e^{-x}(C_1\cos 2x + C_2\sin 2x)\)")],
        [mc(r"The general solution of \(y'' - y = 0\) is:", [r"\(C_1\cos x + C_2\sin x\)", r"\(C_1e^x + C_2e^{-x}\)", r"\((C_1 + C_2x)e^x\)", r"\(Ce^x\)"], 1, r"\(r^2 - 1 = 0\) gives \(r = \pm 1\)."),
         mc(r"The characteristic roots are \(3 \pm 4i\). The solution is:", [r"\(e^{4x}(C_1\cos 3x + C_2\sin 3x)\)", r"\(C_1e^{3x} + C_2e^{4x}\)", r"\(e^{3x}(C_1\cos 4x + C_2\sin 4x)\)", r"\((C_1 + C_2x)e^{3x}\)"], 2,
            r"\(\alpha = 3\) in the exponential, \(\beta = 4\) inside cos and sin."),
         mc(r"A repeated characteristic root \(r = 2\) gives:", [r"\((C_1 + C_2x)e^{2x}\)", r"\(C_1e^{2x} + C_2e^{2x}\)", r"\(C_1e^{2x}\)", r"\(C_1\cos 2x + C_2\sin 2x\)"], 0, "The second solution gets an extra factor of x.")],
    ),

    # ======================= WEEK 11: DIRECTION FIELDS, EULER'S METHOD, MULTIVARIABLE FUNCTIONS =======================
    lesson(
        "direction-fields", 11, "Direction Fields", "direction field slope field isocline equilibrium solution curves stable unstable",
        "Beginner", 20, ["de-intro"],
        r"A first-order DE \(y' = f(x, y)\) tells you the slope of the solution at every point. A <b>direction field</b> "
        r"draws a short segment with that slope at many points, so you can see the shape of every solution without "
        r"solving anything: solution curves follow the segments. <b>Equilibrium solutions</b> are horizontal lines "
        r"where \(y' = 0\). Nearby solutions move toward a <b>stable</b> one and away from an <b>unstable</b> one.",
        [
            [r"Slope at \((x, y)\)", r"y' = f(x, y)"],
            [r"Isoclines (all segments with slope \(c\))", r"f(x, y) = c"],
            [r"Equilibrium solutions of \(y' = f(y)\)", r"f(y_0) = 0 \;\Rightarrow\; y = y_0"],
            ["Stability", r"\text{stable: nearby solutions approach } y_0;\quad \text{unstable: they move away}"],
        ],
        ex(r"Analyze \(y' = y(2 - y)\).",
           [r"Equilibria: \(y(2 - y) = 0\), so \(y = 0\) and \(y = 2\).",
            r"For \(0 \lt y \lt 2\), \(y' \gt 0\): solutions rise toward 2.",
            r"For \(y \gt 2\), \(y' \lt 0\): solutions fall toward 2. For \(y \lt 0\), \(y' \lt 0\): solutions fall away from 0.",
            r"So solutions approach \(y = 2\) from both sides and move away from \(y = 0\)."],
           r"\(y = 2\) is stable; \(y = 0\) is unstable"),
        [r"Using only one coordinate. The slope at \((x, y)\) generally depends on both.",
         r"Drawing equilibria as points. They're horizontal lines \(y = y_0\).",
         "Letting solution curves cross. Solutions of a nice DE never cross."],
        [pr(r"The slope of \(y' = x - y\) at \((2, 1)\).", "Substitute.", "1"),
         pr(r"The isocline of slope 0 for \(y' = x - y\).", r"Set \(x - y = 0\).", r"The line \(y = x\)"),
         pr(r"Equilibria and stability of \(y' = y^2 - 4\).", r"Solve \(y^2 - 4 = 0\), then check signs between and around the roots.", r"\(y = -2\) is stable, \(y = 2\) is unstable")],
        [mc(r"The slope of \(y' = xy\) at \((2, 3)\) is:", ["5", "1.5", "6", "−1"], 2, r"\(2\cdot 3\)."),
         mc(r"The equilibrium solution of \(y' = 3 - y\) is:", [r"\(y = 0\)", r"\(y = -3\)", r"\(x = 3\)", r"\(y = 3\)"], 3, r"\(y' = 0\) when \(y = 3\)."),
         mc(r"In the direction field of \(y' = x\), the segments:", ["are the same along each vertical line", "are all horizontal", "are the same along each horizontal line", "all have slope 1"], 0, r"The slope depends only on \(x\).")],
    ),
    lesson(
        "eulers-method", 11, "Euler's Method", "euler's method step size numerical approximation solution",
        "Intermediate", 20, ["direction-fields"],
        r"Euler's method approximates the solution of \(y' = f(x, y)\), \(y(x_0) = y_0\), by walking along tangent lines. "
        r"From the current point, use the slope \(f(x_n, y_n)\) to step forward a distance \(h\). Repeat. Smaller steps "
        r"give better answers (the error shrinks roughly in proportion to \(h\)), at the cost of more steps.",
        [
            ["Euler's method", r"x_{n+1} = x_n + h,\qquad y_{n+1} = y_n + h\,f(x_n, y_n)"],
            ["Idea", r"\text{follow the tangent line for one step, then recompute the slope}"],
            ["Accuracy", r"\text{error} \approx \text{constant} \times h"],
        ],
        ex(r"Use Euler's method with \(h = 0.1\) to estimate \(y(0.2)\) for \(y' = x + y\), \(y(0) = 1\).",
           [r"Step 1: \(y_1 = 1 + 0.1(0 + 1) = 1.1\) at \(x_1 = 0.1\).",
            r"Step 2: \(y_2 = 1.1 + 0.1(0.1 + 1.1) = 1.22\) at \(x_2 = 0.2\).",
            r"The exact solution is \(y = 2e^x - x - 1\), giving \(y(0.2) \approx 1.2428\). Euler underestimates here because the solution curves upward."],
           r"\(y(0.2) \approx 1.22\)"),
        ["Using the slope at the new point instead of the current one.",
         r"Forgetting to update \(x\) as well as \(y\).",
         "Taking huge steps and trusting the answer."],
        [pr(r"\(y' = 2y\), \(y(0) = 1\), \(h = 0.5\). Estimate \(y(1)\).", r"Two steps: \(y_1 = 1 + 0.5(2) = 2\).", r"\(y_2 = 2 + 0.5(4) = 4\) (exact: \(e^2 \approx 7.39\))"),
         pr(r"\(y' = x^2\), \(y(1) = 0\), \(h = 0.5\). Estimate \(y(2)\).", r"\(y_1 = 0 + 0.5(1^2) = 0.5\).", r"\(y_2 = 0.5 + 0.5(1.5^2) = 1.625\) (exact: \(\frac73 \approx 2.33\))")],
        [mc(r"\(y' = y\), \(y(0) = 1\), \(h = 0.1\). One Euler step gives:", ["1.1", "1.0", "1.105", "0.1"], 0, r"\(1 + 0.1\cdot 1\)."),
         mc("Euler's method updates y using:", [r"\(y_{n+1} = y_n + f(x_n, y_n)\)", r"\(y_{n+1} = y_n + h\,f(x_n, y_n)\)", r"\(y_{n+1} = h\,f(x_n, y_n)\)", r"\(y_{n+1} = y_n - h\,f(x_n, y_n)\)"], 1, "Step size times slope."),
         mc("Halving the step size typically:", ["doubles the error", "has no effect", "roughly halves the error", "makes the error zero"], 2, "Euler's error is proportional to h.")],
    ),
    lesson(
        "multivariable-intro", 11, "Functions of Several Variables", "multivariable function two variables domain range level curves contour map surface z=f(x,y) limits",
        "Intermediate", 25, ["review-graphing"],
        r"A function of two variables \(z = f(x, y)\) takes a point in the plane and returns a number. Its domain is a "
        r"<b>region</b> of the plane, and its graph is a <b>surface</b> in 3D. <b>Level curves</b> \(f(x, y) = k\) "
        r"slice the surface at height \(k\), like contour lines on a hiking map. Limits are trickier than in 1D: if "
        r"two paths toward a point give different values, the limit doesn't exist.",
        [
            ["Function of two variables", r"z = f(x, y),\qquad \text{domain} \subseteq \mathbb{R}^2"],
            [r"Level curves (height \(k\))", r"f(x, y) = k"],
            ["Three variables", r"w = f(x, y, z),\qquad \text{level surfaces } f(x, y, z) = k"],
            ["Two-path test", r"\text{different limits along two paths} \Rightarrow \text{the limit does not exist}"],
        ],
        ex(r"Describe \(f(x, y) = \sqrt{9 - x^2 - y^2}\).",
           [r"Domain: \(9 - x^2 - y^2 \ge 0\), i.e. \(x^2 + y^2 \le 9\), a disk of radius 3.",
            r"Range: from 0 (on the edge) to 3 (at the origin), so \([0, 3]\).",
            r"Level curves: \(\sqrt{9 - x^2 - y^2} = k\) gives \(x^2 + y^2 = 9 - k^2\), circles.",
            r"The surface is the upper half of a sphere of radius 3."],
           r"Domain: disk \(x^2 + y^2 \le 9\); range \([0, 3]\); level curves are circles; the graph is a hemisphere"),
        ["Describing the domain as an interval. It's a region in the plane.",
         "Confusing level curves (in the xy-plane) with slices of the surface.",
         "Checking a 2D limit along only one path."],
        [pr(r"Domain of \(f(x, y) = \ln(x - y)\).", r"The log needs \(x - y \gt 0\).", r"\(y \lt x\): the half-plane below the line \(y = x\)"),
         pr(r"Level curves of \(f(x, y) = x^2 + y^2\).", r"\(x^2 + y^2 = k\).", r"Circles centred at the origin (radius \(\sqrt k\))"),
         pr(r"Does \(\displaystyle\lim_{(x,y)\to(0,0)}\frac{xy}{x^2 + y^2}\) exist?", r"Try the paths \(y = 0\) and \(y = x\).", r"Along \(y = 0\): 0. Along \(y = x\): \(\frac12\). It doesn't exist.")],
        [mc(r"The domain of \(f(x, y) = \frac{1}{x - y}\) is:", [r"\(x \gt y\)", r"\(x \ne 0\)", r"all \((x, y)\) with \(y \ne x\)", r"all of \(\mathbb{R}^2\)"], 2, "The denominator can't be zero."),
         mc(r"The level curves of \(f(x, y) = 2x + y\) are:", ["circles", "parabolas", "points", "parallel lines"], 3, r"\(2x + y = k\) are lines with slope −2."),
         mc(r"For \(f(x, y) = x^2 + y^2\), \(f(1, 2) =\)", ["5", "3", "9", "4"], 0, r"\(1 + 4\).")],
    ),

    # ======================= WEEK 12: PARTIAL DERIVATIVES & TANGENT PLANES =======================
    lesson(
        "partial-derivatives", 12, "Partial Derivatives", "partial derivative fx fy higher order mixed clairaut multivariable",
        "Intermediate", 25, ["multivariable-intro", "chain-rule"],
        r"A partial derivative measures how \(f(x, y)\) changes when you move in <b>one</b> direction only. For "
        r"\(f_x\), treat \(y\) as a constant and differentiate with respect to \(x\); for \(f_y\), do the opposite. "
        r"Geometrically, \(f_x\) is the slope of the surface in the \(x\)-direction. Second partials work the same way, "
        r"and for nice functions the mixed partials are equal (<b>Clairaut's theorem</b>).",
        [
            ["Partial derivatives", r"f_x = \frac{\partial f}{\partial x}\ (y \text{ constant}),\qquad f_y = \frac{\partial f}{\partial y}\ (x \text{ constant})"],
            ["Limit definition", r"f_x(x, y) = \lim_{h\to 0}\frac{f(x + h, y) - f(x, y)}{h}"],
            ["Second-order partials", r"f_{xx},\quad f_{yy},\quad f_{xy} = \frac{\partial}{\partial y}\big(f_x\big)"],
            ["Clairaut's theorem", r"f_{xy} = f_{yx}\ \text{(when they're continuous)}"],
        ],
        ex(r"Find all first and mixed second partials of \(f(x, y) = x^3y^2 + 4xy - y^3\).",
           [r"\(f_x = 3x^2y^2 + 4y\) (treat \(y\) as a constant).",
            r"\(f_y = 2x^3y + 4x - 3y^2\) (treat \(x\) as a constant).",
            r"\(f_{xy} = \frac{\partial}{\partial y}(3x^2y^2 + 4y) = 6x^2y + 4\).",
            r"\(f_{yx} = \frac{\partial}{\partial x}(2x^3y + 4x - 3y^2) = 6x^2y + 4\). They match, as Clairaut predicts."],
           r"\(f_x = 3x^2y^2 + 4y\), \(f_y = 2x^3y + 4x - 3y^2\), \(f_{xy} = f_{yx} = 6x^2y + 4\)"),
        [r"Treating the other variable as a variable. In \(f_x\), \(y\) is just a number.",
         r"Using the product rule on \(x^2y\) for \(f_x\). Since \(y\) is a constant, it's \(2xy\).",
         r"Mixing up the order in \(f_{xy}\) (differentiate by \(x\) first, then \(y\))."],
        [pr(r"Partials of \(f = e^{xy}\).", "Chain rule on each variable.", r"\(f_x = ye^{xy}\), \(f_y = xe^{xy}\)"),
         pr(r"\(f_x\) for \(f = \sin(x^2y)\).", r"Inside \(x^2y\) has \(x\)-derivative \(2xy\).", r"\(f_x = 2xy\cos(x^2y)\)"),
         pr(r"\(f_{xx}\) and \(f_{xy}\) for \(f = x^2 + 3xy\).", r"\(f_x = 2x + 3y\).", r"\(f_{xx} = 2\), \(f_{xy} = 3\)")],
        [mc(r"\(\frac{\partial}{\partial x}(x^3y^2) =\)", [r"\(3x^2y^2\)", r"\(2x^3y\)", r"\(3x^2\)", r"\(6x^2y\)"], 0, r"\(y^2\) acts as a constant."),
         mc(r"\(\frac{\partial}{\partial y}(x^2 + xy^2) =\)", [r"\(2x + y^2\)", r"\(2xy\)", r"\(y^2\)", r"\(2x + 2xy\)"], 1, r"\(x^2\) is constant (derivative 0) and \(xy^2 \to 2xy\)."),
         mc("Clairaut's theorem says:", [r"\(f_x = f_y\)", r"\(f_{xx} = f_{yy}\)", r"\(f_{xy} = f_{yx}\)", r"\(f_{xy} = 0\)"], 2, "The mixed partials are equal.")],
    ),
    lesson(
        "tangent-planes", 12, "Tangent Planes & Linear Approximation", "tangent plane linear approximation linearization differential",
        "Intermediate", 25, ["partial-derivatives"],
        r"Zoom in on a smooth surface and it looks flat: that flat piece is the <b>tangent plane</b>. It's the 3D "
        r"version of a tangent line, built from the two partial derivatives at the point. Near that point, the plane "
        r"(the <b>linearization</b> \(L\)) gives a great approximation of \(f\).",
        [
            [r"Tangent plane at \((x_0, y_0, z_0)\)", r"z - z_0 = f_x(x_0, y_0)(x - x_0) + f_y(x_0, y_0)(y - y_0)"],
            ["Linearization", r"L(x, y) = f(a, b) + f_x(a, b)(x - a) + f_y(a, b)(y - b)"],
            ["Linear approximation", r"f(x, y) \approx L(x, y) \text{ near } (a, b)"],
            ["Total differential", r"dz = f_x\,dx + f_y\,dy"],
        ],
        ex(r"Find the tangent plane to \(z = x^2 + y^2\) at \((1, 2)\).",
           [r"\(z_0 = f(1, 2) = 1 + 4 = 5\).",
            r"\(f_x = 2x\), so \(f_x(1, 2) = 2\). \(f_y = 2y\), so \(f_y(1, 2) = 4\).",
            r"\(z - 5 = 2(x - 1) + 4(y - 2)\).",
            r"Simplify: \(z = 2x + 4y - 5\)."],
           r"\(z = 2x + 4y - 5\)"),
        ["Leaving the partials as formulas instead of evaluating them at the point.",
         r"Forgetting \(z_0\) (the height of the surface at the point).",
         "Using a point that isn't on the surface."],
        [pr(r"Linearize \(f(x, y) = xy\) at \((2, 3)\) and estimate \(f(2.1, 2.9)\).", r"\(f = 6\), \(f_x = y = 3\), \(f_y = x = 2\).",
            r"\(L = 6 + 3(x - 2) + 2(y - 3)\), so \(f(2.1, 2.9) \approx 6.1\) (actual 6.09)"),
         pr(r"Tangent plane to \(z = e^x\cos y\) at \((0, 0)\).", r"\(z_0 = 1\), \(f_x = 1\), \(f_y = 0\).", r"\(z = 1 + x\)"),
         pr(r"Tangent plane to \(z = 3x^2 - y^2\) at \((1, 1)\).", r"\(z_0 = 2\), \(f_x = 6\), \(f_y = -2\).", r"\(z = 6x - 2y - 2\)")],
        [mc(r"The tangent plane to \(z = x^2 + y^2\) at \((1, 1)\) is:", [r"\(z = 2x + 2y\)", r"\(z = x + y\)", r"\(z = 2x + 2y - 2\)", r"\(z = 2x + 2y + 2\)"], 2,
            r"\(z_0 = 2\), \(f_x = f_y = 2\): \(z - 2 = 2(x - 1) + 2(y - 1)\)."),
         mc("The total differential of z = f(x, y) is:", [r"\(dz = f_x + f_y\)", r"\(dz = f_x\,dy + f_y\,dx\)", r"\(dz = f\,dx\,dy\)", r"\(dz = f_x\,dx + f_y\,dy\)"], 3, "Each partial times its own change."),
         mc("A linearization uses:", ["the partial derivatives at the point", "the second derivatives", "only the value f(a, b)", "the gradient at the origin"], 0, "Value plus the two partial-derivative terms.")],
    ),
]
