r"""Practice sets for weeks 1-6. Math is written the same way as in the lessons:
LaTeX inside \( ... \), and \lt instead of a bare "<"."""
from lesson_helpers import pq, pset

PRACTICE_1_6 = {
    # ======================= WEEK 1: PRECALCULUS REVIEW =======================
    1: [
        pset("Factoring", "review-factoring", [
            pq(r"Factor \(3x^3 - 12x\) completely.",
               [r"Always look for a factor common to every term first. Both terms contain \(3\) and \(x\): \(3x^3 = 3x\cdot x^2\) and \(12x = 3x\cdot4\).",
                r"Take it out: \(3x(x^2 - 4)\).",
                r"Now check the bracket. \(x^2 - 4 = x^2 - 2^2\) is a difference of squares, and \(a^2 - b^2 = (a-b)(a+b)\).",
                r"So \(x^2 - 4 = (x-2)(x+2)\), and nothing factors further.",
                r"Check by expanding: \(3x(x^2 - 4) = 3x^3 - 12x\)."],
               r"\(3x(x-2)(x+2)\)", kind="Common factor, then difference of squares"),
            pq(r"Factor \(2x^2 + 7x + 3\).",
               [r"Find two numbers that multiply to \(2 \cdot 3 = 6\) and add to \(7\): \(6\) and \(1\).",
                r"Split the middle term: \(2x^2 + 6x + x + 3\).",
                r"Group: \(2x(x+3) + 1(x+3)\)."],
               r"\((2x+1)(x+3)\)", kind="Trinomial with a leading coefficient"),
            pq(r"Factor \(8x^3 + 27\).",
               [r"Both terms are perfect cubes: \(8x^3 = (2x)^3\) and \(27 = 3^3\). So \(a = 2x\) and \(b = 3\).",
                r"Sum of cubes: \(a^3 + b^3 = (a+b)(a^2 - ab + b^2)\).",
                r"Work out the pieces: \(a^2 = 4x^2\), \(ab = 6x\) and \(b^2 = 9\).",
                r"Put them in: \((2x+3)(4x^2 - 6x + 9)\). The first bracket has the same sign as the question, and the middle sign of the second bracket is the opposite.",
                r"The quadratic \(4x^2 - 6x + 9\) has discriminant \(36 - 144 \lt 0\), so it does not factor further."],
               r"\((2x+3)(4x^2 - 6x + 9)\)", kind="Sum of cubes"),
        ]),
        pset("Expanding", "review-expanding", [
            pq(r"Expand \((3x-2)^2\).",
               [r"A square means the bracket times itself: \((3x-2)(3x-2)\). It is <b>not</b> \(9x^2 - 4\).",
                r"Use \((a-b)^2 = a^2 - 2ab + b^2\) with \(a = 3x\) and \(b = 2\).",
                r"\(a^2 = (3x)^2 = 9x^2\). The 3 is squared as well as the \(x\).",
                r"\(2ab = 2(3x)(2) = 12x\), and \(b^2 = 4\).",
                r"Put them together with the signs \(+, -, +\): \(9x^2 - 12x + 4\)."],
               r"\(9x^2 - 12x + 4\)", kind="Square of a binomial"),
            pq(r"Expand and simplify \((x+h)^2 - 3(x+h) - (x^2 - 3x)\).",
               [r"Expand the square: \((x+h)^2 = x^2 + 2xh + h^2\).",
                r"Distribute the \(-3\): \(-3(x+h) = -3x - 3h\).",
                r"Distribute the minus sign over the last bracket, changing both signs: \(-(x^2 - 3x) = -x^2 + 3x\).",
                r"All together: \(x^2 + 2xh + h^2 - 3x - 3h - x^2 + 3x\).",
                r"Cancel \(x^2\) with \(-x^2\), and \(-3x\) with \(+3x\). Every term that is left contains \(h\)."],
               r"\(2xh + h^2 - 3h\)", kind="Expanding with x + h"),
        ]),
        pset("Simplifying expressions", "review-simplifying", [
            pq(r"Simplify \(\dfrac{x^2 - 5x + 6}{x^2 - 4}\).",
               [r"Factor the top: \((x-2)(x-3)\).",
                r"Factor the bottom: \((x-2)(x+2)\).",
                r"Cancel the common factor \((x-2)\), which needs \(x \ne 2\)."],
               r"\(\dfrac{x-3}{x+2}\), for \(x \ne 2\)", kind="Cancelling common factors"),
            pq(r"Simplify \(\dfrac{\frac{1}{x+h} - \frac1x}{h}\).",
               [r"Simplify the top first. The common denominator of \(\dfrac{1}{x+h}\) and \(\dfrac1x\) is \(x(x+h)\).",
                r"\(\dfrac{1}{x+h} - \dfrac1x = \dfrac{x}{x(x+h)} - \dfrac{x+h}{x(x+h)} = \dfrac{x - (x+h)}{x(x+h)}\). Keep the bracket around \((x+h)\).",
                r"The top simplifies to \(-h\): the fraction is \(\dfrac{-h}{x(x+h)}\).",
                r"Dividing by \(h\) is the same as multiplying by \(\dfrac1h\): \(\dfrac{-h}{x(x+h)}\cdot\dfrac1h\).",
                r"The \(h\) cancels. (Putting \(h = 0\) now gives \(-\dfrac{1}{x^2}\), the derivative of \(\dfrac1x\).)"],
               r"\(-\dfrac{1}{x(x+h)}\)", kind="Fraction inside a fraction"),
            pq(r"Rationalize the denominator of \(\dfrac{6}{\sqrt7 + 2}\).",
               [r"To remove a root from a two-term denominator, multiply top and bottom by its conjugate: change the sign in the middle to get \(\sqrt7 - 2\).",
                r"Bottom: \((\sqrt7 + 2)(\sqrt7 - 2) = (\sqrt7)^2 - 2^2 = 7 - 4 = 3\). The root is gone because the middle terms cancel.",
                r"Top: \(6(\sqrt7 - 2)\).",
                r"So the fraction is \(\dfrac{6(\sqrt7 - 2)}{3} = 2(\sqrt7 - 2)\).",
                r"Expand: \(2\sqrt7 - 4\)."],
               r"\(2\sqrt7 - 4\)", kind="Rationalizing a denominator"),
        ]),
        pset("Solving equations and inequalities", "review-solving", [
            pq(r"Solve \(2x^2 - 5x - 3 = 0\).",
               [r"Look for two numbers that multiply to \(2\cdot(-3) = -6\) and add to \(-5\): they are \(-6\) and \(1\).",
                r"Split the middle term and group: \(2x^2 - 6x + x - 3 = 2x(x-3) + 1(x-3) = (2x+1)(x-3)\).",
                r"A product is zero only when one of its factors is zero: \(2x + 1 = 0\) or \(x - 3 = 0\).",
                r"Solve each: \(x = -\frac12\) or \(x = 3\).",
                r"Check \(x = 3\): \(2(9) - 15 - 3 = 0\)."],
               r"\(x = -\frac12\) or \(x = 3\)", kind="Quadratic by factoring"),
            pq(r"Solve \(x^2 - 6x + 4 = 0\).",
               [r"It doesn't factor nicely, so use the quadratic formula with \(a = 1\), \(b = -6\), \(c = 4\).",
                r"\(x = \dfrac{6 \pm \sqrt{36 - 16}}{2} = \dfrac{6 \pm \sqrt{20}}{2}\).",
                r"Since \(\sqrt{20} = 2\sqrt5\), divide through by 2."],
               r"\(x = 3 \pm \sqrt5\)", kind="Quadratic formula"),
            pq(r"Solve \(x^2 - 2x - 8 \ge 0\).",
               [r"Factor: \((x-4)(x+2) \ge 0\).",
                r"The expression is zero at \(x = -2\) and \(x = 4\), which split the number line into three intervals.",
                r"Test a point in each: \(x = -3\) gives \(+\), \(x = 0\) gives \(-\), \(x = 5\) gives \(+\).",
                r"Keep the positive intervals, and the endpoints because of \(\ge\)."],
               r"\(x \le -2\) or \(x \ge 4\)", kind="Quadratic inequality"),
            pq(r"Solve \(|3x + 2| \lt 7\).",
               [r"\(|A| \lt 7\) means \(-7 \lt A \lt 7\), so \(-7 \lt 3x + 2 \lt 7\).",
                r"Subtract 2 from all three parts: \(-9 \lt 3x \lt 5\).",
                r"Divide by 3."],
               r"\(-3 \lt x \lt \frac53\)", kind="Absolute value inequality"),
        ]),
        pset("Graphing functions", "review-graphing", [
            pq(r"Find the equation of the line through \((-1, 4)\) and \((2, -2)\).",
               [r"Slope: \(m = \dfrac{-2 - 4}{2 - (-1)} = \dfrac{-6}{3} = -2\).",
                r"Point-slope form with \((-1, 4)\): \(y - 4 = -2(x + 1)\).",
                r"Expand: \(y = -2x - 2 + 4\)."],
               r"\(y = -2x + 2\)", kind="Line through two points"),
            pq(r"Find the domain of \(f(x) = \dfrac{\sqrt{x+3}}{x - 1}\).",
               [r"Two things can go wrong in a formula: the square root of a negative number, and division by zero. Check each.",
                r"The square root needs \(x + 3 \ge 0\), so \(x \ge -3\). (Zero inside a root is fine.)",
                r"The denominator needs \(x - 1 \ne 0\), so \(x \ne 1\).",
                r"Both must hold: everything from \(-3\) upward, with the single point 1 removed.",
                r"In interval notation the square bracket at \(-3\) means it is included, and the round brackets at 1 mean it is not."],
               r"\(x \ge -3\) and \(x \ne 1\), which is \([-3, 1) \cup (1, \infty)\)", kind="Domain of a function"),
            pq(r"Describe how to get the graph of \(y = 2(x+1)^2 - 5\) from \(y = x^2\), and give its vertex.",
               [r"\((x+1)\) shifts the graph 1 unit to the left.",
                r"The factor 2 stretches it vertically by 2.",
                r"The \(-5\) shifts it down 5 units.",
                r"In vertex form \(y = a(x-h)^2 + k\), we have \(h = -1\) and \(k = -5\)."],
               r"Shift left 1, stretch vertically by 2, shift down 5. The vertex is \((-1, -5)\).", kind="Transformations of a graph"),
        ]),
    ],

    # ======================= WEEK 2: LIMITS =======================
    2: [
        pset("Limits from graphs and tables", "limits", [
            pq(r"\(f(x) = \begin{cases} 2x + 1 & x \lt 1 \\ x^2 + 2 & x \ge 1 \end{cases}\). Find \(\displaystyle\lim_{x\to 1} f(x)\).",
               [r"From the left, use \(2x + 1\): it approaches \(2(1) + 1 = 3\).",
                r"From the right, use \(x^2 + 2\): it approaches \(1 + 2 = 3\).",
                r"Both sides agree, so the limit exists."],
               r"\(3\)", kind="One-sided limits that agree"),
            pq(r"\(g(x) = \begin{cases} x + 3 & x \lt 0 \\ 1 - x & x \ge 0 \end{cases}\). Find \(\displaystyle\lim_{x\to 0} g(x)\).",
               [r"From the left, \(x + 3\) approaches \(3\).",
                r"From the right, \(1 - x\) approaches \(1\).",
                r"The two one-sided limits are different."],
               r"The limit does not exist (the left side gives 3, the right side gives 1).", kind="One-sided limits that disagree"),
        ]),
        pset("Evaluating limits algebraically", "limits-algebraic", [
            pq(r"Find \(\displaystyle\lim_{x\to 4}\frac{x^2 - 16}{x - 4}\).",
               [r"Plugging in gives \(\frac00\), so simplify first.",
                r"Factor the top: \(\dfrac{(x-4)(x+4)}{x-4} = x + 4\) for \(x \ne 4\).",
                r"Now plug in \(x = 4\)."],
               r"\(8\)", kind="Limit by factoring"),
            pq(r"Find \(\displaystyle\lim_{x\to 2}\frac{x^2 + x - 6}{x^2 - 4}\).",
               [r"Plugging in gives \(\frac00\). Factor both: \(\dfrac{(x+3)(x-2)}{(x-2)(x+2)}\).",
                r"Cancel \((x-2)\) to get \(\dfrac{x+3}{x+2}\).",
                r"Plug in \(x = 2\)."],
               r"\(\frac54\)", kind="Limit by factoring top and bottom"),
            pq(r"Find \(\displaystyle\lim_{x\to 9}\frac{\sqrt{x} - 3}{x - 9}\).",
               [r"Multiply top and bottom by the conjugate \(\sqrt{x} + 3\).",
                r"The top becomes \(x - 9\), so the fraction is \(\dfrac{x - 9}{(x-9)(\sqrt{x} + 3)} = \dfrac{1}{\sqrt{x} + 3}\).",
                r"Plug in \(x = 9\): \(\dfrac{1}{3 + 3}\)."],
               r"\(\frac16\)", kind="Limit with a conjugate"),
            pq(r"Find \(\displaystyle\lim_{h\to 0}\frac{(3+h)^2 - 9}{h}\).",
               [r"Expand the top: \(9 + 6h + h^2 - 9 = 6h + h^2\).",
                r"Divide by \(h\): \(6 + h\).",
                r"Let \(h \to 0\)."],
               r"\(6\)", kind="Limit by expanding"),
            pq(r"Find \(\displaystyle\lim_{x\to 0}\frac{\sin x}{3x}\).",
               [r"Plugging in gives \(\frac00\), so rewrite first.",
                r"Pull the constant out: \(\dfrac{\sin x}{3x} = \dfrac13\cdot\dfrac{\sin x}{x}\).",
                r"A constant factor can be taken outside a limit: \(\dfrac13\displaystyle\lim_{x\to0}\frac{\sin x}{x}\).",
                r"The special limit \(\displaystyle\lim_{x\to0}\frac{\sin x}{x}\) equals 1, so the answer is \(\dfrac13\cdot1\).",
                r"Careful: this is \(\sin x\) over \(3x\), not \(\sin 3x\) over \(3x\). The angle and the bottom must match before the special limit can be used, which is why the 3 was factored out."],
               r"\(\frac13\)", kind="Special trig limit"),
        ]),
        pset("Limits at infinity and infinite limits", "limits-infinity", [
            pq(r"Find \(\displaystyle\lim_{x\to\infty}\frac{4x^3 - x}{2x^3 + 5}\).",
               [r"Top and bottom both grow without bound, so compare how fast.",
                r"Divide every term, top and bottom, by \(x^3\), the highest power in the bottom: \(\dfrac{4 - \frac{1}{x^2}}{2 + \frac{5}{x^3}}\).",
                r"As \(x \to \infty\), \(\dfrac{1}{x^2} \to 0\) and \(\dfrac{5}{x^3} \to 0\).",
                r"What is left is \(\dfrac{4 - 0}{2 + 0} = 2\).",
                r"Shortcut: when the degrees are equal, the limit is the ratio of the leading coefficients. The graph has the horizontal asymptote \(y = 2\)."],
               r"\(2\)", kind="Limit at infinity with equal degrees"),
            pq(r"Find \(\displaystyle\lim_{x\to\infty}\frac{5x + 1}{x^2 - 3}\).",
               [r"The top has degree 1 and the bottom has degree 2, so the bottom grows faster.",
                r"Divide every term by \(x^2\), the highest power in the bottom: \(\dfrac{\frac5x + \frac{1}{x^2}}{1 - \frac{3}{x^2}}\).",
                r"As \(x \to \infty\), each of \(\dfrac5x\), \(\dfrac{1}{x^2}\) and \(\dfrac{3}{x^2}\) goes to 0.",
                r"What is left is \(\dfrac{0 + 0}{1 - 0} = 0\).",
                r"Shortcut: a smaller degree on top always gives the limit 0, and the horizontal asymptote \(y = 0\)."],
               r"\(0\)", kind="Limit at infinity with the bigger degree below"),
            pq(r"Find \(\displaystyle\lim_{x\to 3^-}\frac{2}{x - 3}\) and \(\displaystyle\lim_{x\to 3^+}\frac{2}{x - 3}\).",
               [r"Just left of 3, \(x - 3\) is a tiny negative number, so \(\frac{2}{x-3}\) is a huge negative number.",
                r"Just right of 3, \(x - 3\) is a tiny positive number, so \(\frac{2}{x-3}\) is a huge positive number.",
                r"So \(x = 3\) is a vertical asymptote."],
               r"\(-\infty\) from the left and \(+\infty\) from the right", kind="One-sided infinite limits"),
            pq(r"Find \(\displaystyle\lim_{x\to -\infty}\frac{\sqrt{9x^2 + 2}}{x + 1}\).",
               [r"Factor \(x^2\) out of the root: \(\sqrt{9x^2 + 2} = |x|\sqrt{9 + \frac{2}{x^2}}\).",
                r"For negative \(x\), \(|x| = -x\).",
                r"Divide top and bottom by \(x\): \(\dfrac{-\sqrt{9 + \frac{2}{x^2}}}{1 + \frac1x} \to \dfrac{-3}{1}\)."],
               r"\(-3\)", kind="Square root at negative infinity"),
        ]),
        pset("The epsilon-delta definition", "epsilon-delta", [
            pq(r"Prove that \(\displaystyle\lim_{x\to 3}(2x + 1) = 7\).",
               [r"Start from what we want: \(|(2x + 1) - 7| \lt \varepsilon\).",
                r"Simplify: \(|2x - 6| = 2|x - 3| \lt \varepsilon\), which is the same as \(|x - 3| \lt \frac{\varepsilon}{2}\).",
                r"So choose \(\delta = \frac{\varepsilon}{2}\).",
                r"Check: if \(0 \lt |x - 3| \lt \delta\), then \(|(2x+1) - 7| = 2|x - 3| \lt 2\delta = \varepsilon\)."],
               r"\(\delta = \frac{\varepsilon}{2}\) works for every \(\varepsilon \gt 0\).", kind="Epsilon-delta proof for a line"),
            pq(r"For \(\displaystyle\lim_{x\to 2}(4x - 3) = 5\) and \(\varepsilon = 0.2\), find the largest \(\delta\) that works.",
               [r"We need \(|(4x - 3) - 5| \lt 0.2\).",
                r"Simplify: \(|4x - 8| = 4|x - 2| \lt 0.2\).",
                r"Divide by 4: \(|x - 2| \lt 0.05\)."],
               r"\(\delta = 0.05\)", kind="Finding delta for a given epsilon"),
        ]),
        pset("Continuity", "continuity", [
            pq(r"Find \(k\) so that \(f(x) = \begin{cases} x^2 + k & x \le 1 \\ 3x + 2 & x \gt 1 \end{cases}\) is continuous.",
               [r"The only place it can break is \(x = 1\), where the two pieces meet.",
                r"Left piece at 1: \(1 + k\). Right piece at 1: \(3 + 2 = 5\).",
                r"Set them equal: \(1 + k = 5\)."],
               r"\(k = 4\)", kind="Continuity with one unknown"),
            pq(r"Find and classify the discontinuities of \(f(x) = \dfrac{x^2 - x - 2}{x^2 - 4}\).",
               [r"Factor: \(\dfrac{(x-2)(x+1)}{(x-2)(x+2)}\). The function is undefined at \(x = 2\) and \(x = -2\).",
                r"At \(x = 2\) the factor cancels, and the limit is \(\dfrac{2+1}{2+2} = \dfrac34\). The limit exists, so it is a hole.",
                r"At \(x = -2\) nothing cancels: the bottom goes to 0 and the top doesn't, so the function blows up."],
               r"Removable discontinuity (a hole) at \(x = 2\), infinite discontinuity (vertical asymptote) at \(x = -2\).", kind="Classifying discontinuities"),
        ]),
    ],

    # ======================= WEEK 3: DERIVATIVES =======================
    3: [
        pset("The limit definition of the derivative", "derivative-definition", [
            pq(r"Use the limit definition to differentiate \(f(x) = 3x^2 - x\).",
               [r"\(f(x+h) = 3(x+h)^2 - (x+h) = 3x^2 + 6xh + 3h^2 - x - h\).",
                r"Subtract \(f(x)\): \(f(x+h) - f(x) = 6xh + 3h^2 - h\).",
                r"Divide by \(h\): \(6x + 3h - 1\).",
                r"Let \(h \to 0\)."],
               r"\(f'(x) = 6x - 1\)", kind="First principles for a quadratic"),
            pq(r"Use the limit definition to differentiate \(f(x) = \dfrac{1}{x+1}\).",
               [r"\(f(x+h) - f(x) = \dfrac{1}{x+h+1} - \dfrac{1}{x+1} = \dfrac{(x+1) - (x+h+1)}{(x+h+1)(x+1)} = \dfrac{-h}{(x+h+1)(x+1)}\).",
                r"Divide by \(h\): \(\dfrac{-1}{(x+h+1)(x+1)}\).",
                r"Let \(h \to 0\)."],
               r"\(f'(x) = -\dfrac{1}{(x+1)^2}\)", kind="First principles for a reciprocal"),
            pq(r"Is \(f(x) = |x - 2|\) differentiable at \(x = 2\)? Is it continuous there?",
               [r"For \(x \gt 2\), \(f(x) = x - 2\), which has slope \(1\).",
                r"For \(x \lt 2\), \(f(x) = -(x - 2)\), which has slope \(-1\).",
                r"The slopes from the two sides don't match, so the graph has a corner at \(x = 2\).",
                r"Both pieces approach \(0 = f(2)\), so there is no break in the graph."],
               r"It is continuous at \(x = 2\) but not differentiable there.", kind="Differentiable versus continuous"),
        ]),
        pset("Power rule and basic rules", "derivative-rules", [
            pq(r"Differentiate \(f(x) = 5x^4 - 2x^3 + 7x - 9\).",
               [r"Differentiate term by term, keeping each constant in front.",
                r"\(5x^4\): bring the 4 down and lower the power by one: \(5\cdot4x^3 = 20x^3\).",
                r"\(-2x^3\): \(-2\cdot3x^2 = -6x^2\).",
                r"\(7x = 7x^1\): \(7\cdot1\cdot x^0 = 7\). The derivative of a line is its slope.",
                r"\(-9\) is a constant, so its derivative is 0."],
               r"\(f'(x) = 20x^3 - 6x^2 + 7\)", kind="Power rule on a polynomial"),
            pq(r"Differentiate \(f(x) = \dfrac{6}{x^3} + 4\sqrt{x}\).",
               [r"The power rule needs powers of \(x\), so rewrite: \(f(x) = 6x^{-3} + 4x^{1/2}\).",
                r"First term: \(6\cdot(-3)x^{-3-1} = -18x^{-4}\). Subtracting 1 from \(-3\) gives \(-4\), not \(-2\).",
                r"Second term: \(4\cdot\tfrac12x^{\frac12-1} = 2x^{-1/2}\).",
                r"So \(f'(x) = -18x^{-4} + 2x^{-1/2}\).",
                r"Rewrite without negative exponents: \(-\dfrac{18}{x^4} + \dfrac{2}{\sqrt{x}}\)."],
               r"\(f'(x) = -\dfrac{18}{x^4} + \dfrac{2}{\sqrt{x}}\)", kind="Negative and fractional powers"),
            pq(r"Differentiate \(f(x) = \dfrac{x^3 - 4x + 2}{x}\).",
               [r"There is a single term on the bottom, so divide instead of using the quotient rule.",
                r"\(\dfrac{x^3}{x} = x^2\), \(\dfrac{4x}{x} = 4\) and \(\dfrac2x = 2x^{-1}\). So \(f(x) = x^2 - 4 + 2x^{-1}\).",
                r"Power rule on each term: \(x^2 \to 2x\), the constant \(-4 \to 0\), and \(2x^{-1} \to -2x^{-2}\).",
                r"\(f'(x) = 2x - 2x^{-2} = 2x - \dfrac{2}{x^2}\).",
                r"The quotient rule gives the same answer with more work. Dividing first only works when the bottom is one term."],
               r"\(f'(x) = 2x - \dfrac{2}{x^2}\)", kind="Dividing before differentiating"),
            pq(r"Find the equation of the tangent line to \(y = x^3 - 2x\) at \(x = 2\).",
               [r"The point: \(y(2) = 8 - 4 = 4\), so \((2, 4)\).",
                r"The slope: \(y' = 3x^2 - 2\), so \(y'(2) = 10\).",
                r"Point-slope form: \(y - 4 = 10(x - 2)\)."],
               r"\(y = 10x - 16\)", kind="Tangent line"),
            pq(r"Where does \(f(x) = x^3 - 6x^2 + 9x + 1\) have a horizontal tangent?",
               [r"A horizontal tangent means \(f'(x) = 0\).",
                r"\(f'(x) = 3x^2 - 12x + 9 = 3(x-1)(x-3)\), which is zero at \(x = 1\) and \(x = 3\).",
                r"The heights are \(f(1) = 5\) and \(f(3) = 1\)."],
               r"At \((1, 5)\) and \((3, 1)\)", kind="Horizontal tangents"),
            pq(r"A particle's position is \(s(t) = t^3 - 6t^2 + 9t\) metres after \(t\) seconds. Find its velocity and acceleration at \(t = 2\), and the times when it is at rest.",
               [r"Velocity is the derivative of position: \(v(t) = 3t^2 - 12t + 9\), so \(v(2) = 12 - 24 + 9 = -3\).",
                r"Acceleration is the derivative of velocity: \(a(t) = 6t - 12\), so \(a(2) = 0\).",
                r"At rest means \(v(t) = 0\): \(3(t-1)(t-3) = 0\)."],
               r"\(v(2) = -3\) m/s and \(a(2) = 0\) m/s². It is at rest at \(t = 1\) s and \(t = 3\) s.", kind="Velocity and acceleration"),
            pq(r"Find the second derivative of \(f(x) = x^4 - 3x^2 + 2x\).",
               [r"The second derivative is the derivative of the first derivative.",
                r"First derivative: \(f'(x) = 4x^3 - 6x + 2\).",
                r"Differentiate again, term by term: \(4x^3 \to 12x^2\), \(-6x \to -6\), and \(2 \to 0\).",
                r"\(f''(x) = 12x^2 - 6\).",
                r"\(f'\) tells you the slope. \(f''\) tells you how the slope is changing, which is the concavity."],
               r"\(f''(x) = 12x^2 - 6\)", kind="Second derivative"),
        ]),
        pset("Product rule", "product-rule", [
            pq(r"Differentiate \(y = (x^2 + 1)(3x - 4)\).",
               [r"Product rule \((fg)' = f'g + fg'\) with \(f = x^2 + 1\) and \(g = 3x - 4\).",
                r"\(f' = 2x\) and \(g' = 3\), so \(y' = 2x(3x - 4) + 3(x^2 + 1)\).",
                r"Expand: \(6x^2 - 8x + 3x^2 + 3\)."],
               r"\(y' = 9x^2 - 8x + 3\)", kind="Product rule"),
            pq(r"Differentiate \(y = \sqrt{x}\,(x^3 + 2)\).",
               [r"Product rule with \(f = x^{1/2}\) and \(g = x^3 + 2\): \(f' = \frac12 x^{-1/2}\) and \(g' = 3x^2\).",
                r"\(y' = \frac12 x^{-1/2}(x^3 + 2) + x^{1/2} \cdot 3x^2\).",
                r"Simplify: \(\frac12 x^{5/2} + x^{-1/2} + 3x^{5/2}\)."],
               r"\(y' = \frac72 x^{5/2} + \dfrac{1}{\sqrt{x}}\)", kind="Product rule with a root"),
            pq(r"Given \(f(2) = 3\), \(f'(2) = -1\), \(g(2) = 4\) and \(g'(2) = 5\), find \((fg)'(2)\).",
               [r"Product rule: \((fg)' = f'g + fg'\). It is not \(f'\cdot g'\).",
                r"At \(x = 2\): \((fg)'(2) = f'(2)g(2) + f(2)g'(2)\).",
                r"Plug in the four given numbers: \((-1)(4) + (3)(5)\).",
                r"\(-4 + 15 = 11\).",
                r"No formulas for \(f\) and \(g\) are needed. The product rule only uses their values and slopes at 2."],
               r"\(11\)", kind="Product rule from given values"),
            pq(r"Differentiate \(y = x(x - 1)(x + 2)\) with the three-factor product rule.",
               [r"\((fgh)' = f'gh + fg'h + fgh'\) with \(f = x\), \(g = x - 1\), \(h = x + 2\). Each derivative is 1.",
                r"\(y' = (x-1)(x+2) + x(x+2) + x(x-1)\).",
                r"Expand: \((x^2 + x - 2) + (x^2 + 2x) + (x^2 - x)\)."],
               r"\(y' = 3x^2 + 2x - 2\)", kind="Product of three factors"),
        ]),
    ],

    # ======================= WEEK 4: INVERSE, EXPONENTIAL & TRIG FUNCTIONS =======================
    # This week has no chain rule yet: derivatives here use only the power, product and quotient rules.
    4: [
        pset("Functions and their inverses", "inverse-functions", [
            pq(r"Find the inverse of \(f(x) = 3(x+2)^2 - 5\) if \(x \ge -2\), and give the domain of \(f^{-1}\).",
               [r"Write \(y = 3(x+2)^2 - 5\), then swap \(x\) and \(y\): \(x = 3(y+2)^2 - 5\).",
                r"Isolate the square: \((y+2)^2 = \dfrac{x+5}{3}\).",
                r"Take the square root. The original \(x \ge -2\) becomes \(y \ge -2\), so keep the positive root: \(y + 2 = \sqrt{\dfrac{x+5}{3}}\).",
                r"The domain of \(f^{-1}\) is the range of \(f\). The lowest value of \(f\) is \(-5\)."],
               r"\(f^{-1}(x) = \sqrt{\dfrac{x+5}{3}} - 2\), where \(x \ge -5\)", kind="Inverse of a quadratic on a restricted domain"),
            pq(r"Find the inverse of \(g(x) = -(x-4)^2 + 2\) if \(x \le 4\), and give the domain of \(g^{-1}\).",
               [r"Swap \(x\) and \(y\): \(x = -(y-4)^2 + 2\).",
                r"Isolate the square: \((y-4)^2 = 2 - x\).",
                r"The original \(x \le 4\) becomes \(y \le 4\), so \(y - 4\) is negative. Keep the negative root: \(y - 4 = -\sqrt{2 - x}\).",
                r"The highest value of \(g\) is 2, so the inverse needs \(x \le 2\)."],
               r"\(g^{-1}(x) = 4 - \sqrt{2 - x}\), where \(x \le 2\)", kind="Inverse of a quadratic (left branch)"),
            pq(r"Find the inverse of \(h(x) = \dfrac{2x + 1}{x - 3}\).",
               [r"Swap \(x\) and \(y\): \(x = \dfrac{2y + 1}{y - 3}\).",
                r"Multiply both sides by \((y - 3)\): \(xy - 3x = 2y + 1\).",
                r"Collect the \(y\) terms on one side: \(xy - 2y = 3x + 1\).",
                r"Factor out \(y\) and divide: \(y(x - 2) = 3x + 1\)."],
               r"\(h^{-1}(x) = \dfrac{3x + 1}{x - 2}\), where \(x \ne 2\)", kind="Inverse of a rational function"),
            pq(r"If \(f(2) = 7\), what is \(f^{-1}(7)\)? Is \(f^{-1}(x)\) the same as \(\dfrac{1}{f(x)}\)?",
               [r"An inverse reverses the input and the output: \(f\) sends 2 to 7, so \(f^{-1}\) sends 7 back to 2.",
                r"The \(-1\) on a function name is reserved notation for the inverse. It is not an exponent.",
                r"For any other power, \(f^k(x) = (f(x))^k\). The reciprocal has to be written \((f(x))^{-1}\)."],
               r"\(f^{-1}(7) = 2\). No: \(f^{-1}(x) \ne (f(x))^{-1} = \dfrac{1}{f(x)}\).", kind="Meaning of inverse notation"),
            pq(r"The point \((1, 6)\) is on the graph of \(f\). What point must be on the graph of \(f^{-1}\), and what line are the two graphs mirrored across?",
               [r"\((1, 6)\) on the graph of \(f\) means \(f(1) = 6\).",
                r"The inverse undoes \(f\), so \(f^{-1}(6) = 1\). That puts \((6, 1)\) on the graph of \(f^{-1}\).",
                r"In general, every point \((a, b)\) on \(f\) gives the point \((b, a)\) on \(f^{-1}\): inputs and outputs swap.",
                r"Swapping the coordinates of every point is a reflection in the line \(y = x\).",
                r"So the two graphs are mirror images in \(y = x\). Any point where \(f\) crosses that line stays where it is."],
               r"\((6, 1)\). The graphs are mirror images across \(y = x\).", kind="Graph of an inverse"),
        ]),
        pset("Exponential and logarithmic functions", "exponential-functions", [
            pq(r"Find the inverse of \(f(x) = 5(3^x) - 2\).",
               [r"Swap \(x\) and \(y\): \(x = 5(3^y) - 2\).",
                r"Isolate the exponential: \(3^y = \dfrac{x+2}{5}\).",
                r"A logarithm with the same base undoes it: \(y = \log_3\!\left(\dfrac{x+2}{5}\right)\).",
                r"A logarithm needs a positive input, so \(x + 2 \gt 0\)."],
               r"\(f^{-1}(x) = \log_3\!\left(\dfrac{x+2}{5}\right)\), where \(x \gt -2\)", kind="Inverse of an exponential function"),
            pq(r"Simplify exactly: \(\log_2 48 - \log_2 3\).",
               [r"Neither log is a whole number on its own, but together they simplify.",
                r"Subtracting logs with the same base divides the insides: \(\log_2 48 - \log_2 3 = \log_2\dfrac{48}{3}\).",
                r"\(\dfrac{48}{3} = 16\).",
                r"\(\log_2 16\) asks: 2 to what power gives 16? Since \(2^4 = 16\), the answer is 4."],
               r"\(4\)", kind="Simplifying logs"),
            pq(r"Solve \(3\log_5 x = 6\) exactly, and solve \(2^{x-1} + 3 = 20\) to 1 decimal place.",
               [r"First equation: divide by 3 to get \(\log_5 x = 2\), so \(x = 5^2\).",
                r"Second equation: subtract 3 to get \(2^{x-1} = 17\).",
                r"Take \(\log_2\) of both sides: \(x - 1 = \log_2 17\).",
                r"Change of base: \(\log_2 17 = \dfrac{\ln 17}{\ln 2} \approx 4.09\)."],
               r"\(x = 25\), and \(x = 1 + \log_2 17 \approx 5.1\)", kind="Solving log and exponential equations"),
            pq(r"A binary search takes \(f(n) = \log_2(n)\) steps to find an item in a sorted list of \(n\) items. How many steps does a list of 1,000,000 items take? How many could a linear search with \(f(n) = n\) take?",
               [r"\(\log_2(1{,}000{,}000) = \dfrac{\ln 1{,}000{,}000}{\ln 2} \approx 19.93\).",
                r"Steps are whole numbers, so round up.",
                r"A linear search checks the items one at a time, so the worst case is every item."],
               r"About 20 steps for the binary search, and up to 1,000,000 for the linear search.", kind="Logarithm in context"),
            pq(r"Find the derivative of \(f(x) = 4(5^x) - 3x^3\).",
               [r"The two terms need different rules. In \(5^x\) the variable is in the exponent (exponential rule). In \(x^3\) it is in the base (power rule).",
                r"Exponential rule: \(\dfrac{d}{dx}b^x = b^x\ln b\). So \(4(5^x)\) gives \(4(5^x)\ln5\).",
                r"It is not \(x\cdot5^{x-1}\). The power rule does not work when the exponent is the variable.",
                r"Power rule: \(3x^3\) gives \(9x^2\).",
                r"Subtract: \(f'(x) = 4(5^x)\ln5 - 9x^2\)."],
               r"\(f'(x) = 4(5^x)\ln 5 - 9x^2\)", kind="Derivative of an exponential"),
            pq(r"Find the derivative of \(g(x) = x^2 \cdot 3^x\).",
               [r"Product rule with \(f = x^2\) and \(g = 3^x\): \(f' = 2x\) and \(g' = 3^x\ln 3\).",
                r"\(g'(x) = 2x \cdot 3^x + x^2 \cdot 3^x\ln 3\).",
                r"Factor out \(x \cdot 3^x\)."],
               r"\(g'(x) = x \cdot 3^x\,(2 + x\ln 3)\)", kind="Product rule with an exponential"),
            pq(r"Find the derivative of \(h(x) = \dfrac{e^x}{x^2}\).",
               [r"Quotient rule \(\left(\dfrac fg\right)' = \dfrac{f'g - fg'}{g^2}\) with \(f = e^x\) and \(g = x^2\).",
                r"\(h'(x) = \dfrac{e^x \cdot x^2 - e^x \cdot 2x}{x^4}\).",
                r"Factor \(x e^x\) out of the top and cancel one \(x\)."],
               r"\(h'(x) = \dfrac{e^x(x - 2)}{x^3}\)", kind="Quotient rule with an exponential"),
            pq(r"Find the slope of the tangent to \(g(x) = 2e^x - x^2\) at \(x = \ln 4\).",
               [r"The slope of the tangent at a point is the derivative at that point.",
                r"\(g'(x) = 2e^x - 2x\), because \(e^x\) is its own derivative.",
                r"Put in \(x = \ln4\): \(g'(\ln4) = 2e^{\ln4} - 2\ln4\).",
                r"\(e^{\ln4} = 4\), because \(e^x\) and \(\ln x\) undo each other.",
                r"So the slope is \(8 - 2\ln4 \approx 8 - 2.77 = 5.23\)."],
               r"\(8 - 2\ln 4 \approx 5.23\)", kind="Slope at a point with e"),
        ]),
        pset("Trigonometric functions", "trig-functions", [
            pq(r"Evaluate exactly: \(\sin(210^\circ)\), \(\cos\!\left(\dfrac{5\pi}{6}\right)\) and \(\tan\!\left(\dfrac{3\pi}{4}\right)\).",
               [r"\(210^\circ\) is in quadrant III with reference angle \(30^\circ\). Sine is negative there: \(-\sin 30^\circ = -\frac12\).",
                r"\(\frac{5\pi}{6}\) is in quadrant II with reference angle \(\frac\pi6\). Cosine is negative there: \(-\cos\frac\pi6 = -\frac{\sqrt3}{2}\).",
                r"\(\frac{3\pi}{4}\) is in quadrant II with reference angle \(\frac\pi4\). Tangent is negative there: \(-\tan\frac\pi4 = -1\)."],
               r"\(-\dfrac12\), \(-\dfrac{\sqrt3}{2}\) and \(-1\)", kind="Exact trig values"),
            pq(r"Find the derivative of \(f(x) = 3\sin x - 2\cos x\).",
               [r"The two facts needed: \(\dfrac{d}{dx}\sin x = \cos x\) and \(\dfrac{d}{dx}\cos x = -\sin x\). The minus sign goes with cosine.",
                r"\(3\sin x\) gives \(3\cos x\).",
                r"\(-2\cos x\) gives \(-2\cdot(-\sin x) = +2\sin x\). Two minus signs make a plus.",
                r"\(f'(x) = 3\cos x + 2\sin x\).",
                r"Quick check at \(x = 0\): \(f'(0) = 3\), so the graph should be rising there. It is, because \(-2\cos x\) is at its lowest point and \(3\sin x\) is rising."],
               r"\(f'(x) = 3\cos x + 2\sin x\)", kind="Derivative of sine and cosine"),
            pq(r"Find the derivative of \(g(x) = x^2\sin x\).",
               [r"\(x^2\) times \(\sin x\) is a product, so use \((uv)' = u'v + uv'\).",
                r"\(u = x^2\), so \(u' = 2x\).",
                r"\(v = \sin x\), so \(v' = \cos x\).",
                r"\(g'(x) = 2x\cdot\sin x + x^2\cdot\cos x\).",
                r"This can be factored as \(x(2\sin x + x\cos x)\), which helps when you need to find where it is zero."],
               r"\(g'(x) = 2x\sin x + x^2\cos x\)", kind="Product rule with trig"),
            pq(r"Use the quotient rule to show that \(\dfrac{d}{dx}\sec x = \sec x\tan x\).",
               [r"Write \(\sec x = \dfrac{1}{\cos x}\).",
                r"Quotient rule: \(\dfrac{0 \cdot \cos x - 1 \cdot (-\sin x)}{\cos^2 x} = \dfrac{\sin x}{\cos^2 x}\).",
                r"Split it up: \(\dfrac{1}{\cos x} \cdot \dfrac{\sin x}{\cos x}\)."],
               r"\(\dfrac{\sin x}{\cos^2 x} = \sec x\tan x\)", kind="Deriving the derivative of sec x"),
            pq(r"Find the equation of the tangent to \(f(x) = x\sin x\) at \(x = \pi\), in slope-intercept form.",
               [r"The point: \(f(\pi) = \pi\sin\pi = 0\), so \((\pi, 0)\).",
                r"Product rule: \(f'(x) = \sin x + x\cos x\).",
                r"The slope: \(f'(\pi) = 0 + \pi(-1) = -\pi\).",
                r"Point-slope form: \(y - 0 = -\pi(x - \pi)\)."],
               r"\(y = -\pi x + \pi^2\)", kind="Tangent line with trig"),
        ]),
        pset("Quotient rule", "quotient-rule", [
            pq(r"Differentiate \(y = \dfrac{2x + 1}{x^2 + 3}\).",
               [r"Quotient rule with \(f = 2x + 1\) and \(g = x^2 + 3\): \(f' = 2\) and \(g' = 2x\).",
                r"\(y' = \dfrac{2(x^2 + 3) - (2x + 1)(2x)}{(x^2 + 3)^2}\).",
                r"Expand the top: \(2x^2 + 6 - 4x^2 - 2x\)."],
               r"\(y' = \dfrac{-2x^2 - 2x + 6}{(x^2 + 3)^2}\)", kind="Quotient rule"),
            pq(r"Find the equation of the tangent line to \(y = \dfrac{x}{x + 2}\) at \(x = 2\).",
               [r"The point: \(y(2) = \frac24 = \frac12\).",
                r"Quotient rule: \(y' = \dfrac{(1)(x+2) - x(1)}{(x+2)^2} = \dfrac{2}{(x+2)^2}\).",
                r"The slope: \(y'(2) = \frac{2}{16} = \frac18\).",
                r"Point-slope form: \(y - \frac12 = \frac18(x - 2)\)."],
               r"\(y = \frac18 x + \frac14\)", kind="Tangent line with the quotient rule"),
        ]),
        pset("Derivatives of e^x and a^x", "exp-derivatives", [
            pq(r"Differentiate \(y = 4e^x - x^3 + 7\).",
               [r"Go term by term. The 4 waits outside, and \(e^x\) is its own derivative: \(4e^x\).",
                r"\(-x^3\) is a power, so the power rule gives \(-3x^2\).",
                r"The constant 7 gives 0."],
               r"\(y' = 4e^x - 3x^2\)", kind="e^x term by term"),
            pq(r"Differentiate \(y = 3^x + x^3\).",
               [r"The two terms look alike and follow different rules. Check where the \(x\) is.",
                r"In \(3^x\) the \(x\) is the exponent, so it is an exponential: \(3^x\ln 3\).",
                r"In \(x^3\) the \(x\) is the base, so it is a power: \(3x^2\)."],
               r"\(y' = 3^x\ln 3 + 3x^2\)", kind="An exponential beside a power"),
            pq(r"Find the point on \(y = xe^x\) where the tangent line is horizontal.",
               [r"Product rule with \(f = x\), \(g = e^x\): \(y' = 1\cdot e^x + x\cdot e^x = e^x(x + 1)\).",
                r"Set \(y' = 0\). \(e^x\) is never zero, so \(x + 1 = 0\) and \(x = -1\).",
                r"The height there: \(y(-1) = -e^{-1} = -\dfrac1e\)."],
               r"\(\left(-1, -\frac1e\right)\)", kind="Horizontal tangent with e^x"),
            pq(r"Differentiate \(y = \dfrac{e^x}{x^2 + 1}\) and simplify.",
               [r"Quotient rule with \(f = e^x\), \(f' = e^x\) and \(g = x^2 + 1\), \(g' = 2x\).",
                r"\(y' = \dfrac{e^x(x^2 + 1) - e^x(2x)}{(x^2 + 1)^2}\).",
                r"Factor \(e^x\) out of the top: \(e^x(x^2 - 2x + 1)\).",
                r"\(x^2 - 2x + 1\) is \((x - 1)^2\)."],
               r"\(y' = \dfrac{e^x(x - 1)^2}{(x^2 + 1)^2}\)", kind="Quotient rule with e^x"),
            pq(r"Find the equation of the tangent line to \(y = 2^x\) at \(x = 1\).",
               [r"The point: \(y(1) = 2\).",
                r"\(y' = 2^x\ln 2\), so the slope is \(y'(1) = 2\ln 2\). That is a number, about 1.386.",
                r"Point-slope form: \(y - 2 = 2\ln 2\,(x - 1)\)."],
               r"\(y = 2\ln 2\,(x - 1) + 2\)", kind="Tangent line to a^x"),
            pq(r"For \(y = e^x\sin x\), find \(y'\) and \(y''\).",
               [r"Product rule: \(y' = e^x\sin x + e^x\cos x = e^x(\sin x + \cos x)\).",
                r"Product rule again, with \(f = e^x\) and \(g = \sin x + \cos x\), so \(g' = \cos x - \sin x\).",
                r"\(y'' = e^x(\sin x + \cos x) + e^x(\cos x - \sin x)\).",
                r"The sines cancel."],
               r"\(y' = e^x(\sin x + \cos x)\), \(y'' = 2e^x\cos x\)", kind="Product rule with e^x and trig"),
        ]),
        pset("Harder ln questions", "log-functions", [
            pq(r"Simplify exactly: \(e^{2\ln 3 - \ln 6}\), and \(\ln\!\left(e^5\sqrt{e}\right)\).",
               [r"\(2\ln 3 = \ln 9\), so the exponent is \(\ln 9 - \ln 6 = \ln\frac96 = \ln\frac32\).",
                r"\(e^{\ln(3/2)} = \frac32\).",
                r"For the second one, \(e^5\sqrt{e} = e^5 \cdot e^{1/2} = e^{11/2}\), and \(\ln\) undoes \(e\)."],
               r"\(\dfrac32\) and \(\dfrac{11}{2}\)", kind="Simplifying with e and ln"),
            pq(r"Solve exactly: \(\ln x + \ln(x - 3) = \ln 10\).",
               [r"A sum of logs is the log of a product: \(\ln\big(x(x-3)\big) = \ln 10\).",
                r"So \(x(x - 3) = 10\), which is \(x^2 - 3x - 10 = 0\).",
                r"Factor: \((x - 5)(x + 2) = 0\), so \(x = 5\) or \(x = -2\).",
                r"Check the original equation: \(\ln(-2)\) is not defined, so \(x = -2\) is rejected."],
               r"\(x = 5\)", kind="Log equation with an extraneous root"),
            pq(r"Solve exactly: \(2\ln x - \ln(x + 2) = 0\).",
               [r"Move one log across: \(2\ln x = \ln(x+2)\), and \(2\ln x = \ln(x^2)\).",
                r"So \(x^2 = x + 2\), which is \(x^2 - x - 2 = 0\).",
                r"Factor: \((x - 2)(x + 1) = 0\), so \(x = 2\) or \(x = -1\).",
                r"\(\ln(-1)\) is not defined, so \(x = -1\) is rejected."],
               r"\(x = 2\)", kind="Log equation that becomes a quadratic"),
            pq(r"Solve exactly: \(5e^x = 2e^{3x}\).",
               [r"There is an exponential on each side, so collect them on one side.",
                r"Divide both sides by \(e^x\), which is never zero: \(5 = \dfrac{2e^{3x}}{e^x} = 2e^{2x}\). Dividing powers subtracts the exponents.",
                r"Divide by 2: \(e^{2x} = \dfrac52\).",
                r"Take \(\ln\) of both sides: \(2x = \ln\dfrac52\).",
                r"\(x = \dfrac12\ln\dfrac52 \approx 0.46\)."],
               r"\(x = \frac12\ln\frac52 \approx 0.46\)", kind="Exponential equation with e on both sides"),
            pq(r"Solve \(3^{x+1} = 5^x\) exactly using \(\ln\), then round to 2 decimal places.",
               [r"Take \(\ln\) of both sides and bring the exponents down: \((x+1)\ln 3 = x\ln 5\).",
                r"Expand: \(x\ln 3 + \ln 3 = x\ln 5\).",
                r"Collect the \(x\) terms: \(\ln 3 = x(\ln 5 - \ln 3)\)."],
               r"\(x = \dfrac{\ln 3}{\ln 5 - \ln 3} \approx 2.15\)", kind="Exponential equation with two bases"),
            pq(r"Find the inverse of \(f(x) = 2\ln(x - 1) + 3\), and state the domain and range of \(f^{-1}\).",
               [r"Swap \(x\) and \(y\): \(x = 2\ln(y - 1) + 3\).",
                r"Isolate the log: \(\ln(y - 1) = \dfrac{x - 3}{2}\).",
                r"Raise \(e\) to both sides: \(y - 1 = e^{(x-3)/2}\).",
                r"\(f\) needs \(x \gt 1\) and can output any real number, so \(f^{-1}\) takes any real number and outputs values above 1."],
               r"\(f^{-1}(x) = e^{(x-3)/2} + 1\). Its domain is all real numbers and its range is \(y \gt 1\).", kind="Inverse of a shifted natural log"),
            pq(r"Find the inverse of \(f(x) = \dfrac{e^x - 1}{e^x + 1}\), and state the domain of \(f^{-1}\).",
               [r"Swap \(x\) and \(y\): \(x = \dfrac{e^y - 1}{e^y + 1}\).",
                r"Multiply by \((e^y + 1)\): \(xe^y + x = e^y - 1\).",
                r"Collect the \(e^y\) terms: \(x + 1 = e^y(1 - x)\), so \(e^y = \dfrac{1 + x}{1 - x}\).",
                r"Take \(\ln\) of both sides. The input of \(\ln\) must be positive, which needs \(-1 \lt x \lt 1\)."],
               r"\(f^{-1}(x) = \ln\!\left(\dfrac{1 + x}{1 - x}\right)\), where \(-1 \lt x \lt 1\)", kind="Inverse of a fraction of exponentials"),
            pq(r"Find the derivative of \(f(x) = 2^x \cdot 3^x\) and simplify it to a single exponential.",
               [r"Product rule: \(f'(x) = 2^x\ln 2 \cdot 3^x + 2^x \cdot 3^x\ln 3\).",
                r"Factor out \(2^x \cdot 3^x = 6^x\): \(f'(x) = 6^x(\ln 2 + \ln 3)\).",
                r"\(\ln 2 + \ln 3 = \ln 6\). (This matches differentiating \(6^x\) directly.)"],
               r"\(f'(x) = 6^x\ln 6\)", kind="Derivative of a product of exponentials"),
            pq(r"Find the derivative of \(g(x) = \dfrac{5^x}{e^x}\) and simplify.",
               [r"Quotient rule with top \(5^x\) (derivative \(5^x\ln5\)) and bottom \(e^x\) (derivative \(e^x\)).",
                r"\(g'(x) = \dfrac{5^x\ln5\cdot e^x - 5^x\cdot e^x}{(e^x)^2}\).",
                r"Factor \(5^xe^x\) out of the top: \(\dfrac{5^xe^x(\ln5 - 1)}{(e^x)^2}\).",
                r"Cancel one \(e^x\): \(\dfrac{5^x(\ln5 - 1)}{e^x}\), and \(\dfrac{5^x}{e^x} = \left(\dfrac5e\right)^x\).",
                r"Shortcut: \(g(x) = \left(\dfrac5e\right)^x\) is a single exponential with base \(\dfrac5e\), so \(g'(x) = \left(\dfrac5e\right)^x\ln\dfrac5e\), and \(\ln\dfrac5e = \ln5 - 1\)."],
               r"\(g'(x) = \left(\dfrac5e\right)^x(\ln 5 - 1)\)", kind="Derivative of a quotient of exponentials"),
            pq(r"Find the \(x\)-value where \(f(x) = 2^x - x\ln 4\) has a horizontal tangent.",
               [r"\(f'(x) = 2^x\ln 2 - \ln 4\). (\(\ln 4\) is just a constant.)",
                r"Set \(f'(x) = 0\): \(2^x\ln 2 = \ln 4\).",
                r"\(\ln 4 = \ln(2^2) = 2\ln 2\), so \(2^x = 2\)."],
               r"\(x = 1\)", kind="Horizontal tangent with an exponential"),
            pq(r"Find the equation of the tangent to \(f(x) = xe^x\) at \(x = \ln 2\), in slope-intercept form.",
               [r"The point: \(f(\ln 2) = \ln 2 \cdot e^{\ln 2} = 2\ln 2\).",
                r"Product rule: \(f'(x) = e^x + xe^x = e^x(1 + x)\).",
                r"The slope: \(f'(\ln 2) = 2(1 + \ln 2)\).",
                r"Point-slope form: \(y - 2\ln 2 = 2(1 + \ln 2)(x - \ln 2)\). Expanding, the \(2\ln 2\) terms cancel."],
               r"\(y = 2(1 + \ln 2)\,x - 2(\ln 2)^2\)", kind="Tangent line with e"),
            pq(r"A model for the early days of an outbreak predicts \(f(x) = 1.3^x\) cases \(x\) days after the first case. On what day does it predict 1,000,000 cases, and how fast are cases growing on day 14?",
               [r"Solve \(1.3^x = 1{,}000{,}000\) by taking \(\ln\) of both sides: \(x\ln 1.3 = \ln 1{,}000{,}000\).",
                r"\(x = \dfrac{\ln 1{,}000{,}000}{\ln 1.3} \approx \dfrac{13.816}{0.2624} \approx 52.7\).",
                r"The growth rate is the derivative: \(f'(x) = 1.3^x\ln 1.3\).",
                r"\(f'(14) = 1.3^{14}\ln 1.3 \approx 39.37 \times 0.2624\)."],
               r"After about 52.7 days. On day 14, cases are growing by about 10.3 cases per day.", kind="Exponential model"),
        ]),
    ],

    # ============ WEEK 5: CHAIN & QUOTIENT RULES, IMPLICIT DIFFERENTIATION, LOGARITHMS ============
    5: [
        pset("Chain rule", "chain-rule", [
            pq(r"Differentiate \(y = (2x^3 - 5)^4\).",
               [r"Outside function: \((\ )^4\). Inside function: \(2x^3 - 5\).",
                r"Derivative of the outside, keeping the inside: \(4(2x^3 - 5)^3\).",
                r"Multiply by the derivative of the inside, \(6x^2\)."],
               r"\(y' = 24x^2(2x^3 - 5)^3\)", kind="Chain rule on a power"),
            pq(r"Differentiate \(y = \sqrt{3x^2 + 4}\).",
               [r"Rewrite: \(y = (3x^2 + 4)^{1/2}\).",
                r"Chain rule: \(\frac12(3x^2 + 4)^{-1/2} \cdot 6x\).",
                r"Simplify: \(\frac12 \cdot 6x = 3x\)."],
               r"\(y' = \dfrac{3x}{\sqrt{3x^2 + 4}}\)", kind="Chain rule on a root"),
            pq(r"Differentiate \(y = \cos^2(3x)\).",
               [r"There are three layers: \((\ )^2\), then \(\cos\), then \(3x\).",
                r"Square: \(2\cos(3x)\). Cosine: \(-\sin(3x)\). Inside: \(3\).",
                r"Multiply them together."],
               r"\(y' = -6\sin(3x)\cos(3x)\)", kind="Chain rule with trig"),
            pq(r"Differentiate \(y = x^2(x+1)^5\) and factor your answer.",
               [r"It is a product, with \(u = x^2\) and \(v = (x+1)^5\).",
                r"\(u' = 2x\). For \(v'\), use the chain rule: \(5(x+1)^4\cdot1\), since the inside \(x + 1\) has derivative 1.",
                r"Product rule: \(y' = 2x(x+1)^5 + x^2\cdot5(x+1)^4\).",
                r"Factor out the lowest power of each factor, \(x(x+1)^4\): \(y' = x(x+1)^4\big[2(x+1) + 5x\big]\).",
                r"Simplify the bracket: \(2x + 2 + 5x = 7x + 2\)."],
               r"\(y' = x(x+1)^4(7x + 2)\)", kind="Chain rule with the product rule"),
        ]),
        pset("Implicit differentiation", "implicit", [
            pq(r"Find \(\dfrac{dy}{dx}\) for \(x^2 + xy + y^2 = 7\), and the slope at \((1, 2)\).",
               [r"Differentiate every term with respect to \(x\). The \(xy\) term needs the product rule: \(2x + y + x\,y' + 2y\,y' = 0\).",
                r"Collect the \(y'\) terms: \(y'(x + 2y) = -(2x + y)\).",
                r"So \(y' = -\dfrac{2x + y}{x + 2y}\). At \((1, 2)\): \(-\dfrac{2 + 2}{1 + 4}\)."],
               r"\(\dfrac{dy}{dx} = -\dfrac{2x + y}{x + 2y}\), and the slope at \((1, 2)\) is \(-\dfrac45\)", kind="Implicit differentiation with a product"),
            pq(r"Find the equation of the tangent line to \(x^3 + y^3 = 9\) at \((1, 2)\).",
               [r"Differentiate: \(3x^2 + 3y^2\,y' = 0\), so \(y' = -\dfrac{x^2}{y^2}\).",
                r"At \((1, 2)\): \(y' = -\frac14\).",
                r"Point-slope form: \(y - 2 = -\frac14(x - 1)\)."],
               r"\(y = -\frac14 x + \frac94\)", kind="Implicit tangent line"),
        ]),
        pset("Logarithmic functions", "log-functions", [
            pq(r"Expand \(\ln\dfrac{x^3\sqrt{x+1}}{(x-2)^2}\) using the log laws.",
               [r"Start from the outside. A quotient becomes a subtraction: \(\ln\!\left(x^3\sqrt{x+1}\right) - \ln\!\left((x-2)^2\right)\).",
                r"The product on top becomes an addition: \(\ln(x^3) + \ln\sqrt{x+1} - \ln\!\left((x-2)^2\right)\).",
                r"Write the root as a power: \(\sqrt{x+1} = (x+1)^{1/2}\).",
                r"Bring each exponent down in front: \(3\ln x + \tfrac12\ln(x+1) - 2\ln(x-2)\).",
                r"Stop there. \(\ln(x+1)\) cannot be split, because there is no law for the log of a sum."],
               r"\(3\ln x + \frac12\ln(x+1) - 2\ln(x-2)\)", kind="Expanding a logarithm"),
            pq(r"Solve \(2e^{3x} + 1 = 15\).",
               [r"Get the exponential alone before using logs. Subtract 1: \(2e^{3x} = 14\).",
                r"Divide by 2: \(e^{3x} = 7\).",
                r"Take \(\ln\) of both sides. \(\ln\) undoes \(e\), so the left side is just the exponent: \(3x = \ln7\).",
                r"Divide by 3: \(x = \dfrac{\ln7}{3} \approx \dfrac{1.946}{3} \approx 0.65\).",
                r"Taking \(\ln\) too early is the usual mistake: \(\ln(2e^{3x} + 1)\) does not simplify."],
               r"\(x = \dfrac{\ln 7}{3} \approx 0.65\)", kind="Solving an exponential equation"),
            pq(r"Solve \(\log_3 x + \log_3(x - 6) = 3\).",
               [r"Combine the logs: \(\log_3\big(x(x - 6)\big) = 3\).",
                r"Rewrite as an exponential: \(x(x - 6) = 3^3 = 27\).",
                r"So \(x^2 - 6x - 27 = 0\), which factors as \((x - 9)(x + 3) = 0\).",
                r"\(x = -3\) is rejected because \(\log_3(-3)\) is not defined."],
               r"\(x = 9\)", kind="Log equation with an extraneous root"),
        ]),
        pset("Derivatives of exponentials and logarithms", "exp-log-derivatives", [
            pq(r"Differentiate \(y = x^2\ln x\).",
               [r"It is a product, with \(u = x^2\) and \(v = \ln x\).",
                r"\(u' = 2x\) and \(v' = \dfrac1x\).",
                r"Product rule: \(y' = 2x\cdot\ln x + x^2\cdot\dfrac1x\).",
                r"Simplify the second term: \(x^2\cdot\dfrac1x = x\).",
                r"\(y' = 2x\ln x + x\), which can be written \(x(2\ln x + 1)\)."],
               r"\(y' = 2x\ln x + x\)", kind="Product rule with ln"),
            pq(r"Differentiate \(y = e^{2x}\cos x\).",
               [r"Chain rule: \(\dfrac{d}{dx}e^{2x} = 2e^{2x}\).",
                r"Product rule: \(y' = 2e^{2x}\cos x + e^{2x}(-\sin x)\).",
                r"Factor out \(e^{2x}\)."],
               r"\(y' = e^{2x}(2\cos x - \sin x)\)", kind="Product and chain rules together"),
            pq(r"Differentiate \(y = \ln(x^2 + 4)\).",
               [r"This is a log of a function, so it needs the chain rule: \(\dfrac{d}{dx}\ln g(x) = \dfrac{g'(x)}{g(x)}\).",
                r"The inside is \(g(x) = x^2 + 4\), with \(g'(x) = 2x\).",
                r"Put the derivative of the inside over the inside: \(y' = \dfrac{2x}{x^2+4}\).",
                r"The answer is not \(\dfrac{1}{x^2+4}\). Leaving out the \(2x\) is the most common mistake with logs.",
                r"\(x^2 + 4\) is never zero, so the derivative exists for every \(x\)."],
               r"\(y' = \dfrac{2x}{x^2 + 4}\)", kind="Derivative of ln of a function"),
            pq(r"Use logarithmic differentiation to differentiate \(y = x^{2x}\) (for \(x \gt 0\)).",
               [r"Take \(\ln\) of both sides: \(\ln y = 2x\ln x\).",
                r"Differentiate both sides: \(\dfrac{y'}{y} = 2\ln x + 2x \cdot \frac1x = 2\ln x + 2\).",
                r"Multiply by \(y = x^{2x}\)."],
               r"\(y' = 2x^{2x}(\ln x + 1)\)", kind="Logarithmic differentiation"),
        ]),
    ],

    # ======================= WEEK 6: CRITICAL POINTS & CURVE SKETCHING =======================
    6: [
        pset("Critical points and the first derivative test", "critical-points", [
            pq(r"Find the critical numbers of \(f(x) = x^3 - 6x^2 + 5\).",
               [r"A critical number is an \(x\) in the domain where \(f'(x) = 0\) or \(f'(x)\) does not exist.",
                r"\(f'(x) = 3x^2 - 12x\).",
                r"Factor: \(f'(x) = 3x(x - 4)\).",
                r"\(f'\) is a polynomial, so it exists everywhere. The only critical numbers are its zeros: \(3x = 0\) or \(x - 4 = 0\).",
                r"Critical numbers are \(x\)-values. The points on the graph are \((0, 5)\) and \((4, -27)\)."],
               r"\(x = 0\) and \(x = 4\)", kind="Critical numbers of a polynomial"),
            pq(r"Find where \(f(x) = 2x^3 - 3x^2 - 12x + 1\) is increasing and decreasing, and its local extrema.",
               [r"\(f'(x) = 6x^2 - 6x - 12 = 6(x - 2)(x + 1)\), which is zero at \(x = -1\) and \(x = 2\).",
                r"Sign chart: \(f'(-2) \gt 0\), \(f'(0) \lt 0\), \(f'(3) \gt 0\).",
                r"\(f'\) goes \(+ \to -\) at \(x = -1\) (local max) and \(- \to +\) at \(x = 2\) (local min).",
                r"\(f(-1) = -2 - 3 + 12 + 1 = 8\) and \(f(2) = 16 - 12 - 24 + 1 = -19\)."],
               r"Increasing on \((-\infty, -1)\) and \((2, \infty)\), decreasing on \((-1, 2)\). Local max \((-1, 8)\), local min \((2, -19)\).", kind="Increasing, decreasing and local extrema"),
            pq(r"Find the critical numbers of \(f(x) = x^{1/3}(x - 4)\).",
               [r"Expand first: \(f(x) = x^{4/3} - 4x^{1/3}\).",
                r"\(f'(x) = \frac43 x^{1/3} - \frac43 x^{-2/3} = \dfrac{4(x - 1)}{3x^{2/3}}\).",
                r"\(f'(x) = 0\) when the top is zero: \(x = 1\).",
                r"\(f'\) is undefined when the bottom is zero: \(x = 0\), which is in the domain of \(f\)."],
               r"\(x = 0\) and \(x = 1\)", kind="Critical numbers where the derivative is undefined"),
            pq(r"Find the absolute maximum and minimum of \(f(x) = x^3 - 3x^2 + 1\) on \([-1, 4]\).",
               [r"On a closed interval, the absolute extremes can only be at critical numbers inside the interval or at the endpoints. Check them all.",
                r"\(f'(x) = 3x^2 - 6x = 3x(x-2)\), so the critical numbers are \(x = 0\) and \(x = 2\). Both are inside \([-1, 4]\).",
                r"Evaluate \(f\) at all four candidates: \(f(-1) = -1 - 3 + 1 = -3\), \(f(0) = 1\), \(f(2) = 8 - 12 + 1 = -3\), \(f(4) = 64 - 48 + 1 = 17\).",
                r"The largest value is 17, at the endpoint \(x = 4\).",
                r"The smallest value is \(-3\), and it happens twice: at the endpoint \(x = -1\) and at the critical number \(x = 2\). An absolute minimum is one value, but it can be reached at more than one place."],
               r"Absolute max \(17\) at \(x = 4\). Absolute min \(-3\) at \(x = -1\) and at \(x = 2\).", kind="Absolute extrema on a closed interval"),
            pq(r"Find and classify the critical point of \(f(x) = xe^{-x}\).",
               [r"Product rule: \(f'(x) = e^{-x} - xe^{-x} = e^{-x}(1 - x)\).",
                r"\(e^{-x}\) is never zero, so the only critical number is \(x = 1\).",
                r"\(f' \gt 0\) for \(x \lt 1\) and \(f' \lt 0\) for \(x \gt 1\): the sign goes \(+ \to -\)."],
               r"A local (and absolute) maximum at \(\left(1, \dfrac1e\right)\)", kind="Critical point with an exponential"),
            pq(r"A function has derivative \(f'(x) = (x - 1)^2(x + 2)\). Where does \(f\) have local extrema?",
               [r"\(f'(x) = 0\) at \(x = 1\) and \(x = -2\).",
                r"\((x - 1)^2\) is never negative, so the sign of \(f'\) is the sign of \((x + 2)\).",
                r"At \(x = -2\) the sign goes \(- \to +\): a local minimum.",
                r"At \(x = 1\) the sign stays positive on both sides: no extremum."],
               r"A local minimum at \(x = -2\) only. \(x = 1\) is a critical number but not an extremum.", kind="Extrema from a formula for the derivative"),
        ]),
        pset("Concavity and the second derivative test", "concavity", [
            pq(r"Find the intervals of concavity and the inflection point of \(f(x) = x^3 - 6x^2 + 4\).",
               [r"\(f'(x) = 3x^2 - 12x\) and \(f''(x) = 6x - 12\).",
                r"\(f''(x) = 0\) at \(x = 2\). \(f'' \lt 0\) for \(x \lt 2\) and \(f'' \gt 0\) for \(x \gt 2\).",
                r"The concavity changes at \(x = 2\), and \(f(2) = 8 - 24 + 4 = -12\)."],
               r"Concave down on \((-\infty, 2)\), concave up on \((2, \infty)\). Inflection point \((2, -12)\).", kind="Concavity and inflection point"),
            pq(r"Find the inflection points of \(f(x) = 3x^5 - 5x^4\).",
               [r"\(f'(x) = 15x^4 - 20x^3\) and \(f''(x) = 60x^3 - 60x^2 = 60x^2(x - 1)\).",
                r"\(f''(x) = 0\) at \(x = 0\) and \(x = 1\).",
                r"\(60x^2\) is never negative, so \(f''\) only changes sign at \(x = 1\). At \(x = 0\) it is negative on both sides.",
                r"\(f(1) = 3 - 5 = -2\)."],
               r"One inflection point, at \((1, -2)\). \(x = 0\) is not one.", kind="Checking for a sign change"),
            pq(r"Use the second derivative test to classify the critical points of \(f(x) = x^3 - 12x + 3\).",
               [r"\(f'(x) = 3x^2 - 12 = 3(x - 2)(x + 2)\), so the critical numbers are \(x = \pm 2\).",
                r"\(f''(x) = 6x\). \(f''(2) = 12 \gt 0\): local min. \(f''(-2) = -12 \lt 0\): local max.",
                r"\(f(2) = 8 - 24 + 3 = -13\) and \(f(-2) = -8 + 24 + 3 = 19\)."],
               r"Local min at \((2, -13)\), local max at \((-2, 19)\)", kind="Second derivative test"),
            pq(r"Find and classify the critical points of \(f(x) = x + 2\sin x\) on \((0, 2\pi)\).",
               [r"\(f'(x) = 1 + 2\cos x = 0\) gives \(\cos x = -\frac12\), so \(x = \frac{2\pi}{3}\) or \(x = \frac{4\pi}{3}\).",
                r"\(f''(x) = -2\sin x\).",
                r"\(f''\!\left(\frac{2\pi}{3}\right) = -\sqrt3 \lt 0\): local max. \(f''\!\left(\frac{4\pi}{3}\right) = \sqrt3 \gt 0\): local min."],
               r"Local max at \(x = \frac{2\pi}{3}\) (value \(\frac{2\pi}{3} + \sqrt3 \approx 3.83\)), local min at \(x = \frac{4\pi}{3}\) (value \(\frac{4\pi}{3} - \sqrt3 \approx 2.46\))", kind="Second derivative test with trig"),
        ]),
        pset("Curve sketching", "curve-sketching", [
            pq(r"List the key features of \(f(x) = x^3 - 3x^2\): intercepts, local extrema and inflection point.",
               [r"Intercepts: \(f(x) = x^2(x - 3)\), so the graph meets the \(x\)-axis at \(x = 0\) and \(x = 3\).",
                r"\(f'(x) = 3x^2 - 6x = 3x(x - 2)\): increasing for \(x \lt 0\), decreasing on \((0, 2)\), increasing for \(x \gt 2\).",
                r"So there is a local max at \((0, 0)\) and a local min at \((2, -4)\).",
                r"\(f''(x) = 6x - 6\) changes sign at \(x = 1\), where \(f(1) = -2\)."],
               r"\(x\)-intercepts 0 and 3, local max \((0, 0)\), local min \((2, -4)\), inflection point \((1, -2)\)", kind="Sketching a cubic"),
            pq(r"Find all asymptotes of \(f(x) = \dfrac{2x^2 + 1}{x^2 - 1}\).",
               [r"Vertical asymptotes: find where the bottom is zero. \(x^2 - 1 = (x-1)(x+1) = 0\) at \(x = \pm1\).",
                r"Check the top at those values: \(2(1) + 1 = 3\), which is not zero. So both are real asymptotes, not holes.",
                r"Horizontal asymptotes: take the limit as \(x \to \pm\infty\). Divide top and bottom by \(x^2\): \(\dfrac{2 + \frac{1}{x^2}}{1 - \frac{1}{x^2}}\).",
                r"As \(x \to \pm\infty\) this approaches \(\dfrac21 = 2\). So \(y = 2\) is the horizontal asymptote in both directions.",
                r"There is no slant asymptote. That only happens when the top's degree is exactly one more than the bottom's."],
               r"Vertical asymptotes \(x = 1\) and \(x = -1\), horizontal asymptote \(y = 2\)", kind="Vertical and horizontal asymptotes"),
            pq(r"List the key features of \(f(x) = \dfrac{x}{x^2 - 4}\): asymptotes, symmetry, and where it increases or decreases.",
               [r"Vertical asymptotes where the bottom is zero: \(x = \pm 2\). Horizontal asymptote \(y = 0\), since the bottom has the higher degree.",
                r"\(f(-x) = -f(x)\), so the function is odd (symmetric about the origin). It passes through \((0, 0)\).",
                r"Quotient rule: \(f'(x) = \dfrac{(x^2 - 4) - x(2x)}{(x^2 - 4)^2} = \dfrac{-(x^2 + 4)}{(x^2 - 4)^2}\).",
                r"The top is always negative and the bottom is always positive, so \(f' \lt 0\) wherever it is defined."],
               r"Vertical asymptotes \(x = \pm 2\), horizontal asymptote \(y = 0\), odd, and decreasing on every interval of its domain (no local extrema)", kind="Sketching a rational function"),
            pq(r"Sketch \(f(x) = x^4 - 2x^2\): find its symmetry, local extrema and inflection points.",
               [r"\(f(-x) = f(x)\), so the function is even (symmetric about the \(y\)-axis).",
                r"\(f'(x) = 4x^3 - 4x = 4x(x - 1)(x + 1)\). The signs go \(-, +, -, +\), so there are local minima at \(x = \pm 1\) and a local max at \(x = 0\).",
                r"\(f(\pm 1) = -1\) and \(f(0) = 0\).",
                r"\(f''(x) = 12x^2 - 4 = 0\) at \(x = \pm\frac{1}{\sqrt3}\), where \(f = \frac19 - \frac23 = -\frac59\). The sign of \(f''\) changes at both."],
               r"Even. Local minima \((\pm 1, -1)\), local max \((0, 0)\), inflection points \(\left(\pm\frac{1}{\sqrt3}, -\frac59\right)\). It has a W shape.", kind="Sketching an even quartic"),
        ]),
    ],
}
