r"""Practice sets for weeks 7-12. Math is written the same way as in the lessons:
LaTeX inside \( ... \), and \lt instead of a bare "<"."""
from lesson_helpers import pq, pset

PRACTICE_7_12 = {
    # ================= WEEK 7: IVT, MVT, NEWTON'S METHOD & OPTIMIZATION =================
    7: [
        pset("Intermediate Value Theorem", "ivt", [
            pq(r"Show that \(x^3 - 4x + 1 = 0\) has a solution between 0 and 1.",
               [r"Let \(f(x) = x^3 - 4x + 1\). It is a polynomial, so it is continuous on \([0, 1]\).",
                r"\(f(0) = 1 \gt 0\) and \(f(1) = 1 - 4 + 1 = -2 \lt 0\).",
                r"0 is between \(f(0)\) and \(f(1)\), so the IVT applies."],
               r"By the IVT there is a \(c\) in \((0, 1)\) with \(f(c) = 0\).", kind="Showing a root exists"),
            pq(r"Show that \(e^x = 3 - x\) has a solution in \((0, 1)\).",
               [r"Move everything to one side: let \(g(x) = e^x + x - 3\), which is continuous everywhere.",
                r"\(g(0) = 1 + 0 - 3 = -2 \lt 0\) and \(g(1) = e + 1 - 3 \approx 0.72 \gt 0\).",
                r"\(g\) changes sign on \([0, 1]\), so the IVT gives a \(c\) with \(g(c) = 0\)."],
               r"There is a \(c\) in \((0, 1)\) with \(e^c = 3 - c\).", kind="Showing an equation has a solution"),
            pq(r"Must \(f(x) = x^2 + 1\) take the value 5 somewhere on \([0, 3]\)? If so, find where.",
               [r"\(f\) is continuous, with \(f(0) = 1\) and \(f(3) = 10\).",
                r"5 is between 1 and 10, so the IVT says yes.",
                r"Solve \(c^2 + 1 = 5\): \(c = \pm 2\), and only \(c = 2\) is in the interval."],
               r"Yes, at \(c = 2\)", kind="Intermediate value, then finding it"),
        ]),
        pset("Mean Value Theorem", "mvt", [
            pq(r"Find the value of \(c\) that the Mean Value Theorem guarantees for \(f(x) = x^2 - 4x\) on \([1, 5]\).",
               [r"\(f\) is a polynomial, so it is continuous on \([1, 5]\) and differentiable on \((1, 5)\). The theorem applies.",
                r"\(f(5) = 25 - 20 = 5\) and \(f(1) = 1 - 4 = -3\).",
                r"Average slope: \(\dfrac{f(5) - f(1)}{5 - 1} = \dfrac{5 - (-3)}{4} = 2\).",
                r"\(f'(x) = 2x - 4\). Set \(f'(c) = 2\): \(2c - 4 = 2\), so \(c = 3\).",
                r"\(c = 3\) is inside \((1, 5)\), as it must be. At \(x = 3\) the tangent line is parallel to the line joining the two endpoints."],
               r"\(c = 3\)", kind="Mean Value Theorem for a polynomial"),
            pq(r"Find the value of \(c\) that the Mean Value Theorem guarantees for \(f(x) = \sqrt{x}\) on \([0, 4]\).",
               [r"\(\sqrt{x}\) is continuous on \([0, 4]\) and differentiable on \((0, 4)\). It is not differentiable at 0, but that is an endpoint, which is allowed.",
                r"Average slope: \(\dfrac{\sqrt4 - \sqrt0}{4 - 0} = \dfrac24 = \dfrac12\).",
                r"\(f'(x) = \dfrac{1}{2\sqrt{x}}\).",
                r"Set \(f'(c) = \dfrac12\): \(\dfrac{1}{2\sqrt{c}} = \dfrac12\), so \(\sqrt{c} = 1\) and \(c = 1\).",
                r"\(c = 1\) is inside \((0, 4)\)."],
               r"\(c = 1\)", kind="Mean Value Theorem for a root"),
            pq(r"Check that Rolle's theorem applies to \(f(x) = x^3 - 4x\) on \([-2, 2]\), and find every \(c\) it guarantees.",
               [r"Rolle's theorem has three conditions: continuous on \([-2, 2]\), differentiable on \((-2, 2)\), and equal values at the two endpoints.",
                r"\(f\) is a polynomial, so the first two hold.",
                r"\(f(-2) = -8 + 8 = 0\) and \(f(2) = 8 - 8 = 0\). The endpoints match, so the theorem applies.",
                r"It promises a \(c\) with \(f'(c) = 0\): \(3c^2 - 4 = 0\), so \(c^2 = \frac43\) and \(c = \pm\dfrac{2}{\sqrt3} \approx \pm1.15\).",
                r"Both values are inside \((-2, 2)\), so both count. The theorem promises at least one such \(c\). Here there are two."],
               r"\(c = \pm\dfrac{2}{\sqrt3} \approx \pm 1.15\), both inside \((-2, 2)\)", kind="Rolle's theorem"),
            pq(r"\(f(x) = |x|\) has \(f(-1) = f(1) = 1\), but \(f'(c)\) is never 0. Why doesn't this break Rolle's theorem?",
               [r"Rolle's theorem needs \(f\) to be continuous on \([-1, 1]\), differentiable on \((-1, 1)\), and to have equal values at the endpoints.",
                r"\(|x|\) is continuous, and \(f(-1) = f(1) = 1\). Two of the three conditions hold.",
                r"Differentiable? For \(x \lt 0\), \(|x| = -x\) with slope \(-1\). For \(x \gt 0\), \(|x| = x\) with slope \(1\).",
                r"At \(x = 0\) the slopes from the two sides are different, so there is a corner and \(f'(0)\) does not exist.",
                r"One condition fails, so the theorem makes no promise. There is no contradiction."],
               r"\(f\) is not differentiable at \(x = 0\), so the theorem doesn't apply.", kind="When Rolle's theorem does not apply"),
        ]),
        pset("Newton's method", "newtons-method", [
            pq(r"Use two steps of Newton's method on \(f(x) = x^2 - 5\) from \(x_0 = 2\) to approximate \(\sqrt5\).",
               [r"\(f'(x) = 2x\), so \(x_{n+1} = x_n - \dfrac{x_n^2 - 5}{2x_n}\).",
                r"\(x_1 = 2 - \dfrac{4 - 5}{4} = 2.25\).",
                r"\(x_2 = 2.25 - \dfrac{5.0625 - 5}{4.5} = 2.25 - 0.0139\)."],
               r"\(x_2 \approx 2.2361\) (the true value is \(\sqrt5 \approx 2.23607\))", kind="Newton's method for a square root"),
            pq(r"Use two steps of Newton's method from \(x_0 = 1\) to approximate the root of \(x^3 + x - 1 = 0\).",
               [r"\(f(x) = x^3 + x - 1\) and \(f'(x) = 3x^2 + 1\).",
                r"\(x_1 = 1 - \dfrac{f(1)}{f'(1)} = 1 - \dfrac14 = 0.75\).",
                r"\(f(0.75) = 0.421875 + 0.75 - 1 = 0.171875\) and \(f'(0.75) = 2.6875\).",
                r"\(x_2 = 0.75 - \dfrac{0.171875}{2.6875} \approx 0.75 - 0.0640\)."],
               r"\(x_2 \approx 0.686\) (the root is about 0.6823)", kind="Newton's method for a cubic"),
        ]),
        pset("Optimization", "optimization", [
            pq(r"A farmer has 200 m of fence for a rectangular field along a straight river, and the river side needs no fence. What dimensions give the largest area?",
               [r"Let \(x\) be the two sides that meet the river. The side along the river is then \(200 - 2x\).",
                r"Area: \(A(x) = x(200 - 2x) = 200x - 2x^2\).",
                r"\(A'(x) = 200 - 4x = 0\) at \(x = 50\). \(A'' = -4 \lt 0\), so it is a maximum."],
               r"50 m by 100 m (the 100 m side along the river), for an area of 5000 m²", kind="Largest area with a fixed fence"),
            pq(r"An open-top box with a square base must hold 32 m³. What dimensions use the least material?",
               [r"Let the base be \(x\) by \(x\) and the height \(h\). Volume: \(x^2h = 32\), so \(h = \dfrac{32}{x^2}\).",
                r"Surface area (base plus four sides): \(S = x^2 + 4xh = x^2 + \dfrac{128}{x}\).",
                r"\(S'(x) = 2x - \dfrac{128}{x^2} = 0\) gives \(x^3 = 64\), so \(x = 4\).",
                r"\(S''(x) = 2 + \dfrac{256}{x^3} \gt 0\), so it is a minimum. Then \(h = \frac{32}{16} = 2\)."],
               r"A 4 m by 4 m base and a height of 2 m, using 48 m² of material", kind="Least material for a box"),
            pq(r"Find two positive numbers whose product is 100 and whose sum is as small as possible.",
               [r"Call them \(x\) and \(\dfrac{100}{x}\). Their sum is \(S(x) = x + \dfrac{100}{x}\).",
                r"\(S'(x) = 1 - \dfrac{100}{x^2} = 0\) gives \(x^2 = 100\), so \(x = 10\) (positive).",
                r"\(S''(x) = \dfrac{200}{x^3} \gt 0\), so it is a minimum."],
               r"10 and 10, with a sum of 20", kind="Numbers with the smallest sum"),
            pq(r"Find the point on the curve \(y = \sqrt{x}\) that is closest to \((4, 0)\).",
               [r"The distance from \((x, \sqrt{x})\) to \((4, 0)\) is \(\sqrt{(x - 4)^2 + x}\). Minimize its square instead, which has its minimum at the same place.",
                r"\(D(x) = (x - 4)^2 + x = x^2 - 7x + 16\).",
                r"\(D'(x) = 2x - 7 = 0\) at \(x = \frac72\), and \(D'' = 2 \gt 0\), so it is a minimum."],
               r"\(\left(\frac72, \sqrt{\frac72}\right) \approx (3.5, 1.87)\), at a distance of \(\frac{\sqrt{15}}{2} \approx 1.94\)", kind="Closest point on a curve"),
        ]),
    ],

    # ============ WEEK 8: ANTIDERIVATIVES, AREAS UNDER CURVES & THE FTC ============
    8: [
        pset("Antiderivatives and indefinite integrals", "antiderivatives", [
            pq(r"Find \(\displaystyle\int\left(4x^3 - 6x + 5\right)dx\).",
               [r"Integrate term by term, reversing the power rule: \(\displaystyle\int x^n\,dx = \frac{x^{n+1}}{n+1}\). Raise the power by one, then divide by the new power.",
                r"\(4x^3\) gives \(4\cdot\dfrac{x^4}{4} = x^4\).",
                r"\(-6x\) gives \(-6\cdot\dfrac{x^2}{2} = -3x^2\).",
                r"The constant \(5\) gives \(5x\).",
                r"Add \(C\), because any constant disappears when you differentiate. Check: the derivative of \(x^4 - 3x^2 + 5x + C\) is \(4x^3 - 6x + 5\)."],
               r"\(x^4 - 3x^2 + 5x + C\)", kind="Antiderivative of a polynomial"),
            pq(r"Find \(\displaystyle\int\left(\frac{3}{x^2} + 2\sqrt{x}\right)dx\).",
               [r"Rewrite with exponents so the reverse power rule can be used: \(3x^{-2} + 2x^{1/2}\).",
                r"\(3x^{-2}\): add 1 to the exponent to get \(-1\), then divide by \(-1\): \(3\cdot\dfrac{x^{-1}}{-1} = -3x^{-1} = -\dfrac3x\).",
                r"\(2x^{1/2}\): the new exponent is \(\frac32\). Dividing by \(\frac32\) is multiplying by \(\frac23\): \(2\cdot\frac23x^{3/2} = \frac43x^{3/2}\).",
                r"Add the constant: \(-\dfrac3x + \dfrac43x^{3/2} + C\).",
                r"Check by differentiating: \(-3x^{-1} \to 3x^{-2}\) and \(\frac43x^{3/2} \to 2x^{1/2}\)."],
               r"\(-\dfrac3x + \dfrac43 x^{3/2} + C\)", kind="Antiderivative with negative and fractional powers"),
            pq(r"Find \(\displaystyle\int\left(2e^x - \frac5x + \sec^2 x\right)dx\).",
               [r"None of these is a power of \(x\) that the reverse power rule handles. Each is a standard derivative read backward.",
                r"\(e^x\) is its own derivative, so \(\displaystyle\int2e^x\,dx = 2e^x\).",
                r"\(\displaystyle\int\frac1x\,dx = \ln|x|\). The reverse power rule fails here because it would divide by zero. So \(-\dfrac5x\) gives \(-5\ln|x|\).",
                r"\(\sec^2x\) is the derivative of \(\tan x\), so it gives \(\tan x\).",
                r"Add \(C\). The absolute value in \(\ln|x|\) is there because \(\dfrac1x\) is also defined for negative \(x\)."],
               r"\(2e^x - 5\ln|x| + \tan x + C\)", kind="Exponential, 1/x and trig antiderivatives"),
            pq(r"Find \(f\) if \(f'(x) = 2\cos x + 3\) and \(f(0) = 1\).",
               [r"Undo the derivative: \(\displaystyle\int2\cos x\,dx = 2\sin x\) and \(\displaystyle\int3\,dx = 3x\). So \(f(x) = 2\sin x + 3x + C\).",
                r"That is a whole family of curves, one for each \(C\). The condition \(f(0) = 1\) picks out one of them.",
                r"Put in \(x = 0\): \(f(0) = 2\sin0 + 3(0) + C = C\).",
                r"So \(C = 1\).",
                r"Check both requirements: \(f'(x) = 2\cos x + 3\), and \(f(0) = 0 + 0 + 1 = 1\)."],
               r"\(f(x) = 2\sin x + 3x + 1\)", kind="Initial value problem"),
            pq(r"A particle has acceleration \(a(t) = 6t - 4\), with \(v(0) = 3\) and \(s(0) = 2\). Find its position \(s(t)\).",
               [r"Acceleration is the derivative of velocity, so integrate: \(v(t) = \displaystyle\int(6t - 4)\,dt = 3t^2 - 4t + C\).",
                r"Use \(v(0) = 3\): \(C = 3\), so \(v(t) = 3t^2 - 4t + 3\). Find this constant before integrating again.",
                r"Velocity is the derivative of position, so integrate again: \(s(t) = t^3 - 2t^2 + 3t + D\).",
                r"Use \(s(0) = 2\): \(D = 2\).",
                r"Check: differentiating \(s(t) = t^3 - 2t^2 + 3t + 2\) twice gives \(6t - 4\)."],
               r"\(s(t) = t^3 - 2t^2 + 3t + 2\)", kind="Position from acceleration"),
        ]),
        pset("Areas under curves and Riemann sums", "area-under-curves", [
            pq(r"Estimate the area under \(f(x) = x^2 + 1\) on \([0, 2]\) with a right Riemann sum, \(n = 4\).",
               [r"\(\Delta x = \dfrac{2 - 0}{4} = 0.5\), and the right endpoints are \(0.5, 1, 1.5, 2\).",
                r"Heights: \(f(0.5) = 1.25\), \(f(1) = 2\), \(f(1.5) = 3.25\), \(f(2) = 5\).",
                r"\(R_4 = 0.5(1.25 + 2 + 3.25 + 5) = 0.5(11.5)\)."],
               r"\(R_4 = 5.75\) (an overestimate, since \(f\) is increasing)", kind="Right Riemann sum"),
            pq(r"Find the left Riemann sum \(L_3\) for \(f(x) = \dfrac1x\) on \([1, 4]\). Is it an overestimate or an underestimate?",
               [r"\(\Delta x = 1\), and the left endpoints are \(1, 2, 3\).",
                r"\(L_3 = 1\left(1 + \frac12 + \frac13\right) = \frac{11}{6}\).",
                r"\(f\) is decreasing, so each rectangle's left edge is its tallest point and the rectangle sticks out above the curve."],
               r"\(L_3 = \frac{11}{6} \approx 1.83\), an overestimate", kind="Left Riemann sum"),
            pq(r"Find the midpoint sum \(M_2\) for \(f(x) = 4 - x^2\) on \([0, 2]\).",
               [r"\(\Delta x = 1\), and the midpoints are \(0.5\) and \(1.5\).",
                r"\(f(0.5) = 3.75\) and \(f(1.5) = 1.75\).",
                r"\(M_2 = 1(3.75 + 1.75)\)."],
               r"\(M_2 = 5.5\)", kind="Midpoint sum"),
            pq(r"Use geometry to find \(\displaystyle\int_{-3}^{3}\sqrt{9 - x^2}\,dx\).",
               [r"Square both sides of \(y = \sqrt{9 - x^2}\): \(y^2 = 9 - x^2\), which is \(x^2 + y^2 = 9\). That is a circle of radius 3 centred at the origin.",
                r"A square root is never negative, so the graph is only the top half of the circle.",
                r"From \(x = -3\) to \(x = 3\) is the whole width of that semicircle.",
                r"The integral is the area between the curve and the \(x\)-axis, which is half the area of the disk: \(\frac12\pi r^2 = \frac12\pi(3)^2\).",
                r"\(\dfrac{9\pi}{2} \approx 14.1\). No antiderivative was needed."],
               r"\(\dfrac{9\pi}{2}\)", kind="Integral by geometry"),
            pq(r"Given \(\displaystyle\int_0^5 f(x)\,dx = 7\) and \(\displaystyle\int_0^2 f(x)\,dx = 3\), find \(\displaystyle\int_2^5 f(x)\,dx\), \(\displaystyle\int_5^2 f(x)\,dx\) and \(\displaystyle\int_0^5\big(2f(x) + 1\big)dx\).",
               [r"Split the interval: \(\int_0^2 f + \int_2^5 f = \int_0^5 f\), so \(\int_2^5 f = 7 - 3 = 4\).",
                r"Swapping the limits changes the sign: \(\int_5^2 f = -4\).",
                r"Linearity: \(2\int_0^5 f + \int_0^5 1\,dx = 2(7) + 5\)."],
               r"\(4\), \(-4\) and \(19\)", kind="Properties of definite integrals"),
        ]),
        pset("The Fundamental Theorem of Calculus", "ftc", [
            pq(r"Evaluate \(\displaystyle\int_1^3\left(3x^2 - 2x\right)dx\).",
               [r"Fundamental Theorem, part 2: find an antiderivative \(F\), then compute \(F(3) - F(1)\).",
                r"\(F(x) = x^3 - x^2\). No \(+C\) is needed, because it would cancel in the subtraction.",
                r"\(F(3) = 27 - 9 = 18\).",
                r"\(F(1) = 1 - 1 = 0\).",
                r"\(F(3) - F(1) = 18 - 0 = 18\). Always upper limit minus lower limit."],
               r"\(18\)", kind="Definite integral of a polynomial"),
            pq(r"Evaluate \(\displaystyle\int_1^4\left(\frac{1}{\sqrt{x}} + x\right)dx\).",
               [r"Rewrite \(\dfrac{1}{\sqrt{x}} = x^{-1/2}\).",
                r"Antiderivative: \(x^{-1/2}\) gives \(\dfrac{x^{1/2}}{1/2} = 2\sqrt{x}\), and \(x\) gives \(\dfrac{x^2}{2}\). So \(F(x) = 2\sqrt{x} + \dfrac{x^2}{2}\).",
                r"\(F(4) = 2(2) + \dfrac{16}{2} = 4 + 8 = 12\).",
                r"\(F(1) = 2 + \dfrac12 = \dfrac52\).",
                r"\(F(4) - F(1) = 12 - \dfrac52 = \dfrac{19}{2}\)."],
               r"\(\dfrac{19}{2}\)", kind="Definite integral with a root"),
            pq(r"Find \(\dfrac{d}{dx}\displaystyle\int_2^x\sqrt{t^3 + 1}\,dt\).",
               [r"Fundamental Theorem, part 1: \(\dfrac{d}{dx}\displaystyle\int_a^xf(t)\,dt = f(x)\).",
                r"Check that it fits: the lower limit is a constant (2) and the upper limit is exactly \(x\). It does.",
                r"So the answer is the integrand with \(t\) replaced by \(x\): \(\sqrt{x^3+1}\).",
                r"The lower limit 2 does not appear in the answer. Changing it only changes the integral by a constant, which disappears when you differentiate.",
                r"Do not try to integrate first. \(\sqrt{t^3+1}\) has no simple antiderivative, and none is needed."],
               r"\(\sqrt{x^3 + 1}\)", kind="FTC part 1"),
            pq(r"Find \(\dfrac{d}{dx}\displaystyle\int_1^{x^2}\ln t\,dt\) (for \(x \gt 0\)).",
               [r"The upper limit is \(x^2\), not \(x\), so FTC part 1 needs the chain rule.",
                r"Rule: plug the upper limit into the integrand, then multiply by the derivative of the upper limit.",
                r"Plug in: \(\ln(x^2)\). Derivative of the upper limit: \(2x\). So the answer is \(\ln(x^2)\cdot2x\).",
                r"Simplify with the log law \(\ln(x^2) = 2\ln x\) (valid since \(x \gt 0\)).",
                r"\(2\ln x\cdot2x = 4x\ln x\)."],
               r"\(4x\ln x\)", kind="FTC part 1 with the chain rule"),
            pq(r"A particle moves with velocity \(v(t) = 3t^2 - 12\) m/s for \(0 \le t \le 3\). Find its displacement and the total distance it travels.",
               [r"Displacement: \(\displaystyle\int_0^3 v\,dt = \big[t^3 - 12t\big]_0^3 = 27 - 36 = -9\).",
                r"For distance, find where it turns around: \(v(t) = 0\) at \(t = 2\). It moves backward on \([0, 2]\) and forward on \([2, 3]\).",
                r"\(\displaystyle\int_0^2 v\,dt = 8 - 24 = -16\) and \(\displaystyle\int_2^3 v\,dt = -9 - (-16) = 7\).",
                r"Distance adds the sizes: \(16 + 7\)."],
               r"Displacement \(-9\) m, total distance 23 m", kind="Displacement versus distance"),
        ]),
    ],

    # ============ WEEK 9: SUBSTITUTION, AREAS BETWEEN CURVES & AVERAGE VALUE ============
    9: [
        pset("Integration by substitution", "u-sub", [
            pq(r"Find \(\displaystyle\int 2x(x^2 + 3)^5\,dx\).",
               [r"Let \(u = x^2 + 3\), so \(du = 2x\,dx\). The \(2x\,dx\) is already there.",
                r"The integral becomes \(\displaystyle\int u^5\,du = \dfrac{u^6}{6} + C\).",
                r"Put \(x\) back."],
               r"\(\dfrac{(x^2 + 3)^6}{6} + C\)", kind="Basic substitution"),
            pq(r"Find \(\displaystyle\int x^2\sqrt{x^3 + 1}\,dx\).",
               [r"Look for an inside function whose derivative is also there. Inside the root is \(x^3 + 1\), and its derivative \(3x^2\) is almost the \(x^2\) outside. Let \(u = x^3 + 1\).",
                r"\(du = 3x^2\,dx\), so \(x^2\,dx = \frac13\,du\).",
                r"Rewrite everything in \(u\): \(\displaystyle\frac13\int u^{1/2}\,du\).",
                r"Integrate: \(\dfrac13\cdot\dfrac23u^{3/2} + C = \dfrac29u^{3/2} + C\).",
                r"Substitute back: \(\dfrac29(x^3+1)^{3/2} + C\)."],
               r"\(\frac29(x^3 + 1)^{3/2} + C\)", kind="Substitution with a constant to fix"),
            pq(r"Find \(\displaystyle\int\cos(5x)\,dx\).",
               [r"The inside is \(5x\). Let \(u = 5x\).",
                r"\(du = 5\,dx\), so \(dx = \frac15\,du\).",
                r"The integral becomes \(\displaystyle\frac15\int\cos u\,du = \frac15\sin u + C\).",
                r"Substitute back: \(\dfrac15\sin(5x) + C\).",
                r"Check: the derivative is \(\dfrac15\cos(5x)\cdot5 = \cos(5x)\). When the inside is \(ax + b\), the result is always divided by \(a\)."],
               r"\(\frac15\sin(5x) + C\)", kind="Substitution with a linear inside"),
            pq(r"Find \(\displaystyle\int xe^{x^2}\,dx\).",
               [r"The exponent \(x^2\) is the inside function, and its derivative \(2x\) is almost the \(x\) in front. Let \(u = x^2\).",
                r"\(du = 2x\,dx\), so \(x\,dx = \frac12\,du\).",
                r"The integral becomes \(\displaystyle\frac12\int e^u\,du = \frac12e^u + C\).",
                r"Substitute back: \(\dfrac12e^{x^2} + C\).",
                r"The \(x\) in front is what makes this work. \(\displaystyle\int e^{x^2}\,dx\) on its own cannot be done this way."],
               r"\(\frac12 e^{x^2} + C\)", kind="Substitution with an exponential"),
            pq(r"Find \(\displaystyle\int\frac{\ln x}{x}\,dx\).",
               [r"Write the integrand as \(\ln x\cdot\dfrac1x\). The factor \(\dfrac1x\) is the derivative of \(\ln x\).",
                r"Let \(u = \ln x\), so \(du = \dfrac1x\,dx\).",
                r"The integral becomes \(\displaystyle\int u\,du\).",
                r"Integrate: \(\dfrac{u^2}{2} + C\).",
                r"Substitute back: \(\dfrac{(\ln x)^2}{2} + C\). Note that \((\ln x)^2\) is not the same as \(\ln(x^2)\)."],
               r"\(\dfrac{(\ln x)^2}{2} + C\)", kind="Substitution with a logarithm"),
            pq(r"Evaluate \(\displaystyle\int_0^2\frac{x}{x^2 + 1}\,dx\).",
               [r"Let \(u = x^2 + 1\), so \(x\,dx = \frac12\,du\).",
                r"Change the limits too: \(x = 0\) gives \(u = 1\), and \(x = 2\) gives \(u = 5\).",
                r"\(\frac12\displaystyle\int_1^5\frac{du}{u} = \frac12\big[\ln u\big]_1^5 = \frac12(\ln 5 - \ln 1)\)."],
               r"\(\frac12\ln 5 \approx 0.80\)", kind="Definite integral giving a log"),
            pq(r"Evaluate \(\displaystyle\int_0^1(2x + 1)^3\,dx\).",
               [r"Let \(u = 2x + 1\), so \(dx = \frac12\,du\).",
                r"Change the limits: \(x = 0\) gives \(u = 1\), and \(x = 1\) gives \(u = 3\).",
                r"\(\frac12\displaystyle\int_1^3 u^3\,du = \frac12\left[\dfrac{u^4}{4}\right]_1^3 = \frac18(81 - 1)\)."],
               r"\(10\)", kind="Definite integral with new limits"),
        ]),
        pset("Area between curves", "area-between", [
            pq(r"Find the area between \(y = x^2\) and \(y = x + 2\).",
               [r"Find where they cross: \(x^2 = x + 2\) gives \((x - 2)(x + 1) = 0\), so \(x = -1\) and \(x = 2\).",
                r"Between them the line is on top (at \(x = 0\): \(2 \gt 0\)).",
                r"\(A = \displaystyle\int_{-1}^{2}\left(x + 2 - x^2\right)dx = \left[\dfrac{x^2}{2} + 2x - \dfrac{x^3}{3}\right]_{-1}^{2}\).",
                r"\(= \left(2 + 4 - \frac83\right) - \left(\frac12 - 2 + \frac13\right) = \frac{10}{3} + \frac76\)."],
               r"\(\dfrac92\)", kind="Area between a line and a parabola"),
            pq(r"Find the total area between \(y = x^3\) and \(y = x\).",
               [r"They cross where \(x^3 = x\): \(x = -1, 0, 1\).",
                r"On \([0, 1]\) the line is on top. On \([-1, 0]\) the cubic is on top. By symmetry the two regions have the same area.",
                r"\(A = 2\displaystyle\int_0^1\left(x - x^3\right)dx = 2\left[\dfrac{x^2}{2} - \dfrac{x^4}{4}\right]_0^1 = 2\left(\frac12 - \frac14\right)\)."],
               r"\(\dfrac12\)", kind="Total area between crossing curves"),
            pq(r"Find the area between \(y = e^x\) and \(y = x\) on \([0, 1]\).",
               [r"Decide which curve is on top. At \(x = 0\): \(e^0 = 1\) against \(0\). At \(x = 1\): \(e \approx 2.72\) against \(1\). \(e^x\) is above \(x\) on the whole interval.",
                r"Area \(= \displaystyle\int_0^1(\text{top} - \text{bottom})\,dx = \int_0^1\left(e^x - x\right)dx\).",
                r"Antiderivative: \(e^x - \dfrac{x^2}{2}\).",
                r"At 1: \(e - \dfrac12\). At 0: \(e^0 - 0 = 1\). Remember that \(e^0\) is 1, not 0.",
                r"Subtract: \(e - \dfrac12 - 1 = e - \dfrac32 \approx 1.22\)."],
               r"\(e - \frac32 \approx 1.22\)", kind="Area on a given interval"),
            pq(r"Find the area between \(x = y^2\) and the line \(x = 4\) by integrating in \(y\).",
               [r"They cross where \(y^2 = 4\): \(y = -2\) and \(y = 2\).",
                r"The line \(x = 4\) is on the right, and the parabola \(x = y^2\) is on the left.",
                r"\(A = \displaystyle\int_{-2}^{2}\left(4 - y^2\right)dy = \left[4y - \dfrac{y^3}{3}\right]_{-2}^{2} = \left(8 - \frac83\right) - \left(-8 + \frac83\right)\)."],
               r"\(\dfrac{32}{3}\)", kind="Integrating in y against a vertical line"),
        ]),
        pset("Average value of a function", "average-value", [
            pq(r"Find the average value of \(f(x) = 3x^2 + 1\) on \([0, 2]\).",
               [r"Average value: \(f_{\text{avg}} = \dfrac{1}{b-a}\displaystyle\int_a^bf(x)\,dx\). The integral adds up the heights and dividing by the width averages them.",
                r"Here: \(\dfrac{1}{2-0}\displaystyle\int_0^2\left(3x^2+1\right)dx\).",
                r"Antiderivative: \(x^3 + x\). At 2: \(8 + 2 = 10\). At 0: \(0\).",
                r"\(f_{\text{avg}} = \dfrac12(10) = 5\).",
                r"Sense check: \(f\) runs from 1 to 13 on this interval, and 5 is between them."],
               r"\(5\)", kind="Average value of a polynomial"),
            pq(r"Find the average value of \(f(x) = \sqrt{x}\) on \([0, 4]\), and the \(c\) where \(f(c)\) equals it.",
               [r"\(f_{\text{avg}} = \dfrac{1}{4-0}\displaystyle\int_0^4x^{1/2}\,dx\).",
                r"Antiderivative: \(\dfrac23x^{3/2}\). At 4: \(\dfrac23(8) = \dfrac{16}{3}\). At 0: \(0\).",
                r"\(f_{\text{avg}} = \dfrac14\cdot\dfrac{16}{3} = \dfrac43\).",
                r"Now find where the function equals its average: \(\sqrt{c} = \dfrac43\), so \(c = \dfrac{16}{9} \approx 1.78\).",
                r"\(c\) is inside \([0, 4]\), as the Mean Value Theorem for integrals promises for a continuous function."],
               r"The average value is \(\frac43\), reached at \(c = \frac{16}{9}\).", kind="Average value and where it is reached"),
            pq(r"Find the average value of \(f(x) = \cos x\) on \(\left[0, \frac\pi2\right]\).",
               [r"\(f_{\text{avg}} = \dfrac{1}{\frac\pi2 - 0}\displaystyle\int_0^{\pi/2}\cos x\,dx\).",
                r"Dividing by \(\dfrac\pi2\) is multiplying by \(\dfrac2\pi\).",
                r"\(\displaystyle\int_0^{\pi/2}\cos x\,dx = \big[\sin x\big]_0^{\pi/2} = 1 - 0 = 1\).",
                r"\(f_{\text{avg}} = \dfrac2\pi \approx 0.64\).",
                r"Sense check: cosine falls from 1 to 0 on this interval. The average is above 0.5 because the curve bulges upward."],
               r"\(\dfrac2\pi \approx 0.64\)", kind="Average value of a trig function"),
            pq(r"A car's velocity is \(v(t) = 3t^2 + 2t\) m/s for \(0 \le t \le 4\) s. Find its average velocity.",
               [r"Average velocity is the average value of \(v\): \(\dfrac{1}{4-0}\displaystyle\int_0^4\left(3t^2+2t\right)dt\).",
                r"Antiderivative: \(t^3 + t^2\).",
                r"At 4: \(64 + 16 = 80\). At 0: \(0\). So the integral is 80, which is the displacement in metres.",
                r"Divide by the time: \(\dfrac{80}{4} = 20\) m/s.",
                r"This is the familiar distance over time, with the distance found by integrating."],
               r"\(20\) m/s", kind="Average velocity"),
        ]),
    ],

    # ======================= WEEK 10: DIFFERENTIAL EQUATIONS =======================
    10: [
        pset("Introduction to differential equations", "de-intro", [
            pq(r"State the order of each equation: \(y'' - 3xy' + y = e^x\), and \((y')^3 + y = x\).",
               [r"The order of a differential equation is the highest derivative that appears in it.",
                r"First equation: it contains \(y''\) and \(y'\). The highest is \(y''\), so it is second order.",
                r"Second equation: the only derivative is \(y'\). It is cubed, but a cubed first derivative is still a first derivative.",
                r"So the second equation is first order. Powers do not affect the order.",
                r"The power does matter for a different question: \((y')^3\) makes the second equation nonlinear."],
               r"Second order, and first order", kind="Order of a differential equation"),
            pq(r"Check that \(y = e^{2x} + 3\) is a solution of \(y' - 2y = -6\).",
               [r"To check a solution, substitute it into the equation and see whether the two sides agree for every \(x\).",
                r"Differentiate: \(y' = 2e^{2x}\). The constant 3 disappears.",
                r"Left side: \(y' - 2y = 2e^{2x} - 2\left(e^{2x} + 3\right)\).",
                r"Expand: \(2e^{2x} - 2e^{2x} - 6 = -6\).",
                r"That equals the right side for every \(x\), so \(y = e^{2x} + 3\) is a solution."],
               r"The left side equals \(-6\), so yes, it is a solution.", kind="Checking a solution"),
            pq(r"Check that \(y = x^2 + \dfrac1x\) is a solution of \(xy' + y = 3x^2\).",
               [r"Differentiate: \(y' = 2x - \dfrac{1}{x^2}\).",
                r"\(xy' = 2x^2 - \dfrac1x\).",
                r"Add \(y\): \(2x^2 - \dfrac1x + x^2 + \dfrac1x\)."],
               r"The left side equals \(3x^2\), so yes, it is a solution.", kind="Checking a solution with a product"),
            pq(r"Solve \(y' = 6x^2 - 4\) with \(y(1) = 3\).",
               [r"The right side depends only on \(x\), so integrate both sides directly.",
                r"\(y = \displaystyle\int\left(6x^2 - 4\right)dx = 2x^3 - 4x + C\). This is the general solution.",
                r"Use the initial condition \(y(1) = 3\): \(2(1) - 4(1) + C = 3\).",
                r"\(-2 + C = 3\), so \(C = 5\).",
                r"Check: \(y = 2x^3 - 4x + 5\) gives \(y(1) = 2 - 4 + 5 = 3\)."],
               r"\(y = 2x^3 - 4x + 5\)", kind="Solving by integrating once"),
            pq(r"Solve \(y'' = 12x\) with \(y(0) = 1\) and \(y'(0) = 2\).",
               [r"Integrate once: \(y' = 6x^2 + C_1\).",
                r"Use \(y'(0) = 2\) straight away: \(C_1 = 2\), so \(y' = 6x^2 + 2\).",
                r"Integrate again: \(y = 2x^3 + 2x + C_2\).",
                r"Use \(y(0) = 1\): \(C_2 = 1\).",
                r"A second-order equation needs two integrations, so it has two constants and needs two conditions."],
               r"\(y = 2x^3 + 2x + 1\)", kind="Solving by integrating twice"),
        ]),
        pset("Separable differential equations", "separable-de", [
            pq(r"Solve \(\dfrac{dy}{dx} = \dfrac{x}{y}\) with \(y(0) = 3\).",
               [r"Separate the variables: \(y\,dy = x\,dx\).",
                r"Integrate both sides: \(\dfrac{y^2}{2} = \dfrac{x^2}{2} + C\), so \(y^2 = x^2 + K\).",
                r"Use \(y(0) = 3\): \(K = 9\). Take the positive root because \(y(0)\) is positive."],
               r"\(y = \sqrt{x^2 + 9}\)", kind="Separable equation"),
            pq(r"Solve \(\dfrac{dy}{dx} = 2xy^2\) with \(y(0) = 1\).",
               [r"Separate: \(\dfrac{dy}{y^2} = 2x\,dx\).",
                r"Integrate: \(-\dfrac1y = x^2 + C\).",
                r"Use \(y(0) = 1\): \(-1 = C\). So \(-\dfrac1y = x^2 - 1\)."],
               r"\(y = \dfrac{1}{1 - x^2}\)", kind="Separable equation with a power of y"),
            pq(r"Solve \(\dfrac{dy}{dx} = e^{x - y}\) with \(y(0) = \ln 2\).",
               [r"Split the exponential: \(e^{x-y} = e^x e^{-y}\). Separate: \(e^y\,dy = e^x\,dx\).",
                r"Integrate: \(e^y = e^x + C\).",
                r"Use \(y(0) = \ln 2\): \(2 = 1 + C\), so \(C = 1\). Then take \(\ln\) of both sides."],
               r"\(y = \ln(e^x + 1)\)", kind="Separable equation with exponentials"),
            pq(r"A culture of 500 bacteria grows to 2000 in 6 hours. Assuming \(P = P_0e^{kt}\), find \(k\) and the population after 9 hours.",
               [r"Start with 500, so \(P_0 = 500\) and \(P = 500e^{kt}\).",
                r"Use the second measurement: \(500e^{6k} = 2000\), so \(e^{6k} = 4\).",
                r"Take \(\ln\): \(6k = \ln4\), so \(k = \dfrac{\ln4}{6} \approx 0.231\) per hour.",
                r"\(P(9) = 500e^{9k}\). Since \(9k = 1.5\times6k\), \(e^{9k} = \left(e^{6k}\right)^{1.5} = 4^{1.5} = 8\). So \(P(9) = 4000\).",
                r"Sense check: multiplying by 4 every 6 hours is doubling every 3 hours, so 2000 at 6 hours becomes 4000 at 9 hours."],
               r"\(k = \dfrac{\ln 4}{6} \approx 0.231\), and \(P(9) = 4000\) bacteria", kind="Exponential growth"),
            pq(r"A substance has a half-life of 30 years. How long until only 10% of it is left?",
               [r"Decay model: \(y = y_0e^{kt}\), with \(k\) negative.",
                r"Half-life 30 years: \(e^{30k} = \frac12\). Take \(\ln\): \(30k = -\ln2\), so \(k = -\dfrac{\ln2}{30} \approx -0.0231\) per year.",
                r"10% left means \(e^{kt} = 0.1\), so \(kt = \ln0.1 = -\ln10\).",
                r"\(t = \dfrac{-\ln10}{k} = \dfrac{30\ln10}{\ln2} \approx 30(3.32) \approx 99.7\) years.",
                r"Sense check: 3 half-lives (90 years) leave 12.5% and 4 half-lives (120 years) leave 6.25%, so 10% should come between them."],
               r"About 99.7 years", kind="Half-life"),
            pq(r"Coffee at 90°C is left in a 20°C room and is at 70°C after 5 minutes. Use Newton's law of cooling to find its temperature after 10 minutes.",
               [r"\(T = T_s + (T_0 - T_s)e^{kt} = 20 + 70e^{kt}\).",
                r"At \(t = 5\): \(70 = 20 + 70e^{5k}\), so \(e^{5k} = \frac57\).",
                r"At \(t = 10\): \(e^{10k} = \left(e^{5k}\right)^2 = \frac{25}{49}\), so \(T = 20 + 70 \cdot \frac{25}{49}\)."],
               r"About 55.7°C", kind="Newton's law of cooling"),
        ]),
        pset("Linear second-order differential equations", "second-order-linear", [
            pq(r"Solve \(y'' - y' - 6y = 0\).",
               [r"Trying \(y = e^{rx}\) turns the equation into the characteristic equation: replace \(y''\) by \(r^2\), \(y'\) by \(r\) and \(y\) by 1. That gives \(r^2 - r - 6 = 0\).",
                r"Factor: \((r-3)(r+2) = 0\).",
                r"The roots are \(r = 3\) and \(r = -2\): two different real roots.",
                r"Each root gives a solution \(e^{rx}\), and the general solution is any combination of them: \(y = C_1e^{3x} + C_2e^{-2x}\).",
                r"Check one of them: for \(y = e^{3x}\), \(y'' - y' - 6y = 9e^{3x} - 3e^{3x} - 6e^{3x} = 0\)."],
               r"\(y = C_1e^{3x} + C_2e^{-2x}\)", kind="Distinct real roots"),
            pq(r"Solve \(y'' - 4y' + 4y = 0\) with \(y(0) = 1\) and \(y'(0) = 5\).",
               [r"Characteristic equation: \(r^2 - 4r + 4 = (r - 2)^2 = 0\), a repeated root \(r = 2\).",
                r"General solution: \(y = (C_1 + C_2x)e^{2x}\). \(y(0) = 1\) gives \(C_1 = 1\).",
                r"\(y' = C_2e^{2x} + 2(C_1 + C_2x)e^{2x}\), so \(y'(0) = C_2 + 2 = 5\) and \(C_2 = 3\)."],
               r"\(y = (1 + 3x)e^{2x}\)", kind="Repeated root with initial conditions"),
            pq(r"Solve \(y'' + 4y' + 13y = 0\).",
               [r"Characteristic equation: \(r^2 + 4r + 13 = 0\).",
                r"Quadratic formula: \(r = \dfrac{-4 \pm \sqrt{16 - 52}}{2} = \dfrac{-4 \pm 6i}{2} = -2 \pm 3i\).",
                r"Complex roots \(\alpha \pm \beta i\) with \(\alpha = -2\) and \(\beta = 3\)."],
               r"\(y = e^{-2x}\big(C_1\cos 3x + C_2\sin 3x\big)\)", kind="Complex roots"),
            pq(r"Solve \(y'' + 9y = 0\) with \(y(0) = 2\) and \(y'(0) = 3\).",
               [r"Characteristic equation: \(r^2 + 9 = 0\), so \(r = \pm 3i\).",
                r"General solution: \(y = C_1\cos 3x + C_2\sin 3x\). \(y(0) = 2\) gives \(C_1 = 2\).",
                r"\(y' = -3C_1\sin 3x + 3C_2\cos 3x\), so \(y'(0) = 3C_2 = 3\) and \(C_2 = 1\)."],
               r"\(y = 2\cos 3x + \sin 3x\)", kind="Pure imaginary roots with initial conditions"),
        ]),
    ],

    # ====== WEEK 11: DIRECTION FIELDS, EULER'S METHOD & MULTIVARIABLE FUNCTIONS ======
    11: [
        pset("Direction fields", "direction-fields", [
            pq(r"For \(y' = x + y\), find the slope of the direction field at \((0, 0)\), \((1, 1)\), \((-1, 2)\) and \((2, -2)\).",
               [r"A direction field draws a short segment at each point, with the slope the equation gives there. To find it, put the point into the right side.",
                r"At \((0, 0)\): \(0 + 0 = 0\). The segment is flat.",
                r"At \((1, 1)\): \(1 + 1 = 2\). The segment rises steeply.",
                r"At \((-1, 2)\): \(-1 + 2 = 1\). At \((2, -2)\): \(2 + (-2) = 0\), flat again.",
                r"The two flat ones are both on the line \(y = -x\), which is where \(x + y = 0\)."],
               r"\(0\), \(2\), \(1\) and \(0\)", kind="Slopes in a direction field"),
            pq(r"For \(y' = x + y\), find the isoclines for slope 0 and slope 1.",
               [r"An isocline is a curve along which every segment has the same slope \(c\).",
                r"Set the right side equal to \(c\): \(x + y = c\).",
                r"Slope 0: \(x + y = 0\), which is the line \(y = -x\).",
                r"Slope 1: \(x + y = 1\), which is the line \(y = 1 - x\).",
                r"Every isocline here is a line with slope \(-1\). Drawing a few of them and marking the slope on each is a quick way to sketch the field."],
               r"The lines \(y = -x\) and \(y = 1 - x\)", kind="Isoclines"),
            pq(r"In the direction field of \(y' = x^2 - y\), where are the segments horizontal? Is the slope at \((1, 3)\) positive or negative?",
               [r"A horizontal segment has slope 0, so set the right side to zero: \(x^2 - y = 0\).",
                r"That is \(y = x^2\). Every segment on this parabola is flat.",
                r"At \((1, 3)\): \(1^2 - 3 = -2\). The slope is negative, so a solution through that point is going down.",
                r"\((1, 3)\) is above the parabola, which has height 1 at \(x = 1\).",
                r"In general \(y \gt x^2\) makes \(x^2 - y\) negative: slopes are negative above the parabola and positive below it."],
               r"Horizontal along the parabola \(y = x^2\). The slope at \((1, 3)\) is \(-2\), which is negative.", kind="Where the field is horizontal"),
            pq(r"Find the equilibrium solutions of \(y' = y(3 - y)\) and say whether each is stable. What happens to the solution with \(y(0) = 1\) as \(x \to \infty\)?",
               [r"Equilibria are where \(y' = 0\): \(y = 0\) and \(y = 3\).",
                r"Sign of \(y'\): negative for \(y \lt 0\), positive for \(0 \lt y \lt 3\), negative for \(y \gt 3\).",
                r"Near \(y = 3\), solutions below rise and solutions above fall, so they move toward it. Near \(y = 0\) they move away.",
                r"A solution starting at \(y = 1\) is between 0 and 3, so it rises toward 3."],
               r"\(y = 0\) is unstable and \(y = 3\) is stable. The solution with \(y(0) = 1\) approaches 3.", kind="Equilibrium solutions and stability"),
            pq(r"Find the equilibrium solutions of \(y' = (y - 1)(y + 2)\) and classify their stability.",
               [r"Equilibria: \(y = 1\) and \(y = -2\).",
                r"Sign of \(y'\): positive for \(y \gt 1\), negative for \(-2 \lt y \lt 1\), positive for \(y \lt -2\).",
                r"Around \(y = -2\): solutions below rise and solutions above fall, so they approach it. Around \(y = 1\): solutions above rise and solutions below fall, so they leave."],
               r"\(y = -2\) is stable and \(y = 1\) is unstable", kind="Classifying equilibria"),
        ]),
        pset("Euler's method", "eulers-method", [
            pq(r"Use Euler's method with \(h = 0.5\) to estimate \(y(1)\) for \(y' = x - y\), \(y(0) = 1\).",
               [r"Going from \(x = 0\) to \(x = 1\) with \(h = 0.5\) takes two steps. Each step is \(y_{\text{new}} = y_{\text{old}} + h\cdot\text{slope}\).",
                r"Step 1, at \((0, 1)\): slope \(= 0 - 1 = -1\). \(y_1 = 1 + 0.5(-1) = 0.5\), and \(x\) moves to \(0.5\).",
                r"Step 2, at \((0.5, 0.5)\): slope \(= 0.5 - 0.5 = 0\). \(y_2 = 0.5 + 0.5(0) = 0.5\), and \(x\) moves to \(1\).",
                r"So \(y(1) \approx 0.5\).",
                r"The exact solution is \(y = x - 1 + 2e^{-x}\), which gives \(y(1) \approx 0.736\). Two big steps are only a rough estimate."],
               r"\(y(1) \approx 0.5\)", kind="Euler's method with two steps"),
            pq(r"Use Euler's method with \(h = 0.1\) to estimate \(y(1.2)\) for \(y' = xy\), \(y(1) = 2\).",
               [r"Going from \(x = 1\) to \(x = 1.2\) with \(h = 0.1\) takes two steps.",
                r"Step 1, at \((1, 2)\): slope \(= 1\cdot2 = 2\). \(y_1 = 2 + 0.1(2) = 2.2\), and \(x\) moves to \(1.1\).",
                r"Step 2, at \((1.1, 2.2)\): slope \(= 1.1\cdot2.2 = 2.42\). \(y_2 = 2.2 + 0.1(2.42) = 2.442\), and \(x\) moves to \(1.2\).",
                r"So \(y(1.2) \approx 2.442\).",
                r"Recalculate the slope at every new point. Reusing the first slope is the usual mistake. (The exact value is about 2.492.)"],
               r"\(y(1.2) \approx 2.442\)", kind="Euler's method with a small step"),
            pq(r"Use Euler's method with \(h = 0.25\) to estimate \(y(1)\) for \(y' = y\), \(y(0) = 1\). The exact answer is \(e\). Is the estimate too high or too low, and why?",
               [r"Each step multiplies \(y\) by \(1 + h\): \(y_{n+1} = y_n + 0.25y_n = 1.25y_n\).",
                r"Four steps reach \(x = 1\): \(y_4 = 1.25^4 \approx 2.441\).",
                r"The true solution \(y = e^x\) curves upward (concave up), so each tangent-line step falls below it."],
               r"\(y(1) \approx 2.441\), lower than \(e \approx 2.718\). A smaller step size would get closer.", kind="Euler's method against the exact answer"),
        ]),
        pset("Functions of several variables", "multivariable-intro", [
            pq(r"For \(f(x, y) = x^2y - 3y\), find \(f(2, -1)\) and \(f(0, 5)\).",
               [r"The function takes two inputs. The first number is \(x\) and the second is \(y\).",
                r"\(f(2, -1)\): put \(x = 2\) and \(y = -1\) into \(x^2y - 3y\): \((2)^2(-1) - 3(-1)\).",
                r"\(= -4 + 3 = -1\).",
                r"\(f(0, 5)\): \((0)^2(5) - 3(5) = 0 - 15 = -15\).",
                r"The order matters: \(f(-1, 2) = (1)(2) - 6 = -4\), which is different from \(f(2, -1)\)."],
               r"\(-1\) and \(-15\)", kind="Evaluating a function of two variables"),
            pq(r"Find the domain and range of \(f(x, y) = \sqrt{16 - x^2 - y^2}\).",
               [r"Domain: the inside of the square root must not be negative: \(16 - x^2 - y^2 \ge 0\).",
                r"Rearrange: \(x^2 + y^2 \le 16\). That is the disk of radius 4 centred at the origin, with the edge included.",
                r"Range: find the smallest and largest outputs. On the edge of the disk the inside is 0, so \(f = 0\).",
                r"At the origin the inside is 16, its largest value, so \(f = 4\).",
                r"Every value in between happens somewhere, so the range is \([0, 4]\). The graph is the top half of a sphere of radius 4."],
               r"Domain: the disk \(x^2 + y^2 \le 16\) (radius 4, edge included). Range: \([0, 4]\).", kind="Domain and range"),
            pq(r"Find and describe the domain of \(f(x, y) = \ln(y - x^2)\).",
               [r"A logarithm needs a strictly positive input: \(y - x^2 \gt 0\).",
                r"Rearrange: \(y \gt x^2\).",
                r"The boundary is the parabola \(y = x^2\). To see which side is meant, test a point: \((0, 1)\) gives \(1 \gt 0\), which is true.",
                r"So the domain is the region above the parabola (inside its bowl).",
                r"The parabola itself is not included, because \(\ln0\) is undefined. On a sketch it would be drawn dashed."],
               r"All points with \(y \gt x^2\), the region strictly above the parabola", kind="Domain with a logarithm"),
            pq(r"Describe the level curves of \(f(x, y) = 4x^2 + y^2\) for \(k = 4\) and \(k = 16\).",
               [r"Set \(f(x, y) = k\). For \(k = 4\): \(4x^2 + y^2 = 4\), or \(x^2 + \dfrac{y^2}{4} = 1\).",
                r"For \(k = 16\): \(4x^2 + y^2 = 16\), or \(\dfrac{x^2}{4} + \dfrac{y^2}{16} = 1\).",
                r"Both are ellipses centred at the origin, twice as tall as they are wide."],
               r"Ellipses: one through \((\pm 1, 0)\) and \((0, \pm 2)\), the other through \((\pm 2, 0)\) and \((0, \pm 4)\)", kind="Level curves"),
            pq(r"Find \(\displaystyle\lim_{(x,y)\to(1,2)}\frac{x^2y + 3}{x + y}\).",
               [r"Try direct substitution first. It works whenever the function is continuous at the point.",
                r"This is a polynomial divided by a polynomial, which is continuous wherever the bottom is not zero.",
                r"At \((1, 2)\) the bottom is \(1 + 2 = 3\), not zero.",
                r"So the limit is the value: \(\dfrac{(1)^2(2) + 3}{1 + 2} = \dfrac53\)."],
               r"\(\dfrac53\)", kind="Limit by substitution"),
            pq(r"Show that \(\displaystyle\lim_{(x,y)\to(0,0)}\frac{x^2 - y^2}{x^2 + y^2}\) does not exist.",
               [r"Approach along the \(x\)-axis (\(y = 0\)): \(\dfrac{x^2}{x^2} = 1\).",
                r"Approach along the \(y\)-axis (\(x = 0\)): \(\dfrac{-y^2}{y^2} = -1\).",
                r"Two paths give two different values."],
               r"The limit does not exist, by the two-path test.", kind="Two-path test"),
        ]),
    ],

    # ================= WEEK 12: PARTIAL DERIVATIVES & TANGENT PLANES =================
    12: [
        pset("Partial derivatives", "partial-derivatives", [
            pq(r"Find \(f_x\) and \(f_y\) for \(f(x, y) = 3x^2y - 5xy^3 + 2x\).",
               [r"For \(f_x\), treat \(y\) as if it were a number and differentiate in \(x\).",
                r"\(3x^2y \to 6xy\). \(-5xy^3 \to -5y^3\), because \(y^3\) is just a constant coefficient of \(x\). \(2x \to 2\).",
                r"\(f_x = 6xy - 5y^3 + 2\).",
                r"For \(f_y\), treat \(x\) as a number. \(3x^2y \to 3x^2\). \(-5xy^3 \to -15xy^2\). \(2x \to 0\), because it has no \(y\) in it.",
                r"\(f_y = 3x^2 - 15xy^2\)."],
               r"\(f_x = 6xy - 5y^3 + 2\) and \(f_y = 3x^2 - 15xy^2\)", kind="Partial derivatives of a polynomial"),
            pq(r"Find \(f_x\) and \(f_y\) for \(f(x, y) = xe^{xy}\).",
               [r"For \(f_x\): \(x\) appears in both factors, \(x\) and \(e^{xy}\), so use the product rule with \(y\) held constant.",
                r"The derivative of \(x\) is 1. The derivative of \(e^{xy}\) in \(x\) is \(ye^{xy}\), by the chain rule: the inside \(xy\) has \(x\)-derivative \(y\).",
                r"\(f_x = (1)e^{xy} + x\cdot ye^{xy} = e^{xy}(1 + xy)\).",
                r"For \(f_y\): the \(x\) in front is now a constant multiplier, so no product rule is needed. The derivative of \(e^{xy}\) in \(y\) is \(xe^{xy}\).",
                r"\(f_y = x\cdot xe^{xy} = x^2e^{xy}\)."],
               r"\(f_x = e^{xy}(1 + xy)\) and \(f_y = x^2e^{xy}\)", kind="Partial derivatives with the product rule"),
            pq(r"Find \(f_x\) and \(f_y\) for \(f(x, y) = \ln(x^2 + y^2)\).",
               [r"Chain rule: the derivative of \(\ln u\) is \(\dfrac1u\) times the derivative of \(u\), with \(u = x^2 + y^2\).",
                r"For \(f_x\): the \(x\)-derivative of \(x^2 + y^2\) is \(2x\), since \(y^2\) is a constant. So \(f_x = \dfrac{2x}{x^2+y^2}\).",
                r"For \(f_y\): the \(y\)-derivative of \(x^2 + y^2\) is \(2y\). So \(f_y = \dfrac{2y}{x^2+y^2}\).",
                r"The function treats \(x\) and \(y\) the same way, so the two answers have the same shape with the letters swapped.",
                r"Neither exists at the origin, where the function itself is undefined."],
               r"\(f_x = \dfrac{2x}{x^2 + y^2}\) and \(f_y = \dfrac{2y}{x^2 + y^2}\)", kind="Partial derivatives of a logarithm"),
            pq(r"For \(f(x, y) = x^3y + y^2\), find \(f_x(1, 2)\) and \(f_y(1, 2)\).",
               [r"Differentiate first and plug in afterward. If you plug in first, everything becomes a constant and the derivative is lost.",
                r"\(f_x = 3x^2y\), treating \(y\) as a constant. The \(y^2\) term has no \(x\), so it gives 0.",
                r"\(f_x(1, 2) = 3(1)^2(2) = 6\).",
                r"\(f_y = x^3 + 2y\), treating \(x\) as a constant.",
                r"\(f_y(1, 2) = 1 + 4 = 5\)."],
               r"\(f_x(1, 2) = 6\) and \(f_y(1, 2) = 5\)", kind="Partial derivatives at a point"),
            pq(r"Find all the second partial derivatives of \(f(x, y) = x^4y^2 - 2xy^3\).",
               [r"First partials: \(f_x = 4x^3y^2 - 2y^3\) and \(f_y = 2x^4y - 6xy^2\).",
                r"\(f_{xx} = 12x^2y^2\) and \(f_{yy} = 2x^4 - 12xy\).",
                r"\(f_{xy}\) is the \(y\)-derivative of \(f_x\): \(8x^3y - 6y^2\). \(f_{yx}\) is the \(x\)-derivative of \(f_y\): also \(8x^3y - 6y^2\)."],
               r"\(f_{xx} = 12x^2y^2\), \(f_{yy} = 2x^4 - 12xy\), \(f_{xy} = f_{yx} = 8x^3y - 6y^2\)", kind="Second partial derivatives"),
            pq(r"Check Clairaut's theorem for \(f(x, y) = x\sin y + ye^x\).",
               [r"Clairaut's theorem says the two mixed partials are equal, \(f_{xy} = f_{yx}\), when they are continuous.",
                r"\(f_x = \sin y + ye^x\). (In \(x\sin y\) the \(\sin y\) is a constant. In \(ye^x\) the \(y\) is a constant.)",
                r"Differentiate that in \(y\): \(f_{xy} = \cos y + e^x\).",
                r"Other order: \(f_y = x\cos y + e^x\).",
                r"Differentiate that in \(x\): \(f_{yx} = \cos y + e^x\). The same, as promised."],
               r"\(f_{xy} = f_{yx} = \cos y + e^x\), as the theorem says", kind="Clairaut's theorem"),
            pq(r"Use the limit definition to find \(f_x\) for \(f(x, y) = x^2y\).",
               [r"\(f_x = \displaystyle\lim_{h\to 0}\frac{(x+h)^2y - x^2y}{h}\).",
                r"Expand the top: \(x^2y + 2xhy + h^2y - x^2y = 2xhy + h^2y\).",
                r"Divide by \(h\): \(2xy + hy\). Let \(h \to 0\)."],
               r"\(f_x = 2xy\)", kind="Partial derivative from the limit definition"),
            pq(r"The temperature on a metal plate is \(T(x, y) = 100 - x^2 - 2y^2\) degrees. Find \(T_x(3, 1)\) and \(T_y(3, 1)\), and say what \(T_x(3, 1)\) means.",
               [r"\(T_x = -2x\). The terms \(100\) and \(-2y^2\) are constants when differentiating in \(x\).",
                r"\(T_x(3, 1) = -6\).",
                r"\(T_y = -4y\), so \(T_y(3, 1) = -4\).",
                r"\(T_x(3, 1) = -6\) is the rate of change of temperature as you move in the \(x\)-direction with \(y\) fixed: about 6 degrees colder per unit moved.",
                r"Both are negative because the plate is hottest at the origin and \((3, 1)\) is moving away from it in both directions."],
               r"\(T_x(3, 1) = -6\) and \(T_y(3, 1) = -4\). At \((3, 1)\), the temperature drops about 6 degrees per unit moved in the \(x\)-direction.", kind="Meaning of a partial derivative"),
            pq(r"Find all three first partial derivatives of \(f(x, y, z) = xy^2z^3\).",
               [r"A function of three variables has three first partial derivatives. For each one, treat the other two variables as constants.",
                r"\(f_x\): only \(x\) varies, and its derivative is 1. \(f_x = y^2z^3\).",
                r"\(f_y\): \(y^2 \to 2y\), with \(x\) and \(z^3\) as constant factors. \(f_y = 2xyz^3\).",
                r"\(f_z\): \(z^3 \to 3z^2\), with \(xy^2\) as a constant factor. \(f_z = 3xy^2z^2\)."],
               r"\(f_x = y^2z^3\), \(f_y = 2xyz^3\), \(f_z = 3xy^2z^2\)", kind="Function of three variables"),
        ]),
        pset("Tangent planes and linear approximation", "tangent-planes", [
            pq(r"Find the tangent plane to \(z = 2x^2 + y^2\) at \((1, 1, 3)\).",
               [r"\(f_x = 4x\) and \(f_y = 2y\), so \(f_x(1, 1) = 4\) and \(f_y(1, 1) = 2\).",
                r"Tangent plane: \(z - 3 = 4(x - 1) + 2(y - 1)\).",
                r"Expand: \(z = 4x - 4 + 2y - 2 + 3\)."],
               r"\(z = 4x + 2y - 3\)", kind="Tangent plane"),
            pq(r"Find the tangent plane to \(z = xy^2\) at the point where \((x, y) = (2, 1)\).",
               [r"The height: \(z_0 = 2(1)^2 = 2\).",
                r"\(f_x = y^2 = 1\) and \(f_y = 2xy = 4\) at \((2, 1)\).",
                r"Tangent plane: \(z - 2 = 1(x - 2) + 4(y - 1)\)."],
               r"\(z = x + 4y - 4\)", kind="Tangent plane at a given (x, y)"),
            pq(r"Find the tangent plane to \(z = \sqrt{x^2 + y^2}\) at the point where \((x, y) = (3, 4)\).",
               [r"The height: \(z_0 = \sqrt{9 + 16} = 5\).",
                r"\(f_x = \dfrac{x}{\sqrt{x^2 + y^2}} = \dfrac35\) and \(f_y = \dfrac{y}{\sqrt{x^2 + y^2}} = \dfrac45\) at \((3, 4)\).",
                r"Tangent plane: \(z - 5 = \frac35(x - 3) + \frac45(y - 4)\). The constants add up to \(5 - \frac95 - \frac{16}{5} = 0\)."],
               r"\(z = \frac35 x + \frac45 y\)", kind="Tangent plane to a cone"),
            pq(r"Use the linearization of \(f(x, y) = \sqrt{x^2 + y^2}\) at \((3, 4)\) to estimate \(f(3.1, 3.9)\).",
               [r"The linearization is \(L(x, y) = f(a, b) + f_x(a, b)(x - a) + f_y(a, b)(y - b)\). Here \(f(3, 4) = \sqrt{9 + 16} = 5\).",
                r"\(f_x = \dfrac{x}{\sqrt{x^2+y^2}}\), so \(f_x(3, 4) = \dfrac35\). \(f_y = \dfrac{y}{\sqrt{x^2+y^2}}\), so \(f_y(3, 4) = \dfrac45\).",
                r"\(L(x, y) = 5 + \dfrac35(x - 3) + \dfrac45(y - 4)\). The constants cancel (\(5 - \frac95 - \frac{16}{5} = 0\)), leaving \(L(x, y) = \dfrac35x + \dfrac45y\).",
                r"The point \((3.1, 3.9)\) is \(0.1\) to the right and \(0.1\) down: \(L = 5 + 0.6(0.1) + 0.8(-0.1) = 5 + 0.06 - 0.08 = 4.98\).",
                r"The true value is \(\sqrt{9.61 + 15.21} = \sqrt{24.82} \approx 4.982\)."],
               r"\(f(3.1, 3.9) \approx 4.98\) (the true value is about 4.982)", kind="Linear approximation"),
            pq(r"Linearize \(f(x, y) = x^2y\) at \((2, 3)\) and use it to estimate \(f(2.05, 2.9)\).",
               [r"\(f(2, 3) = 12\), \(f_x = 2xy = 12\) and \(f_y = x^2 = 4\) at \((2, 3)\).",
                r"\(L(x, y) = 12 + 12(x - 2) + 4(y - 3)\).",
                r"\(L(2.05, 2.9) = 12 + 12(0.05) + 4(-0.1) = 12 + 0.6 - 0.4\)."],
               r"\(f(2.05, 2.9) \approx 12.2\) (the true value is about 12.19)", kind="Linearization and an estimate"),
            pq(r"A cylinder has volume \(V = \pi r^2h\). Use the total differential to estimate the change in volume when \(r\) grows from 5 to 5.1 cm and \(h\) shrinks from 10 to 9.8 cm.",
               [r"\(dV = V_r\,dr + V_h\,dh = 2\pi rh\,dr + \pi r^2\,dh\).",
                r"Plug in \(r = 5\), \(h = 10\), \(dr = 0.1\), \(dh = -0.2\): \(2\pi(5)(10)(0.1) + \pi(25)(-0.2)\).",
                r"\(= 10\pi - 5\pi\)."],
               r"\(dV = 5\pi \approx 15.7\) cm³, so the volume grows by about 15.7 cm³", kind="Total differential"),
        ]),
    ],
}
