r"""Practice sets for weeks 1-6. Math is written the same way as in the lessons:
LaTeX inside \( ... \), and \lt instead of a bare "<"."""
from lesson_helpers import pq, pset

PRACTICE_1_6 = {
    # ======================= WEEK 1: PRECALCULUS REVIEW =======================
    1: [
        pset("Factoring", "review-factoring", [
            pq(r"Factor \(3x^3 - 12x\) completely.",
               [r"Pull out the common factor \(3x\): \(3x(x^2 - 4)\).",
                r"\(x^2 - 4\) is a difference of squares: \((x-2)(x+2)\)."],
               r"\(3x(x-2)(x+2)\)"),
            pq(r"Factor \(2x^2 + 7x + 3\).",
               [r"Find two numbers that multiply to \(2 \cdot 3 = 6\) and add to \(7\): \(6\) and \(1\).",
                r"Split the middle term: \(2x^2 + 6x + x + 3\).",
                r"Group: \(2x(x+3) + 1(x+3)\)."],
               r"\((2x+1)(x+3)\)"),
            pq(r"Factor \(8x^3 + 27\).",
               [r"It is a sum of cubes with \(a = 2x\) and \(b = 3\).",
                r"Use \(a^3 + b^3 = (a+b)(a^2 - ab + b^2)\), where \(a^2 = 4x^2\), \(ab = 6x\) and \(b^2 = 9\)."],
               r"\((2x+3)(4x^2 - 6x + 9)\)"),
        ]),
        pset("Expanding", "review-expanding", [
            pq(r"Expand \((3x-2)^2\).",
               [r"Use \((a-b)^2 = a^2 - 2ab + b^2\) with \(a = 3x\) and \(b = 2\).",
                r"\(a^2 = 9x^2\), \(2ab = 12x\), \(b^2 = 4\)."],
               r"\(9x^2 - 12x + 4\)"),
            pq(r"Expand and simplify \((x+h)^2 - 3(x+h) - (x^2 - 3x)\).",
               [r"Expand each part: \(x^2 + 2xh + h^2 - 3x - 3h - x^2 + 3x\).",
                r"The \(x^2\) terms cancel, and so do \(-3x\) and \(+3x\)."],
               r"\(2xh + h^2 - 3h\)"),
        ]),
        pset("Simplifying expressions", "review-simplifying", [
            pq(r"Simplify \(\dfrac{x^2 - 5x + 6}{x^2 - 4}\).",
               [r"Factor the top: \((x-2)(x-3)\).",
                r"Factor the bottom: \((x-2)(x+2)\).",
                r"Cancel the common factor \((x-2)\), which needs \(x \ne 2\)."],
               r"\(\dfrac{x-3}{x+2}\), for \(x \ne 2\)"),
            pq(r"Simplify \(\dfrac{\frac{1}{x+h} - \frac1x}{h}\).",
               [r"Combine the top over the common denominator \(x(x+h)\): \(\dfrac{x - (x+h)}{x(x+h)} = \dfrac{-h}{x(x+h)}\).",
                r"Dividing by \(h\) cancels the \(h\) on top."],
               r"\(-\dfrac{1}{x(x+h)}\)"),
            pq(r"Rationalize the denominator of \(\dfrac{6}{\sqrt7 + 2}\).",
               [r"Multiply top and bottom by the conjugate \(\sqrt7 - 2\).",
                r"The bottom becomes \(7 - 4 = 3\), so the fraction is \(\dfrac{6(\sqrt7 - 2)}{3}\)."],
               r"\(2\sqrt7 - 4\)"),
        ]),
        pset("Solving equations and inequalities", "review-solving", [
            pq(r"Solve \(2x^2 - 5x - 3 = 0\).",
               [r"Factor: \((2x+1)(x-3) = 0\).",
                r"Set each factor to zero: \(2x + 1 = 0\) or \(x - 3 = 0\)."],
               r"\(x = -\frac12\) or \(x = 3\)"),
            pq(r"Solve \(x^2 - 6x + 4 = 0\).",
               [r"It doesn't factor nicely, so use the quadratic formula with \(a = 1\), \(b = -6\), \(c = 4\).",
                r"\(x = \dfrac{6 \pm \sqrt{36 - 16}}{2} = \dfrac{6 \pm \sqrt{20}}{2}\).",
                r"Since \(\sqrt{20} = 2\sqrt5\), divide through by 2."],
               r"\(x = 3 \pm \sqrt5\)"),
            pq(r"Solve \(x^2 - 2x - 8 \ge 0\).",
               [r"Factor: \((x-4)(x+2) \ge 0\).",
                r"The expression is zero at \(x = -2\) and \(x = 4\), which split the number line into three intervals.",
                r"Test a point in each: \(x = -3\) gives \(+\), \(x = 0\) gives \(-\), \(x = 5\) gives \(+\).",
                r"Keep the positive intervals, and the endpoints because of \(\ge\)."],
               r"\(x \le -2\) or \(x \ge 4\)"),
            pq(r"Solve \(|3x + 2| \lt 7\).",
               [r"\(|A| \lt 7\) means \(-7 \lt A \lt 7\), so \(-7 \lt 3x + 2 \lt 7\).",
                r"Subtract 2 from all three parts: \(-9 \lt 3x \lt 5\).",
                r"Divide by 3."],
               r"\(-3 \lt x \lt \frac53\)"),
        ]),
        pset("Graphing functions", "review-graphing", [
            pq(r"Find the equation of the line through \((-1, 4)\) and \((2, -2)\).",
               [r"Slope: \(m = \dfrac{-2 - 4}{2 - (-1)} = \dfrac{-6}{3} = -2\).",
                r"Point-slope form with \((-1, 4)\): \(y - 4 = -2(x + 1)\).",
                r"Expand: \(y = -2x - 2 + 4\)."],
               r"\(y = -2x + 2\)"),
            pq(r"Find the domain of \(f(x) = \dfrac{\sqrt{x+3}}{x - 1}\).",
               [r"The square root needs \(x + 3 \ge 0\), so \(x \ge -3\).",
                r"The denominator can't be zero, so \(x \ne 1\)."],
               r"\(x \ge -3\) and \(x \ne 1\), which is \([-3, 1) \cup (1, \infty)\)"),
            pq(r"Describe how to get the graph of \(y = 2(x+1)^2 - 5\) from \(y = x^2\), and give its vertex.",
               [r"\((x+1)\) shifts the graph 1 unit to the left.",
                r"The factor 2 stretches it vertically by 2.",
                r"The \(-5\) shifts it down 5 units.",
                r"In vertex form \(y = a(x-h)^2 + k\), we have \(h = -1\) and \(k = -5\)."],
               r"Shift left 1, stretch vertically by 2, shift down 5. The vertex is \((-1, -5)\)."),
        ]),
    ],

    # ======================= WEEK 2: LIMITS =======================
    2: [
        pset("Limits from graphs and tables", "limits", [
            pq(r"\(f(x) = \begin{cases} 2x + 1 & x \lt 1 \\ x^2 + 2 & x \ge 1 \end{cases}\). Find \(\displaystyle\lim_{x\to 1} f(x)\).",
               [r"From the left, use \(2x + 1\): it approaches \(2(1) + 1 = 3\).",
                r"From the right, use \(x^2 + 2\): it approaches \(1 + 2 = 3\).",
                r"Both sides agree, so the limit exists."],
               r"\(3\)"),
            pq(r"\(g(x) = \begin{cases} x + 3 & x \lt 0 \\ 1 - x & x \ge 0 \end{cases}\). Find \(\displaystyle\lim_{x\to 0} g(x)\).",
               [r"From the left, \(x + 3\) approaches \(3\).",
                r"From the right, \(1 - x\) approaches \(1\).",
                r"The two one-sided limits are different."],
               r"The limit does not exist (the left side gives 3, the right side gives 1)."),
        ]),
        pset("Evaluating limits algebraically", "limits-algebraic", [
            pq(r"Find \(\displaystyle\lim_{x\to 4}\frac{x^2 - 16}{x - 4}\).",
               [r"Plugging in gives \(\frac00\), so simplify first.",
                r"Factor the top: \(\dfrac{(x-4)(x+4)}{x-4} = x + 4\) for \(x \ne 4\).",
                r"Now plug in \(x = 4\)."],
               r"\(8\)"),
            pq(r"Find \(\displaystyle\lim_{x\to 2}\frac{x^2 + x - 6}{x^2 - 4}\).",
               [r"Plugging in gives \(\frac00\). Factor both: \(\dfrac{(x+3)(x-2)}{(x-2)(x+2)}\).",
                r"Cancel \((x-2)\) to get \(\dfrac{x+3}{x+2}\).",
                r"Plug in \(x = 2\)."],
               r"\(\frac54\)"),
            pq(r"Find \(\displaystyle\lim_{x\to 9}\frac{\sqrt{x} - 3}{x - 9}\).",
               [r"Multiply top and bottom by the conjugate \(\sqrt{x} + 3\).",
                r"The top becomes \(x - 9\), so the fraction is \(\dfrac{x - 9}{(x-9)(\sqrt{x} + 3)} = \dfrac{1}{\sqrt{x} + 3}\).",
                r"Plug in \(x = 9\): \(\dfrac{1}{3 + 3}\)."],
               r"\(\frac16\)"),
            pq(r"Find \(\displaystyle\lim_{h\to 0}\frac{(3+h)^2 - 9}{h}\).",
               [r"Expand the top: \(9 + 6h + h^2 - 9 = 6h + h^2\).",
                r"Divide by \(h\): \(6 + h\).",
                r"Let \(h \to 0\)."],
               r"\(6\)"),
            pq(r"Find \(\displaystyle\lim_{x\to 0}\frac{\sin x}{3x}\).",
               [r"Pull out the constant: \(\dfrac13 \cdot \dfrac{\sin x}{x}\).",
                r"Use the special limit \(\displaystyle\lim_{x\to 0}\frac{\sin x}{x} = 1\)."],
               r"\(\frac13\)"),
        ]),
        pset("Limits at infinity and infinite limits", "limits-infinity", [
            pq(r"Find \(\displaystyle\lim_{x\to\infty}\frac{4x^3 - x}{2x^3 + 5}\).",
               [r"Divide the top and bottom by \(x^3\), the highest power: \(\dfrac{4 - \frac{1}{x^2}}{2 + \frac{5}{x^3}}\).",
                r"As \(x \to \infty\), the terms \(\frac{1}{x^2}\) and \(\frac{5}{x^3}\) go to 0."],
               r"\(2\)"),
            pq(r"Find \(\displaystyle\lim_{x\to\infty}\frac{5x + 1}{x^2 - 3}\).",
               [r"The degree of the top (1) is less than the degree of the bottom (2).",
                r"Divide by \(x^2\): \(\dfrac{\frac5x + \frac{1}{x^2}}{1 - \frac{3}{x^2}} \to \dfrac{0}{1}\)."],
               r"\(0\)"),
            pq(r"Find \(\displaystyle\lim_{x\to 3^-}\frac{2}{x - 3}\) and \(\displaystyle\lim_{x\to 3^+}\frac{2}{x - 3}\).",
               [r"Just left of 3, \(x - 3\) is a tiny negative number, so \(\frac{2}{x-3}\) is a huge negative number.",
                r"Just right of 3, \(x - 3\) is a tiny positive number, so \(\frac{2}{x-3}\) is a huge positive number.",
                r"So \(x = 3\) is a vertical asymptote."],
               r"\(-\infty\) from the left and \(+\infty\) from the right"),
            pq(r"Find \(\displaystyle\lim_{x\to -\infty}\frac{\sqrt{9x^2 + 2}}{x + 1}\).",
               [r"Factor \(x^2\) out of the root: \(\sqrt{9x^2 + 2} = |x|\sqrt{9 + \frac{2}{x^2}}\).",
                r"For negative \(x\), \(|x| = -x\).",
                r"Divide top and bottom by \(x\): \(\dfrac{-\sqrt{9 + \frac{2}{x^2}}}{1 + \frac1x} \to \dfrac{-3}{1}\)."],
               r"\(-3\)"),
        ]),
        pset("The epsilon-delta definition", "epsilon-delta", [
            pq(r"Prove that \(\displaystyle\lim_{x\to 3}(2x + 1) = 7\).",
               [r"Start from what we want: \(|(2x + 1) - 7| \lt \varepsilon\).",
                r"Simplify: \(|2x - 6| = 2|x - 3| \lt \varepsilon\), which is the same as \(|x - 3| \lt \frac{\varepsilon}{2}\).",
                r"So choose \(\delta = \frac{\varepsilon}{2}\).",
                r"Check: if \(0 \lt |x - 3| \lt \delta\), then \(|(2x+1) - 7| = 2|x - 3| \lt 2\delta = \varepsilon\)."],
               r"\(\delta = \frac{\varepsilon}{2}\) works for every \(\varepsilon \gt 0\)."),
            pq(r"For \(\displaystyle\lim_{x\to 2}(4x - 3) = 5\) and \(\varepsilon = 0.2\), find the largest \(\delta\) that works.",
               [r"We need \(|(4x - 3) - 5| \lt 0.2\).",
                r"Simplify: \(|4x - 8| = 4|x - 2| \lt 0.2\).",
                r"Divide by 4: \(|x - 2| \lt 0.05\)."],
               r"\(\delta = 0.05\)"),
        ]),
        pset("Continuity", "continuity", [
            pq(r"Find \(k\) so that \(f(x) = \begin{cases} x^2 + k & x \le 1 \\ 3x + 2 & x \gt 1 \end{cases}\) is continuous.",
               [r"The only place it can break is \(x = 1\), where the two pieces meet.",
                r"Left piece at 1: \(1 + k\). Right piece at 1: \(3 + 2 = 5\).",
                r"Set them equal: \(1 + k = 5\)."],
               r"\(k = 4\)"),
            pq(r"Find and classify the discontinuities of \(f(x) = \dfrac{x^2 - x - 2}{x^2 - 4}\).",
               [r"Factor: \(\dfrac{(x-2)(x+1)}{(x-2)(x+2)}\). The function is undefined at \(x = 2\) and \(x = -2\).",
                r"At \(x = 2\) the factor cancels, and the limit is \(\dfrac{2+1}{2+2} = \dfrac34\). The limit exists, so it is a hole.",
                r"At \(x = -2\) nothing cancels: the bottom goes to 0 and the top doesn't, so the function blows up."],
               r"Removable discontinuity (a hole) at \(x = 2\), infinite discontinuity (vertical asymptote) at \(x = -2\)."),
        ]),
    ],

    # ======================= WEEK 3: DERIVATIVES =======================
    3: [
        pset("The limit definition of the derivative", "derivative-definition", [
            pq(r"Use the limit definition to differentiate \(f(x) = 3x^2 - x\).",
               [r"\(f(x+h) = 3(x+h)^2 - (x+h) = 3x^2 + 6xh + 3h^2 - x - h\).",
                r"Subtract \(f(x)\): \(f(x+h) - f(x) = 6xh + 3h^2 - h\).",
                r"Divide by \(h\): \(6x + 3h - 1\).",
                r"Let \(h \to 0\)."],
               r"\(f'(x) = 6x - 1\)"),
            pq(r"Use the limit definition to differentiate \(f(x) = \dfrac{1}{x+1}\).",
               [r"\(f(x+h) - f(x) = \dfrac{1}{x+h+1} - \dfrac{1}{x+1} = \dfrac{(x+1) - (x+h+1)}{(x+h+1)(x+1)} = \dfrac{-h}{(x+h+1)(x+1)}\).",
                r"Divide by \(h\): \(\dfrac{-1}{(x+h+1)(x+1)}\).",
                r"Let \(h \to 0\)."],
               r"\(f'(x) = -\dfrac{1}{(x+1)^2}\)"),
            pq(r"Is \(f(x) = |x - 2|\) differentiable at \(x = 2\)? Is it continuous there?",
               [r"For \(x \gt 2\), \(f(x) = x - 2\), which has slope \(1\).",
                r"For \(x \lt 2\), \(f(x) = -(x - 2)\), which has slope \(-1\).",
                r"The slopes from the two sides don't match, so the graph has a corner at \(x = 2\).",
                r"Both pieces approach \(0 = f(2)\), so there is no break in the graph."],
               r"It is continuous at \(x = 2\) but not differentiable there."),
        ]),
        pset("Power rule and basic rules", "derivative-rules", [
            pq(r"Differentiate \(f(x) = 5x^4 - 2x^3 + 7x - 9\).",
               [r"Use the power rule on each term: \(5 \cdot 4x^3\), \(-2 \cdot 3x^2\), and \(7\).",
                r"The constant \(-9\) has derivative 0."],
               r"\(f'(x) = 20x^3 - 6x^2 + 7\)"),
            pq(r"Differentiate \(f(x) = \dfrac{6}{x^3} + 4\sqrt{x}\).",
               [r"Rewrite with exponents: \(f(x) = 6x^{-3} + 4x^{1/2}\).",
                r"Power rule: \(6(-3)x^{-4} + 4 \cdot \frac12 x^{-1/2} = -18x^{-4} + 2x^{-1/2}\)."],
               r"\(f'(x) = -\dfrac{18}{x^4} + \dfrac{2}{\sqrt{x}}\)"),
            pq(r"Differentiate \(f(x) = \dfrac{x^3 - 4x + 2}{x}\).",
               [r"Divide each term by \(x\) first: \(f(x) = x^2 - 4 + 2x^{-1}\).",
                r"Power rule: \(2x - 0 - 2x^{-2}\)."],
               r"\(f'(x) = 2x - \dfrac{2}{x^2}\)"),
            pq(r"Find the equation of the tangent line to \(y = x^3 - 2x\) at \(x = 2\).",
               [r"The point: \(y(2) = 8 - 4 = 4\), so \((2, 4)\).",
                r"The slope: \(y' = 3x^2 - 2\), so \(y'(2) = 10\).",
                r"Point-slope form: \(y - 4 = 10(x - 2)\)."],
               r"\(y = 10x - 16\)"),
            pq(r"Where does \(f(x) = x^3 - 6x^2 + 9x + 1\) have a horizontal tangent?",
               [r"A horizontal tangent means \(f'(x) = 0\).",
                r"\(f'(x) = 3x^2 - 12x + 9 = 3(x-1)(x-3)\), which is zero at \(x = 1\) and \(x = 3\).",
                r"The heights are \(f(1) = 5\) and \(f(3) = 1\)."],
               r"At \((1, 5)\) and \((3, 1)\)"),
            pq(r"A particle's position is \(s(t) = t^3 - 6t^2 + 9t\) metres after \(t\) seconds. Find its velocity and acceleration at \(t = 2\), and the times when it is at rest.",
               [r"Velocity is the derivative of position: \(v(t) = 3t^2 - 12t + 9\), so \(v(2) = 12 - 24 + 9 = -3\).",
                r"Acceleration is the derivative of velocity: \(a(t) = 6t - 12\), so \(a(2) = 0\).",
                r"At rest means \(v(t) = 0\): \(3(t-1)(t-3) = 0\)."],
               r"\(v(2) = -3\) m/s and \(a(2) = 0\) m/s². It is at rest at \(t = 1\) s and \(t = 3\) s."),
            pq(r"Find the second derivative of \(f(x) = x^4 - 3x^2 + 2x\).",
               [r"First derivative: \(f'(x) = 4x^3 - 6x + 2\).",
                r"Differentiate again."],
               r"\(f''(x) = 12x^2 - 6\)"),
        ]),
        pset("Product rule", "product-rule", [
            pq(r"Differentiate \(y = (x^2 + 1)(3x - 4)\).",
               [r"Product rule \((fg)' = f'g + fg'\) with \(f = x^2 + 1\) and \(g = 3x - 4\).",
                r"\(f' = 2x\) and \(g' = 3\), so \(y' = 2x(3x - 4) + 3(x^2 + 1)\).",
                r"Expand: \(6x^2 - 8x + 3x^2 + 3\)."],
               r"\(y' = 9x^2 - 8x + 3\)"),
            pq(r"Differentiate \(y = \sqrt{x}\,(x^3 + 2)\).",
               [r"Product rule with \(f = x^{1/2}\) and \(g = x^3 + 2\): \(f' = \frac12 x^{-1/2}\) and \(g' = 3x^2\).",
                r"\(y' = \frac12 x^{-1/2}(x^3 + 2) + x^{1/2} \cdot 3x^2\).",
                r"Simplify: \(\frac12 x^{5/2} + x^{-1/2} + 3x^{5/2}\)."],
               r"\(y' = \frac72 x^{5/2} + \dfrac{1}{\sqrt{x}}\)"),
            pq(r"Given \(f(2) = 3\), \(f'(2) = -1\), \(g(2) = 4\) and \(g'(2) = 5\), find \((fg)'(2)\).",
               [r"Product rule at \(x = 2\): \((fg)'(2) = f'(2)g(2) + f(2)g'(2)\).",
                r"Plug in: \((-1)(4) + (3)(5) = -4 + 15\)."],
               r"\(11\)"),
            pq(r"Differentiate \(y = x(x - 1)(x + 2)\) with the three-factor product rule.",
               [r"\((fgh)' = f'gh + fg'h + fgh'\) with \(f = x\), \(g = x - 1\), \(h = x + 2\). Each derivative is 1.",
                r"\(y' = (x-1)(x+2) + x(x+2) + x(x-1)\).",
                r"Expand: \((x^2 + x - 2) + (x^2 + 2x) + (x^2 - x)\)."],
               r"\(y' = 3x^2 + 2x - 2\)"),
        ]),
    ],

    # ======================= WEEK 4: INVERSE, EXPONENTIAL & TRIG FUNCTIONS =======================
    # This week has no chain rule yet: derivatives here use only the power, product and quotient rules.
    4: [
        pset("Functions and their inverses", "inverse-functions", [
            pq(r"Find the inverse of \(f(x) = 3(x+2)^2 - 5\) if \(x \ge -2\), and give the domain of \(f^{-1}\).",
               [r"Write \(y = 3(x+2)^2 - 5\), then swap \(x\) and \(y\): \(x = 3(y+2)^2 - 5\).",
                r"Isolate the square: \((y+2)^2 = \dfrac{x+5}{3}\).",
                r"Take the square root. The original \(x \ge -2\) becomes \(y \ge -2\), so keep the positive root: \(y + 2 = \sqrt{\dfrac{x+5}{3}}\).",
                r"The domain of \(f^{-1}\) is the range of \(f\). The lowest value of \(f\) is \(-5\)."],
               r"\(f^{-1}(x) = \sqrt{\dfrac{x+5}{3}} - 2\), where \(x \ge -5\)"),
            pq(r"Find the inverse of \(g(x) = -(x-4)^2 + 2\) if \(x \le 4\), and give the domain of \(g^{-1}\).",
               [r"Swap \(x\) and \(y\): \(x = -(y-4)^2 + 2\).",
                r"Isolate the square: \((y-4)^2 = 2 - x\).",
                r"The original \(x \le 4\) becomes \(y \le 4\), so \(y - 4\) is negative. Keep the negative root: \(y - 4 = -\sqrt{2 - x}\).",
                r"The highest value of \(g\) is 2, so the inverse needs \(x \le 2\)."],
               r"\(g^{-1}(x) = 4 - \sqrt{2 - x}\), where \(x \le 2\)"),
            pq(r"Find the inverse of \(h(x) = \dfrac{2x + 1}{x - 3}\).",
               [r"Swap \(x\) and \(y\): \(x = \dfrac{2y + 1}{y - 3}\).",
                r"Multiply both sides by \((y - 3)\): \(xy - 3x = 2y + 1\).",
                r"Collect the \(y\) terms on one side: \(xy - 2y = 3x + 1\).",
                r"Factor out \(y\) and divide: \(y(x - 2) = 3x + 1\)."],
               r"\(h^{-1}(x) = \dfrac{3x + 1}{x - 2}\), where \(x \ne 2\)"),
            pq(r"If \(f(2) = 7\), what is \(f^{-1}(7)\)? Is \(f^{-1}(x)\) the same as \(\dfrac{1}{f(x)}\)?",
               [r"An inverse reverses the input and the output: \(f\) sends 2 to 7, so \(f^{-1}\) sends 7 back to 2.",
                r"The \(-1\) on a function name is reserved notation for the inverse. It is not an exponent.",
                r"For any other power, \(f^k(x) = (f(x))^k\). The reciprocal has to be written \((f(x))^{-1}\)."],
               r"\(f^{-1}(7) = 2\). No: \(f^{-1}(x) \ne (f(x))^{-1} = \dfrac{1}{f(x)}\)."),
            pq(r"The point \((1, 6)\) is on the graph of \(f\). What point must be on the graph of \(f^{-1}\), and what line are the two graphs mirrored across?",
               [r"Every point \((x, y)\) on \(f\) becomes \((y, x)\) on \(f^{-1}\).",
                r"Swapping the coordinates of every point reflects the graph across the line \(y = x\)."],
               r"\((6, 1)\). The graphs are mirror images across \(y = x\)."),
        ]),
        pset("Exponential and logarithmic functions", "exponential-functions", [
            pq(r"Find the inverse of \(f(x) = 5(3^x) - 2\).",
               [r"Swap \(x\) and \(y\): \(x = 5(3^y) - 2\).",
                r"Isolate the exponential: \(3^y = \dfrac{x+2}{5}\).",
                r"A logarithm with the same base undoes it: \(y = \log_3\!\left(\dfrac{x+2}{5}\right)\).",
                r"A logarithm needs a positive input, so \(x + 2 \gt 0\)."],
               r"\(f^{-1}(x) = \log_3\!\left(\dfrac{x+2}{5}\right)\), where \(x \gt -2\)"),
            pq(r"Simplify exactly: \(\log_2 48 - \log_2 3\).",
               [r"A difference of logs is the log of a quotient: \(\log_2\dfrac{48}{3} = \log_2 16\).",
                r"\(16 = 2^4\)."],
               r"\(4\)"),
            pq(r"Solve \(3\log_5 x = 6\) exactly, and solve \(2^{x-1} + 3 = 20\) to 1 decimal place.",
               [r"First equation: divide by 3 to get \(\log_5 x = 2\), so \(x = 5^2\).",
                r"Second equation: subtract 3 to get \(2^{x-1} = 17\).",
                r"Take \(\log_2\) of both sides: \(x - 1 = \log_2 17\).",
                r"Change of base: \(\log_2 17 = \dfrac{\ln 17}{\ln 2} \approx 4.09\)."],
               r"\(x = 25\), and \(x = 1 + \log_2 17 \approx 5.1\)"),
            pq(r"A binary search takes \(f(n) = \log_2(n)\) steps to find an item in a sorted list of \(n\) items. How many steps does a list of 1,000,000 items take? How many could a linear search with \(f(n) = n\) take?",
               [r"\(\log_2(1{,}000{,}000) = \dfrac{\ln 1{,}000{,}000}{\ln 2} \approx 19.93\).",
                r"Steps are whole numbers, so round up.",
                r"A linear search checks the items one at a time, so the worst case is every item."],
               r"About 20 steps for the binary search, and up to 1,000,000 for the linear search."),
            pq(r"Find the derivative of \(f(x) = 4(5^x) - 3x^3\).",
               [r"Exponential rule: \(\dfrac{d}{dx}b^x = b^x\ln b\), so \(4(5^x)\) gives \(4(5^x)\ln 5\).",
                r"Power rule: \(3x^3\) gives \(9x^2\)."],
               r"\(f'(x) = 4(5^x)\ln 5 - 9x^2\)"),
            pq(r"Find the derivative of \(g(x) = x^2 \cdot 3^x\).",
               [r"Product rule with \(f = x^2\) and \(g = 3^x\): \(f' = 2x\) and \(g' = 3^x\ln 3\).",
                r"\(g'(x) = 2x \cdot 3^x + x^2 \cdot 3^x\ln 3\).",
                r"Factor out \(x \cdot 3^x\)."],
               r"\(g'(x) = x \cdot 3^x\,(2 + x\ln 3)\)"),
            pq(r"Find the derivative of \(h(x) = \dfrac{e^x}{x^2}\).",
               [r"Quotient rule \(\left(\dfrac fg\right)' = \dfrac{f'g - fg'}{g^2}\) with \(f = e^x\) and \(g = x^2\).",
                r"\(h'(x) = \dfrac{e^x \cdot x^2 - e^x \cdot 2x}{x^4}\).",
                r"Factor \(x e^x\) out of the top and cancel one \(x\)."],
               r"\(h'(x) = \dfrac{e^x(x - 2)}{x^3}\)"),
            pq(r"Find the slope of the tangent to \(g(x) = 2e^x - x^2\) at \(x = \ln 4\).",
               [r"\(g'(x) = 2e^x - 2x\).",
                r"At \(x = \ln 4\), \(e^{\ln 4} = 4\), so \(g'(\ln 4) = 2(4) - 2\ln 4\)."],
               r"\(8 - 2\ln 4 \approx 5.23\)"),
        ]),
        pset("Trigonometric functions", "trig-functions", [
            pq(r"Evaluate exactly: \(\sin(210^\circ)\), \(\cos\!\left(\dfrac{5\pi}{6}\right)\) and \(\tan\!\left(\dfrac{3\pi}{4}\right)\).",
               [r"\(210^\circ\) is in quadrant III with reference angle \(30^\circ\). Sine is negative there: \(-\sin 30^\circ = -\frac12\).",
                r"\(\frac{5\pi}{6}\) is in quadrant II with reference angle \(\frac\pi6\). Cosine is negative there: \(-\cos\frac\pi6 = -\frac{\sqrt3}{2}\).",
                r"\(\frac{3\pi}{4}\) is in quadrant II with reference angle \(\frac\pi4\). Tangent is negative there: \(-\tan\frac\pi4 = -1\)."],
               r"\(-\dfrac12\), \(-\dfrac{\sqrt3}{2}\) and \(-1\)"),
            pq(r"Find the derivative of \(f(x) = 3\sin x - 2\cos x\).",
               [r"\(\dfrac{d}{dx}\sin x = \cos x\), so \(3\sin x\) gives \(3\cos x\).",
                r"\(\dfrac{d}{dx}\cos x = -\sin x\), so \(-2\cos x\) gives \(+2\sin x\)."],
               r"\(f'(x) = 3\cos x + 2\sin x\)"),
            pq(r"Find the derivative of \(g(x) = x^2\sin x\).",
               [r"Product rule with \(f = x^2\) and \(g = \sin x\): \(f' = 2x\) and \(g' = \cos x\)."],
               r"\(g'(x) = 2x\sin x + x^2\cos x\)"),
            pq(r"Use the quotient rule to show that \(\dfrac{d}{dx}\sec x = \sec x\tan x\).",
               [r"Write \(\sec x = \dfrac{1}{\cos x}\).",
                r"Quotient rule: \(\dfrac{0 \cdot \cos x - 1 \cdot (-\sin x)}{\cos^2 x} = \dfrac{\sin x}{\cos^2 x}\).",
                r"Split it up: \(\dfrac{1}{\cos x} \cdot \dfrac{\sin x}{\cos x}\)."],
               r"\(\dfrac{\sin x}{\cos^2 x} = \sec x\tan x\)"),
            pq(r"Find the equation of the tangent to \(f(x) = x\sin x\) at \(x = \pi\), in slope-intercept form.",
               [r"The point: \(f(\pi) = \pi\sin\pi = 0\), so \((\pi, 0)\).",
                r"Product rule: \(f'(x) = \sin x + x\cos x\).",
                r"The slope: \(f'(\pi) = 0 + \pi(-1) = -\pi\).",
                r"Point-slope form: \(y - 0 = -\pi(x - \pi)\)."],
               r"\(y = -\pi x + \pi^2\)"),
        ]),
        pset("Harder ln questions", "log-functions", [
            pq(r"Simplify exactly: \(e^{2\ln 3 - \ln 6}\), and \(\ln\!\left(e^5\sqrt{e}\right)\).",
               [r"\(2\ln 3 = \ln 9\), so the exponent is \(\ln 9 - \ln 6 = \ln\frac96 = \ln\frac32\).",
                r"\(e^{\ln(3/2)} = \frac32\).",
                r"For the second one, \(e^5\sqrt{e} = e^5 \cdot e^{1/2} = e^{11/2}\), and \(\ln\) undoes \(e\)."],
               r"\(\dfrac32\) and \(\dfrac{11}{2}\)"),
            pq(r"Solve exactly: \(\ln x + \ln(x - 3) = \ln 10\).",
               [r"A sum of logs is the log of a product: \(\ln\big(x(x-3)\big) = \ln 10\).",
                r"So \(x(x - 3) = 10\), which is \(x^2 - 3x - 10 = 0\).",
                r"Factor: \((x - 5)(x + 2) = 0\), so \(x = 5\) or \(x = -2\).",
                r"Check the original equation: \(\ln(-2)\) is not defined, so \(x = -2\) is rejected."],
               r"\(x = 5\)"),
            pq(r"Solve exactly: \(2\ln x - \ln(x + 2) = 0\).",
               [r"Move one log across: \(2\ln x = \ln(x+2)\), and \(2\ln x = \ln(x^2)\).",
                r"So \(x^2 = x + 2\), which is \(x^2 - x - 2 = 0\).",
                r"Factor: \((x - 2)(x + 1) = 0\), so \(x = 2\) or \(x = -1\).",
                r"\(\ln(-1)\) is not defined, so \(x = -1\) is rejected."],
               r"\(x = 2\)"),
            pq(r"Solve exactly: \(5e^x = 2e^{3x}\).",
               [r"Divide both sides by \(2e^x\) (it is never zero): \(\dfrac52 = \dfrac{e^{3x}}{e^x} = e^{2x}\).",
                r"Take \(\ln\) of both sides: \(2x = \ln\frac52\)."],
               r"\(x = \frac12\ln\frac52 \approx 0.46\)"),
            pq(r"Solve \(3^{x+1} = 5^x\) exactly using \(\ln\), then round to 2 decimal places.",
               [r"Take \(\ln\) of both sides and bring the exponents down: \((x+1)\ln 3 = x\ln 5\).",
                r"Expand: \(x\ln 3 + \ln 3 = x\ln 5\).",
                r"Collect the \(x\) terms: \(\ln 3 = x(\ln 5 - \ln 3)\)."],
               r"\(x = \dfrac{\ln 3}{\ln 5 - \ln 3} \approx 2.15\)"),
            pq(r"Find the inverse of \(f(x) = 2\ln(x - 1) + 3\), and state the domain and range of \(f^{-1}\).",
               [r"Swap \(x\) and \(y\): \(x = 2\ln(y - 1) + 3\).",
                r"Isolate the log: \(\ln(y - 1) = \dfrac{x - 3}{2}\).",
                r"Raise \(e\) to both sides: \(y - 1 = e^{(x-3)/2}\).",
                r"\(f\) needs \(x \gt 1\) and can output any real number, so \(f^{-1}\) takes any real number and outputs values above 1."],
               r"\(f^{-1}(x) = e^{(x-3)/2} + 1\). Its domain is all real numbers and its range is \(y \gt 1\)."),
            pq(r"Find the inverse of \(f(x) = \dfrac{e^x - 1}{e^x + 1}\), and state the domain of \(f^{-1}\).",
               [r"Swap \(x\) and \(y\): \(x = \dfrac{e^y - 1}{e^y + 1}\).",
                r"Multiply by \((e^y + 1)\): \(xe^y + x = e^y - 1\).",
                r"Collect the \(e^y\) terms: \(x + 1 = e^y(1 - x)\), so \(e^y = \dfrac{1 + x}{1 - x}\).",
                r"Take \(\ln\) of both sides. The input of \(\ln\) must be positive, which needs \(-1 \lt x \lt 1\)."],
               r"\(f^{-1}(x) = \ln\!\left(\dfrac{1 + x}{1 - x}\right)\), where \(-1 \lt x \lt 1\)"),
            pq(r"Find the derivative of \(f(x) = 2^x \cdot 3^x\) and simplify it to a single exponential.",
               [r"Product rule: \(f'(x) = 2^x\ln 2 \cdot 3^x + 2^x \cdot 3^x\ln 3\).",
                r"Factor out \(2^x \cdot 3^x = 6^x\): \(f'(x) = 6^x(\ln 2 + \ln 3)\).",
                r"\(\ln 2 + \ln 3 = \ln 6\). (This matches differentiating \(6^x\) directly.)"],
               r"\(f'(x) = 6^x\ln 6\)"),
            pq(r"Find the derivative of \(g(x) = \dfrac{5^x}{e^x}\) and simplify.",
               [r"Quotient rule: \(g'(x) = \dfrac{5^x\ln 5 \cdot e^x - 5^x \cdot e^x}{(e^x)^2}\).",
                r"Factor \(5^x e^x\) out of the top and cancel one \(e^x\): \(\dfrac{5^x(\ln 5 - 1)}{e^x}\)."],
               r"\(g'(x) = \left(\dfrac5e\right)^x(\ln 5 - 1)\)"),
            pq(r"Find the \(x\)-value where \(f(x) = 2^x - x\ln 4\) has a horizontal tangent.",
               [r"\(f'(x) = 2^x\ln 2 - \ln 4\). (\(\ln 4\) is just a constant.)",
                r"Set \(f'(x) = 0\): \(2^x\ln 2 = \ln 4\).",
                r"\(\ln 4 = \ln(2^2) = 2\ln 2\), so \(2^x = 2\)."],
               r"\(x = 1\)"),
            pq(r"Find the equation of the tangent to \(f(x) = xe^x\) at \(x = \ln 2\), in slope-intercept form.",
               [r"The point: \(f(\ln 2) = \ln 2 \cdot e^{\ln 2} = 2\ln 2\).",
                r"Product rule: \(f'(x) = e^x + xe^x = e^x(1 + x)\).",
                r"The slope: \(f'(\ln 2) = 2(1 + \ln 2)\).",
                r"Point-slope form: \(y - 2\ln 2 = 2(1 + \ln 2)(x - \ln 2)\). Expanding, the \(2\ln 2\) terms cancel."],
               r"\(y = 2(1 + \ln 2)\,x - 2(\ln 2)^2\)"),
            pq(r"A model for the early days of an outbreak predicts \(f(x) = 1.3^x\) cases \(x\) days after the first case. On what day does it predict 1,000,000 cases, and how fast are cases growing on day 14?",
               [r"Solve \(1.3^x = 1{,}000{,}000\) by taking \(\ln\) of both sides: \(x\ln 1.3 = \ln 1{,}000{,}000\).",
                r"\(x = \dfrac{\ln 1{,}000{,}000}{\ln 1.3} \approx \dfrac{13.816}{0.2624} \approx 52.7\).",
                r"The growth rate is the derivative: \(f'(x) = 1.3^x\ln 1.3\).",
                r"\(f'(14) = 1.3^{14}\ln 1.3 \approx 39.37 \times 0.2624\)."],
               r"After about 52.7 days. On day 14, cases are growing by about 10.3 cases per day."),
        ]),
    ],

    # ============ WEEK 5: CHAIN & QUOTIENT RULES, IMPLICIT DIFFERENTIATION, LOGARITHMS ============
    5: [
        pset("Chain rule", "chain-rule", [
            pq(r"Differentiate \(y = (2x^3 - 5)^4\).",
               [r"Outside function: \((\ )^4\). Inside function: \(2x^3 - 5\).",
                r"Derivative of the outside, keeping the inside: \(4(2x^3 - 5)^3\).",
                r"Multiply by the derivative of the inside, \(6x^2\)."],
               r"\(y' = 24x^2(2x^3 - 5)^3\)"),
            pq(r"Differentiate \(y = \sqrt{3x^2 + 4}\).",
               [r"Rewrite: \(y = (3x^2 + 4)^{1/2}\).",
                r"Chain rule: \(\frac12(3x^2 + 4)^{-1/2} \cdot 6x\).",
                r"Simplify: \(\frac12 \cdot 6x = 3x\)."],
               r"\(y' = \dfrac{3x}{\sqrt{3x^2 + 4}}\)"),
            pq(r"Differentiate \(y = \cos^2(3x)\).",
               [r"There are three layers: \((\ )^2\), then \(\cos\), then \(3x\).",
                r"Square: \(2\cos(3x)\). Cosine: \(-\sin(3x)\). Inside: \(3\).",
                r"Multiply them together."],
               r"\(y' = -6\sin(3x)\cos(3x)\)"),
            pq(r"Differentiate \(y = x^2(x+1)^5\) and factor your answer.",
               [r"Product rule: \(y' = 2x(x+1)^5 + x^2 \cdot 5(x+1)^4\). (The chain rule on \((x+1)^5\) multiplies by 1.)",
                r"Factor out \(x(x+1)^4\): \(x(x+1)^4\big[2(x+1) + 5x\big]\)."],
               r"\(y' = x(x+1)^4(7x + 2)\)"),
        ]),
        pset("Quotient rule", "quotient-rule", [
            pq(r"Differentiate \(y = \dfrac{2x + 1}{x^2 + 3}\).",
               [r"Quotient rule with \(f = 2x + 1\) and \(g = x^2 + 3\): \(f' = 2\) and \(g' = 2x\).",
                r"\(y' = \dfrac{2(x^2 + 3) - (2x + 1)(2x)}{(x^2 + 3)^2}\).",
                r"Expand the top: \(2x^2 + 6 - 4x^2 - 2x\)."],
               r"\(y' = \dfrac{-2x^2 - 2x + 6}{(x^2 + 3)^2}\)"),
            pq(r"Find the equation of the tangent line to \(y = \dfrac{x}{x + 2}\) at \(x = 2\).",
               [r"The point: \(y(2) = \frac24 = \frac12\).",
                r"Quotient rule: \(y' = \dfrac{(1)(x+2) - x(1)}{(x+2)^2} = \dfrac{2}{(x+2)^2}\).",
                r"The slope: \(y'(2) = \frac{2}{16} = \frac18\).",
                r"Point-slope form: \(y - \frac12 = \frac18(x - 2)\)."],
               r"\(y = \frac18 x + \frac14\)"),
        ]),
        pset("Implicit differentiation", "implicit", [
            pq(r"Find \(\dfrac{dy}{dx}\) for \(x^2 + xy + y^2 = 7\), and the slope at \((1, 2)\).",
               [r"Differentiate every term with respect to \(x\). The \(xy\) term needs the product rule: \(2x + y + x\,y' + 2y\,y' = 0\).",
                r"Collect the \(y'\) terms: \(y'(x + 2y) = -(2x + y)\).",
                r"So \(y' = -\dfrac{2x + y}{x + 2y}\). At \((1, 2)\): \(-\dfrac{2 + 2}{1 + 4}\)."],
               r"\(\dfrac{dy}{dx} = -\dfrac{2x + y}{x + 2y}\), and the slope at \((1, 2)\) is \(-\dfrac45\)"),
            pq(r"Find the equation of the tangent line to \(x^3 + y^3 = 9\) at \((1, 2)\).",
               [r"Differentiate: \(3x^2 + 3y^2\,y' = 0\), so \(y' = -\dfrac{x^2}{y^2}\).",
                r"At \((1, 2)\): \(y' = -\frac14\).",
                r"Point-slope form: \(y - 2 = -\frac14(x - 1)\)."],
               r"\(y = -\frac14 x + \frac94\)"),
        ]),
        pset("Logarithmic functions", "log-functions", [
            pq(r"Expand \(\ln\dfrac{x^3\sqrt{x+1}}{(x-2)^2}\) using the log laws.",
               [r"A quotient becomes a difference, and a product becomes a sum: \(\ln(x^3) + \ln\sqrt{x+1} - \ln\big((x-2)^2\big)\).",
                r"Bring each exponent down in front. The square root is the power \(\frac12\)."],
               r"\(3\ln x + \frac12\ln(x+1) - 2\ln(x-2)\)"),
            pq(r"Solve \(2e^{3x} + 1 = 15\).",
               [r"Isolate the exponential: \(2e^{3x} = 14\), so \(e^{3x} = 7\).",
                r"Take \(\ln\) of both sides: \(3x = \ln 7\)."],
               r"\(x = \dfrac{\ln 7}{3} \approx 0.65\)"),
            pq(r"Solve \(\log_3 x + \log_3(x - 6) = 3\).",
               [r"Combine the logs: \(\log_3\big(x(x - 6)\big) = 3\).",
                r"Rewrite as an exponential: \(x(x - 6) = 3^3 = 27\).",
                r"So \(x^2 - 6x - 27 = 0\), which factors as \((x - 9)(x + 3) = 0\).",
                r"\(x = -3\) is rejected because \(\log_3(-3)\) is not defined."],
               r"\(x = 9\)"),
        ]),
        pset("Derivatives of exponentials and logarithms", "exp-log-derivatives", [
            pq(r"Differentiate \(y = x^2\ln x\).",
               [r"Product rule with \(f = x^2\) and \(g = \ln x\): \(f' = 2x\) and \(g' = \frac1x\).",
                r"\(y' = 2x\ln x + x^2 \cdot \frac1x\)."],
               r"\(y' = 2x\ln x + x\)"),
            pq(r"Differentiate \(y = e^{2x}\cos x\).",
               [r"Chain rule: \(\dfrac{d}{dx}e^{2x} = 2e^{2x}\).",
                r"Product rule: \(y' = 2e^{2x}\cos x + e^{2x}(-\sin x)\).",
                r"Factor out \(e^{2x}\)."],
               r"\(y' = e^{2x}(2\cos x - \sin x)\)"),
            pq(r"Differentiate \(y = \ln(x^2 + 4)\).",
               [r"Use \(\dfrac{d}{dx}\ln g(x) = \dfrac{g'(x)}{g(x)}\) with \(g(x) = x^2 + 4\).",
                r"\(g'(x) = 2x\)."],
               r"\(y' = \dfrac{2x}{x^2 + 4}\)"),
            pq(r"Use logarithmic differentiation to differentiate \(y = x^{2x}\) (for \(x \gt 0\)).",
               [r"Take \(\ln\) of both sides: \(\ln y = 2x\ln x\).",
                r"Differentiate both sides: \(\dfrac{y'}{y} = 2\ln x + 2x \cdot \frac1x = 2\ln x + 2\).",
                r"Multiply by \(y = x^{2x}\)."],
               r"\(y' = 2x^{2x}(\ln x + 1)\)"),
        ]),
    ],

    # ======================= WEEK 6: CRITICAL POINTS & CURVE SKETCHING =======================
    6: [
        pset("Critical points and the first derivative test", "critical-points", [
            pq(r"Find the critical numbers of \(f(x) = x^3 - 6x^2 + 5\).",
               [r"\(f'(x) = 3x^2 - 12x = 3x(x - 4)\).",
                r"\(f'\) is defined everywhere, so the critical numbers are where \(f'(x) = 0\)."],
               r"\(x = 0\) and \(x = 4\)"),
            pq(r"Find where \(f(x) = 2x^3 - 3x^2 - 12x + 1\) is increasing and decreasing, and its local extrema.",
               [r"\(f'(x) = 6x^2 - 6x - 12 = 6(x - 2)(x + 1)\), which is zero at \(x = -1\) and \(x = 2\).",
                r"Sign chart: \(f'(-2) \gt 0\), \(f'(0) \lt 0\), \(f'(3) \gt 0\).",
                r"\(f'\) goes \(+ \to -\) at \(x = -1\) (local max) and \(- \to +\) at \(x = 2\) (local min).",
                r"\(f(-1) = -2 - 3 + 12 + 1 = 8\) and \(f(2) = 16 - 12 - 24 + 1 = -19\)."],
               r"Increasing on \((-\infty, -1)\) and \((2, \infty)\), decreasing on \((-1, 2)\). Local max \((-1, 8)\), local min \((2, -19)\)."),
            pq(r"Find the critical numbers of \(f(x) = x^{1/3}(x - 4)\).",
               [r"Expand first: \(f(x) = x^{4/3} - 4x^{1/3}\).",
                r"\(f'(x) = \frac43 x^{1/3} - \frac43 x^{-2/3} = \dfrac{4(x - 1)}{3x^{2/3}}\).",
                r"\(f'(x) = 0\) when the top is zero: \(x = 1\).",
                r"\(f'\) is undefined when the bottom is zero: \(x = 0\), which is in the domain of \(f\)."],
               r"\(x = 0\) and \(x = 1\)"),
            pq(r"Find the absolute maximum and minimum of \(f(x) = x^3 - 3x^2 + 1\) on \([-1, 4]\).",
               [r"\(f'(x) = 3x^2 - 6x = 3x(x - 2)\), so the critical numbers are \(x = 0\) and \(x = 2\). Both are in the interval.",
                r"Compare the values at the endpoints and the critical numbers: \(f(-1) = -3\), \(f(0) = 1\), \(f(2) = -3\), \(f(4) = 17\)."],
               r"Absolute max \(17\) at \(x = 4\). Absolute min \(-3\) at \(x = -1\) and at \(x = 2\)."),
            pq(r"Find and classify the critical point of \(f(x) = xe^{-x}\).",
               [r"Product rule: \(f'(x) = e^{-x} - xe^{-x} = e^{-x}(1 - x)\).",
                r"\(e^{-x}\) is never zero, so the only critical number is \(x = 1\).",
                r"\(f' \gt 0\) for \(x \lt 1\) and \(f' \lt 0\) for \(x \gt 1\): the sign goes \(+ \to -\)."],
               r"A local (and absolute) maximum at \(\left(1, \dfrac1e\right)\)"),
            pq(r"A function has derivative \(f'(x) = (x - 1)^2(x + 2)\). Where does \(f\) have local extrema?",
               [r"\(f'(x) = 0\) at \(x = 1\) and \(x = -2\).",
                r"\((x - 1)^2\) is never negative, so the sign of \(f'\) is the sign of \((x + 2)\).",
                r"At \(x = -2\) the sign goes \(- \to +\): a local minimum.",
                r"At \(x = 1\) the sign stays positive on both sides: no extremum."],
               r"A local minimum at \(x = -2\) only. \(x = 1\) is a critical number but not an extremum."),
        ]),
        pset("Concavity and the second derivative test", "concavity", [
            pq(r"Find the intervals of concavity and the inflection point of \(f(x) = x^3 - 6x^2 + 4\).",
               [r"\(f'(x) = 3x^2 - 12x\) and \(f''(x) = 6x - 12\).",
                r"\(f''(x) = 0\) at \(x = 2\). \(f'' \lt 0\) for \(x \lt 2\) and \(f'' \gt 0\) for \(x \gt 2\).",
                r"The concavity changes at \(x = 2\), and \(f(2) = 8 - 24 + 4 = -12\)."],
               r"Concave down on \((-\infty, 2)\), concave up on \((2, \infty)\). Inflection point \((2, -12)\)."),
            pq(r"Find the inflection points of \(f(x) = 3x^5 - 5x^4\).",
               [r"\(f'(x) = 15x^4 - 20x^3\) and \(f''(x) = 60x^3 - 60x^2 = 60x^2(x - 1)\).",
                r"\(f''(x) = 0\) at \(x = 0\) and \(x = 1\).",
                r"\(60x^2\) is never negative, so \(f''\) only changes sign at \(x = 1\). At \(x = 0\) it is negative on both sides.",
                r"\(f(1) = 3 - 5 = -2\)."],
               r"One inflection point, at \((1, -2)\). \(x = 0\) is not one."),
            pq(r"Use the second derivative test to classify the critical points of \(f(x) = x^3 - 12x + 3\).",
               [r"\(f'(x) = 3x^2 - 12 = 3(x - 2)(x + 2)\), so the critical numbers are \(x = \pm 2\).",
                r"\(f''(x) = 6x\). \(f''(2) = 12 \gt 0\): local min. \(f''(-2) = -12 \lt 0\): local max.",
                r"\(f(2) = 8 - 24 + 3 = -13\) and \(f(-2) = -8 + 24 + 3 = 19\)."],
               r"Local min at \((2, -13)\), local max at \((-2, 19)\)"),
            pq(r"Find and classify the critical points of \(f(x) = x + 2\sin x\) on \((0, 2\pi)\).",
               [r"\(f'(x) = 1 + 2\cos x = 0\) gives \(\cos x = -\frac12\), so \(x = \frac{2\pi}{3}\) or \(x = \frac{4\pi}{3}\).",
                r"\(f''(x) = -2\sin x\).",
                r"\(f''\!\left(\frac{2\pi}{3}\right) = -\sqrt3 \lt 0\): local max. \(f''\!\left(\frac{4\pi}{3}\right) = \sqrt3 \gt 0\): local min."],
               r"Local max at \(x = \frac{2\pi}{3}\) (value \(\frac{2\pi}{3} + \sqrt3 \approx 3.83\)), local min at \(x = \frac{4\pi}{3}\) (value \(\frac{4\pi}{3} - \sqrt3 \approx 2.46\))"),
        ]),
        pset("Curve sketching", "curve-sketching", [
            pq(r"List the key features of \(f(x) = x^3 - 3x^2\): intercepts, local extrema and inflection point.",
               [r"Intercepts: \(f(x) = x^2(x - 3)\), so the graph meets the \(x\)-axis at \(x = 0\) and \(x = 3\).",
                r"\(f'(x) = 3x^2 - 6x = 3x(x - 2)\): increasing for \(x \lt 0\), decreasing on \((0, 2)\), increasing for \(x \gt 2\).",
                r"So there is a local max at \((0, 0)\) and a local min at \((2, -4)\).",
                r"\(f''(x) = 6x - 6\) changes sign at \(x = 1\), where \(f(1) = -2\)."],
               r"\(x\)-intercepts 0 and 3, local max \((0, 0)\), local min \((2, -4)\), inflection point \((1, -2)\)"),
            pq(r"Find all asymptotes of \(f(x) = \dfrac{2x^2 + 1}{x^2 - 1}\).",
               [r"Vertical: the bottom is zero at \(x = \pm 1\) and the top isn't, so the function blows up there.",
                r"Horizontal: the degrees match, so the limit as \(x \to \pm\infty\) is the ratio of leading coefficients, \(\frac21\)."],
               r"Vertical asymptotes \(x = 1\) and \(x = -1\), horizontal asymptote \(y = 2\)"),
            pq(r"List the key features of \(f(x) = \dfrac{x}{x^2 - 4}\): asymptotes, symmetry, and where it increases or decreases.",
               [r"Vertical asymptotes where the bottom is zero: \(x = \pm 2\). Horizontal asymptote \(y = 0\), since the bottom has the higher degree.",
                r"\(f(-x) = -f(x)\), so the function is odd (symmetric about the origin). It passes through \((0, 0)\).",
                r"Quotient rule: \(f'(x) = \dfrac{(x^2 - 4) - x(2x)}{(x^2 - 4)^2} = \dfrac{-(x^2 + 4)}{(x^2 - 4)^2}\).",
                r"The top is always negative and the bottom is always positive, so \(f' \lt 0\) wherever it is defined."],
               r"Vertical asymptotes \(x = \pm 2\), horizontal asymptote \(y = 0\), odd, and decreasing on every interval of its domain (no local extrema)"),
            pq(r"Sketch \(f(x) = x^4 - 2x^2\): find its symmetry, local extrema and inflection points.",
               [r"\(f(-x) = f(x)\), so the function is even (symmetric about the \(y\)-axis).",
                r"\(f'(x) = 4x^3 - 4x = 4x(x - 1)(x + 1)\). The signs go \(-, +, -, +\), so there are local minima at \(x = \pm 1\) and a local max at \(x = 0\).",
                r"\(f(\pm 1) = -1\) and \(f(0) = 0\).",
                r"\(f''(x) = 12x^2 - 4 = 0\) at \(x = \pm\frac{1}{\sqrt3}\), where \(f = \frac19 - \frac23 = -\frac59\). The sign of \(f''\) changes at both."],
               r"Even. Local minima \((\pm 1, -1)\), local max \((0, 0)\), inflection points \(\left(\pm\frac{1}{\sqrt3}, -\frac59\right)\). It has a W shape."),
        ]),
    ],
}
