r"""Practice sets for weeks 7-12. Math is written the same way as in the lessons:
LaTeX inside \( ... \), and \lt instead of a bare "<"."""
from lesson_helpers import pq, pset

PRACTICE_7_12 = {
    # ================= WEEK 7: IVT, MVT, NEWTON'S METHOD & OPTIMIZATION =================
    7: [
        pset("Intermediate Value Theorem", "ivt", [
            pq(r"Show that \(x^3 - 4x + 1 = 0\) has a solution between 0 and 1.",
               [r"Let \(f(x) = x^3 - 4x + 1\). It is a polynomial, so it is continuous on \([0, 1]\).",
                r"\(f(0) = 1 \gt 0\) and \(f(1) = 1 - 4 + 1 = -2 \lt 0\).",
                r"0 is between \(f(0)\) and \(f(1)\), so the IVT applies."],
               r"By the IVT there is a \(c\) in \((0, 1)\) with \(f(c) = 0\)."),
            pq(r"Show that \(e^x = 3 - x\) has a solution in \((0, 1)\).",
               [r"Move everything to one side: let \(g(x) = e^x + x - 3\), which is continuous everywhere.",
                r"\(g(0) = 1 + 0 - 3 = -2 \lt 0\) and \(g(1) = e + 1 - 3 \approx 0.72 \gt 0\).",
                r"\(g\) changes sign on \([0, 1]\), so the IVT gives a \(c\) with \(g(c) = 0\)."],
               r"There is a \(c\) in \((0, 1)\) with \(e^c = 3 - c\)."),
            pq(r"Must \(f(x) = x^2 + 1\) take the value 5 somewhere on \([0, 3]\)? If so, find where.",
               [r"\(f\) is continuous, with \(f(0) = 1\) and \(f(3) = 10\).",
                r"5 is between 1 and 10, so the IVT says yes.",
                r"Solve \(c^2 + 1 = 5\): \(c = \pm 2\), and only \(c = 2\) is in the interval."],
               r"Yes, at \(c = 2\)"),
        ]),
        pset("Mean Value Theorem", "mvt", [
            pq(r"Find the value of \(c\) that the Mean Value Theorem guarantees for \(f(x) = x^2 - 4x\) on \([1, 5]\).",
               [r"Average slope: \(\dfrac{f(5) - f(1)}{5 - 1} = \dfrac{5 - (-3)}{4} = 2\).",
                r"\(f'(x) = 2x - 4\). Set \(2c - 4 = 2\)."],
               r"\(c = 3\)"),
            pq(r"Find the value of \(c\) that the Mean Value Theorem guarantees for \(f(x) = \sqrt{x}\) on \([0, 4]\).",
               [r"Average slope: \(\dfrac{\sqrt4 - \sqrt0}{4 - 0} = \dfrac12\).",
                r"\(f'(x) = \dfrac{1}{2\sqrt{x}}\). Set \(\dfrac{1}{2\sqrt{c}} = \dfrac12\), so \(\sqrt{c} = 1\)."],
               r"\(c = 1\)"),
            pq(r"Check that Rolle's theorem applies to \(f(x) = x^3 - 4x\) on \([-2, 2]\), and find every \(c\) it guarantees.",
               [r"\(f\) is a polynomial, so it is continuous and differentiable. \(f(-2) = -8 + 8 = 0\) and \(f(2) = 8 - 8 = 0\), so the endpoints match.",
                r"Solve \(f'(c) = 3c^2 - 4 = 0\): \(c^2 = \frac43\)."],
               r"\(c = \pm\dfrac{2}{\sqrt3} \approx \pm 1.15\), both inside \((-2, 2)\)"),
            pq(r"\(f(x) = |x|\) has \(f(-1) = f(1) = 1\), but \(f'(c)\) is never 0. Why doesn't this break Rolle's theorem?",
               [r"Rolle's theorem needs \(f\) to be differentiable on the whole open interval \((-1, 1)\).",
                r"\(|x|\) has a corner at \(x = 0\): the slope is \(-1\) on the left and \(1\) on the right."],
               r"\(f\) is not differentiable at \(x = 0\), so the theorem doesn't apply."),
        ]),
        pset("Newton's method", "newtons-method", [
            pq(r"Use two steps of Newton's method on \(f(x) = x^2 - 5\) from \(x_0 = 2\) to approximate \(\sqrt5\).",
               [r"\(f'(x) = 2x\), so \(x_{n+1} = x_n - \dfrac{x_n^2 - 5}{2x_n}\).",
                r"\(x_1 = 2 - \dfrac{4 - 5}{4} = 2.25\).",
                r"\(x_2 = 2.25 - \dfrac{5.0625 - 5}{4.5} = 2.25 - 0.0139\)."],
               r"\(x_2 \approx 2.2361\) (the true value is \(\sqrt5 \approx 2.23607\))"),
            pq(r"Use two steps of Newton's method from \(x_0 = 1\) to approximate the root of \(x^3 + x - 1 = 0\).",
               [r"\(f(x) = x^3 + x - 1\) and \(f'(x) = 3x^2 + 1\).",
                r"\(x_1 = 1 - \dfrac{f(1)}{f'(1)} = 1 - \dfrac14 = 0.75\).",
                r"\(f(0.75) = 0.421875 + 0.75 - 1 = 0.171875\) and \(f'(0.75) = 2.6875\).",
                r"\(x_2 = 0.75 - \dfrac{0.171875}{2.6875} \approx 0.75 - 0.0640\)."],
               r"\(x_2 \approx 0.686\) (the root is about 0.6823)"),
        ]),
        pset("Optimization", "optimization", [
            pq(r"A farmer has 200 m of fence for a rectangular field along a straight river, and the river side needs no fence. What dimensions give the largest area?",
               [r"Let \(x\) be the two sides that meet the river. The side along the river is then \(200 - 2x\).",
                r"Area: \(A(x) = x(200 - 2x) = 200x - 2x^2\).",
                r"\(A'(x) = 200 - 4x = 0\) at \(x = 50\). \(A'' = -4 \lt 0\), so it is a maximum."],
               r"50 m by 100 m (the 100 m side along the river), for an area of 5000 m²"),
            pq(r"An open-top box with a square base must hold 32 m³. What dimensions use the least material?",
               [r"Let the base be \(x\) by \(x\) and the height \(h\). Volume: \(x^2h = 32\), so \(h = \dfrac{32}{x^2}\).",
                r"Surface area (base plus four sides): \(S = x^2 + 4xh = x^2 + \dfrac{128}{x}\).",
                r"\(S'(x) = 2x - \dfrac{128}{x^2} = 0\) gives \(x^3 = 64\), so \(x = 4\).",
                r"\(S''(x) = 2 + \dfrac{256}{x^3} \gt 0\), so it is a minimum. Then \(h = \frac{32}{16} = 2\)."],
               r"A 4 m by 4 m base and a height of 2 m, using 48 m² of material"),
            pq(r"Find two positive numbers whose product is 100 and whose sum is as small as possible.",
               [r"Call them \(x\) and \(\dfrac{100}{x}\). Their sum is \(S(x) = x + \dfrac{100}{x}\).",
                r"\(S'(x) = 1 - \dfrac{100}{x^2} = 0\) gives \(x^2 = 100\), so \(x = 10\) (positive).",
                r"\(S''(x) = \dfrac{200}{x^3} \gt 0\), so it is a minimum."],
               r"10 and 10, with a sum of 20"),
            pq(r"Find the point on the curve \(y = \sqrt{x}\) that is closest to \((4, 0)\).",
               [r"The distance from \((x, \sqrt{x})\) to \((4, 0)\) is \(\sqrt{(x - 4)^2 + x}\). Minimize its square instead, which has its minimum at the same place.",
                r"\(D(x) = (x - 4)^2 + x = x^2 - 7x + 16\).",
                r"\(D'(x) = 2x - 7 = 0\) at \(x = \frac72\), and \(D'' = 2 \gt 0\), so it is a minimum."],
               r"\(\left(\frac72, \sqrt{\frac72}\right) \approx (3.5, 1.87)\), at a distance of \(\frac{\sqrt{15}}{2} \approx 1.94\)"),
        ]),
    ],

    # ============ WEEK 8: ANTIDERIVATIVES, AREAS UNDER CURVES & THE FTC ============
    8: [
        pset("Antiderivatives and indefinite integrals", "antiderivatives", [
            pq(r"Find \(\displaystyle\int\left(4x^3 - 6x + 5\right)dx\).",
               [r"Reverse the power rule on each term: raise the power by 1 and divide by the new power.",
                r"\(4 \cdot \dfrac{x^4}{4} - 6 \cdot \dfrac{x^2}{2} + 5x\), then add \(C\)."],
               r"\(x^4 - 3x^2 + 5x + C\)"),
            pq(r"Find \(\displaystyle\int\left(\frac{3}{x^2} + 2\sqrt{x}\right)dx\).",
               [r"Rewrite with exponents: \(3x^{-2} + 2x^{1/2}\).",
                r"Reverse power rule: \(3 \cdot \dfrac{x^{-1}}{-1} + 2 \cdot \dfrac{x^{3/2}}{3/2}\)."],
               r"\(-\dfrac3x + \dfrac43 x^{3/2} + C\)"),
            pq(r"Find \(\displaystyle\int\left(2e^x - \frac5x + \sec^2 x\right)dx\).",
               [r"\(\int e^x\,dx = e^x\), \(\int\frac1x\,dx = \ln|x|\) and \(\int\sec^2x\,dx = \tan x\).",
                r"Keep the constants in front and add \(C\)."],
               r"\(2e^x - 5\ln|x| + \tan x + C\)"),
            pq(r"Find \(f\) if \(f'(x) = 2\cos x + 3\) and \(f(0) = 1\).",
               [r"Antidifferentiate: \(f(x) = 2\sin x + 3x + C\).",
                r"Use \(f(0) = 1\): \(2\sin 0 + 0 + C = 1\), so \(C = 1\)."],
               r"\(f(x) = 2\sin x + 3x + 1\)"),
            pq(r"A particle has acceleration \(a(t) = 6t - 4\), with \(v(0) = 3\) and \(s(0) = 2\). Find its position \(s(t)\).",
               [r"Velocity is an antiderivative of acceleration: \(v(t) = 3t^2 - 4t + C\). \(v(0) = 3\) gives \(C = 3\).",
                r"Position is an antiderivative of velocity: \(s(t) = t^3 - 2t^2 + 3t + D\). \(s(0) = 2\) gives \(D = 2\)."],
               r"\(s(t) = t^3 - 2t^2 + 3t + 2\)"),
        ]),
        pset("Areas under curves and Riemann sums", "area-under-curves", [
            pq(r"Estimate the area under \(f(x) = x^2 + 1\) on \([0, 2]\) with a right Riemann sum, \(n = 4\).",
               [r"\(\Delta x = \dfrac{2 - 0}{4} = 0.5\), and the right endpoints are \(0.5, 1, 1.5, 2\).",
                r"Heights: \(f(0.5) = 1.25\), \(f(1) = 2\), \(f(1.5) = 3.25\), \(f(2) = 5\).",
                r"\(R_4 = 0.5(1.25 + 2 + 3.25 + 5) = 0.5(11.5)\)."],
               r"\(R_4 = 5.75\) (an overestimate, since \(f\) is increasing)"),
            pq(r"Find the left Riemann sum \(L_3\) for \(f(x) = \dfrac1x\) on \([1, 4]\). Is it an overestimate or an underestimate?",
               [r"\(\Delta x = 1\), and the left endpoints are \(1, 2, 3\).",
                r"\(L_3 = 1\left(1 + \frac12 + \frac13\right) = \frac{11}{6}\).",
                r"\(f\) is decreasing, so each rectangle's left edge is its tallest point and the rectangle sticks out above the curve."],
               r"\(L_3 = \frac{11}{6} \approx 1.83\), an overestimate"),
            pq(r"Find the midpoint sum \(M_2\) for \(f(x) = 4 - x^2\) on \([0, 2]\).",
               [r"\(\Delta x = 1\), and the midpoints are \(0.5\) and \(1.5\).",
                r"\(f(0.5) = 3.75\) and \(f(1.5) = 1.75\).",
                r"\(M_2 = 1(3.75 + 1.75)\)."],
               r"\(M_2 = 5.5\)"),
            pq(r"Use geometry to find \(\displaystyle\int_{-3}^{3}\sqrt{9 - x^2}\,dx\).",
               [r"\(y = \sqrt{9 - x^2}\) is the top half of the circle \(x^2 + y^2 = 9\), which has radius 3.",
                r"The integral is the area of that half disk: \(\frac12\pi(3)^2\)."],
               r"\(\dfrac{9\pi}{2}\)"),
            pq(r"Given \(\displaystyle\int_0^5 f(x)\,dx = 7\) and \(\displaystyle\int_0^2 f(x)\,dx = 3\), find \(\displaystyle\int_2^5 f(x)\,dx\), \(\displaystyle\int_5^2 f(x)\,dx\) and \(\displaystyle\int_0^5\big(2f(x) + 1\big)dx\).",
               [r"Split the interval: \(\int_0^2 f + \int_2^5 f = \int_0^5 f\), so \(\int_2^5 f = 7 - 3 = 4\).",
                r"Swapping the limits changes the sign: \(\int_5^2 f = -4\).",
                r"Linearity: \(2\int_0^5 f + \int_0^5 1\,dx = 2(7) + 5\)."],
               r"\(4\), \(-4\) and \(19\)"),
        ]),
        pset("The Fundamental Theorem of Calculus", "ftc", [
            pq(r"Evaluate \(\displaystyle\int_1^3\left(3x^2 - 2x\right)dx\).",
               [r"An antiderivative is \(F(x) = x^3 - x^2\).",
                r"\(F(3) - F(1) = (27 - 9) - (1 - 1)\)."],
               r"\(18\)"),
            pq(r"Evaluate \(\displaystyle\int_1^4\left(\frac{1}{\sqrt{x}} + x\right)dx\).",
               [r"Rewrite \(\frac{1}{\sqrt{x}} = x^{-1/2}\). An antiderivative is \(F(x) = 2\sqrt{x} + \dfrac{x^2}{2}\).",
                r"\(F(4) = 4 + 8 = 12\) and \(F(1) = 2 + \frac12 = \frac52\)."],
               r"\(\dfrac{19}{2}\)"),
            pq(r"Find \(\dfrac{d}{dx}\displaystyle\int_2^x\sqrt{t^3 + 1}\,dt\).",
               [r"FTC part 1: differentiating an integral with respect to its upper limit gives back the integrand.",
                r"Replace \(t\) with \(x\)."],
               r"\(\sqrt{x^3 + 1}\)"),
            pq(r"Find \(\dfrac{d}{dx}\displaystyle\int_1^{x^2}\ln t\,dt\) (for \(x \gt 0\)).",
               [r"The upper limit is \(x^2\), so FTC part 1 needs the chain rule: plug in the upper limit, then multiply by its derivative.",
                r"\(\ln(x^2) \cdot 2x\), and \(\ln(x^2) = 2\ln x\)."],
               r"\(4x\ln x\)"),
            pq(r"A particle moves with velocity \(v(t) = 3t^2 - 12\) m/s for \(0 \le t \le 3\). Find its displacement and the total distance it travels.",
               [r"Displacement: \(\displaystyle\int_0^3 v\,dt = \big[t^3 - 12t\big]_0^3 = 27 - 36 = -9\).",
                r"For distance, find where it turns around: \(v(t) = 0\) at \(t = 2\). It moves backward on \([0, 2]\) and forward on \([2, 3]\).",
                r"\(\displaystyle\int_0^2 v\,dt = 8 - 24 = -16\) and \(\displaystyle\int_2^3 v\,dt = -9 - (-16) = 7\).",
                r"Distance adds the sizes: \(16 + 7\)."],
               r"Displacement \(-9\) m, total distance 23 m"),
        ]),
    ],

    # ============ WEEK 9: SUBSTITUTION, AREAS BETWEEN CURVES & AVERAGE VALUE ============
    9: [
        pset("Integration by substitution", "u-sub", [
            pq(r"Find \(\displaystyle\int 2x(x^2 + 3)^5\,dx\).",
               [r"Let \(u = x^2 + 3\), so \(du = 2x\,dx\). The \(2x\,dx\) is already there.",
                r"The integral becomes \(\displaystyle\int u^5\,du = \dfrac{u^6}{6} + C\).",
                r"Put \(x\) back."],
               r"\(\dfrac{(x^2 + 3)^6}{6} + C\)"),
            pq(r"Find \(\displaystyle\int x^2\sqrt{x^3 + 1}\,dx\).",
               [r"Let \(u = x^3 + 1\), so \(du = 3x^2\,dx\) and \(x^2\,dx = \frac13\,du\).",
                r"The integral becomes \(\frac13\displaystyle\int u^{1/2}\,du = \frac13 \cdot \frac23 u^{3/2} + C\)."],
               r"\(\frac29(x^3 + 1)^{3/2} + C\)"),
            pq(r"Find \(\displaystyle\int\cos(5x)\,dx\).",
               [r"Let \(u = 5x\), so \(du = 5\,dx\) and \(dx = \frac15\,du\).",
                r"The integral becomes \(\frac15\displaystyle\int\cos u\,du = \frac15\sin u + C\)."],
               r"\(\frac15\sin(5x) + C\)"),
            pq(r"Find \(\displaystyle\int xe^{x^2}\,dx\).",
               [r"Let \(u = x^2\), so \(du = 2x\,dx\) and \(x\,dx = \frac12\,du\).",
                r"The integral becomes \(\frac12\displaystyle\int e^u\,du = \frac12 e^u + C\)."],
               r"\(\frac12 e^{x^2} + C\)"),
            pq(r"Find \(\displaystyle\int\frac{\ln x}{x}\,dx\).",
               [r"Let \(u = \ln x\), so \(du = \frac1x\,dx\).",
                r"The integral becomes \(\displaystyle\int u\,du = \dfrac{u^2}{2} + C\)."],
               r"\(\dfrac{(\ln x)^2}{2} + C\)"),
            pq(r"Evaluate \(\displaystyle\int_0^2\frac{x}{x^2 + 1}\,dx\).",
               [r"Let \(u = x^2 + 1\), so \(x\,dx = \frac12\,du\).",
                r"Change the limits too: \(x = 0\) gives \(u = 1\), and \(x = 2\) gives \(u = 5\).",
                r"\(\frac12\displaystyle\int_1^5\frac{du}{u} = \frac12\big[\ln u\big]_1^5 = \frac12(\ln 5 - \ln 1)\)."],
               r"\(\frac12\ln 5 \approx 0.80\)"),
            pq(r"Evaluate \(\displaystyle\int_0^1(2x + 1)^3\,dx\).",
               [r"Let \(u = 2x + 1\), so \(dx = \frac12\,du\).",
                r"Change the limits: \(x = 0\) gives \(u = 1\), and \(x = 1\) gives \(u = 3\).",
                r"\(\frac12\displaystyle\int_1^3 u^3\,du = \frac12\left[\dfrac{u^4}{4}\right]_1^3 = \frac18(81 - 1)\)."],
               r"\(10\)"),
        ]),
        pset("Area between curves", "area-between", [
            pq(r"Find the area between \(y = x^2\) and \(y = x + 2\).",
               [r"Find where they cross: \(x^2 = x + 2\) gives \((x - 2)(x + 1) = 0\), so \(x = -1\) and \(x = 2\).",
                r"Between them the line is on top (at \(x = 0\): \(2 \gt 0\)).",
                r"\(A = \displaystyle\int_{-1}^{2}\left(x + 2 - x^2\right)dx = \left[\dfrac{x^2}{2} + 2x - \dfrac{x^3}{3}\right]_{-1}^{2}\).",
                r"\(= \left(2 + 4 - \frac83\right) - \left(\frac12 - 2 + \frac13\right) = \frac{10}{3} + \frac76\)."],
               r"\(\dfrac92\)"),
            pq(r"Find the total area between \(y = x^3\) and \(y = x\).",
               [r"They cross where \(x^3 = x\): \(x = -1, 0, 1\).",
                r"On \([0, 1]\) the line is on top. On \([-1, 0]\) the cubic is on top. By symmetry the two regions have the same area.",
                r"\(A = 2\displaystyle\int_0^1\left(x - x^3\right)dx = 2\left[\dfrac{x^2}{2} - \dfrac{x^4}{4}\right]_0^1 = 2\left(\frac12 - \frac14\right)\)."],
               r"\(\dfrac12\)"),
            pq(r"Find the area between \(y = e^x\) and \(y = x\) on \([0, 1]\).",
               [r"\(e^x \gt x\) on the whole interval, so \(e^x\) is the top curve.",
                r"\(A = \displaystyle\int_0^1\left(e^x - x\right)dx = \left[e^x - \dfrac{x^2}{2}\right]_0^1 = \left(e - \frac12\right) - 1\)."],
               r"\(e - \frac32 \approx 1.22\)"),
            pq(r"Find the area between \(x = y^2\) and the line \(x = 4\) by integrating in \(y\).",
               [r"They cross where \(y^2 = 4\): \(y = -2\) and \(y = 2\).",
                r"The line \(x = 4\) is on the right, and the parabola \(x = y^2\) is on the left.",
                r"\(A = \displaystyle\int_{-2}^{2}\left(4 - y^2\right)dy = \left[4y - \dfrac{y^3}{3}\right]_{-2}^{2} = \left(8 - \frac83\right) - \left(-8 + \frac83\right)\)."],
               r"\(\dfrac{32}{3}\)"),
        ]),
        pset("Average value of a function", "average-value", [
            pq(r"Find the average value of \(f(x) = 3x^2 + 1\) on \([0, 2]\).",
               [r"\(f_{\text{avg}} = \dfrac{1}{2 - 0}\displaystyle\int_0^2\left(3x^2 + 1\right)dx\).",
                r"\(= \frac12\big[x^3 + x\big]_0^2 = \frac12(10)\)."],
               r"\(5\)"),
            pq(r"Find the average value of \(f(x) = \sqrt{x}\) on \([0, 4]\), and the \(c\) where \(f(c)\) equals it.",
               [r"\(f_{\text{avg}} = \frac14\displaystyle\int_0^4 x^{1/2}\,dx = \frac14\left[\frac23 x^{3/2}\right]_0^4 = \frac14 \cdot \frac23 \cdot 8 = \frac43\).",
                r"Solve \(\sqrt{c} = \frac43\) by squaring."],
               r"The average value is \(\frac43\), reached at \(c = \frac{16}{9}\)."),
            pq(r"Find the average value of \(f(x) = \cos x\) on \(\left[0, \frac\pi2\right]\).",
               [r"\(f_{\text{avg}} = \dfrac{1}{\pi/2}\displaystyle\int_0^{\pi/2}\cos x\,dx = \dfrac2\pi\big[\sin x\big]_0^{\pi/2}\).",
                r"\(\sin\frac\pi2 - \sin 0 = 1\)."],
               r"\(\dfrac2\pi \approx 0.64\)"),
            pq(r"A car's velocity is \(v(t) = 3t^2 + 2t\) m/s for \(0 \le t \le 4\) s. Find its average velocity.",
               [r"\(v_{\text{avg}} = \frac14\displaystyle\int_0^4\left(3t^2 + 2t\right)dt = \frac14\big[t^3 + t^2\big]_0^4\).",
                r"\(= \frac14(64 + 16)\)."],
               r"\(20\) m/s"),
        ]),
    ],

    # ======================= WEEK 10: DIFFERENTIAL EQUATIONS =======================
    10: [
        pset("Introduction to differential equations", "de-intro", [
            pq(r"State the order of each equation: \(y'' - 3xy' + y = e^x\), and \((y')^3 + y = x\).",
               [r"The order is the highest derivative that appears, not the highest power.",
                r"The first equation contains \(y''\). The second contains only \(y'\) (cubed, but still a first derivative)."],
               r"Second order, and first order"),
            pq(r"Check that \(y = e^{2x} + 3\) is a solution of \(y' - 2y = -6\).",
               [r"Differentiate: \(y' = 2e^{2x}\).",
                r"Plug into the left side: \(2e^{2x} - 2(e^{2x} + 3) = 2e^{2x} - 2e^{2x} - 6\)."],
               r"The left side equals \(-6\), so yes, it is a solution."),
            pq(r"Check that \(y = x^2 + \dfrac1x\) is a solution of \(xy' + y = 3x^2\).",
               [r"Differentiate: \(y' = 2x - \dfrac{1}{x^2}\).",
                r"\(xy' = 2x^2 - \dfrac1x\).",
                r"Add \(y\): \(2x^2 - \dfrac1x + x^2 + \dfrac1x\)."],
               r"The left side equals \(3x^2\), so yes, it is a solution."),
            pq(r"Solve \(y' = 6x^2 - 4\) with \(y(1) = 3\).",
               [r"Integrate both sides: \(y = 2x^3 - 4x + C\).",
                r"Use \(y(1) = 3\): \(2 - 4 + C = 3\), so \(C = 5\)."],
               r"\(y = 2x^3 - 4x + 5\)"),
            pq(r"Solve \(y'' = 12x\) with \(y(0) = 1\) and \(y'(0) = 2\).",
               [r"Integrate once: \(y' = 6x^2 + C_1\). \(y'(0) = 2\) gives \(C_1 = 2\).",
                r"Integrate again: \(y = 2x^3 + 2x + C_2\). \(y(0) = 1\) gives \(C_2 = 1\)."],
               r"\(y = 2x^3 + 2x + 1\)"),
        ]),
        pset("Separable differential equations", "separable-de", [
            pq(r"Solve \(\dfrac{dy}{dx} = \dfrac{x}{y}\) with \(y(0) = 3\).",
               [r"Separate the variables: \(y\,dy = x\,dx\).",
                r"Integrate both sides: \(\dfrac{y^2}{2} = \dfrac{x^2}{2} + C\), so \(y^2 = x^2 + K\).",
                r"Use \(y(0) = 3\): \(K = 9\). Take the positive root because \(y(0)\) is positive."],
               r"\(y = \sqrt{x^2 + 9}\)"),
            pq(r"Solve \(\dfrac{dy}{dx} = 2xy^2\) with \(y(0) = 1\).",
               [r"Separate: \(\dfrac{dy}{y^2} = 2x\,dx\).",
                r"Integrate: \(-\dfrac1y = x^2 + C\).",
                r"Use \(y(0) = 1\): \(-1 = C\). So \(-\dfrac1y = x^2 - 1\)."],
               r"\(y = \dfrac{1}{1 - x^2}\)"),
            pq(r"Solve \(\dfrac{dy}{dx} = e^{x - y}\) with \(y(0) = \ln 2\).",
               [r"Split the exponential: \(e^{x-y} = e^x e^{-y}\). Separate: \(e^y\,dy = e^x\,dx\).",
                r"Integrate: \(e^y = e^x + C\).",
                r"Use \(y(0) = \ln 2\): \(2 = 1 + C\), so \(C = 1\). Then take \(\ln\) of both sides."],
               r"\(y = \ln(e^x + 1)\)"),
            pq(r"A culture of 500 bacteria grows to 2000 in 6 hours. Assuming \(P = P_0e^{kt}\), find \(k\) and the population after 9 hours.",
               [r"\(2000 = 500e^{6k}\), so \(e^{6k} = 4\) and \(k = \dfrac{\ln 4}{6} \approx 0.231\) per hour.",
                r"\(P(9) = 500e^{9k} = 500\left(e^{6k}\right)^{1.5} = 500 \cdot 4^{1.5} = 500 \cdot 8\)."],
               r"\(k = \dfrac{\ln 4}{6} \approx 0.231\), and \(P(9) = 4000\) bacteria"),
            pq(r"A substance has a half-life of 30 years. How long until only 10% of it is left?",
               [r"Decay model: \(y = y_0e^{kt}\). Half-life: \(\frac12 = e^{30k}\), so \(k = -\dfrac{\ln 2}{30}\).",
                r"Solve \(0.1 = e^{kt}\): \(t = \dfrac{\ln 0.1}{k} = \dfrac{30\ln 10}{\ln 2}\)."],
               r"About 99.7 years"),
            pq(r"Coffee at 90°C is left in a 20°C room and is at 70°C after 5 minutes. Use Newton's law of cooling to find its temperature after 10 minutes.",
               [r"\(T = T_s + (T_0 - T_s)e^{kt} = 20 + 70e^{kt}\).",
                r"At \(t = 5\): \(70 = 20 + 70e^{5k}\), so \(e^{5k} = \frac57\).",
                r"At \(t = 10\): \(e^{10k} = \left(e^{5k}\right)^2 = \frac{25}{49}\), so \(T = 20 + 70 \cdot \frac{25}{49}\)."],
               r"About 55.7°C"),
        ]),
        pset("Linear second-order differential equations", "second-order-linear", [
            pq(r"Solve \(y'' - y' - 6y = 0\).",
               [r"Characteristic equation: \(r^2 - r - 6 = 0\).",
                r"Factor: \((r - 3)(r + 2) = 0\), so \(r = 3\) and \(r = -2\) (two different real roots)."],
               r"\(y = C_1e^{3x} + C_2e^{-2x}\)"),
            pq(r"Solve \(y'' - 4y' + 4y = 0\) with \(y(0) = 1\) and \(y'(0) = 5\).",
               [r"Characteristic equation: \(r^2 - 4r + 4 = (r - 2)^2 = 0\), a repeated root \(r = 2\).",
                r"General solution: \(y = (C_1 + C_2x)e^{2x}\). \(y(0) = 1\) gives \(C_1 = 1\).",
                r"\(y' = C_2e^{2x} + 2(C_1 + C_2x)e^{2x}\), so \(y'(0) = C_2 + 2 = 5\) and \(C_2 = 3\)."],
               r"\(y = (1 + 3x)e^{2x}\)"),
            pq(r"Solve \(y'' + 4y' + 13y = 0\).",
               [r"Characteristic equation: \(r^2 + 4r + 13 = 0\).",
                r"Quadratic formula: \(r = \dfrac{-4 \pm \sqrt{16 - 52}}{2} = \dfrac{-4 \pm 6i}{2} = -2 \pm 3i\).",
                r"Complex roots \(\alpha \pm \beta i\) with \(\alpha = -2\) and \(\beta = 3\)."],
               r"\(y = e^{-2x}\big(C_1\cos 3x + C_2\sin 3x\big)\)"),
            pq(r"Solve \(y'' + 9y = 0\) with \(y(0) = 2\) and \(y'(0) = 3\).",
               [r"Characteristic equation: \(r^2 + 9 = 0\), so \(r = \pm 3i\).",
                r"General solution: \(y = C_1\cos 3x + C_2\sin 3x\). \(y(0) = 2\) gives \(C_1 = 2\).",
                r"\(y' = -3C_1\sin 3x + 3C_2\cos 3x\), so \(y'(0) = 3C_2 = 3\) and \(C_2 = 1\)."],
               r"\(y = 2\cos 3x + \sin 3x\)"),
        ]),
    ],

    # ====== WEEK 11: DIRECTION FIELDS, EULER'S METHOD & MULTIVARIABLE FUNCTIONS ======
    11: [
        pset("Direction fields", "direction-fields", [
            pq(r"For \(y' = x + y\), find the slope of the direction field at \((0, 0)\), \((1, 1)\), \((-1, 2)\) and \((2, -2)\).",
               [r"The slope at a point is the right side of the equation with that point plugged in.",
                r"\(0 + 0\), \(1 + 1\), \(-1 + 2\) and \(2 + (-2)\)."],
               r"\(0\), \(2\), \(1\) and \(0\)"),
            pq(r"For \(y' = x + y\), find the isoclines for slope 0 and slope 1.",
               [r"An isocline is the set of points where the slope equals a chosen constant \(c\): \(x + y = c\).",
                r"Slope 0: \(x + y = 0\). Slope 1: \(x + y = 1\)."],
               r"The lines \(y = -x\) and \(y = 1 - x\)"),
            pq(r"In the direction field of \(y' = x^2 - y\), where are the segments horizontal? Is the slope at \((1, 3)\) positive or negative?",
               [r"Horizontal means slope 0: \(x^2 - y = 0\).",
                r"At \((1, 3)\): \(1 - 3 = -2\)."],
               r"Horizontal along the parabola \(y = x^2\). The slope at \((1, 3)\) is \(-2\), which is negative."),
            pq(r"Find the equilibrium solutions of \(y' = y(3 - y)\) and say whether each is stable. What happens to the solution with \(y(0) = 1\) as \(x \to \infty\)?",
               [r"Equilibria are where \(y' = 0\): \(y = 0\) and \(y = 3\).",
                r"Sign of \(y'\): negative for \(y \lt 0\), positive for \(0 \lt y \lt 3\), negative for \(y \gt 3\).",
                r"Near \(y = 3\), solutions below rise and solutions above fall, so they move toward it. Near \(y = 0\) they move away.",
                r"A solution starting at \(y = 1\) is between 0 and 3, so it rises toward 3."],
               r"\(y = 0\) is unstable and \(y = 3\) is stable. The solution with \(y(0) = 1\) approaches 3."),
            pq(r"Find the equilibrium solutions of \(y' = (y - 1)(y + 2)\) and classify their stability.",
               [r"Equilibria: \(y = 1\) and \(y = -2\).",
                r"Sign of \(y'\): positive for \(y \gt 1\), negative for \(-2 \lt y \lt 1\), positive for \(y \lt -2\).",
                r"Around \(y = -2\): solutions below rise and solutions above fall, so they approach it. Around \(y = 1\): solutions above rise and solutions below fall, so they leave."],
               r"\(y = -2\) is stable and \(y = 1\) is unstable"),
        ]),
        pset("Euler's method", "eulers-method", [
            pq(r"Use Euler's method with \(h = 0.5\) to estimate \(y(1)\) for \(y' = x - y\), \(y(0) = 1\).",
               [r"Start at \((0, 1)\). Slope: \(0 - 1 = -1\). Step: \(y_1 = 1 + 0.5(-1) = 0.5\), at \(x = 0.5\).",
                r"At \((0.5, 0.5)\). Slope: \(0.5 - 0.5 = 0\). Step: \(y_2 = 0.5 + 0.5(0) = 0.5\), at \(x = 1\)."],
               r"\(y(1) \approx 0.5\)"),
            pq(r"Use Euler's method with \(h = 0.1\) to estimate \(y(1.2)\) for \(y' = xy\), \(y(1) = 2\).",
               [r"Start at \((1, 2)\). Slope: \(1 \cdot 2 = 2\). Step: \(y_1 = 2 + 0.1(2) = 2.2\), at \(x = 1.1\).",
                r"At \((1.1, 2.2)\). Slope: \(1.1 \cdot 2.2 = 2.42\). Step: \(y_2 = 2.2 + 0.1(2.42)\), at \(x = 1.2\)."],
               r"\(y(1.2) \approx 2.442\)"),
            pq(r"Use Euler's method with \(h = 0.25\) to estimate \(y(1)\) for \(y' = y\), \(y(0) = 1\). The exact answer is \(e\). Is the estimate too high or too low, and why?",
               [r"Each step multiplies \(y\) by \(1 + h\): \(y_{n+1} = y_n + 0.25y_n = 1.25y_n\).",
                r"Four steps reach \(x = 1\): \(y_4 = 1.25^4 \approx 2.441\).",
                r"The true solution \(y = e^x\) curves upward (concave up), so each tangent-line step falls below it."],
               r"\(y(1) \approx 2.441\), lower than \(e \approx 2.718\). A smaller step size would get closer."),
        ]),
        pset("Functions of several variables", "multivariable-intro", [
            pq(r"For \(f(x, y) = x^2y - 3y\), find \(f(2, -1)\) and \(f(0, 5)\).",
               [r"\(f(2, -1) = (4)(-1) - 3(-1) = -4 + 3\).",
                r"\(f(0, 5) = 0 - 15\)."],
               r"\(-1\) and \(-15\)"),
            pq(r"Find the domain and range of \(f(x, y) = \sqrt{16 - x^2 - y^2}\).",
               [r"The square root needs \(16 - x^2 - y^2 \ge 0\), which is \(x^2 + y^2 \le 16\).",
                r"Inside that disk, \(16 - x^2 - y^2\) runs from 0 (on the edge) up to 16 (at the origin), so its root runs from 0 to 4."],
               r"Domain: the disk \(x^2 + y^2 \le 16\) (radius 4, edge included). Range: \([0, 4]\)."),
            pq(r"Find and describe the domain of \(f(x, y) = \ln(y - x^2)\).",
               [r"A logarithm needs a positive input: \(y - x^2 \gt 0\).",
                r"That is \(y \gt x^2\): the points above the parabola \(y = x^2\), not including the parabola itself."],
               r"All points with \(y \gt x^2\), the region strictly above the parabola"),
            pq(r"Describe the level curves of \(f(x, y) = 4x^2 + y^2\) for \(k = 4\) and \(k = 16\).",
               [r"Set \(f(x, y) = k\). For \(k = 4\): \(4x^2 + y^2 = 4\), or \(x^2 + \dfrac{y^2}{4} = 1\).",
                r"For \(k = 16\): \(4x^2 + y^2 = 16\), or \(\dfrac{x^2}{4} + \dfrac{y^2}{16} = 1\).",
                r"Both are ellipses centred at the origin, twice as tall as they are wide."],
               r"Ellipses: one through \((\pm 1, 0)\) and \((0, \pm 2)\), the other through \((\pm 2, 0)\) and \((0, \pm 4)\)"),
            pq(r"Find \(\displaystyle\lim_{(x,y)\to(1,2)}\frac{x^2y + 3}{x + y}\).",
               [r"The function is a quotient of polynomials and the bottom is not zero at \((1, 2)\), so it is continuous there.",
                r"Plug in: \(\dfrac{(1)(2) + 3}{1 + 2}\)."],
               r"\(\dfrac53\)"),
            pq(r"Show that \(\displaystyle\lim_{(x,y)\to(0,0)}\frac{x^2 - y^2}{x^2 + y^2}\) does not exist.",
               [r"Approach along the \(x\)-axis (\(y = 0\)): \(\dfrac{x^2}{x^2} = 1\).",
                r"Approach along the \(y\)-axis (\(x = 0\)): \(\dfrac{-y^2}{y^2} = -1\).",
                r"Two paths give two different values."],
               r"The limit does not exist, by the two-path test."),
        ]),
    ],

    # ================= WEEK 12: PARTIAL DERIVATIVES & TANGENT PLANES =================
    12: [
        pset("Partial derivatives", "partial-derivatives", [
            pq(r"Find \(f_x\) and \(f_y\) for \(f(x, y) = 3x^2y - 5xy^3 + 2x\).",
               [r"For \(f_x\), treat \(y\) as a constant: \(6xy - 5y^3 + 2\).",
                r"For \(f_y\), treat \(x\) as a constant: \(3x^2 - 15xy^2 + 0\)."],
               r"\(f_x = 6xy - 5y^3 + 2\) and \(f_y = 3x^2 - 15xy^2\)"),
            pq(r"Find \(f_x\) and \(f_y\) for \(f(x, y) = xe^{xy}\).",
               [r"\(f_x\) needs the product rule, because \(x\) appears twice: \(e^{xy} + x \cdot ye^{xy}\).",
                r"\(f_y\): the \(x\) in front is a constant, and the chain rule on \(e^{xy}\) multiplies by \(x\)."],
               r"\(f_x = e^{xy}(1 + xy)\) and \(f_y = x^2e^{xy}\)"),
            pq(r"Find \(f_x\) and \(f_y\) for \(f(x, y) = \ln(x^2 + y^2)\).",
               [r"Chain rule: \(\dfrac{1}{x^2 + y^2}\) times the derivative of the inside.",
                r"The inside has \(x\)-derivative \(2x\) and \(y\)-derivative \(2y\)."],
               r"\(f_x = \dfrac{2x}{x^2 + y^2}\) and \(f_y = \dfrac{2y}{x^2 + y^2}\)"),
            pq(r"For \(f(x, y) = x^3y + y^2\), find \(f_x(1, 2)\) and \(f_y(1, 2)\).",
               [r"\(f_x = 3x^2y\), so \(f_x(1, 2) = 3(1)(2)\).",
                r"\(f_y = x^3 + 2y\), so \(f_y(1, 2) = 1 + 4\)."],
               r"\(f_x(1, 2) = 6\) and \(f_y(1, 2) = 5\)"),
            pq(r"Find all the second partial derivatives of \(f(x, y) = x^4y^2 - 2xy^3\).",
               [r"First partials: \(f_x = 4x^3y^2 - 2y^3\) and \(f_y = 2x^4y - 6xy^2\).",
                r"\(f_{xx} = 12x^2y^2\) and \(f_{yy} = 2x^4 - 12xy\).",
                r"\(f_{xy}\) is the \(y\)-derivative of \(f_x\): \(8x^3y - 6y^2\). \(f_{yx}\) is the \(x\)-derivative of \(f_y\): also \(8x^3y - 6y^2\)."],
               r"\(f_{xx} = 12x^2y^2\), \(f_{yy} = 2x^4 - 12xy\), \(f_{xy} = f_{yx} = 8x^3y - 6y^2\)"),
            pq(r"Check Clairaut's theorem for \(f(x, y) = x\sin y + ye^x\).",
               [r"\(f_x = \sin y + ye^x\), so \(f_{xy} = \cos y + e^x\).",
                r"\(f_y = x\cos y + e^x\), so \(f_{yx} = \cos y + e^x\)."],
               r"\(f_{xy} = f_{yx} = \cos y + e^x\), as the theorem says"),
            pq(r"Use the limit definition to find \(f_x\) for \(f(x, y) = x^2y\).",
               [r"\(f_x = \displaystyle\lim_{h\to 0}\frac{(x+h)^2y - x^2y}{h}\).",
                r"Expand the top: \(x^2y + 2xhy + h^2y - x^2y = 2xhy + h^2y\).",
                r"Divide by \(h\): \(2xy + hy\). Let \(h \to 0\)."],
               r"\(f_x = 2xy\)"),
            pq(r"The temperature on a metal plate is \(T(x, y) = 100 - x^2 - 2y^2\) degrees. Find \(T_x(3, 1)\) and \(T_y(3, 1)\), and say what \(T_x(3, 1)\) means.",
               [r"\(T_x = -2x\), so \(T_x(3, 1) = -6\).",
                r"\(T_y = -4y\), so \(T_y(3, 1) = -4\)."],
               r"\(T_x(3, 1) = -6\) and \(T_y(3, 1) = -4\). At \((3, 1)\), the temperature drops about 6 degrees per unit moved in the \(x\)-direction."),
            pq(r"Find all three first partial derivatives of \(f(x, y, z) = xy^2z^3\).",
               [r"For each one, treat the other two variables as constants.",
                r"\(f_x = y^2z^3\), \(f_y = x \cdot 2y \cdot z^3\), \(f_z = xy^2 \cdot 3z^2\)."],
               r"\(f_x = y^2z^3\), \(f_y = 2xyz^3\), \(f_z = 3xy^2z^2\)"),
        ]),
        pset("Tangent planes and linear approximation", "tangent-planes", [
            pq(r"Find the tangent plane to \(z = 2x^2 + y^2\) at \((1, 1, 3)\).",
               [r"\(f_x = 4x\) and \(f_y = 2y\), so \(f_x(1, 1) = 4\) and \(f_y(1, 1) = 2\).",
                r"Tangent plane: \(z - 3 = 4(x - 1) + 2(y - 1)\).",
                r"Expand: \(z = 4x - 4 + 2y - 2 + 3\)."],
               r"\(z = 4x + 2y - 3\)"),
            pq(r"Find the tangent plane to \(z = xy^2\) at the point where \((x, y) = (2, 1)\).",
               [r"The height: \(z_0 = 2(1)^2 = 2\).",
                r"\(f_x = y^2 = 1\) and \(f_y = 2xy = 4\) at \((2, 1)\).",
                r"Tangent plane: \(z - 2 = 1(x - 2) + 4(y - 1)\)."],
               r"\(z = x + 4y - 4\)"),
            pq(r"Find the tangent plane to \(z = \sqrt{x^2 + y^2}\) at the point where \((x, y) = (3, 4)\).",
               [r"The height: \(z_0 = \sqrt{9 + 16} = 5\).",
                r"\(f_x = \dfrac{x}{\sqrt{x^2 + y^2}} = \dfrac35\) and \(f_y = \dfrac{y}{\sqrt{x^2 + y^2}} = \dfrac45\) at \((3, 4)\).",
                r"Tangent plane: \(z - 5 = \frac35(x - 3) + \frac45(y - 4)\). The constants add up to \(5 - \frac95 - \frac{16}{5} = 0\)."],
               r"\(z = \frac35 x + \frac45 y\)"),
            pq(r"Use the linearization of \(f(x, y) = \sqrt{x^2 + y^2}\) at \((3, 4)\) to estimate \(f(3.1, 3.9)\).",
               [r"From the tangent plane at \((3, 4)\): \(L(x, y) = \frac35 x + \frac45 y\).",
                r"\(L(3.1, 3.9) = 0.6(3.1) + 0.8(3.9) = 1.86 + 3.12\)."],
               r"\(f(3.1, 3.9) \approx 4.98\) (the true value is about 4.982)"),
            pq(r"Linearize \(f(x, y) = x^2y\) at \((2, 3)\) and use it to estimate \(f(2.05, 2.9)\).",
               [r"\(f(2, 3) = 12\), \(f_x = 2xy = 12\) and \(f_y = x^2 = 4\) at \((2, 3)\).",
                r"\(L(x, y) = 12 + 12(x - 2) + 4(y - 3)\).",
                r"\(L(2.05, 2.9) = 12 + 12(0.05) + 4(-0.1) = 12 + 0.6 - 0.4\)."],
               r"\(f(2.05, 2.9) \approx 12.2\) (the true value is about 12.19)"),
            pq(r"A cylinder has volume \(V = \pi r^2h\). Use the total differential to estimate the change in volume when \(r\) grows from 5 to 5.1 cm and \(h\) shrinks from 10 to 9.8 cm.",
               [r"\(dV = V_r\,dr + V_h\,dh = 2\pi rh\,dr + \pi r^2\,dh\).",
                r"Plug in \(r = 5\), \(h = 10\), \(dr = 0.1\), \(dh = -0.2\): \(2\pi(5)(10)(0.1) + \pi(25)(-0.2)\).",
                r"\(= 10\pi - 5\pi\)."],
               r"\(dV = 5\pi \approx 15.7\) cm³, so the volume grows by about 15.7 cm³"),
        ]),
    ],
}
