"""How people search for each lesson's topic.

Drawn from Google's search suggestions for every topic (keywords.csv lists them, with what the
searcher wants and whether a lesson page can answer it). People mostly add "formula", "examples",
"practice problems", "rules" or "steps" to a topic's name, and often use a different name from
the lesson's own.

SEARCH[lesson id] = (title shown in search results, other names people use for the topic)
"""

SEARCH = {
    "review-factoring": ("Factoring Polynomials: Methods, Examples & Practice", []),
    "review-expanding": ("Expanding Brackets & FOIL: Examples and Practice", ["the FOIL method", "multiplying binomials"]),
    "review-simplifying": ("Simplifying Rational Expressions & Exponent Rules", []),
    "review-solving": ("Solving Quadratic Equations & Inequalities: Examples", []),
    "review-graphing": ("Graphing Functions & Transformations: Rules, Examples", []),
    "limits": ("Limits Explained: Graphs, Tables & One-Sided Limits", []),
    "limits-algebraic": ("Evaluating Limits Algebraically: Methods & Examples", ["finding limits", "limit laws"]),
    "limits-infinity": ("Limits at Infinity & Infinite Limits: Rules, Examples", []),
    "epsilon-delta": ("Epsilon-Delta Proofs: Definition, Examples & Practice",
                      ["delta-epsilon proofs", "the precise (formal) definition of a limit"]),
    "continuity": ("Continuity & Discontinuities: Definition, Types, Examples", []),
    "derivative-definition": ("Limit Definition of the Derivative: Formula & Examples",
                              ["differentiation from first principles", "the difference quotient"]),
    "derivative-rules": ("Power Rule & Derivative Rules: Formula, Examples", []),
    "product-rule": ("Product Rule: Formula, Examples & Practice Problems", []),
    "inverse-functions": ("Inverse Functions & Inverse Trig Derivatives: Examples", []),
    "exponential-functions": ("Exponential Functions: Growth, Decay, Rules & Examples", []),
    "trig-functions": ("Derivatives of Trig Functions & the Unit Circle", []),
    "chain-rule": ("Chain Rule: Formula, Examples & Practice Problems", []),
    "quotient-rule": ("Quotient Rule: Formula, Examples & Practice Problems", []),
    "implicit": ("Implicit Differentiation: Steps, Examples & Practice", []),
    "log-functions": ("Logarithm Rules & Natural Log (ln): Laws and Examples", ["log laws", "properties of logarithms"]),
    "exp-derivatives": ("Derivative of e^x and a^x: Rules, Examples & Practice", []),
    "exp-log-derivatives": ("Derivative of ln x & Logarithmic Differentiation: Examples", []),
    "critical-points": ("Critical Points & First Derivative Test: Examples", ["critical numbers"]),
    "concavity": ("Concavity, Inflection Points & Second Derivative Test", []),
    "curve-sketching": ("Curve Sketching: Steps, Examples & Practice Problems", []),
    "ivt": ("Intermediate Value Theorem (IVT): Examples & Practice", ["IVT"]),
    "mvt": ("Mean Value Theorem & Rolle's Theorem: Examples", ["MVT"]),
    "newtons-method": ("Newton's Method: Formula, Examples & Practice", ["the Newton-Raphson method"]),
    "optimization": ("Optimization Problems in Calculus: Steps & Examples", ["max and min problems"]),
    "antiderivatives": ("Antiderivatives & Indefinite Integrals: Rules, Examples", []),
    "area-under-curves": ("Riemann Sums & Area Under a Curve: Formula, Examples", []),
    "ftc": ("Fundamental Theorem of Calculus: Parts 1 & 2, Examples", ["FTC"]),
    "u-sub": ("U-Substitution: Steps, Examples & Practice Problems", ["u-substitution", "u-sub", "change of variables"]),
    "area-between": ("Area Between Curves: Formula, Examples & Practice", []),
    "average-value": ("Average Value of a Function: Formula & Examples", []),
    "de-intro": ("Introduction to Differential Equations: Basics & Examples", []),
    "separable-de": ("Separable Differential Equations: Steps & Examples", ["separation of variables"]),
    "second-order-linear": ("Second-Order Linear Differential Equations: Examples", []),
    "direction-fields": ("Slope Fields (Direction Fields): How to Draw, Examples", ["slope fields"]),
    "eulers-method": ("Euler's Method: Formula, Examples & Practice Problems", []),
    "multivariable-intro": ("Functions of Several Variables & Level Curves", ["multivariable functions", "contour maps"]),
    "partial-derivatives": ("Partial Derivatives: Rules, Examples & Practice", []),
    "tangent-planes": ("Tangent Planes & Linear Approximation: Formula, Examples", ["linearization"]),
    "related-rates": ("Related Rates: Steps, Examples & Practice Problems", []),
    "lhopital": ("L'Hôpital's Rule: When to Use It, Examples & Practice", ["L'Hopital's rule", "L'Hospital's rule"]),
    "ibp": ("Integration by Parts: Formula, Examples & Practice", []),
    "trig-integrals": ("Trig Substitution & Trig Integrals: Rules, Examples", []),
    "partial-fractions": ("Partial Fractions: Decomposition Steps & Examples", ["partial fraction decomposition"]),
    "improper-integrals": ("Improper Integrals: Convergence, Examples & Practice", []),
    "series-tests": ("Series Convergence Tests: Ratio, Comparison & More", []),
    "taylor": ("Taylor, Maclaurin & Power Series: Formula, Examples", []),
    "parametric-polar": ("Parametric Equations & Polar Coordinates in Calculus", []),
    "vectors": ("Vectors, Dot Product & Cross Product: Formulas, Examples", []),
    "lines-planes": ("Equations of Lines & Planes in 3D: Formulas, Examples", []),
    "partial-gradient": ("Gradient & Directional Derivatives: Formula, Examples", []),
    "lagrange": ("Lagrange Multipliers: Method, Examples & Practice", []),
    "double-triple": ("Double & Triple Integrals: How to Set Up, Examples", []),
    "cyl-sph": ("Cylindrical & Spherical Coordinates: Formulas, Examples", []),
    "vector-calc": ("Line Integrals, Green's, Stokes' & Divergence Theorems", []),
}
