r"""Visual lesson for "5 The Chain Rule and Implicit Differentiation" (MATH 29599).

Six episodes, one subtopic each, following the notes' own examples and homework.
"say" is spoken by text-to-speech, so it is plain English. LaTeX fields can use the
highlight macros \hl{} (cyan), \pk{} (pink), \yl{} (yellow) and \gr{} (green).
"""
from ._build import (beats, cards, compare, episode, equation, expert, graph, layers, mc,
                     pause, title)
from .chain_rule_2 import EPISODE_4, EPISODE_5, EPISODE_6
from .chain_rule_read import ARTICLES

# ======================================================================
# Episode 1: The Chain Rule
# ======================================================================
EPISODE_1 = episode(
    "Functions in layers: the Chain Rule",
    "How to differentiate (2x+1)^16 without expanding 16 brackets.",
    [
        title("🧅", "Functions have layers", "Episode 1 · The Chain Rule",
              "POV: you just mastered the power rule, and then your prof drops 2x plus 1, all to the 16th power.",
              "Expanding that would take forever. Today you learn the shortcut every calculus student needs: the chain rule."),
        equation("The problem", [
            r"f(x) = (2x+1)^{16}",
            r"\underbrace{(2x+1)(2x+1)\cdots(2x+1)}_{16\text{ copies}}",
            r"\text{Expand all that? } \pk{\text{No thanks.}}",
        ],
            "Here's our function: f of x equals 2x plus 1, to the 16th.",
            "One option is to multiply it out. That's 16 copies of the same bracket.",
            "That would take pages. The power rule alone can't handle it, because the thing being raised to a power isn't just x."),
        layers("See the layers", [
            ("Outside", r"(\,\square\,)^{16}", r"16(2x+1)^{15}"),
            ("Inside", r"2x+1", r"2"),
        ], r"f'(x) = 16(2x+1)^{15}\cdot 2 = \yl{32(2x+1)^{15}}",
            ("Instead, look at the function like an onion. It has an outside layer and an inside layer.", "build"),
            ("The inside layer is 2x plus 1. The outside layer takes whatever is inside and raises it to the 16th.", "hold"),
            ("Peel the outside first. The derivative of something to the 16th is 16 times that something to the 15th. Leave the inside alone.", "peel"),
            ("Now peel the inside. The derivative of 2x plus 1 is just 2.", "peel"),
            ("Multiply the layers: 16 times 2x plus 1 to the 15th, times 2. That's 32 times 2x plus 1 to the 15th.", "result")),
        equation("Name the layers", [
            r"\text{Inside: }\ \hl{u = g(x)}",
            r"\text{Outside: }\ \pk{y = f(u)}",
            r"\hl{\frac{du}{dx} = g'(x)} \qquad \pk{\frac{dy}{du} = f'(u)}",
        ],
            "To make it official, give the inside layer its own name. Let u equal g of x.",
            "Then the outside layer is y equals f of u. Now each layer is a simple function on its own.",
            "Each layer has its own derivative: d u d x for the inside, and d y d u for the outside."),
        compare("The Chain Rule, two ways",
                ("Leibniz notation", [r"\frac{dy}{dx} = \pk{\frac{dy}{du}}\cdot\hl{\frac{du}{dx}}"]),
                ("Function notation", [r"\big[f(g(x))\big]' = \pk{f'(g(x))}\cdot\hl{g'(x)}"]),
                ("Multiply the layers and you get the chain rule. In Leibniz notation: d y d x equals d y d u times d u d x.", "left"),
                ("It looks like the d u's cancel, like fractions. They aren't really fractions, but it's a great way to remember it.", "hold"),
                ("In function notation: the derivative of f of g of x is f prime of g of x, times g prime of x.", "right"),
                ("Same rule, two outfits. Derivative of the outside with the inside left alone, times the derivative of the inside.", "link")),
        equation("Example 5.1A, all the details", [
            r"\text{Let } \hl{u = 2x+1} \;\Rightarrow\; \frac{du}{dx} = 2",
            r"\text{Then } \pk{f = u^{16}} \;\Rightarrow\; \frac{df}{du} = 16u^{15}",
            r"\frac{df}{dx} = \frac{df}{du}\cdot\frac{du}{dx} = 16u^{15}\cdot 2",
            r"= 32u^{15} = \yl{32(2x+1)^{15}}",
        ],
            "Here's Example 5.1A written the way your prof wants it, with every substitution detail. Let u equal 2x plus 1, so d u d x equals 2.",
            "Then f equals u to the 16th, so d f d u equals 16 u to the 15th.",
            "Chain rule: d f d u times d u d x. That's 16 u to the 15th, times 2.",
            "Simplify to 32 u to the 15th, then swap u back out. The answer is 32 times 2x plus 1, to the 15th."),
        cards("Why do we multiply?", [
            ("⚙️", "Gears", r"Gear B spins 3× as fast as gear A. Gear C spins 2× as fast as gear B."),
            ("✖️", "Rates stack", r"So gear C spins \(3 \times 2 = 6\)× as fast as gear A."),
            ("🔗", "That's the chain rule", r"\(\frac{dy}{dx} = \frac{dy}{du}\cdot\frac{du}{dx}\): rate of the outside × rate of the inside."),
        ],
            "Why multiply? Think about gears. Gear B spins 3 times as fast as gear A, and gear C spins twice as fast as gear B.",
            "Then gear C spins 3 times 2, which is 6 times as fast as gear A. Rates of change stack by multiplying.",
            "That's exactly the chain rule. How fast y changes with x equals how fast y changes with u, times how fast u changes with x."),
        graph("Check it on a graph", [{"fn": "(2*x+1)^3", "label": r"\(y=(2x+1)^3\)"}],
              {"xmin": -1.1, "xmax": 0.7, "ymin": -2.5, "ymax": 6},
              ("Let's test the chain rule on a graph. Here's 2x plus 1, cubed.", "draw"),
              ("The chain rule says its derivative is 3 times 2x plus 1 squared, times 2. At x equals 0, that's 6.", "hold"),
              ("And look: the tangent line at x equals 0 has a slope of exactly 6. The chain rule checks out.", "tangent:0"),
              ("Watch the slope change as we slide along the curve. Flat at x equals negative one half, then steeper and steeper.", "trace")),
        equation("Example 5.1B", [
            r"g(x) = 4(x^2 - x + 2)^{12}",
            r"\hl{u = x^2 - x + 2} \;\Rightarrow\; \frac{du}{dx} = 2x - 1",
            r"\pk{g = 4u^{12}} \;\Rightarrow\; \frac{dg}{du} = 48u^{11}",
            r"\frac{dg}{dx} = 48u^{11}\cdot(2x-1)",
            r"= \yl{48(2x-1)(x^2-x+2)^{11}}",
        ],
            "Example 5.1B: g of x equals 4 times x squared minus x plus 2, all to the 12th.",
            "The inside is x squared minus x plus 2, so its derivative is 2x minus 1.",
            "The outside is 4 u to the 12th. Its derivative is 48 u to the 11th. The 4 just comes along for the ride.",
            "Multiply: 48 u to the 11th, times 2x minus 1.",
            "Put the inside back in and tidy up: 48 times 2x minus 1, times x squared minus x plus 2 to the 11th."),
        pause(r"\frac{d}{dx}(5x-3)^4 = \;?", r"4(5x-3)^3\cdot 5 = \yl{20(5x-3)^3}",
              "Your turn. Find the derivative of 5x minus 3, to the 4th. Pause the video if you need more time.",
              "Outside: 4 times 5x minus 3, cubed. Inside: 5. Multiply to get 20 times 5x minus 3, cubed. Did you get it?"),
        cards("Recap", [
            ("🧅", "Spot the layers", r"Find the inside \(u\) and what the outside does to it."),
            ("🔪", "Peel the outside", r"Differentiate the outside layer. Leave the inside alone."),
            ("✖️", "Times the inside's derivative", r"\(\frac{dy}{dx} = \frac{dy}{du}\cdot\frac{du}{dx}\)"),
        ],
            "Quick recap. One: spot the layers. What's inside, and what is the outside doing to it?",
            "Two: differentiate the outside layer, and leave the inside alone.",
            "Three: multiply by the derivative of the inside. Now go crush the practice questions."),
    ],
    easy=[
        mc(r"\(\frac{d}{dx}(x+5)^3 =\)", [r"\(3(x+5)^2\)", r"\(3(x+5)^3\)", r"\((x+5)^2\)", r"\(3x^2\)"], 0,
           "Outside: 3 times the inside squared. Inside: x + 5 has derivative 1, so nothing changes."),
        mc(r"In \(y=(4x-1)^7\), the inside layer is:", [r"\(u^7\)", r"\(4x-1\)", r"\(7\)", r"\((4x-1)^7\)"], 1,
           "The inside is whatever gets raised to the 7th: 4x − 1."),
        mc(r"\(\frac{d}{dx}(3x+2)^2 =\)", [r"\(2(3x+2)\)", r"\(3(3x+2)^2\)", r"\(6(3x+2)\)", r"\(18x\)"], 2,
           r"\(2(3x+2)\cdot 3 = 6(3x+2)\). Don't forget the inside's derivative, 3."),
        mc(r"The chain rule in Leibniz notation says \(\frac{dy}{dx} =\)",
           [r"\(\frac{dy}{du}+\frac{du}{dx}\)", r"\(\frac{du}{dy}\cdot\frac{dx}{du}\)", r"\(\frac{dy}{du}\div\frac{du}{dx}\)", r"\(\frac{dy}{du}\cdot\frac{du}{dx}\)"], 3,
           "Multiply the layer derivatives. The du's 'cancel'."),
        mc(r"If \(u = 2x+1\), then \(\frac{du}{dx} =\)", [r"\(2\)", r"\(2x\)", r"\(1\)", r"\(x\)"], 0,
           "The derivative of 2x + 1 is 2."),
    ],
    intermediate=[
        mc(r"\(\frac{d}{dx}(x^2+1)^5 =\)", [r"\(5(x^2+1)^4\)", r"\(10x(x^2+1)^4\)", r"\(10x(x^2+1)^5\)", r"\(5(2x)^4\)"], 1,
           r"\(5(x^2+1)^4\cdot 2x = 10x(x^2+1)^4\)."),
        mc(r"\(\frac{d}{dx}\sqrt{3x+1} =\)", [r"\(\frac{1}{2\sqrt{3x+1}}\)", r"\(\frac{3}{\sqrt{3x+1}}\)", r"\(\frac{3}{2\sqrt{3x+1}}\)", r"\(\frac32\sqrt{3x+1}\)"], 2,
           r"\((3x+1)^{1/2}\to \frac12(3x+1)^{-1/2}\cdot 3\)."),
        mc(r"\(\frac{d}{dx}\,\frac{1}{(2x-5)^3} =\)", [r"\(-\frac{6}{(2x-5)^4}\)", r"\(-\frac{3}{(2x-5)^4}\)", r"\(\frac{6}{(2x-5)^2}\)", r"\(-\frac{6}{(2x-5)^2}\)"], 0,
           r"Rewrite as \((2x-5)^{-3}\): \(-3(2x-5)^{-4}\cdot 2 = -\frac{6}{(2x-5)^4}\)."),
        mc(r"From the homework: \(f(x) = 2(3x+1)^9\). \(f'(x) =\)", [r"\(18(3x+1)^8\)", r"\(54(3x+1)^9\)", r"\(6(3x+1)^8\)", r"\(54(3x+1)^8\)"], 3,
           r"\(\frac{df}{du} = 18u^8\) and \(\frac{du}{dx} = 3\), so \(54(3x+1)^8\)."),
        mc(r"\(\frac{d}{dx}\sin(5x) =\)", [r"\(5\cos(5x)\)", r"\(\cos(5x)\)", r"\(-5\cos(5x)\)", r"\(5\sin(5x)\)"], 0,
           r"Outside: \(\cos(5x)\). Inside: \(5x\) has derivative 5."),
    ],
    advanced=[
        mc(r"Homework #2: \(g(x) = 6\sqrt[3]{1-2x}\). \(g'(x) =\)",
           [r"\(\frac{2}{\sqrt[3]{(1-2x)^2}}\)", r"\(-\frac{4}{\sqrt[3]{(1-2x)^2}}\)", r"\(-4\sqrt[3]{1-2x}\)", r"\(-\frac{12}{\sqrt[3]{(1-2x)^2}}\)"], 1,
           r"\(g = 6u^{1/3}\), so \(\frac{dg}{du} = 2u^{-2/3}\). Times \(\frac{du}{dx} = -2\) gives \(-\frac{4}{\sqrt[3]{(1-2x)^2}}\)."),
        mc(r"\(\frac{d}{dx}e^{x^2-3x} =\)", [r"\(e^{x^2-3x}\)", r"\((2x-3)e^{2x-3}\)", r"\((2x-3)e^{x^2-3x}\)", r"\((x^2-3x)e^{x^2-3x-1}\)"], 2,
           r"The outside \(e^u\) is its own derivative. Times the inside's derivative \(2x-3\)."),
        mc(r"\(h(x) = f(g(x))\), with \(g(2)=5\), \(g'(2)=3\), \(f'(5)=-4\), \(f'(2)=7\). Find \(h'(2)\).", [r"\(21\)", r"\(-4\)", r"\(15\)", r"\(-12\)"], 3,
           r"\(h'(2) = f'(g(2))\cdot g'(2) = f'(5)\cdot 3 = -12\). The \(f'(2)\) is a trap."),
        mc(r"The slope of the tangent to \(y = (x^2-3)^4\) at \(x = 2\) is:", [r"\(16\)", r"\(4\)", r"\(32\)", r"\(8\)"], 0,
           r"\(y' = 4(x^2-3)^3\cdot 2x\). At \(x=2\): \(4(1)^3\cdot 4 = 16\)."),
        mc(r"\(\frac{d}{dx}\cos(x^3) =\)", [r"\(-\sin(3x^2)\)", r"\(-3x^2\sin(x^3)\)", r"\(3x^2\sin(x^3)\)", r"\(-\sin(x^3)\)"], 1,
           r"Outside: \(-\sin(x^3)\). Inside: \(3x^2\)."),
    ],
    expert=[
        expert(r"Find the equation of the tangent line to \(y = (2x-3)^5\) at \(x = 2\).",
               "You need a point and a slope. The point comes from y(2); the slope from y'(2).",
               [r"Point: \(y(2) = (4-3)^5 = 1\), so the point is \((2, 1)\).",
                r"Slope: \(y' = 5(2x-3)^4\cdot 2 = 10(2x-3)^4\), so \(y'(2) = 10\).",
                r"Point-slope form: \(y - 1 = 10(x - 2)\)."],
               r"\(y = 10x - 19\)"),
        expert(r"Find every \(x\) where \(f(x) = (x^2-4x)^3\) has a horizontal tangent line.",
               "Horizontal tangent means f'(x) = 0. A product is zero when any factor is zero.",
               [r"\(f'(x) = 3(x^2-4x)^2(2x-4)\).",
                r"\(3(x^2-4x)^2 = 0\) when \(x(x-4) = 0\): \(x = 0\) or \(x = 4\).",
                r"\(2x - 4 = 0\) when \(x = 2\)."],
               r"\(x = 0,\ 2,\ 4\)"),
        expert(r"\(h(x) = \sqrt{f(x)}\), where \(f(3) = 16\) and \(f'(3) = 8\). Find \(h'(3)\) and explain what it means.",
               r"Treat the square root as the outside layer and f(x) as the inside.",
               [r"\(h = (f(x))^{1/2}\), so \(h'(x) = \frac12(f(x))^{-1/2}\cdot f'(x) = \frac{f'(x)}{2\sqrt{f(x)}}\).",
                r"\(h'(3) = \frac{8}{2\sqrt{16}} = \frac{8}{8} = 1\).",
                r"Meaning: at \(x = 3\), \(h\) increases 1 unit for each unit increase in \(x\)."],
               r"\(h'(3) = 1\)"),
    ],
)

# ======================================================================
# Episode 2: Chain Rule combos (Example 5.1C)
# ======================================================================
EPISODE_2 = episode(
    "Combo moves: Chain Rule + other rules",
    "The chain rule teams up with the sum and product rules. Example 5.1C, step by step.",
    [
        title("🧩", "Combo moves", "Episode 2 · Chain Rule + other rules",
              "Real exam questions almost never use the chain rule alone. It teams up with the sum rule, the power rule, and the product rule.",
              "Today we build combos, just like Example 5.1C."),
        cards("Your toolkit", [
            ("➕", "Sum rule", r"\((f+g)' = f' + g'\)"),
            ("⚡", "Power rule", r"\((x^n)' = nx^{n-1}\)"),
            ("✖️", "Product rule", r"\((fg)' = f'g + fg'\)"),
            ("🔗", "Chain rule", r"\(\big[f(g(x))\big]' = f'(g(x))\,g'(x)\)"),
        ],
            "Here's your toolkit. The sum rule: differentiate each term separately.",
            "The power rule: bring the power down and subtract one.",
            "The product rule: first prime times second, plus first times second prime.",
            "And the chain rule, for anything with layers. Today they all work together."),
        equation("Trap alert: sin³x", [
            r"\sin^3 x = (\sin x)^3",
            r"\text{Inside: } \hl{u = \sin x} \qquad \text{Outside: } \pk{u^3}",
            r"\frac{d}{dx}(\sin x)^3 = \pk{3(\sin x)^2}\cdot\hl{\cos x}",
        ],
            "First, a notation trap. Sine cubed of x means: take sine of x, then cube the answer.",
            "So the inside layer is sine x, and the outside layer is cubing.",
            "Outside derivative: 3 sine squared x. Times the inside derivative, cosine x."),
        equation("Example 5.1C, part 1", [
            r"f(x) = \hl{4x^3} + \pk{\sin^3 x}",
            r"f'(x) = \hl{12x^2} + \frac{d}{dx}(\sin x)^3",
            r"f'(x) = 12x^2 + \yl{3\sin^2 x\cos x}",
        ],
            "Example 5.1C. f of x equals 4 x cubed plus sine cubed x. It's a sum, so differentiate each term separately.",
            "4 x cubed is a plain power rule: 12 x squared. The second term needs the chain rule.",
            "We just did it: 3 sine squared x, times cosine x. Add them up and you're done."),
        equation("Example 5.1C, part 2", [
            r"g(x) = \hl{(3x^2-x)}\,\pk{(4x+1)^3}",
            r"g' = \hl{(6x-1)}(4x+1)^3 + (3x^2-x)\,\pk{\frac{d}{dx}(4x+1)^3}",
            r"\frac{d}{dx}(4x+1)^3 = 3(4x+1)^2\cdot 4 = \pk{12(4x+1)^2}",
            r"g' = (6x-1)(4x+1)^3 + 12(3x^2-x)(4x+1)^2",
        ],
            "Part 2: g of x equals 3x squared minus x, times 4x plus 1 cubed. Two factors multiplied, so the product rule is the main move.",
            "Product rule: derivative of the first times the second, plus the first times the derivative of the second.",
            "The derivative of 4x plus 1 cubed needs the chain rule: 3 times 4x plus 1 squared, times 4. That's 12 times 4x plus 1 squared.",
            "Plug it in. Most profs accept this form, but we can make it much cleaner."),
        equation("Factor it like a pro", [
            r"g' = \yl{(4x+1)^2}\big[(6x-1)(4x+1) + 12(3x^2-x)\big]",
            r"= (4x+1)^2\big[24x^2+2x-1 + 36x^2-12x\big]",
            r"= \yl{(4x+1)^2(60x^2-10x-1)}",
        ],
            "Both terms share 4x plus 1, squared. Pull it out front as a common factor.",
            "Expand inside the brackets. 6x minus 1 times 4x plus 1 is 24 x squared plus 2x minus 1. And 12 times 3x squared minus x is 36 x squared minus 12x.",
            "Combine like terms: 60 x squared minus 10x minus 1. Clean, factored, done."),
        graph("Why factoring pays off", [{"fn": "(3*x^2 - x)*(4*x+1)^3", "label": r"\(g(x)=(3x^2-x)(4x+1)^3\)"}],
              {"xmin": -0.55, "xmax": 0.45, "ymin": -0.9, "ymax": 0.9},
              ("Here's g on a graph. The factored derivative tells us exactly where it goes flat.", "draw"),
              ("Set g prime to zero. 4x plus 1 squared is zero at x equals negative one quarter. Flat tangent there.", "tangent:-0.25"),
              ("And 60 x squared minus 10x minus 1 is zero at about negative 0.07 and 0.24. Flat tangents at both.", "tangent:-0.07033;tangent:0.23699"),
              ("You could never spot those from the messy unfactored version. That's why factoring is worth it.", "hold")),
        pause(r"\frac{d}{dx}\Big[x^2(x+1)^3\Big] = \;?",
              r"2x(x+1)^3 + 3x^2(x+1)^2 = \yl{x(x+1)^2(5x+2)}",
              "Your turn: x squared times x plus 1 cubed. Product rule on the outside, chain rule inside. Go!",
              "2x times x plus 1 cubed, plus x squared times 3 times x plus 1 squared. Factor out x times x plus 1 squared, and you get x times x plus 1 squared, times 5x plus 2."),
        cards("Combo checklist", [
            ("👀", "Find the main move", "Is the whole thing a sum, a product, or one big layer?"),
            ("🔗", "Chain any inside function", r"Any piece like \((4x+1)^3\) or \(\sin^3 x\) needs the chain rule."),
            ("🧹", "Factor at the end", "Pull out common powers. It makes zeros and slopes easy to find."),
        ],
            "Combo checklist. First, find the main move. Is the whole function a sum, a product, or one big layer?",
            "Second, any piece with an inside function needs the chain rule.",
            "Third, factor at the end. Pull out common powers so the answer is easy to use. Practice time!"),
    ],
    easy=[
        mc(r"\(\frac{d}{dx}\big[x^3 + (2x+1)^2\big] =\)", [r"\(3x^2 + 2(2x+1)\)", r"\(3x^2 + 4(2x+1)\)", r"\(3x^2 + (2x+1)\)", r"\(3x^2 + 4x\)"], 1,
           r"Sum rule, then the chain rule on the second term: \(2(2x+1)\cdot 2 = 4(2x+1)\)."),
        mc(r"\(\sin^2 x\) means:", [r"\(\sin(x^2)\)", r"\(\sin(\sin x)\)", r"\((\sin x)^2\)", r"\(2\sin x\)"], 2,
           "Square the value of sin x."),
        mc(r"\(\frac{d}{dx}\sin^2 x =\)", [r"\(2\sin x\cos x\)", r"\(2\sin x\)", r"\(\cos^2 x\)", r"\(2\cos x\)"], 0,
           r"Outside \(u^2 \to 2u\), inside \(\sin x \to \cos x\)."),
        mc(r"For \(x^4(x-1)^5\), the main rule to start with is:", ["Quotient rule", "Sum rule", "Power rule only", "Product rule"], 3,
           "It's two factors multiplied together."),
        mc(r"\(\frac{d}{dx}\big[5x + (x-2)^3\big] =\)", [r"\(5 + 3(x-2)^2\)", r"\(5x + 3(x-2)^2\)", r"\(5 + (x-2)^2\)", r"\(3(x-2)^2\)"], 0,
           r"\(5\), plus \(3(x-2)^2\cdot 1\)."),
    ],
    intermediate=[
        mc(r"\(\frac{d}{dx}\big[x(x+1)^4\big] =\)", [r"\(4x(x+1)^3\)", r"\(4(x+1)^3\)", r"\((x+1)^4 + 4x(x+1)^3\)", r"\((x+1)^4 + 4(x+1)^3\)"], 2,
           r"Product rule: \(1\cdot(x+1)^4 + x\cdot 4(x+1)^3\)."),
        mc(r"\(\frac{d}{dx}\cos^3 x =\)", [r"\(3\cos^2 x\sin x\)", r"\(-3\cos^2 x\sin x\)", r"\(3\cos^2 x\)", r"\(-\sin^3 x\)"], 1,
           r"\(3\cos^2 x\cdot(-\sin x)\)."),
        mc(r"\(\frac{d}{dx}\big[2x^5 - \sqrt{x^2+9}\big] =\)",
           [r"\(10x^4 - \frac{x}{\sqrt{x^2+9}}\)", r"\(10x^4 - \frac{1}{2\sqrt{x^2+9}}\)", r"\(10x^4 - \frac{2x}{\sqrt{x^2+9}}\)", r"\(10x^4 + \frac{x}{\sqrt{x^2+9}}\)"], 0,
           r"\(\frac{1}{2\sqrt{x^2+9}}\cdot 2x = \frac{x}{\sqrt{x^2+9}}\), and keep the minus sign."),
        mc(r"\(\frac{d}{dx}\big[x^2\sin(3x)\big] =\)",
           [r"\(2x\sin 3x + x^2\cos 3x\)", r"\(6x\cos 3x\)", r"\(2x\cos 3x\)", r"\(2x\sin 3x + 3x^2\cos 3x\)"], 3,
           r"Product rule, and the chain rule gives \(\frac{d}{dx}\sin 3x = 3\cos 3x\)."),
        mc(r"Factor \((x+1)^4 + 4x(x+1)^3\):", [r"\((x+1)^3(4x+1)\)", r"\((x+1)^3(5x+1)\)", r"\(5x(x+1)^3\)", r"\((x+1)^4(5x)\)"], 1,
           r"\((x+1)^3\big[(x+1) + 4x\big] = (x+1)^3(5x+1)\)."),
    ],
    advanced=[
        mc(r"\(\frac{d}{dx}\,\frac{(2x+1)^3}{x} =\)",
           [r"\(\frac{6(2x+1)^2}{x}\)", r"\(\frac{(2x+1)^2(8x-1)}{x^2}\)", r"\(\frac{(2x+1)^2(4x-1)}{x^2}\)", r"\(\frac{6(2x+1)^2(x-1)}{x^2}\)"], 2,
           r"Quotient rule: \(\frac{6(2x+1)^2\cdot x - (2x+1)^3}{x^2} = \frac{(2x+1)^2(6x - 2x - 1)}{x^2}\)."),
        mc(r"\(\frac{d}{dx}\big[(x^2-1)^3(x+2)^2\big] =\)",
           [r"\(2(x^2-1)^2(x+2)(4x^2+6x-1)\)", r"\(12x(x^2-1)^2(x+2)\)", r"\((x^2-1)^2(x+2)(4x^2+6x-1)\)", r"\(2(x^2-1)^2(x+2)(3x^2+6x-1)\)"], 0,
           r"\(6x(x^2-1)^2(x+2)^2 + 2(x^2-1)^3(x+2)\), then factor out \(2(x^2-1)^2(x+2)\): \(3x(x+2) + (x^2-1) = 4x^2+6x-1\)."),
        mc(r"The slope of \(y = x(x-1)^4\) at \(x = 2\) is:", [r"\(8\)", r"\(1\)", r"\(17\)", r"\(9\)"], 3,
           r"\(y' = (x-1)^4 + 4x(x-1)^3\). At \(x=2\): \(1 + 8 = 9\)."),
        mc(r"\(\frac{d}{dx}\sin^2(3x) =\)", [r"\(2\sin(3x)\cos(3x)\)", r"\(6\sin(3x)\cos(3x)\)", r"\(3\cos^2(3x)\)", r"\(6\cos(3x)\)"], 1,
           r"Three layers: \(2\sin(3x)\cdot\cos(3x)\cdot 3\)."),
        mc(r"\(\frac{d}{dx}\big[x^3e^{2x}\big] =\)", [r"\(x^2e^{2x}(3+2x)\)", r"\(3x^2e^{2x}\)", r"\(6x^2e^{2x}\)", r"\(x^2e^{2x}(3+x)\)"], 0,
           r"\(3x^2e^{2x} + x^3\cdot 2e^{2x}\), factor out \(x^2e^{2x}\)."),
    ],
    expert=[
        expert(r"Find every exact \(x\) where \(g(x) = (3x^2-x)(4x+1)^3\) has a horizontal tangent.",
               "Use the factored derivative from the episode and set each factor to zero.",
               [r"\(g'(x) = (4x+1)^2(60x^2-10x-1)\).",
                r"\((4x+1)^2 = 0\) gives \(x = -\frac14\).",
                r"\(60x^2 - 10x - 1 = 0\): \(x = \frac{10 \pm \sqrt{100 + 240}}{120} = \frac{10 \pm 2\sqrt{85}}{120} = \frac{5 \pm \sqrt{85}}{60}\)."],
               r"\(x = -\frac14,\ \frac{5-\sqrt{85}}{60},\ \frac{5+\sqrt{85}}{60}\)"),
        expert(r"Differentiate \(y = \sqrt{x}\,(1-x)^3\) and find where its tangent is horizontal for \(x \gt 0\).",
               r"Product rule, chain rule on \((1-x)^3\), then factor out \((1-x)^2\) and put everything over \(2\sqrt{x}\).",
               [r"\(y' = \frac{1}{2\sqrt x}(1-x)^3 + \sqrt x\cdot 3(1-x)^2\cdot(-1)\).",
                r"Factor: \(y' = (1-x)^2\left[\frac{1-x}{2\sqrt x} - 3\sqrt x\right] = \frac{(1-x)^2\,(1 - x - 6x)}{2\sqrt x}\).",
                r"So \(y' = \frac{(1-x)^2(1-7x)}{2\sqrt x}\), which is 0 when \(x = 1\) or \(x = \frac17\)."],
               r"\(y' = \frac{(1-x)^2(1-7x)}{2\sqrt{x}}\); horizontal at \(x = \frac17\) and \(x = 1\)"),
        expert(r"\(F(x) = f(x)\,[g(x)]^2\), with \(f(1)=3\), \(f'(1)=-2\), \(g(1)=4\), \(g'(1)=5\). Find \(F'(1)\).",
               r"Product rule on \(f\cdot g^2\), and the chain rule on \(g^2\).",
               [r"\(F'(x) = f'(x)[g(x)]^2 + f(x)\cdot 2g(x)g'(x)\).",
                r"\(F'(1) = (-2)(4)^2 + 3\cdot 2\cdot 4\cdot 5\).",
                r"\(= -32 + 120 = 88\)."],
               r"\(F'(1) = 88\)"),
    ],
)

# ======================================================================
# Episode 3: Many layers (Example 5.1D)
# ======================================================================
EPISODE_3 = episode(
    "Layers on layers: peel the onion",
    "Three, four, even five layers. Example 5.1D: the slope of cos²((e^(2x)+1)³) at x = 0.",
    [
        title("🪆", "Layers on layers", "Episode 3 · Many layers",
              "What if a function has three, four, or even five layers, like a set of nesting dolls?",
              "Good news: there's no new rule. You just keep peeling, one layer at a time."),
        equation("Layer by layer", [
            r"\Big[\pk{f}\big(\hl{g}(\yl{h}(x))\big)\Big]'",
            r"= \pk{f'\big(g(h(x))\big)}\cdot\hl{g'\big(h(x)\big)}\cdot\yl{h'(x)}",
        ],
            "Here's the general rule from your notes: three functions nested inside each other. f of g of h of x.",
            "Take the derivative of the outside f, leaving everything inside alone. Times the derivative of g, leaving h alone. Times the derivative of h.",
            ("Every layer gives one factor. Three layers, three factors multiplied together.", "hold")),
        layers("Peel sin³(2x)", [
            ("Layer 1 · outside", r"(\,\square\,)^3", r"3\sin^2(2x)"),
            ("Layer 2", r"\sin(\,\square\,)", r"\cos(2x)"),
            ("Layer 3 · core", r"2x", r"2"),
        ], r"\frac{dy}{dx} = \yl{6\sin^2(2x)\cos(2x)}",
            ("Let's peel y equals sine cubed of 2x. Three layers: cubing on the outside, sine in the middle, and 2x at the core.", "build"),
            ("Layer one, the cube: 3 times sine of 2x, squared.", "peel"),
            ("Layer two, the sine: cosine of 2x.", "peel"),
            ("Layer three, the core: 2x has derivative 2.", "peel"),
            ("Multiply all three: 6 sine squared of 2x, times cosine of 2x.", "result")),
        equation("Example 5.1D: the boss level", [
            r"f(x) = \cos^2\!\Big(\big(e^{2x}+1\big)^3\Big)",
            r"= \Big[\cos\Big(\big(e^{2x}+1\big)^3\Big)\Big]^2",
            r"\text{Find the slope of the tangent at } x = 0",
        ],
            "Now the boss level, Example 5.1D. f of x equals cosine squared of e to the 2x plus 1, all cubed.",
            "First rewrite it so the layers are obvious. The square is on the outside of everything.",
            "Our job: find the slope of the tangent line at x equals 0."),
        layers("Five layers!", [
            ("Square", r"(\,\square\,)^2", r"2\cos\big((e^{2x}+1)^3\big)"),
            ("Cosine", r"\cos(\,\square\,)", r"-\sin\big((e^{2x}+1)^3\big)"),
            ("Cube", r"(\,\square\,)^3", r"3(e^{2x}+1)^2"),
            ("Exponential + 1", r"e^{\square}+1", r"e^{2x}"),
            ("Core", r"2x", r"2"),
        ], r"f'(x) = 2\cos(u)\cdot(-\sin u)\cdot 3(e^{2x}+1)^2\cdot e^{2x}\cdot 2,\quad u = (e^{2x}+1)^3",
            ("Count the layers. Square, cosine, cube, e to the something plus 1, and 2x at the core. Five layers!", "build"),
            ("Layer one, the square: 2 times cosine of the inside.", "peel"),
            ("Layer two, cosine: negative sine of the inside.", "peel"),
            ("Layer three, the cube: 3 times e to the 2x plus 1, squared.", "peel"),
            ("Layer four: e to the 2x, plus 1, has derivative e to the 2x.", "peel"),
            ("Layer five, the core: 2x gives 2.", "peel"),
            ("Five layers, five factors, all multiplied. Don't simplify yet. Just plug in x equals 0.", "result")),
        equation("Slope at x = 0", [
            r"x = 0:\quad u = (e^0+1)^3 = 2^3 = 8",
            r"f'(0) = 2\cos 8\cdot(-\sin 8)\cdot 3(2)^2\cdot 1\cdot 2",
            r"= -48\sin 8\cos 8 = -24\sin 16",
            r"\approx \yl{6.91}",
        ],
            "At x equals 0, e to the 0 is 1. So the inside is 1 plus 1, cubed, which is 8.",
            "Plug in: 2 cosine 8, times negative sine 8, times 3 times 2 squared, times 1, times 2.",
            "That's negative 48 sine 8 cosine 8. Using the double angle identity, it equals negative 24 sine 16.",
            "Put it in your calculator in radians: about 6.91."),
        graph("See the slope", [{"fn": "cos((exp(2*x)+1)^3)^2", "label": r"\(f(x)=\cos^2\big((e^{2x}+1)^3\big)\)"}],
              {"xmin": -0.25, "xmax": 0.25, "ymin": -0.15, "ymax": 1.15},
              ("Here's what this function looks like. It wiggles faster and faster as x grows, because the inside layers explode.", "draw"),
              ("And at x equals 0, the tangent line has slope 6.91, exactly what the chain rule predicted.", "tangent:0"),
              ("Five layers, one slope, zero panic.", "hold")),
        cards("Don't lose a layer", [
            ("🎯", "Work outside in", "Peel the outermost layer first, then move inward."),
            ("📝", "Write each factor", "Write one derivative per layer before multiplying."),
            ("🔢", "Count your factors", "Number of layers = number of factors in the answer."),
        ],
            "Three tips so you never lose a layer. One: work from the outside in.",
            "Two: write down each layer's derivative before you multiply anything.",
            "Three: count. The number of layers should equal the number of factors in your answer."),
        pause(r"\frac{d}{dx}\sqrt{\cos(3x)} = \;?",
              r"\frac{1}{2\sqrt{\cos 3x}}\cdot(-\sin 3x)\cdot 3 = \yl{-\frac{3\sin 3x}{2\sqrt{\cos 3x}}}",
              "Quick challenge: the derivative of the square root of cosine of 3x. Three layers. Go!",
              "Square root gives 1 over 2 root cosine 3x. Cosine gives negative sine 3x. And 3x gives 3. Multiply: negative 3 sine 3x over 2 root cosine 3x."),
        cards("Recap", [
            ("🪆", "Any number of layers", r"\(\big[f(g(h(x)))\big]' = f'\cdot g'\cdot h'\)"),
            ("🔪", "Peel one at a time", "Each layer's derivative keeps everything inside it untouched."),
            ("🧮", "Plug in last", "For a slope at a point, substitute after differentiating."),
        ],
            "Recap: the chain rule works for any number of layers. One factor per layer.",
            "Peel one layer at a time, and leave everything inside it untouched.",
            "And for a slope at a point, plug the number in at the very end. Practice time!"),
    ],
    easy=[
        mc(r"How many layers does \(\sin^3(2x)\) have?", ["1", "2", "3", "4"], 2, "Cube, sine, and 2x."),
        mc(r"\(\frac{d}{dx}e^{3x} =\)", [r"\(e^{3x}\)", r"\(3e^{3x}\)", r"\(3xe^{3x-1}\)", r"\(e^3\)"], 1, r"Outside \(e^u\), inside \(3x\to 3\)."),
        mc(r"The derivative of \(f(g(h(x)))\) is a product of how many factors?", ["1", "2", "4", "3"], 3, "One factor per layer."),
        mc(r"\(\frac{d}{dx}\sin(x^2) =\)", [r"\(2x\cos(x^2)\)", r"\(\cos(x^2)\)", r"\(\cos(2x)\)", r"\(2x\sin(x^2)\)"], 0, r"Outside \(\cos(x^2)\), inside \(2x\)."),
        mc(r"In \(\cos^2(5x)\), the innermost layer is:", [r"\(\cos\)", r"\(5x\)", "the square", r"\(\cos(5x)\)"], 1, "The core is 5x."),
    ],
    intermediate=[
        mc(r"\(\frac{d}{dx}\cos^2(5x) =\)", [r"\(-2\cos(5x)\sin(5x)\)", r"\(10\cos(5x)\)", r"\(-10\cos(5x)\sin(5x)\)", r"\(2\cos(5x)\)"], 2,
           r"\(2\cos(5x)\cdot(-\sin 5x)\cdot 5\)."),
        mc(r"\(\frac{d}{dx}(1+\sin 2x)^4 =\)", [r"\(4(1+\sin 2x)^3\)", r"\(8\cos(2x)(1+\sin 2x)^3\)", r"\(4\cos(2x)(1+\sin 2x)^3\)", r"\(8(1+\sin 2x)^3\)"], 1,
           r"\(4(1+\sin 2x)^3\cdot\cos 2x\cdot 2\)."),
        mc(r"\(\frac{d}{dx}e^{\sin(x^2)} =\)", [r"\(\cos(x^2)e^{\sin(x^2)}\)", r"\(e^{\sin(x^2)}\)", r"\(2xe^{\cos(x^2)}\)", r"\(2x\cos(x^2)e^{\sin(x^2)}\)"], 3,
           "Three layers: exponential, sine, x squared."),
        mc(r"\(\frac{d}{dx}\sqrt{1+(2x+1)^3} =\)",
           [r"\(\frac{3(2x+1)^2}{\sqrt{1+(2x+1)^3}}\)", r"\(\frac{3(2x+1)^2}{2\sqrt{1+(2x+1)^3}}\)", r"\(\frac{6(2x+1)^2}{\sqrt{1+(2x+1)^3}}\)", r"\(\frac{1}{2\sqrt{1+(2x+1)^3}}\)"], 0,
           r"\(\frac{1}{2\sqrt{\cdots}}\cdot 3(2x+1)^2\cdot 2\), and the 2s cancel."),
        mc(r"\(\frac{d}{dx}\sin^3(x^2) =\)", [r"\(3\sin^2(x^2)\cos(x^2)\)", r"\(6x\sin^2(x^2)\)", r"\(6x\sin^2(x^2)\cos(x^2)\)", r"\(3\sin^2(2x)\cos(x^2)\)"], 2,
           r"\(3\sin^2(x^2)\cdot\cos(x^2)\cdot 2x\)."),
    ],
    advanced=[
        mc(r"\(h(x) = f(g(k(x)))\), with \(k(1)=2\), \(k'(1)=3\), \(g(2)=5\), \(g'(2)=-1\), \(f'(5)=4\). Find \(h'(1)\).", [r"\(12\)", r"\(7\)", r"\(-4\)", r"\(-12\)"], 3,
           r"\(f'(g(k(1)))\cdot g'(k(1))\cdot k'(1) = f'(5)\cdot g'(2)\cdot 3 = 4\cdot(-1)\cdot 3\)."),
        mc(r"The slope of \(y = \cos(\pi x^2)\) at \(x = 1\) is:", [r"\(0\)", r"\(-2\pi\)", r"\(2\pi\)", r"\(-\pi\)"], 0,
           r"\(y' = -\sin(\pi x^2)\cdot 2\pi x\). At \(x=1\), \(\sin\pi = 0\)."),
        mc(r"\(\frac{d}{dx}\cos^3\!\big(e^{2x}\big) =\)",
           [r"\(-3\cos^2(e^{2x})\sin(e^{2x})\)", r"\(-6e^{2x}\cos^2(e^{2x})\sin(e^{2x})\)", r"\(6e^{2x}\cos^2(e^{2x})\sin(e^{2x})\)", r"\(-3e^{2x}\cos^2(e^{2x})\)"], 1,
           r"Four layers: \(3\cos^2(\cdot)\cdot(-\sin(\cdot))\cdot e^{2x}\cdot 2\)."),
        mc(r"For \(y = (e^{2x}+1)^3\), \(y'(0) =\)", [r"\(12\)", r"\(8\)", r"\(24\)", r"\(6\)"], 2,
           r"\(y' = 3(e^{2x}+1)^2\cdot 2e^{2x}\). At 0: \(3\cdot 4\cdot 2 = 24\)."),
        mc(r"\(\frac{d}{dx}\tan(\sqrt{x}) =\)", [r"\(\sec^2(\sqrt x)\)", r"\(\frac{\sec(\sqrt x)}{2\sqrt x}\)", r"\(\frac{\tan(\sqrt x)}{2\sqrt x}\)", r"\(\frac{\sec^2(\sqrt x)}{2\sqrt x}\)"], 3,
           r"Outside \(\sec^2(\sqrt x)\), inside \(\frac{1}{2\sqrt x}\)."),
    ],
    expert=[
        expert(r"Find the slope of the tangent to \(f(x) = \sin^2\!\left(\frac{\pi}{4}x^3\right)\) at \(x = 1\).",
               r"Three layers: square, sine, and \(\frac\pi4 x^3\). At \(x=1\) the inside is \(\frac\pi4\).",
               [r"\(f'(x) = 2\sin\!\left(\frac\pi4x^3\right)\cos\!\left(\frac\pi4x^3\right)\cdot\frac{3\pi}{4}x^2\).",
                r"At \(x = 1\): \(2\cdot\frac{\sqrt2}{2}\cdot\frac{\sqrt2}{2}\cdot\frac{3\pi}{4}\).",
                r"\(= 1\cdot\frac{3\pi}{4} = \frac{3\pi}{4}\)."],
               r"\(\frac{3\pi}{4}\)"),
        expert(r"Let \(y = \sqrt{1+\sqrt{1+x}}\). Find \(y'(3)\) exactly.",
               "Two square-root layers wrapped around 1 + x. Evaluate the inner roots at x = 3 first.",
               [r"\(y' = \frac{1}{2\sqrt{1+\sqrt{1+x}}}\cdot\frac{1}{2\sqrt{1+x}}\).",
                r"At \(x = 3\): \(\sqrt{1+3} = 2\), so \(\sqrt{1+2} = \sqrt3\).",
                r"\(y'(3) = \frac{1}{2\sqrt3}\cdot\frac{1}{4} = \frac{1}{8\sqrt3} = \frac{\sqrt3}{24}\)."],
               r"\(\frac{\sqrt3}{24}\)"),
        expert(r"\(H(x) = \big[f(g(x))\big]^3\), with \(f(2)=1\), \(f'(2)=4\), \(g(1)=2\), \(g'(1)=-3\). Find \(H'(1)\).",
               "Three layers: cube, f, and g. Work out g(1) first so you know where to evaluate f and f'.",
               [r"\(H'(x) = 3\big[f(g(x))\big]^2\cdot f'(g(x))\cdot g'(x)\).",
                r"\(g(1) = 2\), so \(f(g(1)) = f(2) = 1\) and \(f'(g(1)) = f'(2) = 4\).",
                r"\(H'(1) = 3(1)^2\cdot 4\cdot(-3) = -36\)."],
               r"\(H'(1) = -36\)"),
    ],
)

VIDEO = {
    "id": "chain-rule-implicit",
    "title": "The Chain Rule & Implicit Differentiation",
    "source": "MATH 29599 · Lesson 5",
    # SHA-256 of the lesson PDF, so uploads of it get this video.
    "sha256": ["e0c12cf0a2876a1dc4d7b41ff64f45813aa9f96e15a01c3b31214ba3de51f569"],
    "episodes": [EPISODE_1, EPISODE_2, EPISODE_3, EPISODE_4, EPISODE_5, EPISODE_6],
}

# The reading version of each episode, for text-first learners.
for _episode, _article in zip(VIDEO["episodes"], ARTICLES):
    _episode["article"] = _article.strip()
