r"""Episodes 4-6 of the Chain Rule & Implicit Differentiation lesson (section 5.2)."""
from ._build import cards, compare, episode, equation, expert, graph, layers, mc, pause, title

CIRCLE = {"implicit": "x^2 + y^2 - 9", "label": r"\(x^2+y^2=9\)"}
HW_CURVE = {"implicit": "x^2*y + x*y^2 + x^3 - 3", "label": r"\(x^2y+xy^2+x^3=3\)"}
HW_VIEW = {"xmin": -0.6, "xmax": 2.6, "ymin": -3.2, "ymax": 2.4, "equal": True}

# ======================================================================
# Episode 4: Implicit Differentiation (Example 5.2A)
# ======================================================================
EPISODE_4 = episode(
    "When y won't cooperate: Implicit Differentiation",
    "Find slopes on curves that can't be written as y = f(x). Example 5.2A and homework #1.",
    [
        title("🌀", "When y won't cooperate", "Episode 4 · Implicit Differentiation",
              "So far every function looked like y equals something with x. But some curves refuse to be written that way.",
              "Today you learn implicit differentiation: how to find slopes when y is tangled up with x."),
        graph("Not a function", [CIRCLE], {"xmin": -7.1, "xmax": 7.1, "ymin": -4, "ymax": 4, "equal": True},
              ("Take the circle x squared plus y squared equals 9. A perfectly nice curve.", "draw"),
              ("But it fails the vertical line test. One x value hits the circle twice, so we can't write it as y equals f of x.", "vline:1.8"),
              ("Still, every point has a tangent line with a slope. We just need a new way to find it.", "tangentxy:1.8,2.4,-0.75")),
        equation("The key idea", [
            r"\frac{d}{dx}\big[f(x)\big] = f'(x)",
            r"\frac{d}{dx}\big[f(y)\big] = f'(y)\,\hl{\frac{dy}{dx}}",
        ],
            "Here's the move: apply d by d x to both sides of the equation. Anything that only has x differentiates normally.",
            "But anything with y in it gets an extra d y d x stuck on the end.",
            ("Why? Because y secretly depends on x. It's the chain rule in disguise.", "hold")),
        layers("Why the extra dy/dx?", [
            ("Outside", r"(\,\square\,)^3", r"3y^2"),
            ("Inside", r"y = y(x)", r"\frac{dy}{dx}"),
        ], r"\frac{d}{dx}\big[y^3\big] = \yl{3y^2\,\frac{dy}{dx}}",
            ("Think of y cubed as two layers. The inside is y, which is secretly a function of x. The outside is cubing.", "build"),
            ("Peel the outside: 3 y squared.", "peel"),
            ("Peel the inside: y itself. Its derivative with respect to x is d y d x.", "peel"),
            ("Multiply: 3 y squared times d y d x. That's the proof from your notes.", "result")),
        equation("Slope of the circle", [
            r"x^2 + y^2 = 9",
            r"2x + \hl{2y\frac{dy}{dx}} = 0",
            r"\frac{dy}{dx} = -\frac{x}{y}",
            r"\text{At } (1.8,\ 2.4):\quad \frac{dy}{dx} = -\frac{1.8}{2.4} = \yl{-0.75}",
        ],
            "Back to the circle. x squared plus y squared equals 9.",
            "Differentiate both sides. x squared gives 2x. y squared gives 2y, times d y d x. And 9 is a constant, so it gives 0.",
            "Solve for d y d x: negative x over y.",
            "At the point 1.8, 2.4, the slope is negative 0.75. That's the tangent line we saw on the graph."),
        equation("Example 5.2A", [
            r"2x^2 - 3y^2 = 4x^3y",
            r"4x - 6y\frac{dy}{dx} = 12x^2y + 4x^3\frac{dy}{dx}",
            r"4x - 12x^2y = 4x^3\frac{dy}{dx} + 6y\frac{dy}{dx}",
            r"4x - 12x^2y = \frac{dy}{dx}\,\big(4x^3 + 6y\big)",
            r"\frac{dy}{dx} = \frac{4x - 12x^2y}{4x^3+6y} = \yl{\frac{2x - 6x^2y}{2x^3+3y}}",
        ],
            "Example 5.2A: 2 x squared minus 3 y squared equals 4 x cubed y.",
            "Differentiate both sides. Left: 4x minus 6y d y d x. The right side is a product, so use the product rule: 12 x squared y, plus 4 x cubed d y d x.",
            "Now gather every d y d x term on one side, and everything else on the other.",
            "Factor out d y d x.",
            "Divide, and cancel a common factor of 2. That's the slope at any point on the curve."),
        cards("The 4-step recipe", [
            ("1️⃣", "Differentiate both sides", r"Apply \(\frac{d}{dx}\) to every term."),
            ("2️⃣", "Tag every y-term", r"Each \(y\) derivative gets a \(\frac{dy}{dx}\)."),
            ("3️⃣", "Collect", r"Move all \(\frac{dy}{dx}\) terms to one side."),
            ("4️⃣", "Factor and divide", r"Factor out \(\frac{dy}{dx}\) and solve."),
        ],
            "Here's the recipe. Step 1: differentiate both sides with respect to x.",
            "Step 2: every time you differentiate something with y, tag it with d y d x.",
            "Step 3: collect all the d y d x terms on one side.",
            "Step 4: factor out d y d x and divide. Works every time."),
        equation("Homework #1", [
            r"y - xy^3 = 2",
            r"\frac{dy}{dx} - \Big(y^3 + 3xy^2\frac{dy}{dx}\Big) = 0",
            r"\frac{dy}{dx}\,\big(1 - 3xy^2\big) = y^3",
            r"\frac{dy}{dx} = \yl{\frac{y^3}{1-3xy^2}}",
        ],
            "Let's run the recipe on homework question 1: y minus x y cubed equals 2.",
            "Differentiate. y gives d y d x. And x y cubed is a product: y cubed, plus x times 3 y squared d y d x. Keep those brackets so the minus sign hits both terms.",
            "Move y cubed over and factor out d y d x.",
            "Divide: d y d x equals y cubed over 1 minus 3 x y squared."),
        pause(r"x^2 + xy + y^2 = 7:\quad \frac{dy}{dx} = \;?",
              r"2x + y + x\frac{dy}{dx} + 2y\frac{dy}{dx} = 0 \;\Rightarrow\; \yl{\frac{dy}{dx} = -\frac{2x+y}{x+2y}}",
              "Your turn. x squared plus x y plus y squared equals 7. Find d y d x. Watch out for that x y term!",
              "2x, plus y plus x d y d x from the product rule, plus 2y d y d x, equals 0. Solve: negative 2x plus y, over x plus 2y."),
        cards("Recap", [
            ("🌀", "Relations, not functions", "Implicit differentiation finds slopes without solving for y."),
            ("🏷️", "The y-tag", r"\(\frac{d}{dx}\big[f(y)\big] = f'(y)\frac{dy}{dx}\), the chain rule in disguise."),
            ("✖️", "Watch products", r"Terms like \(xy^3\) need the product rule too."),
        ],
            "Recap. Implicit differentiation finds slopes even when you can't solve for y.",
            "Every y term picks up a d y d x. That's just the chain rule.",
            "And watch out for products like x y cubed. They need the product rule too. Practice time!"),
    ],
    easy=[
        mc(r"\(\frac{d}{dx}\big[y^2\big] =\)", [r"\(2y\)", r"\(2y\frac{dy}{dx}\)", r"\(\frac{dy}{dx}\)", r"\(2x\)"], 1, r"Chain rule: \(y\) depends on \(x\)."),
        mc(r"\(\frac{d}{dx}\big[x^3\big] =\)", [r"\(3x^2\)", r"\(3x^2\frac{dy}{dx}\)", r"\(3y^2\)", r"\(x^2\)"], 0, "Terms with only x differentiate normally. No dy/dx."),
        mc("Implicit differentiation is most useful when:", ["y is already isolated", "the function is a polynomial", "y can't easily be isolated", "there is no x"], 2,
           "It lets you find dy/dx without solving for y."),
        mc(r"For \(x^2 + y^2 = 25\), \(\frac{dy}{dx} =\)", [r"\(\frac{x}{y}\)", r"\(-\frac{y}{x}\)", r"\(-2x\)", r"\(-\frac{x}{y}\)"], 3, r"\(2x + 2y\frac{dy}{dx} = 0\)."),
        mc(r"\(\frac{d}{dx}\big[5y\big] =\)", [r"\(5\frac{dy}{dx}\)", r"\(5\)", r"\(5y\)", r"\(0\)"], 0, "Tag the y-term with dy/dx."),
    ],
    intermediate=[
        mc(r"\(\frac{d}{dx}\big[xy\big] =\)", [r"\(\frac{dy}{dx}\)", r"\(x\frac{dy}{dx}\)", r"\(y + x\frac{dy}{dx}\)", r"\(y\)"], 2, "Product rule: (x)'y + x(y)'."),
        mc(r"If \(x^3 + y^3 = 8\), then \(\frac{dy}{dx} =\)", [r"\(-\frac{x^2}{y^2}\)", r"\(\frac{x^2}{y^2}\)", r"\(-\frac{y^2}{x^2}\)", r"\(-\frac{x}{y}\)"], 0,
           r"\(3x^2 + 3y^2\frac{dy}{dx} = 0\)."),
        mc(r"\(\frac{d}{dx}\big[\sin y\big] =\)", [r"\(\cos y\)", r"\(-\cos y\frac{dy}{dx}\)", r"\(\cos x\)", r"\(\cos y\,\frac{dy}{dx}\)"], 3, "Chain rule on sin(y)."),
        mc(r"On \(xy = 6\), the slope at \((2, 3)\) is:", [r"\(-\frac23\)", r"\(-\frac32\)", r"\(\frac32\)", r"\(-6\)"], 1,
           r"\(y + x\frac{dy}{dx} = 0\Rightarrow \frac{dy}{dx} = -\frac{y}{x} = -\frac32\)."),
        mc(r"If \(y^2 = 4x\), then \(\frac{dy}{dx} =\)", [r"\(\frac{2}{y}\)", r"\(4\)", r"\(\frac{y}{2}\)", r"\(2y\)"], 0, r"\(2y\frac{dy}{dx} = 4\)."),
    ],
    advanced=[
        mc(r"If \(x^2y + y^3 = 10\), then \(\frac{dy}{dx} =\)",
           [r"\(-\frac{2x}{x^2+3y^2}\)", r"\(\frac{-2xy}{x^2+3y^2}\)", r"\(\frac{2xy}{x^2+3y^2}\)", r"\(-\frac{2xy}{3y^2}\)"], 1,
           r"\(2xy + x^2\frac{dy}{dx} + 3y^2\frac{dy}{dx} = 0\)."),
        mc(r"The slope of \(x^2 + xy + y^2 = 7\) at \((1, 2)\) is:", [r"\(-\frac54\)", r"\(\frac45\)", r"\(-\frac45\)", r"\(-1\)"], 2,
           r"\(\frac{dy}{dx} = -\frac{2x+y}{x+2y} = -\frac{4}{5}\)."),
        mc(r"If \(e^y = x + y\), then \(\frac{dy}{dx} =\)", [r"\(e^{-y}\)", r"\(\frac{1}{e^y+1}\)", r"\(e^y - 1\)", r"\(\frac{1}{e^y-1}\)"], 3,
           r"\(e^y\frac{dy}{dx} = 1 + \frac{dy}{dx}\), so \(\frac{dy}{dx}(e^y - 1) = 1\)."),
        mc(r"If \(\sin(xy) = x\), then \(\frac{dy}{dx} =\)",
           [r"\(\frac{1 - y\cos(xy)}{x\cos(xy)}\)", r"\(\frac{1}{\cos(xy)}\)", r"\(\frac{1 - \cos(xy)}{x}\)", r"\(\frac{y\cos(xy)-1}{x}\)"], 0,
           r"\(\cos(xy)\,(y + x\frac{dy}{dx}) = 1\)."),
        mc(r"If \(\sqrt{x} + \sqrt{y} = 5\), then \(\frac{dy}{dx} =\)", [r"\(\sqrt{\frac{x}{y}}\)", r"\(-\frac{\sqrt x}{\sqrt y}\)", r"\(-\frac{\sqrt y}{\sqrt x}\)", r"\(-\frac{1}{2\sqrt x}\)"], 2,
           r"\(\frac{1}{2\sqrt x} + \frac{1}{2\sqrt y}\frac{dy}{dx} = 0\)."),
    ],
    expert=[
        expert(r"Find all points on \(x^2 + xy + y^2 = 3\) where the tangent line is horizontal.",
               "Horizontal means dy/dx = 0, so the numerator of dy/dx is 0. Then use the original equation to find the points.",
               [r"\(2x + y + x\frac{dy}{dx} + 2y\frac{dy}{dx} = 0\Rightarrow \frac{dy}{dx} = -\frac{2x+y}{x+2y}\).",
                r"\(\frac{dy}{dx} = 0\) when \(2x + y = 0\), so \(y = -2x\).",
                r"Substitute: \(x^2 + x(-2x) + 4x^2 = 3\Rightarrow 3x^2 = 3\Rightarrow x = \pm1\).",
                r"Points \((1,-2)\) and \((-1, 2)\). Check: the denominator \(x + 2y = \mp3 \ne 0\)."],
               r"\((1, -2)\) and \((-1, 2)\)"),
        expert(r"Find the slope of the folium \(x^3 + y^3 = 6xy\) at the point \((3, 3)\).",
               "Product rule on 6xy. Collect the dy/dx terms, then substitute (3, 3).",
               [r"\(3x^2 + 3y^2\frac{dy}{dx} = 6y + 6x\frac{dy}{dx}\).",
                r"\(\frac{dy}{dx}(3y^2 - 6x) = 6y - 3x^2\Rightarrow \frac{dy}{dx} = \frac{2y - x^2}{y^2 - 2x}\).",
                r"At \((3,3)\): \(\frac{6 - 9}{9 - 6} = -1\)."],
               r"\(-1\)"),
        expert(r"For \(x^2 + y^2 = 9\), find \(\frac{d^2y}{dx^2}\) in terms of \(y\) only.",
               r"Differentiate \(\frac{dy}{dx} = -\frac{x}{y}\) again with the quotient rule, then use \(x^2 + y^2 = 9\).",
               [r"\(\frac{d^2y}{dx^2} = -\frac{y - x\frac{dy}{dx}}{y^2}\).",
                r"Substitute \(\frac{dy}{dx} = -\frac{x}{y}\): \(-\frac{y + \frac{x^2}{y}}{y^2} = -\frac{y^2 + x^2}{y^3}\).",
                r"Since \(x^2 + y^2 = 9\): \(\frac{d^2y}{dx^2} = -\frac{9}{y^3}\)."],
               r"\(-\frac{9}{y^3}\)"),
    ],
)

# ======================================================================
# Episode 5: Tangent lines on implicit curves (homework #2-4)
# ======================================================================
EPISODE_5 = episode(
    "Tangent lines on wild curves",
    "Homework #2 to #4: points, slopes and tangent line equations on implicit curves.",
    [
        title("📐", "Tangents on wild curves", "Episode 5 · Implicit tangent lines",
              "POV: the question says find the tangent lines, plural, at x equals 1. Wait, how can there be more than one?",
              "Implicit curves can pass through the same x value more than once. Let's solve homework questions 2 to 4 together."),
        graph("Meet the curve", [HW_CURVE], HW_VIEW,
              ("Here's the curve x squared y plus x y squared plus x cubed equals 3.", "draw"),
              ("Draw the line x equals 1. It crosses the curve twice! So there are two points, and two tangent lines.", "vline:1"),
              ("Those points are 1, negative 2 and 1, 1. Let's find them with algebra.", "point:1,-2;point:1,1")),
        equation("Step 1: find the points", [
            r"x = 1:\quad y + y^2 + 1 = 3",
            r"y^2 + y - 2 = 0",
            r"(y+2)(y-1) = 0",
            r"y = -2,\ y = 1 \quad\Rightarrow\quad \yl{(1,-2)\ \text{and}\ (1,1)}",
        ],
            "Step 1: plug x equals 1 into the equation. You get y plus y squared plus 1 equals 3.",
            "Move everything to one side: y squared plus y minus 2 equals 0.",
            "Factor it: y plus 2, times y minus 1.",
            "So y equals negative 2 or 1. Two points: 1, negative 2 and 1, 1."),
        equation("Step 2: differentiate", [
            r"\hl{2xy + x^2\frac{dy}{dx}} + \pk{y^2 + 2xy\frac{dy}{dx}} + 3x^2 = 0",
            r"\frac{dy}{dx}\big(x^2 + 2xy\big) = -\big(3x^2 + 2xy + y^2\big)",
            r"\frac{dy}{dx} = \yl{-\frac{3x^2 + 2xy + y^2}{x^2 + 2xy}}",
        ],
            "Step 2: differentiate both sides. x squared y and x y squared are both products, so each one needs the product rule.",
            "Collect the d y d x terms on the left and factor.",
            "Divide. Now we have a slope formula that works at any point on the curve."),
        equation("Step 3: slope at each point", [
            r"(1,-2):\quad m = -\frac{3 - 4 + 4}{1 - 4} = -\frac{3}{-3} = \yl{1}",
            r"(1,1):\quad m = -\frac{3 + 2 + 1}{1 + 2} = -\frac{6}{3} = \yl{-2}",
        ],
            "Step 3: plug in each point. At 1, negative 2: the top is 3 minus 4 plus 4, which is 3. The bottom is 1 minus 4, which is negative 3. So the slope is 1.",
            "At 1, 1: the top is 6 and the bottom is 3, so the slope is negative 2."),
        equation("Step 4: tangent line equations", [
            r"y - y_1 = m(x - x_1)",
            r"(1,-2),\ m = 1:\quad y + 2 = x - 1 \;\Rightarrow\; \yl{y = x - 3}",
            r"(1,1),\ m = -2:\quad y - 1 = -2(x - 1) \;\Rightarrow\; \yl{y = -2x + 3}",
        ],
            "Step 4, homework question 3: write the tangent lines using point-slope form.",
            "Through 1, negative 2 with slope 1: y plus 2 equals x minus 1, so y equals x minus 3.",
            "Through 1, 1 with slope negative 2: y minus 1 equals negative 2 times x minus 1, so y equals negative 2x plus 3."),
        graph("Both tangents", [HW_CURVE], HW_VIEW,
              ("Back to the graph to check our work.", "draw"),
              ("At 1, negative 2, a line with slope 1 just kisses the curve.", "tangentxy:1,-2,1"),
              ("And at 1, 1, the line with slope negative 2. Both tangent lines, exactly as calculated.", "tangentxy:1,1,-2")),
        equation("Homework #4: where is the slope 1/4?", [
            r"y + \sqrt{y} = x",
            r"\frac{dy}{dx} + \frac{1}{2\sqrt{y}}\,\frac{dy}{dx} = 1",
            r"\frac14 + \frac{1}{2\sqrt y}\cdot\frac14 = 1 \;\Rightarrow\; \frac{1}{8\sqrt y} = \frac34",
            r"\sqrt{y} = \frac16 \;\Rightarrow\; y = \frac{1}{36}",
            r"x = \frac{1}{36} + \frac16 = \frac{7}{36}\quad\Rightarrow\quad \yl{\left(\tfrac{7}{36},\ \tfrac{1}{36}\right)}",
        ],
            "Question 4 flips it around. The relation y plus root y equals x has a tangent with slope one quarter. Where?",
            "Differentiate: d y d x, plus 1 over 2 root y times d y d x, equals 1.",
            "Now plug in the slope, one quarter, for d y d x. That leaves 1 over 8 root y equals three quarters.",
            "So root y equals one sixth, and y equals 1 over 36.",
            "Plug y back into the original equation to get x: 1 over 36 plus one sixth is 7 over 36."),
        graph("Zoom in", [{"implicit": "y + sqrt(y) - x", "label": r"\(y+\sqrt{y}=x\)"}],
              {"xmin": -0.05, "xmax": 0.75, "ymin": -0.06, "ymax": 0.39, "equal": True},
              ("Here's that curve, zoomed way in near the origin.", "draw"),
              ("At 7 over 36, 1 over 36, the tangent has slope one quarter. It crosses the y axis just below zero, at about negative 0.021, just like the graph in your notes.", "tangentxy:0.194444,0.027778,0.25")),
        pause(r"\text{Tangent to } x^2+y^2=25 \text{ at } (3,4)?",
              r"m = -\tfrac{3}{4},\quad y - 4 = -\tfrac34(x-3) \;\Rightarrow\; \yl{y = -\tfrac34 x + \tfrac{25}{4}}",
              "Your turn. Find the tangent line to x squared plus y squared equals 25 at the point 3, 4.",
              "The slope is negative x over y, so negative three quarters. Point-slope form gives y equals negative three quarters x plus 25 over 4."),
        cards("Recap", [
            ("📍", "Find the point(s)", "Plug the known coordinate into the original equation."),
            ("🌀", "Differentiate implicitly", r"Solve for \(\frac{dy}{dx}\), or plug the point in first."),
            ("📏", "Slope at each point", r"Substitute each point into \(\frac{dy}{dx}\)."),
            ("✍️", "Point-slope form", r"\(y - y_1 = m(x - x_1)\)"),
        ],
            "Recap. One: find the point or points by plugging into the original equation.",
            "Two: differentiate implicitly. You can solve for d y d x first, or plug the point in first. Both work.",
            "Three: get the slope at each point.",
            "Four: point-slope form gives the tangent line. You've got this. Practice time!"),
    ],
    easy=[
        mc("Point-slope form of a line is:", [r"\(y = mx\)", r"\(y - y_1 = m(x - x_1)\)", r"\(y = m(x + x_1)\)", r"\(x - x_1 = m(y - y_1)\)"], 1, "Slope m through the point (x1, y1)."),
        mc(r"A curve has slope \(-2\) at \((1, 1)\). Its tangent line is:", [r"\(y - 1 = 2(x - 1)\)", r"\(y + 1 = -2(x + 1)\)", r"\(y - 1 = -2(x - 1)\)", r"\(y = -2x\)"], 2,
           "Plug m = −2 and (1, 1) into point-slope form."),
        mc("To find the points on a curve where x = 1, you:", ["differentiate first", "set y = 0", "set dy/dx = 0", "substitute x = 1 into the equation and solve for y"], 3,
           "Use the original equation to get the y-coordinates."),
        mc(r"The slope of \(x^2 + y^2 = 25\) at \((3, 4)\) is:", [r"\(-\frac34\)", r"\(\frac34\)", r"\(-\frac43\)", r"\(\frac43\)"], 0, r"\(\frac{dy}{dx} = -\frac{x}{y}\)."),
        mc("A curve can have two points with the same x-value when:", ["it's a straight line", "it fails the vertical line test", "it is a function", "its slope is zero"], 1,
           "That's exactly what 'not a function' means."),
    ],
    intermediate=[
        mc(r"The tangent line to \(x^2 + y^2 = 25\) at \((3, 4)\) is:",
           [r"\(y = \frac34x + 4\)", r"\(y = -\frac43x + 8\)", r"\(y = -\frac34x + \frac{25}{4}\)", r"\(y = -\frac34x + 4\)"], 2,
           r"\(y - 4 = -\frac34(x - 3)\)."),
        mc(r"The points on \(x^2 + y^2 = 10\) where \(x = 1\) are:", [r"\((1, 3)\) only", r"\((1, 3)\) and \((1, -3)\)", r"\((1, 9)\) and \((1, -9)\)", r"\((1, \sqrt{10})\)"], 1,
           r"\(1 + y^2 = 10\Rightarrow y = \pm3\)."),
        mc(r"The slopes of \(x^2 + y^2 = 10\) at \((1, 3)\) and \((1, -3)\) are:",
           [r"\(-\frac13\) and \(\frac13\)", r"\(\frac13\) and \(-\frac13\)", r"\(-3\) and \(3\)", r"both \(-\frac13\)"], 0, r"\(-\frac{x}{y}\) at each point."),
        mc(r"The tangent to \(xy = 4\) at \((2, 2)\) is:", [r"\(y = x\)", r"\(y = -x\)", r"\(y = x + 4\)", r"\(y = -x + 4\)"], 3,
           r"\(\frac{dy}{dx} = -\frac{y}{x} = -1\), so \(y - 2 = -(x - 2)\)."),
        mc(r"On a circle, \(\frac{dy}{dx} = -\frac{x}{y}\). The tangent is vertical where:", [r"\(x = 0\)", r"\(y = 0\)", r"\(x = y\)", "never"], 1,
           "Vertical tangent: the denominator of dy/dx is 0."),
    ],
    advanced=[
        mc(r"The slope of \(y^2 = x^3\) at \((1, 1)\) is:", [r"\(\frac23\)", r"\(3\)", r"\(\frac32\)", r"\(1\)"], 2, r"\(2y\frac{dy}{dx} = 3x^2\Rightarrow\frac{dy}{dx} = \frac{3x^2}{2y}\)."),
        mc(r"The tangent to \(x^2 - xy + y^2 = 3\) at \((1, 2)\) is:", [r"\(y = 2\)", r"\(x = 1\)", r"\(y = x + 1\)", r"\(y = -x + 3\)"], 0,
           r"\(\frac{dy}{dx} = \frac{y - 2x}{2y - x} = \frac{0}{3} = 0\): horizontal."),
        mc(r"Where does \(y + \sqrt{y} = x\) have slope \(\frac13\)?",
           [r"\(\left(\frac14, \frac{1}{16}\right)\)", r"\(\left(\frac{5}{16}, \frac14\right)\)", r"\(\left(\frac{3}{16}, \frac{1}{16}\right)\)", r"\(\left(\frac{5}{16}, \frac{1}{16}\right)\)"], 3,
           r"\(\frac13\left(1 + \frac{1}{2\sqrt y}\right) = 1\Rightarrow\sqrt y = \frac14\), so \(y = \frac1{16}\) and \(x = \frac1{16} + \frac14\)."),
        mc(r"The normal line (perpendicular to the tangent) to \(x^2 + y^2 = 25\) at \((3, 4)\) is:",
           [r"\(y = -\frac34x\)", r"\(y = \frac43x\)", r"\(y = \frac34x + \frac74\)", r"\(y = -\frac43x + 8\)"], 1,
           r"Tangent slope \(-\frac34\), so the normal slope is \(\frac43\). It passes through the centre."),
        mc(r"From the notes: the tangent to \(x^2y + xy^2 + x^3 = 3\) at \((1, 1)\) is:", [r"\(y = x - 3\)", r"\(y = 2x - 1\)", r"\(y = -2x + 3\)", r"\(y = -x + 2\)"], 2,
           "Slope −2 through (1, 1)."),
    ],
    expert=[
        expert(r"Find the equations of all tangent lines to \(x^2 + y^2 = 25\) that have slope \(\frac34\).",
               r"Set \(-\frac{x}{y} = \frac34\) to find where on the circle that happens. There are two points.",
               [r"\(-\frac{x}{y} = \frac34\Rightarrow x = -\frac34y\).",
                r"Substitute: \(\frac{9}{16}y^2 + y^2 = 25\Rightarrow\frac{25}{16}y^2 = 25\Rightarrow y = \pm4\).",
                r"Points \((-3, 4)\) and \((3, -4)\).",
                r"Lines: \(y - 4 = \frac34(x + 3)\) and \(y + 4 = \frac34(x - 3)\)."],
               r"\(y = \frac34x + \frac{25}{4}\) and \(y = \frac34x - \frac{25}{4}\)"),
        expert(r"Find the points where \(x^2 - xy + y^2 = 3\) has a vertical tangent line.",
               "A vertical tangent happens where the denominator of dy/dx is 0 (and the numerator isn't).",
               [r"\(2x - y - x\frac{dy}{dx} + 2y\frac{dy}{dx} = 0\Rightarrow\frac{dy}{dx} = \frac{y - 2x}{2y - x}\).",
                r"Denominator zero: \(x = 2y\).",
                r"Substitute: \(4y^2 - 2y^2 + y^2 = 3\Rightarrow y = \pm1\), giving \((2, 1)\) and \((-2, -1)\).",
                r"Check the numerator: \(y - 2x = \mp3 \ne 0\). So both tangents are vertical."],
               r"\((2, 1)\) and \((-2, -1)\)"),
        expert(r"Find the tangent line to \(y + \sqrt{y} = x\) at \(\left(\frac{7}{36}, \frac{1}{36}\right)\). What is its \(y\)-intercept?",
               "You already know the slope there is 1/4. Plug the point into y = mx + b to find b.",
               [r"\(y = \frac14x + b\) through \(\left(\frac{7}{36}, \frac{1}{36}\right)\): \(\frac1{36} = \frac{7}{144} + b\).",
                r"\(b = \frac{4}{144} - \frac{7}{144} = -\frac{3}{144} = -\frac1{48}\).",
                r"\(-\frac{1}{48}\approx -0.021\), which matches the graph in the notes."],
               r"\(y = \frac14x - \frac1{48}\); \(y\)-intercept \(-\frac1{48}\approx -0.021\)"),
    ],
)

# ======================================================================
# Episode 6: New rules from implicit differentiation (5.2B, 5.2C)
# ======================================================================
EPISODE_6 = episode(
    "Unlocking new rules: fractional powers & logs",
    "Prove the power rule for any fraction, the router example 5.2B, and why d/dx ln x = 1/x.",
    [
        title("🔓", "Unlocking new rules", "Episode 6 · Power rule & logarithms",
              "Implicit differentiation isn't only for weird curves. It's a tool for proving brand new derivative rules.",
              "Today you unlock the power rule for fractional powers, and the derivative of the natural log."),
        cards("What we know so far", [
            ("✅", "Proven already", r"\(\frac{d}{dx}x^n = nx^{n-1}\) for \(n = 0, 1, 2, 3, \dots\)"),
            ("❓", "But what about roots?", r"\(\sqrt{x} = x^{1/2}\), \(\sqrt[3]{x^2} = x^{2/3}\)"),
            ("🎯", "Goal", r"Prove it for every rational power \(n = \frac{a}{b}\)."),
        ],
            "Earlier you proved the power rule, but only for whole number powers like 0, 1, 2, 3.",
            "What about square roots and cube roots? Those are fractional powers, like x to the one half.",
            "Our goal: prove the power rule works for every fraction a over b."),
        equation("Proof: power rule for n = a/b", [
            r"y = x^{a/b}",
            r"y^{\,b} = x^{a}",
            r"\hl{b\,y^{\,b-1}\frac{dy}{dx}} = a\,x^{a-1}",
            r"\frac{dy}{dx} = \frac{a}{b}\cdot\frac{x^{a-1}}{y^{\,b-1}}",
            r"= \frac{a}{b}\cdot\frac{x^{a-1}}{x^{a - a/b}} = \yl{\frac{a}{b}\,x^{\frac{a}{b}-1}}",
        ],
            "Let y equal x to the a over b, where a and b are integers.",
            "Raise both sides to the power b. Now there are only whole number powers: y to the b equals x to the a.",
            "Differentiate implicitly. The left side uses the chain rule: b y to the b minus 1, times d y d x. The right side is a x to the a minus 1.",
            "Solve for d y d x.",
            "Replace y with x to the a over b and simplify the exponents. You get a over b, times x to the a over b minus 1. The power rule works for fractions too!"),
        equation("Example 5.2B: the router", [
            r"f(x) = 2x + 6\sqrt{x} = 2x + 6x^{1/2}",
            r"f'(x) = 2 + 6\cdot\tfrac12x^{-1/2} = 2 + \frac{3}{\sqrt{x}}",
            r"f'(4) = 2 + \frac32 = \yl{3.5\ \text{MB/min}}",
        ],
            "Example 5.2B. A router transfers f of x equals 2x plus 6 root x megabytes in the first x minutes. How fast is data moving at 4 minutes?",
            "Rewrite the root as x to the one half. The derivative is 2, plus 6 times one half x to the negative one half. That's 2 plus 3 over root x.",
            "At x equals 4: 2 plus 3 over 2. That's 3.5 megabytes per minute."),
        graph("The data curve", [{"fn": "2*x + 6*sqrt(x)", "label": r"\(f(x)=2x+6\sqrt{x}\)"}],
              {"xmin": -0.4, "xmax": 9, "ymin": -2, "ymax": 32},
              ("Here's the data curve. It shoots up at the start, then settles into a steadier climb.", "draw"),
              ("At 4 minutes, the tangent line has slope 3.5. That's the instantaneous rate of data transfer.", "tangent:4"),
              ("Slide along the curve and watch the rate drop as time goes on. It heads toward 2 megabytes per minute.", "trace")),
        equation("Example 5.2C: why d/dx ln x = 1/x", [
            r"y = \ln x",
            r"e^{y} = x",
            r"\hl{e^{y}\frac{dy}{dx}} = 1",
            r"\frac{dy}{dx} = \frac{1}{e^{y}} = \yl{\frac{1}{x}}",
        ],
            "Example 5.2C: prove that the derivative of ln x is 1 over x. Start with y equals ln x.",
            "Rewrite it in exponential form: e to the y equals x.",
            "Differentiate implicitly. The derivative of e to the y is e to the y, times d y d x. The right side gives 1.",
            "Solve: d y d x equals 1 over e to the y. But e to the y is just x, so the derivative of ln x is 1 over x."),
        compare("Log rules",
                ("Natural log", [r"\frac{d}{dx}\ln x = \frac{1}{x}"]),
                ("Any base b", [r"\frac{d}{dx}\log_b x = \frac{1}{x\ln b}"]),
                ("Here's the natural log rule we just proved: 1 over x.", "left"),
                ("For any other base b, you get 1 over x ln b. The ln b is a constant that appears when you change the base.", "right"),
                ("For example, the derivative of log base 10 of x is 1 over x ln 10.", "hold")),
        equation("Logs + the chain rule", [
            r"\frac{d}{dx}\ln\big(\hl{g(x)}\big) = \frac{\hl{g'(x)}}{g(x)}",
            r"\frac{d}{dx}\ln\big(x^2+1\big) = \yl{\frac{2x}{x^2+1}}",
        ],
            "Team up the log rule with the chain rule: the derivative of ln of g of x is g prime over g.",
            "For example, the derivative of ln of x squared plus 1 is 2x over x squared plus 1."),
        pause(r"\frac{d}{dx}\,4\sqrt[3]{x^2} = \;?",
              r"4x^{2/3} \;\to\; \tfrac83x^{-1/3} = \yl{\frac{8}{3\sqrt[3]{x}}}",
              "Final challenge: the derivative of 4 times the cube root of x squared.",
              "Rewrite it as 4 x to the two thirds. The power rule gives 8 thirds x to the negative one third, which is 8 over 3 cube root x."),
        cards("You finished the lesson! 🎉", [
            ("🔗", "Chain rule", r"Multiply the derivative of every layer: \(\frac{dy}{dx} = \frac{dy}{du}\cdot\frac{du}{dx}\)."),
            ("🌀", "Implicit differentiation", r"Every \(y\)-term picks up a \(\frac{dy}{dx}\)."),
            ("🔓", "New rules", r"\(\frac{d}{dx}x^{a/b} = \frac ab x^{\frac ab - 1}\), \(\frac{d}{dx}\ln x = \frac1x\), \(\frac{d}{dx}\log_b x = \frac{1}{x\ln b}\)"),
        ],
            "That's the whole lesson! The chain rule: multiply the derivative of every layer.",
            "Implicit differentiation: every y term picks up a d y d x.",
            "And the new rules: fractional powers, ln x, and log base b. One last round of practice and you've mastered lesson 5."),
    ],
    easy=[
        mc(r"\(\frac{d}{dx}\sqrt{x} =\)", [r"\(\frac{1}{2\sqrt{x}}\)", r"\(2\sqrt{x}\)", r"\(\frac{1}{\sqrt x}\)", r"\(\frac12\sqrt{x}\)"], 0, r"\(x^{1/2}\to\frac12x^{-1/2}\)."),
        mc(r"\(\frac{d}{dx}\ln x =\)", [r"\(\ln x\)", r"\(e^x\)", r"\(\frac{1}{x}\)", r"\(x\)"], 2, "Proved in Example 5.2C."),
        mc(r"\(\sqrt[3]{x}\) written as a power is:", [r"\(x^3\)", r"\(x^{1/3}\)", r"\(x^{-3}\)", r"\(3x\)"], 1, "The cube root is the power one third."),
        mc(r"\(\frac{d}{dx}x^{3/2} =\)", [r"\(\frac23x^{1/2}\)", r"\(\frac32x^{3/2}\)", r"\(x^{1/2}\)", r"\(\frac32x^{1/2}\)"], 3, "Bring 3/2 down, subtract 1 from the power."),
        mc(r"To prove \(\frac{d}{dx}\ln x = \frac1x\), we rewrite \(y = \ln x\) as:", [r"\(e^y = x\)", r"\(y = e^x\)", r"\(x = \ln y\)", r"\(y^x = e\)"], 0, "Exponential form."),
    ],
    intermediate=[
        mc(r"\(\frac{d}{dx}\,\frac{1}{\sqrt{x}} =\)", [r"\(\frac{1}{2\sqrt x}\)", r"\(-\frac{1}{2x^{3/2}}\)", r"\(-\frac{1}{\sqrt{x}}\)", r"\(-2x^{-3/2}\)"], 1, r"\(x^{-1/2}\to-\frac12x^{-3/2}\)."),
        mc(r"\(\frac{d}{dx}\log_2 x =\)", [r"\(\frac{1}{2x}\)", r"\(\frac{\ln 2}{x}\)", r"\(\frac{1}{x\ln 2}\)", r"\(\frac{2}{x}\)"], 2, r"\(\frac{1}{x\ln b}\) with \(b = 2\)."),
        mc(r"\(\frac{d}{dx}\ln(3x) =\)", [r"\(\frac{3}{x}\)", r"\(\frac{1}{3x}\)", r"\(3\ln x\)", r"\(\frac{1}{x}\)"], 3, r"\(\frac{3}{3x} = \frac1x\)."),
        mc(r"\(\frac{d}{dx}x^{2/3} =\)", [r"\(\frac{2}{3\sqrt[3]{x}}\)", r"\(\frac23\sqrt[3]{x}\)", r"\(\frac{3}{2}x^{1/3}\)", r"\(\frac{2}{3}x^{5/3}\)"], 0, r"\(\frac23x^{-1/3}\)."),
        mc(r"For the router \(f(x) = 2x + 6\sqrt{x}\), \(f'(9) =\)", [r"\(2\)", r"\(3\)", r"\(4\)", r"\(3.5\)"], 1, r"\(2 + \frac{3}{\sqrt9} = 3\) MB/min."),
    ],
    advanced=[
        mc(r"\(\frac{d}{dx}\ln(x^2+1) =\)", [r"\(\frac{1}{x^2+1}\)", r"\(\frac{2x}{x^2+1}\)", r"\(2x\ln(x^2+1)\)", r"\(\frac{2}{x}\)"], 1, r"\(\frac{g'}{g}\) with \(g = x^2+1\)."),
        mc(r"\(\frac{d}{dx}\ln(\sin x) =\)", [r"\(\frac{1}{\sin x}\)", r"\(\tan x\)", r"\(-\cot x\)", r"\(\cot x\)"], 3, r"\(\frac{\cos x}{\sin x} = \cot x\)."),
        mc(r"\(\frac{d}{dx}\sqrt[4]{x^3} =\)", [r"\(\frac34x^{-1/4}\)", r"\(\frac43x^{1/3}\)", r"\(\frac34x^{1/4}\)", r"\(\frac{3}{4\sqrt{x}}\)"], 0, r"\(x^{3/4}\to\frac34x^{-1/4}\)."),
        mc(r"\(\frac{d}{dx}\big[x\ln x\big] =\)", [r"\(\frac1x\)", r"\(\ln x\)", r"\(\ln x + 1\)", r"\(x + \ln x\)"], 2, r"Product rule: \(\ln x + x\cdot\frac1x\)."),
        mc(r"\(\frac{d}{dx}\log_{10}(x^2) =\)", [r"\(\frac{2}{x}\)", r"\(\frac{1}{x^2\ln10}\)", r"\(\frac{2x}{\ln 10}\)", r"\(\frac{2}{x\ln 10}\)"], 3, r"\(\frac{2x}{x^2\ln10} = \frac{2}{x\ln 10}\)."),
    ],
    expert=[
        expert(r"Use implicit differentiation to prove \(\frac{d}{dx}\log_b x = \frac{1}{x\ln b}\).",
               r"Copy the ln x proof: rewrite in exponential form. You'll need \(\frac{d}{dx}b^y = b^y\ln b\,\frac{dy}{dx}\).",
               [r"Let \(y = \log_b x\), so \(b^y = x\).",
                r"Differentiate: \(b^y\ln b\,\frac{dy}{dx} = 1\).",
                r"\(\frac{dy}{dx} = \frac{1}{b^y\ln b} = \frac{1}{x\ln b}\), since \(b^y = x\).",
                r"(Alternative: \(\log_b x = \frac{\ln x}{\ln b}\), and \(\ln b\) is a constant.)"],
               r"\(\frac{d}{dx}\log_b x = \frac{1}{x\ln b}\)"),
        expert(r"Use implicit differentiation to find \(\frac{d}{dx}\arcsin x\).",
               r"Write \(y = \arcsin x\) as \(\sin y = x\). Afterwards, rewrite \(\cos y\) in terms of \(x\) with a Pythagorean identity.",
               [r"\(\sin y = x\), where \(-\frac\pi2 \le y \le \frac\pi2\).",
                r"Differentiate: \(\cos y\,\frac{dy}{dx} = 1\Rightarrow\frac{dy}{dx} = \frac{1}{\cos y}\).",
                r"\(\cos y = \sqrt{1 - \sin^2 y} = \sqrt{1 - x^2}\) (positive, since \(y\) is between \(-\frac\pi2\) and \(\frac\pi2\))."],
               r"\(\frac{d}{dx}\arcsin x = \frac{1}{\sqrt{1-x^2}}\)"),
        expert(r"\(f(x) = 4\sqrt{x} - \ln x\). Find where the tangent is horizontal, and the equation of that tangent line.",
               r"Set \(f'(x) = 0\). Multiplying both sides by \(x\) clears the fractions.",
               [r"\(f'(x) = \frac{2}{\sqrt x} - \frac1x = 0\Rightarrow\frac{2}{\sqrt x} = \frac1x\Rightarrow 2x = \sqrt x\).",
                r"\(2\sqrt x = 1\Rightarrow x = \frac14\).",
                r"\(f\left(\frac14\right) = 4\cdot\frac12 - \ln\frac14 = 2 + \ln 4\).",
                r"A horizontal tangent has slope 0, so it is \(y = 2 + \ln 4\)."],
               r"\(x = \frac14\); tangent \(y = 2 + \ln 4\approx 3.39\)"),
    ],
)
